### ISSUE TITLE
Dependencies menu includes dev-dependencies

### ISSUE THREAD

**Issue by daschl** [rust-lang/docs.rs#100]
Hi!

I don't know if its intended, but it seems that the dependencies section includes dev-dependencies as well. It is a bit confusing in the sense that one might expect all of these dependencies being pulled in into their project even if thats not the case.

I'd vote to either have two sections (dependencies and dev dependencies) or just to show the regular dependencies in that section. Or maybe add a small "dev" flag to the dev ones?

**Comment by crumblingstatue** [comment]
I agree that this is confusing.

For example, it makes it look like [byteorder 1.0.0](https://docs.rs/crate/byteorder/1.0.0) is depending on unstable `0.x` crates, even though those are just dev-dependencies.

**Comment by Kixiron** [comment]
Triage: This could be fairly easy to do, maybe something to think about as part of #740

**Comment by syphar** [comment]
dev dependencies are flagged: 
![Image](https://github.com/user-attachments/assets/dac2346b-b429-4743-93a1-616b4bb053c7)
