### ISSUE TITLE
wavecar_rs needs more build time

### ISSUE THREAD

**Issue by Ionizing** [rust-lang/docs.rs#1001]
**Crate name:** wavecar_rs
**Build failure link:** https://docs.rs/crate/wavecar_rs/0.1.0/builds/285405

**Requested RAM limit:** 3GB
**Requested timeout:** 30min
**Requested number of targets:** 10

**Why your crate needs the resource increases:** That crate depends on `fftw` and `openblas`, which consumes a lot of time during the build.

**Comment by jyn514** [comment]
30 minutes is longer than we normally extend for. Would 20 or 25 minutes work instead?

Note that this is for each target, so it needs to be multiplied by 5 - please first set `targets = []` in `package.metadata.docs.rs` so that your crate only builds for one target.

**Comment by Ionizing** [comment]
> Would 20 or 25 minutes work instead?

Okay, 25 minutes may solve it. If it still fails I would try other solutions.

> please first set targets = [] in package.metadata.docs.rs

Okay, I'll fix it soon.

**Comment by jyn514** [comment]
In the meantime I can limit it in production so you don't have to make a new release.

**Comment by Ionizing** [comment]
Thank you very much~

**Comment by Ionizing** [comment]
It seems the doc build is completed successfully, thanks for your help!
