### ISSUE TITLE
Wrong readme showing on landing page

### ISSUE THREAD

**Issue by timkaas** [rust-lang/docs.rs#1008]
When searching for my crate on docs.rs I'm directed to the following page <https://docs.rs/relativedelta/0.2.1/relativedelta/>.
But the usage shows version relativedelta = "0.1", despite it being version 0.2.1, and version 0.1 being yanked
However, when looking at the crate from this page <https://docs.rs/crate/relativedelta/0.2.1> the correct readme is shown, which shows version relativedelta = "0.2"

It is unclear where this version info is taken from, as I cant find anything in my source or readme which should refer to the old version. Or why the readme in its entirety is not shown on the first landing page.

**Comment by Nemo157** [comment]
The first link is the library documentation, generated by rustdoc from <https://docs.rs/crate/relativedelta/0.2.1/source/src/lib.rs>.

**Comment by timkaas** [comment]
Ahh jeez - thanks
