### ISSUE TITLE
Add crates to the database before building them

### ISSUE THREAD

**Issue by jyn514** [rust-lang/docs.rs#1011]
Right now, all targets are built before the crate is added to the database. We should change this:

- We could avoid having documentation on S3 that isn't deleted if the queue reader panics and doesn't add the crate to the database (https://github.com/rust-lang/docs.rs/pull/928#discussion_r464969159) - if a panic or crash happens, we can delete the documentation the next time the server starts up.

- We could display documentation for the default target before all crates have finished being built. After that, we would upload each target as it completes.

- We could show which crate is currently being built. Currently, the queue looks like this: 
![image](https://user-images.githubusercontent.com/23638587/91477102-e89d7780-e86b-11ea-9d5f-c7e53ed38ac0.png)

This shows the crates that are scheduled, but doesn't say which is currently being built. You can usually infer that it's the first in the queue, but this isn't always the case - sometimes a crate will be de-prioritized while building, so it will show up at the bottom of the queue even though it's currently being built.

It would be great to show
a) which crate is being built
b) a link on /:crate/:version to the build queue

**Comment by pietroalbini** [comment]
This would also allow to create a "crate is queued to be built" page in `https://docs.rs/:crate`, while we wait for the first version of a crate to be published.
