### ISSUE TITLE
meta: Cargo.toml package info seems out-of-date

### ISSUE THREAD

**Issue by camelid** [rust-lang/docs.rs#1030]
I don't know if this is intentional, but the name of the `docs.rs` crate is still `cratesfyi` and the author is Onur Aslan:

https://github.com/rust-lang/docs.rs/blob/49099068e383bacb67f775537d3e61a3f58919e0/Cargo.toml#L1-L4

Shouldn't the name be `docs-rs` or something and the author be `The Rust Project Developers` like with the rustc crates?

**Comment by jyn514** [comment]
This would be a good first PR :)

**Comment by jyn514** [comment]
Oh - but please leave the name of the binary as `cratesfyi`, or we'll have to change all the scripts in prod.

**Comment by jyn514** [comment]
See also #244.

**Comment by camelid** [comment]
No rustbot, but still:

@rustbot claim

**Comment by camelid** [comment]
Should I update the sub-crate `Cargo.toml` files? Including the `cratesfyi` one, it would be:

* https://github.com/rust-lang/docs.rs/blob/49099068e383bacb67f775537d3e61a3f58919e0/Cargo.toml
* https://github.com/rust-lang/docs.rs/blob/49099068e383bacb67f775537d3e61a3f58919e0/metadata/Cargo.toml
* https://github.com/rust-lang/docs.rs/blob/49099068e383bacb67f775537d3e61a3f58919e0/src/web/badge/Cargo.toml

**Comment by jyn514** [comment]
Hmm ... @rust-lang/docs-rs how do you feel about changing the `authors` field in all the packages to `The Rust Project Developers` or something similar? That's what rustc does: https://github.com/rust-lang/rust/blob/7dfbf59f100c52e991796739ff21b9720219703f/compiler/rustc/Cargo.toml#L2

**Comment by pietroalbini** [comment]
I'd *add* "The Rust Project Developers" in addition to Onur. They still created the project, and that should be credited.

**Comment by camelid** [comment]
So something like this then?

```toml
authors = ["Onur Aslan <...>", "The Rust Project Developers"]
```

(And the same sort of change for the inner crates.)

Rustfmt does it that way, but has `The Rustfmt developers` as the second author. Should we do `The docs.rs Developers` or go with `The Rust Project Developers`? Personally I think it might be better to go with `The Rust Project Developers` since we're all part of the Rust project and so it's the same authors.

**Comment by jyn514** [comment]
I like "The Rust Project Developers" but I don't feel strongly about it.

**Comment by Kixiron** [comment]
Wouldn't this be a good place to use the Docs.rs Team?

**Comment by pietroalbini** [comment]
I think "The Rust Project Developers" is the most appropriate here.

**Comment by camelid** [comment]
Opened #1039.
