### ISSUE TITLE
Sandbox limits increase request for rza1

### ISSUE THREAD

**Issue by yvt** [rust-lang/docs.rs#1031]
**Crate name:** `rza1`
**Build failure link:** https://docs.rs/crate/rza1/0.1.0/builds/289059

**Requested RAM limit:** 6GB
**Requested timeout:** 15 min is OK

**Why your crate needs the resource increases:**
`rza1` is a typical `svd2rust`-generated peripheral access crate and hence it's very resource-intensive to documentate.

**Comment by jyn514** [comment]
@yvt Do you need multiple targets? If not I'm going to limit it to just the default to avoid too much strain on our resources. Otherwise this seems fine.

**Comment by yvt** [comment]
@jyn514 No, we don't need multiple targets. (Actually, I've heard about it somewhere else and already [disabled](https://github.com/rz-rs/rza1/commit/52007f62b1d37604969fd5dae5d3d275883ee982) non-default targets, though this change hasn't been published yet).

**Comment by jyn514** [comment]
Raised the limit and rebuilt the crate so you don't need to publish a new version :) https://docs.rs/rza1/0.1.0/rza1/

**Comment by yvt** [comment]
Thank you!
