### ISSUE TITLE
Sandbox limits increase request for stm32mp1 crate

### ISSUE THREAD

**Issue by adamgreig** [rust-lang/docs.rs#1037]
**Crate name:** stm32mp1
**Build failure link:** https://docs.rs/crate/stm32mp1/0.11.0/builds/290188

**Requested RAM limit:** 8GB
**Requested timeout:** 15min
**Requested number of targets:** 1

**Why your crate needs the resource increases:**

Related to #608, we've added support for a new family of microcontrollers with this new crate. As with the other crates, since the device has a large number of registers the crate has many functions and so takes a fair bit of RAM to document.

In a local sandbox I measured 3.8GB RAM usage; I've requested 8GB to align with the other related crates as I anticipate we'll be adding a couple more devices to this crate soon which could increase its usage. For now 5GB would also just about work though.

As ever thanks for running docs.rs!

**Comment by jyn514** [comment]
I updated the limits to 6 GB memory and 1 target. Let me know if 6 GB isn't enough after adding more microcontrollers and I can bump it more.

I also queued and rebuilt 0.11.0 so you don't have to publish a new version :) https://docs.rs/stm32mp1/0.11.0/stm32mp1/
