### ISSUE TITLE
Show different message than 'Go to latest version' on pre-releases

### ISSUE THREAD

**Issue by Kixiron** [rust-lang/docs.rs#1044]
We automatically redirect to the first non-prerelease version when available, but on pre-release versions we still display the "Go to latest version" box in the tab, see [sqlx v0.4.0-beta.1](https://docs.rs/sqlx/0.4.0-beta.1/sqlx/index.html)

**Comment by Nemo157** [comment]
I think the link/warning should still be displayed, but changed wording to something like "Go to stable version".
