### ISSUE TITLE
Underscore/Dash in crate name

### ISSUE THREAD

**Issue by NickeZ** [rust-lang/docs.rs#105]
Hi,

I think the following should be supported: `https://docs.rs/tokio_core`.

Today I have to write `https://docs.rs/tokio-core` to end up at `https://docs.rs/tokio-core/0.1.4/tokio_core/`

**Comment by ruuda** [comment]
It would be nice to at least consider `-` and `_` to be equivalent for search. Currently, searching for e.g. `lazy-static` turns up no results even though a `lazy_static` crate does exist, and it is probably what the user was looking for.

**Comment by dtolnay** [comment]
:+1: https://crates.io/crates/tokio-core and https://crates.io/crates/tokio_core already refer to the same crate, so https://docs.rs/tokio-core and https://docs.rs/tokio_core should as well.

**Comment by Folyd** [comment]
Any progress on this issue? Kind of annoy that https://docs.rs/async_std show `The requested resource does not exist`, but https://docs.rs/async-std is redirected success to https://docs.rs/async-std/1.5.0/async_std/.

**Comment by jyn514** [comment]
@Folyd there is an open PR for this feature, but it needs changes and hasn't been updated by the author: #348
