### ISSUE TITLE
db error in Getting started

### ISSUE THREAD

**Issue by giraffate** [rust-lang/docs.rs#1054]
The following error happens when creating the first crate in https://github.com/rust-lang/docs.rs#getting-started. This error was resolved after migration command `cargo run -- database migrate`. Is these command execution order reversed?

```
$ cargo run -- build crate regex 1.3.1
(snip)
db error: ERROR: relation "blacklisted_crates" does not exist
```

**Comment by jyn514** [comment]
Hmm, those migrations should have been run automatically. Did you have an existing docs.rs clone from a while ago?

**Comment by giraffate** [comment]
I first have a docs.rs clone a month ago and ran the command up to `docker-compose up -d db s3` at that time. And, I ran the command of createing first crate a while ago.

**Comment by jyn514** [comment]
Ok, so the bug then is that the cache invalidation is wrong, it should rerun the migrations when there are changes, not just the first time.

**Comment by giraffate** [comment]
Ok, thanks for your info!

**Comment by jsha** [comment]
FYI, I just got this error when doing a totally fresh checkout of docs.rs. I think it was because the README.md instructions say to run `cargo run -- build crate regex 1.3.1` before `cargo run -- database migrate`. I ran the migrate, and now the `build crate` command succeeds.
