### ISSUE TITLE
404 for favicon on recent docs

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/docs.rs#1070]
e.g. https://docs.rs/chrono/0.4.18/chrono/

Since nightly-2020-09-26 it appears that rustdoc is using a `.svg` favicon, which isn't being stored as part of the essential files.

**Comment by icp1994** [comment]
Is the change not live yet? The chrono favicon still doesn't load for me.

**Comment by jyn514** [comment]
@icp1994 that's #464. I'll see if I can rebuild chrono manually sometime today.
