### ISSUE TITLE
Pagination links are broken when viewing releases by author

### ISSUE THREAD

**Issue by connec** [rust-lang/docs.rs#1073]
When viewing the releases for an author at `https://docs.rs/releases/{author}/` the pagination links are incorrectly set to `/releases/author/{n}`.

This would seem to be a bug in the construction of `page_link` [here](https://github.com/rust-lang/docs.rs/blob/38ba774e14eb4f658d834218d003583e423c5f37/templates/releases/releases.html#L60), which is then interpolated into the pagination links [here](https://github.com/rust-lang/docs.rs/blob/38ba774e14eb4f658d834218d003583e423c5f37/templates/releases/releases.html#L66) and [here](https://github.com/rust-lang/docs.rs/blob/38ba774e14eb4f658d834218d003583e423c5f37/templates/releases/releases.html#L72).

Presumably, if the `release_type` is `"author"`, then `page_link` should instead be set to `"/releases/" ~ author`.

**Comment by jyn514** [comment]
@connec are you interested in working on this yourself? It looks like you already have a good idea of how to fix it :)

**Comment by connec** [comment]
@jyn514 I haven't started anything yet as I don't have time right now to establish a build environment to validate my suggested fix. I may get around to it, but I wouldn't want to put off anyone else's efforts!
