### ISSUE TITLE
dns error

### ISSUE THREAD

**Issue by mosuka** [rust-lang/docs.rs#1078]
**Crate name:** lindera
**Build failure link:** https://docs.rs/crate/lindera/0.6.0/builds/300984

**Additional details:** It fails to download data from Google Drive in build.rs due to DNS error.
But Tthe local build succeeds.
Is it possible for you to solve this problem?

**Comment by jyn514** [comment]
This is intended behavior, we don't allow internet access in the builds.

**Comment by mosuka** [comment]
@jyn514 Thank you for your confirmation.

**Comment by Manuel030** [comment]
For anyone else facing issues with downloads in custom build scripts:

You can disable builds on doc.rs to use default features:

```
[package.metadata.docs.rs]
no-default-features = true
```

Simply hide your download in a default feature and compile conditionally in `build.rs` like so:

```
#[cfg(feature = "download-stuff")]
download_stuff();

```
