### ISSUE TITLE
Pressing space to close a header menu (navigating with keyboard instead of mouse) will scroll down the page, not just close the menu

### ISSUE THREAD

**Issue by jyn514** [rust-lang/docs.rs#1082]
_Originally posted by @jyn514 in https://github.com/rust-lang/docs.rs/pull/1081#issuecomment-705666955_

**Comment by GuillaumeGomez** [comment]
It's not a bug. If you an interaction with just the item and nothing else, you have the "enter" key. Space is supposed to scroll except when in a text field.

**Comment by jyn514** [comment]
@GuillaumeGomez space should either scroll or open them enu. It shouldn't do both.

**Comment by GuillaumeGomez** [comment]
I'd argue it definitely should. :p

**Comment by GuillaumeGomez** [comment]
Or more like: we shouldn't handle this ourselves.

**Comment by jyn514** [comment]
If you want to remove space handling and make it so you can only open the menu with enter, I'm fine with that. But the current behavior is not at all helpful or expected.

**Comment by GuillaumeGomez** [comment]
It's definitely expected. If I use space and I'm not in a text field, it's supposed to scroll down.

**Comment by notriddle** [comment]
> It's not a bug. If you want an interaction with just the item and nothing else, you have the "enter" key. Space is supposed to scroll except when in a text field.

I've opened a pull request that traps the space key entirely. I'm willing to entertain the possibility of not handling the spacebar at all, too:

* The example set [by WAI](https://www.w3.org/TR/wai-aria-practices-1.1/examples/menubar/menubar-1/menubar-1.html) and by the menus on GitHub both trap space. I don't want to deviate from industry consensus without very good reason.

* Enter still acts as "link click" when the right-side drop down menus are selected.
