### ISSUE TITLE
docs.rs pages are left-aligned

### ISSUE THREAD

**Issue by jyn514** [rust-lang/docs.rs#1084]
This is a regression introduced by https://github.com/rust-lang/docs.rs/pull/1079 - only the /crate pages should be left-aligned, not /about and index. cc @jsha , do you think you have time to follow-up and fix this? I think a simple fix would be to only apply left-aligns to /crate pages, not sure if we have custom CSS for them yet but it shouldn't be too hard to add.

**Comment by jsha** [comment]
Oops, sorry about that! I'll send a fix.
