### ISSUE TITLE
An error during template rendering could throw the server into an infinite loop

### ISSUE THREAD

**Issue by Kixiron** [rust-lang/docs.rs#1087]
We have a call to `ctry!` within [`WebPage::into_response`](https://github.com/rust-lang/docs.rs/blob/master/src/web/page/web_page.rs#L44-L52), which means that if the rendering of a template fails we call `WebPage::into_response` on an `ErrorPage`. I'm not really sure what conditions would have to line up in order for it to happen, but it's possible that the server could get into an infinite loop of rendering and failing templates which wouldn't be good

**Comment by jyn514** [comment]
That could only happen if the error page itself fails to render. Since we test the error page, I don't think this is an issue in practice.

**Comment by Kixiron** [comment]
Agreed, it's super unlikely to happen, but it is a possible footgun

**Comment by jyn514** [comment]
Yup, you're right, this sends the server into an infinite loop:
```diff
diff --git a/templates/error.html b/templates/error.html
index e7685ec..6a1b855 100644
--- a/templates/error.html
+++ b/templates/error.html
@@ -9,4 +9,5 @@
     <div class="description">
         {{ message | default(value="") }}
     </div>
+    {{ oops }}
 {%- endblock header -%}
```
and then fetching `/not_here`.

**Comment by jyn514** [comment]
I think it might honestly better to just panic in that case; that way it only crashes a single request instead of locking up the server. We test errors anyway so it shouldn't ever happen in prod.
