### ISSUE TITLE
Summary of re-exports not shown

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/docs.rs#1088]
Some of the generated docs on docs.rs have been affected by https://github.com/rust-lang/rust/issues/77783. Please rebuild the docs with the next nightly.

In particular: https://docs.rs/trait-union/0.1.4/trait_union/index.html

**Comment by jyn514** [comment]
I requeued the affected crates: https://docs.rs/releases/queue

For posterity, the command I used was

```sql
SELECT name, version FROM crates
        INNER JOIN releases ON crates.id = releases.crate_id
        INNER JOIN builds ON releases.id = builds.rid
where rustc_version like '%2020-10-11%' and not exists(select * from queue where name = crates.name);
```
