### ISSUE TITLE
Unify dashes and underscores in search

### ISSUE THREAD

**Issue by phil-opp** [rust-lang/docs.rs#1101]
The docs.rs search function doesn't always unify dashes and underscores right now. For example, [a search for `serde-j` ](https://docs.rs/releases/search?query=serde-j) yields crates like `serde-json-core` or `tokio-serde-json-mirror` , but not the `serde_json` crate. The [search on crates.io](https://crates.io/search?q=serde-j) does not seem to have this problem.

(Originally reported [on internals.rust-lang.org](https://internals.rust-lang.org/t/pre-rfc-unify-dashes-and-underscores-on-crates-io/13216/5?u=phil_opp)).

**Comment by Kixiron** [comment]
This could be solved with nothing more than a `query.replace('-', '_')` (as much as I don't like the allocation), but the behavior looks stranger than that so I'll investigate to see if that actually helps things any

**Comment by jyn514** [comment]
Fixed by https://github.com/rust-lang/docs.rs/pull/1521.
