### ISSUE TITLE
"Platform" button unresponsive with no targets

### ISSUE THREAD

**Issue by XAMPPRocky** [rust-lang/docs.rs#1111]
The platform button in the navbar currently gives no feedback if there are no platforms. I feel it would more appropriate to display something or hide the button entirely.

- Example crate: https://docs.rs/crate/timeago-cli/0.1.3

**Comment by jyn514** [comment]
Mentoring instructions: In https://github.com/rust-lang/docs.rs/blob/5f4f6cf533e8e5db478df55fc6918855c1b135fd/templates/header/package_navigation.html#L43-L44
check whether `platforms` is empty, not whether it is truthy. https://tera.netlify.app/docs/#control-structures
