### ISSUE TITLE
Custom favicons and logos result in third-party requests

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/docs.rs#1114]
Loading <https://docs.rs/http-types/2.6.0/http_types/> results in requests to <https://yoshuawuyts.com/assets/http-rs/logo-rounded.png> and <https://yoshuawuyts.com/assets/http-rs/favicon.ico> for the logo and favicon. It seems like we should be proxying these similar to github.

**Comment by jyn514** [comment]
I remember seeing an issue for this a while ago, but I can't find it any more :( I don't think it was https://github.com/rust-lang/docs.rs/issues/921, there was something else.

**Comment by jyn514** [comment]
It was https://github.com/rust-lang/docs.rs/issues/66
