### ISSUE TITLE
x86_64-unknown-linux-gnu missing from Platform list

### ISSUE THREAD

**Issue by bbqsrc** [rust-lang/docs.rs#1119]
**Crate name:** pathos 0.2.0

**Additional details:**

My Cargo.toml contains this:

```
[package.metadata.docs.rs]
targets = [
    "aarch64-apple-ios",
    "aarch64-linux-android",
    "x86_64-apple-darwin",
    "x86_64-pc-windows-msvc",
    "x86_64-unknown-linux-gnu",
]
```

Docs.rs shows this:

<img width="184" alt="image" src="https://user-images.githubusercontent.com/279099/97082541-c7a69800-160a-11eb-9bce-4b8f3c4a362f.png">

`x86_64-unknown-linux-gnu` has gone missing, and there's no build error. 😄

**Comment by jyn514** [comment]
Well this is odd. The target builds successfully:
```
[DEBUG] docs_rs::docbuilder::rustwide_builder: building package pathos 0.2.0 for x86_64-unknown-linux-gnu
[INFO] rustwide::cmd: running `Command { std: "/home/cratesfyi/workspace/cargo-home/bin/cargo" "+nightly" "metadata" "--format-version" "1", kill_on_drop: false }`
[INFO] rustwide::cmd: running `Command { std: "docker" "create" "-v" "/home/cratesfyi/workspace/builds/pathos-0.2.0/target:/opt/rustwide/target:rw,Z" "-v" "/home/cratesfyi/w
:58.937104814Z" level=warning msg="Your kernel does not support swap limit capabilities,or the cgroup is not mounted. Memory limited without swap."
[INFO] rustwide::cmd: [stdout] 3e6456721a870907005c0169402a51fce28f270b574684c5b69053d8eb1c898a
[INFO] rustwide::cmd: [stderr] WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
[INFO] rustwide::cmd: running `Command { std: "docker" "start" "-a" "3e6456721a870907005c0169402a51fce28f270b574684c5b69053d8eb1c898a", kill_on_drop: false }`
:04:59.047635476Z" level=info msg="shim containerd-shim started" address="/containerd-shim/moby/3e6456721a870907005c0169402a51fce28f270b574684c5b69053d8eb1c898a/shim.sock" d
... snip ...
[INFO] rustwide::cmd: [stderr]  Documenting pathos v0.2.0 (/opt/rustwide/workdir)
[INFO] rustwide::cmd: [stderr]     Finished dev [unoptimized + debuginfo] target(s) in 3.17s
```
but it never gets added to the database, docs.rs just starts building the next target instead:
```
[DEBUG] docs_rs::docbuilder::rustwide_builder: building package pathos 0.2.0 for x86_64-pc-windows-msvc
```
and that target does get added:
```
[DEBUG] docs_rs::docbuilder::rustwide_builder: adding documentation for target x86_64-pc-windows-msvc to the database
```

**Comment by jyn514** [comment]
I don't think it's related to this bug, but this logic is also wrong: https://github.com/rust-lang/docs.rs/blob/0e83b5db13b5adb6f99fafff6d60a6ad49a369ec/src/docbuilder/rustwide_builder.rs#L328-L334
It hardcodes that the default target is the host, which is not correct.

**Comment by jyn514** [comment]
One of these two conditions isn't being taken: https://github.com/rust-lang/docs.rs/blob/0e83b5db13b5adb6f99fafff6d60a6ad49a369ec/src/docbuilder/rustwide_builder.rs#L429-L433

**Comment by jyn514** [comment]
This turned out to be https://github.com/rust-lang/docs.rs/issues/1556 - since you put aarch64-apple-ios first, it ended up as the default target. https://github.com/rust-lang/docs.rs/pull/1559 should fix it.
