### ISSUE TITLE
Hide yanked crate versions.

### ISSUE THREAD

**Issue by dpc** [rust-lang/docs.rs#112]
Recently crates.io added quite a bit of fixes around yanked crates. Eg. when the latest version were yanked, the default one will be first version that is not yanked.

Also, generally skipping yanked versions in UI elements would be great. They can still be displayed if explicitly picked through a URL though.

**Comment by crumblingstatue** [comment]
I agree that docs.rs should at least warn the user if they are looking at the docs for a yanked crate.

I often don't even look at crates.io anymore, and just copy the version straight from docs.rs.

Except I didn't realize that the version I copied has been yanked.

**Comment by cramertj** [comment]
Relatedly, the `https://docs.rs/<crate_name>` link should probably go to the latest non-yanked version. For example,  https://docs.rs/futures  currently points to `futures` 0.2.1, which was yanked.

cc @onur
