### ISSUE TITLE
Weird build failure from cargo in microkelvin 0.4.0

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/docs.rs#1133]
**Crate name:** microkelvin
**Build failure link:** https://docs.rs/crate/microkelvin/0.4.0/builds/309422

**Additional details:** 
Not my crate, but I noticed this randomly. It is `cargo` that is emitting the error here, it seems to think it needs to re-extract `const-arrayvec` even though it's already extracted.

**Comment by jyn514** [comment]
This is a cargo bug, right? Shouldn't it be reported upstream? I don't think it should ever touch `registry/src` once it's been populated the first time.

**Comment by Nemo157** [comment]
I think so, I'm gonna take a closer look later and probably open an upstream issue, but just in case it's something we're doing wrong.

**Comment by Nemo157** [comment]
This was just fixed on the cargo side, once there's a new version of cargo in a nightly we could retry `microkelvin` and see if it builds now.

**Comment by jyn514** [comment]
This is waiting on https://github.com/rust-lang/rust/pull/78972.

**Comment by jyn514** [comment]
I rebuilt it; it gave a compile error but nothing from cargo.

https://docs.rs/crate/microkelvin/0.4.0/builds/317833
