### ISSUE TITLE
The maximum width for the top bar is broken when "go to latest version" element appears

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/docs.rs#1135]
![Screenshot from 2020-10-27 16-49-47](https://user-images.githubusercontent.com/3050060/97327002-dabca080-1874-11eb-8881-7b5ce6071de8.png)

Another thing that could have the same result is the crate name: we should give it a fixed width, whatever the crate name's length.

**Comment by arusahni** [comment]
@jyn514 @GuillaumeGomez this may have been addressed by #1232 as well.
