### ISSUE TITLE
Search identifiers directly in a future version

### ISSUE THREAD

**Issue by crlf0710** [rust-lang/docs.rs#114]
I wonder if it is possible to search a specific struct or constant or trait directly from the front page...

**Comment by Kixiron** [comment]
This would be much to intensive and complex to do, as it would require every search to search the entirety of our inventory which is A. Stored in S3 which would require downloading it all and B. Over 200k crates worth of documentation. These two things make it impossible computationally and far too costly

**Comment by jyn514** [comment]
I would like to support searching in dependencies eventually (https://github.com/rust-lang/docs.rs/issues/494), which might be close to your use case.
