### ISSUE TITLE
Add a place for discussion about each crate?

### ISSUE THREAD

**Issue by crlf0710** [rust-lang/docs.rs#115]
Just like reddit but for each crate.

**Comment by dtolnay** [comment]
What sort of discussions are you imagining? I would expect that most discussion would happen on the crate's issue tracker or IRC.

**Comment by onur** [comment]
When I first started this project I was planning to add something like [cpanratings](http://cpanratings.perl.org/). But IMO features like this should be available in crates.io. Docs.rs will only provide documentation of crates, I am not trying to replace crates.io just providing an easy way to access documentations.

**Comment by crlf0710** [comment]
@dtolnay I'm imagining things like:
1. In clippy's discussion: the nightly version of rustc supported which people should use to compile and run it. (Should be pinned to the top)
2. In each crate's discussion: what people used it think of it. Its pros and cons. Traps and rough edges previous people using it falls into and should be careful (not necessarily a bug).
3. Some crates are no longer supported by their authors - Looking for help or just deprecating.

@onur I understand. But i also look forward for crates.io have some kind of integration of all these above and the docs.rs site too. Don't really want to jump between crates.io and docs.rs back and forth from my personal view.

**Comment by jyn514** [comment]
I don't think this is in scope for docs.rs. If you want to discuss rust crates, you can post on users.rust-lang.org/.
