### ISSUE TITLE
My crate depends on the win32 api on windows, therefor it fails to build

### ISSUE THREAD

**Issue by bamilab** [rust-lang/docs.rs#1153]
**Crate name:**
browser-window

**Build failure link:**
https://docs.rs/crate/browser-window/0.0.5/builds/311087

**Additional details:**
My crate depends on browser-window-ffi, which only works on Windows at the moment. browser-window-ffi is a crate that contains ffi bindings to c/c++ code that's contained in that crate. It uses the win32 API and so it includes windows.h within C. Also, it uses an external C++ library (CEF3), which the developer needs to setup manually. Right now the build fails because windows.h is not found, which makes sense because it isn't build on a windows machine. But I think it will still fail because cef3 headers won't be found of course.

**Comment by jyn514** [comment]
@bamilab does it work if you set `default-target = "x86_64-pc-windows-msvc"`? https://docs.rs/about/metadata, https://github.com/retep998/winapi-rs/blob/0.3/Cargo.toml#L15

**Comment by jyn514** [comment]
>  I think it will still fail because cef3 headers won't be found of course

You can add them to the build environment by making a PR to crates-build-env: https://forge.rust-lang.org/docs-rs/add-dependencies.html

**Comment by bamilab** [comment]
No, I have this in the Cargo.toml of browser-window and browser-window-ffi:

[package.metadata.docs.rs]
all-features = true
default-target = "x86_64-pc-windows-msvc"
targets = ["x86_64-pc-windows-msvc", "i686-pc-windows-msvc"]

**Comment by bamilab** [comment]
> 
> 
> > I think it will still fail because cef3 headers won't be found of course
> 
> You can add them to the build environment by making a PR to crates-build-env: https://forge.rust-lang.org/docs-rs/add-dependencies.html

I cloned the git repo and saw there is a windows directory in which is explained that vcpkg packages can be added.
This is just what I need.

So if I create a pull request does that mean that docs.rs will change their windows build environment to have cef3 somewhere on their system?
Also, there still seems to be the problem that docs.rs tries to build it on a linux machine with x86_64-pc-windows-msvc as the target.

**Comment by bamilab** [comment]
I find it weird that the crate winapi is having no problems though..

**Comment by jyn514** [comment]
@bamilab the windows directory is not used for docs.rs. All windows builds are cross-compiled.

I'm not sure why works either.

**Comment by bamilab** [comment]
I've found a temporary solution.

I've basically added this to the beginning of my build.rs file's main function:

`if let Ok(_) = env::var("DOCS_RS") {
		return
	}`

Which means that if docs.rs build my crate, it actually build nothing, which succeeds. :D

**Comment by jyn514** [comment]
Sounds like it works! Do you want to keep the issue open, since your docs are now showing up?

**Comment by bamilab** [comment]
Hmmm. I think it might still be usefull to keep this open. I mean, there got to be someone else eventually who needs his crate published, but depends on some external c lib that docs.rs doesn't recognize. Maybe a more elegant solution needs to be made available for those cases?

**Comment by jyn514** [comment]
There is no general purpose solution for "my rust crate needs system dependencies that aren't installed". I'd rather have each issue tracked individually.
