### ISSUE TITLE
Background color for code blocks on some docs don't match the page

### ISSUE THREAD

**Issue by jyn514** [rust-lang/docs.rs#1155]
https://docs.rs/rusty_v8/0.11.0/rusty_v8/struct.Local.html
![image](https://user-images.githubusercontent.com/23638587/97931378-78afdf80-1d3b-11eb-8bf1-0734c4a0ce5c.png)

I think it's something to do with changing rustdoc styles, since new docs look fine: https://docs.rs/tokio/0.3.3/tokio/runtime/struct.Runtime.html#trait-implementations
![image](https://user-images.githubusercontent.com/23638587/97931462-a39a3380-1d3b-11eb-9cb3-98f255ed7424.png)

Thanks to @RDambrosio016 for the bug report!

**Comment by Nemo157** [comment]
It's a bug in the source (or the rustdoc markdown handling), [this line](https://docs.rs/rusty_v8/0.11.0/src/rusty_v8/handle.rs.html#46) opens an `<object>` element and doesn't close it, resulting in the rest of the page being nested under the `object` and applying the wrong styles in some locations.

**Comment by jyn514** [comment]
I'll close this in favor of the upstream bug, then.
