### ISSUE TITLE
Ban crawlers from following `target-redirect` urls

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/docs.rs#1161]
If we update the "Platform" drop-down on the crate page to link directly (since the root page is guaranteed to exist on all targets and doesn't need checking) then we could probably ban crawlers from the `target-redirect` urls since they create a very dense, uninteresting, mesh of interlinking redirects.

**Comment by syphar** [comment]
@Nemo157 I guess this issue can be closed, right?

**Comment by Nemo157** [comment]
👍
