### ISSUE TITLE
Wrong --extern-html-root-url key used

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/docs.rs#1166]
https://github.com/rust-lang/docs.rs/blob/9ca26817b38453ee4fec7e1330bbd734174a87ed/src/docbuilder/rustwide_builder.rs#L525

This should almost certainly be `dep.library_name()` or something similar, to handle dependencies which rename their library (I don't know of any example build logs to see if it's an issue though). See https://github.com/rust-lang/rust/issues/76296 as well, we can't actually give a unique name here when things like duplicate renamed dependencies come into play.

**Comment by jyn514** [comment]
Rustdoc expects the library name anyway, we can't do anything about that until https://github.com/rust-lang/rust/issues/76296 is fixed. We definitely shouldn't be using `.replace()` though.
