### ISSUE TITLE
What Operating System are the Crate Builds Done On?

### ISSUE THREAD

**Issue by nevalackin** [rust-lang/docs.rs#1167]
Refer to title.
Not an issue, however I didn't know where else to ask this so I decided to ask here.

**Comment by pietroalbini** [comment]
We're building the crates on Ubuntu inside [this Docker image](https://github.com/rust-lang/crates-build-env), which contains a bunch of preinstalled packages. If you need an extra dependency installed you can open an issue or PR there.

**Comment by nevalackin** [comment]
Can you change the operating system crates are built on by changing the default-target in [package.metadata.docs.rs]?
e.g. 

```
[package.metadata.docs.rs]
default-target = "x86_64-pc-windows-msvc"
```

**Comment by pietroalbini** [comment]
We still build the crates on Ubuntu, we just cross-compile the documentation.

**Comment by jyn514** [comment]
> I didn't know where else to ask this so I decided to ask here.

We should probably link to the discord page on https://docs.rs/about, we have a link on https://www.rust-lang.org/governance/teams/dev-tools#docs-rs but that's hard to find.

> We still build the crates on Ubuntu, we just cross-compile the documentation.

That should probably be documented on https://docs.rs/about/builds.

@nevalackin are you interested in making those changes? They'd go in https://github.com/rust-lang/docs.rs/tree/master/templates/core/about.

**Comment by jyn514** [comment]
> We should probably link to the discord page on https://docs.rs/about, we have a link on https://www.rust-lang.org/governance/teams/dev-tools#docs-rs but that's hard to find.

It turns out we already have a link in #contact at the bottom of https://docs.rs/about. I'm not sure what more we could do here :/

**Comment by jyn514** [comment]
Fixed in https://github.com/rust-lang/docs.rs/pull/1189.
