### ISSUE TITLE
Go to latest version should keep Fragment Identifiers

### ISSUE THREAD

**Issue by Nokel81** [rust-lang/docs.rs#1168]
Similar to #944

**Comment by jyn514** [comment]
Mentoring instructions: similar to query urls, if there is a hash fragment in the URL, add it to the rewritten url: https://github.com/rust-lang/docs.rs/blob/master/src/web/rustdoc.rs#L399-L402

Please also add a test, there's an example in https://github.com/rust-lang/docs.rs/blob/master/src/web/rustdoc.rs#L399-L402.

**Comment by Nemo157** [comment]
Fragments aren't sent to the server. I don't know if there's a flag we can add to the redirect to say to preserve fragments, or if this is just fundamentally not possible.

**Comment by pietroalbini** [comment]
A thing we could do is turn the fragment into a query parameter with JS when the user clicks the link, but dunno how well it will work.

**Comment by Nemo157** [comment]
Oh, wait, this isn't from the redirect. We would need to have something like some JS that copies the fragment off the current url into the `href` of the url when the link is clicked.
