### ISSUE TITLE
`rustdoc-args = [ "--cfg docsrs" ]` no longer works

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/docs.rs#1170]
**Crate name:** adler
**Build failure link:** https://docs.rs/crate/adler/1.0.0/builds/313381

**Additional details:**
This used to work fine on the previous version, 0.2.3: https://docs.rs/adler/0.2.3/adler/

**Comment by Nemo157** [comment]
That working was a bug https://github.com/rust-lang/docs.rs/issues/1038, I probably should have opened an issue for you to fix it since that build was the one I noticed it in 😓. You can use either `["--cfg=docsrs"]` or `["--cfg", "docsrs"]` for it.

**Comment by jonas-schievink** [comment]
Yes, that would have been useful. I can't believe I'm the only one who did this :sweat_smile:
