### ISSUE TITLE
xosd-sys failed to build

### ISSUE THREAD

**Issue by Chronophylos** [rust-lang/docs.rs#1171]
**Crate name:** xosd-sys
**Build failure link:** https://docs.rs/crate/xosd-sys/2.2.14/builds/313339

**Additional details:** I added the missing dependency to `crates-build-env`. The build should work if restarted.

**Comment by jyn514** [comment]
Queued and rebuilt: https://docs.rs/xosd-sys/2.2.14/xosd_sys/

**Comment by Chronophylos** [comment]
Thank you
