### ISSUE TITLE
Add support for multiple sitemaps

### ISSUE THREAD

**Issue by jsha** [rust-lang/docs.rs#1174]
Per https://support.google.com/webmasters/answer/183668?hl=en&ref_topic=4581190,

> All formats limit a single sitemap to 50MB (uncompressed) and 50,000 URLs.

The current sitemap at https://docs.rs/sitemap.xml is 5.3MB (fine) and 41,000 URLs. Soon the size of the Rust ecosystem will grow to the point that additional sitemaps are needed.

**Comment by jsha** [comment]
I saw an announcement today that crates.io had reached 50,000 crates: https://twitter.com/rustlang/status/1331020962628767748. That made me think of this issue again. The sitemap is still only at 41,617 URLs, though. Purely out of curiosity, any idea why the discrepancy?

**Comment by jyn514** [comment]
Hmm, that sounds like the sitemap is buggy:

```
cratesfyi=> select count(*) from crates;
 count 
-------
 50938
```

**Comment by njasm** [comment]
Out of those 50k, how many of them have their latest version yanked?

(I expect not have crates in the site map where the latest published version is yanked)

**Comment by jyn514** [comment]
Rather than guessing, you can just read the source ;)

https://github.com/rust-lang/docs.rs/blob/master/src/web/sitemap.rs#L27

The difference is that docs.rs doesn't include crates that failed to build in the sitemap.

**Comment by njasm** [comment]
sweet! :)

**Comment by syphar** [comment]
I created #1222 as a potential solution, up to discussion of course.

**Comment by camelid** [comment]
Should this be closed since #1222 has been merged?

**Comment by jyn514** [comment]
Let's wait until #1222 is deployed.

**Comment by Nemo157** [comment]
Is there some way to verify google's view of the sitemaps after deployment?

**Comment by syphar** [comment]
in google webmaster tools, yes. 

Also you can ping them to directly load the sitemap and see the result, if I remember correctly.
