### ISSUE TITLE
Renamed optional dependencies get the wrong feature name recorded

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/docs.rs#1175]
`async-compression 0.3.6` has a `tokio-02` and a `tokio-03` optional dependency, but these both get recorded and displayed as `tokio`. Dumping out of the database I see:

```
{
  ...
  "(all-implementations,\"{futures-io,stream,tokio-02,tokio-03}\")",
  ...
  "(tokio,{})",
  "(tokio,{})",
  ...
}
```

So `all-implementations` depends on `tokio-02` and `tokio-03`, but the optional dependencies themselves show `tokio`.

https://github.com/rust-lang/docs.rs/blob/b527df80a7332b35294c02b2922a2899dee43aaa/src/db/add_package.rs#L240

Here it needs to take the renamed name (but unfortunately our little cargo-metadata dataset doesn't record this currently).

**Comment by almusil** [comment]
Since we need the rename, it would be also wise to extend the Feature in database with optional dependency indicator. It will be easier that way to filter etc IMO. WDYT?

**Comment by jyn514** [comment]
Sure, if you want to do both at once I'd be fine with that.

**Comment by jyn514** [comment]
Fixed by https://github.com/rust-lang/docs.rs/pull/1180 I think.

**Comment by Nemo157** [comment]
Yep, https://docs.rs/crate/async-compression/0.3.7/features shows `tokio-02` and `tokio-03` headings.
