### ISSUE TITLE
Make fewer github requests

### ISSUE THREAD

**Issue by jyn514** [rust-lang/docs.rs#1176]
This is a meta tracking issue, but for convenience I'm going to put the steps for solving it here too.

Currently, docs.rs makes way too many requests to the GitHub API:
![image](https://user-images.githubusercontent.com/23638587/98851007-9fe56b80-2423-11eb-88cd-1ccaeb763a84.png)

Note how bors and crater are only making around 20 requests per hour - docs.rs makes _5000_, and only stops because it hits the rate limit. We should fix this.

1. The first and most pressing issue is that we're making requests for repos that no longer exist:

```
 [DEBUG] docs_rs::utils::github_updater: Starting update of all crates
 [DEBUG] docs_rs::utils::github_updater: Updating BrewStillery
 [WARN] docs_rs::utils::github_updater: Failed to update BrewStillery: HTTP status client error (404 Not Found) for url (https://api.github.com/repos/MonkeyLog/BrewStillery)
 [DEBUG] docs_rs::utils::github_updater: Updating FPS
 [WARN] docs_rs::utils::github_updater: Failed to update FPS: HTTP status client error (404 Not Found) for url (https://api.github.com/repos/leeopop/FPS)
 [DEBUG] docs_rs::utils::github_updater: Updating Lattice
 [WARN] docs_rs::utils::github_updater: Failed to update Lattice: HTTP status client error (404 Not Found) for url (https://api.github.com/repos/andrew-lucker/Lattice)
...
```

We should cache this failure and not retry the next time, to avoid wasting calls on deleted repos. The cache should be invalidated then next time the crate is published, in case the repository URL is changed, and we should fix the code to deal with a renamed URL: https://github.com/rust-lang/docs.rs/blob/master/src/utils/github_updater.rs#L68-L69

2. We should stop updating so frequently. Right now we update github stars once per day; we could probably turn that down to 1 week without trouble.

There may be other improvements lying around - I had the idea to fetch multiple repositories at once, but looking at https://docs.github.com/en/free-pro-team@latest/rest/overview/resources-in-the-rest-api#detailed-representations I don't think it's possible.

**Comment by jyn514** [comment]
> I had the idea to fetch multiple repositories at once

I think this would be possible if we used the GraphQL API instead of REST. Thanks @nickmccurdy for the suggestion!

**Comment by nickmccurdy** [comment]
> I had the idea to fetch multiple repositories at once
You can do this with the GraphQL API, for example if you have a repositories field you can do `repositories { edges { node { starGazers } } }`. Note that rate limiting for this is dynamic, some requests will use more or less of your rate limit than others.
