### ISSUE TITLE
Use cargo's rustdoc-map instead to link to dependencies

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/docs.rs#1177]
Currently we're generating `--extern-html-root-url` flags to pass to rustdoc ourselves:

https://github.com/rust-lang/docs.rs/blob/b527df80a7332b35294c02b2922a2899dee43aaa/src/docbuilder/rustwide_builder.rs#L521-L529

This has issues (https://github.com/rust-lang/docs.rs/issues/1166, https://github.com/rust-lang/docs.rs/issues/1165).

Cargo has an [unstable `rustdoc-map` feature](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#rustdoc-map) https://github.com/rust-lang/cargo/issues/8296 intended to allow users to do a similar thing easily via a simple url template. We can likely use this instead of doing it manually.

**Comment by jyn514** [comment]
This needs rustdoc to crates.io to docs.rs automatically before we can use it - right now you have to set a field in `.cargo/config`, but rustwide removes `config` before building the crate.
