### ISSUE TITLE
usd-rs 0.0.3 failed to build

### ISSUE THREAD

**Issue by luke-titley** [rust-lang/docs.rs#1178]
**Crate name:**
usd-rs
**Build failure link:**
https://docs.rs/crate/usd/0.0.3/builds/315265
**Additional details:**
usd-rs depends on usd-cpp, that's a crate I wrote to build a c++ library that usd-rs wraps. The crate uses a utility that is bundled with the c++ library that will download it's dependencies (namely boost and tbb). Please can you grant network access for this reason?

I'm not sure if there's a way to generate the docs for my crate without building the upstream dependencies, but that would be the ideal.

Thanks again,
Luke

**Comment by jyn514** [comment]
Docs.rs does not allow network access for any reason. If you need boost and tbb you can install them in the build image: https://forge.rust-lang.org/docs-rs/add-dependencies.html

**Comment by jyn514** [comment]
> I'm not sure if there's a way to generate the docs for my crate without building the upstream dependencies, but that would be the ideal.

I assume you have a build.rs that's compiling the c++ dependency? You can check if the `DOCS_RS` env variable is set and skip the compile if so: https://docs.rs/about/builds

**Comment by luke-titley** [comment]
ah, great, thank you!

Sent with [ProtonMail](https://protonmail.com/?utm_campaign=ww-all-2a-mail-pmm_mail-protonmail_signature&utm_source=proton_users&utm_medium=cta&utm_content=sent_with_protonmail_secure_email) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
