### ISSUE TITLE
Hide the search crate text field by default

### ISSUE THREAD

**Issue by antoyo** [rust-lang/docs.rs#118]
Hi!

Some web plugins/web browsers have a shortcut to focus the first text field in a page, which is what I use in Rust documentations to start a search within the crate.
However, on docs.rs, there's another "Find crate" text field which is before the documentation search field which forbids me to use this shortcut.

So, it would be nice to hide the "Find crate" text field by default, requiring to click a button or hover to show the text field.
Another solution that would make it after the other text field would also fix this issue.

If you need help to implement that, I can contribute.

Thanks.

**Comment by onur** [comment]
I am not sure but I think adding `tabindex="-1"` should fix this issue. Can you tell me which browser or plugin acting like this, so I can test it?

**Comment by antoyo** [comment]
Vimperator is a plugin for Firefox which allows to select the first field with the sortcut `gi`.
There are other plugins/browsers, but in my case, I develop my own, so adding the `tabindex="-1"` will be enough for me.
However, it does not seem to work with Vimperator (I don't really care, but other people might care :) ).

**Comment by onur** [comment]
`2gi` is working fine for vimperator and vimium. TBH I am not sure about changing a basic text input with javascript.

**Comment by antoyo** [comment]
What about just adding `tabindex="-1"`?
That does not require JavaScript.

**Comment by onur** [comment]
Sure, I can do that when I am home.

**Comment by antoyo** [comment]
Thanks!

**Comment by antoyo** [comment]
This has been somehow removed.
Can we add this back?

**Comment by jyn514** [comment]
It seems this was removed in https://github.com/rust-lang/docs.rs/pull/611, cc @GuillaumeGomez . I think it should be as easy as adding back `tabindex="-1"`?

**Comment by GuillaumeGomez** [comment]
Normally it should be just that, indeed. Want me to send the PR?

**Comment by jyn514** [comment]
That would be great :)

**Comment by GuillaumeGomez** [comment]
Opened #741. :)

**Comment by antoyo** [comment]
That was removed again.
cc @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
It's been removed in [this commit](https://github.com/rust-lang/docs.rs/commit/df7654bdf4e74d55f44d1381e7285e751c8cf991).
