### ISSUE TITLE
Non-ascii identifier link is broken

### ISSUE THREAD

**Issue by euclio** [rust-lang/docs.rs#1184]
The link to `Ω` is broken on this page: https://docs.rs/const_unit_poc/1.0.0/const_unit_poc/units/index.html

The link works correctly if the documentation is built locally.

**Comment by jyn514** [comment]
Well that's odd. I wonder if S3 doesn't like non-ascii identifiers ...

**Comment by jyn514** [comment]
I found the issue - we're not url-decoding the file before requesting it from s3:

```
2020/11/21 19:36:44 [DEBUG] tokio_postgres::prepare: preparing query s8: SELECT
                 path, mime, date_updated, compression,
                 (CASE WHEN LENGTH(content) <= $2 THEN content ELSE NULL END) AS content,
                 (LENGTH(content) > $2) AS is_too_big
             FROM files
             WHERE path = $1;
2020/11/21 19:36:44 [DEBUG] tokio_postgres::query: executing statement s8 with parameters: ["const_unit_poc/1.0.0/const_unit_poc/units/constant.%CE%A9.html", 52428800]
```

I think we just need to change this line: https://github.com/rust-lang/docs.rs/blob/c0718f545e7a0d564ec1745c3cc3127039842274/src/web/file.rs#L59

Fortunately, the file is *in* the database, so the crate won't need to be rebuilt, it's just a bug on the frontend.
