### ISSUE TITLE
Docker issue while building generator_extensions documentation.

### ISSUE THREAD

**Issue by nwsharp** [rust-lang/docs.rs#1196]
**Crate name:** generator_extensions
**Build failure link:** https://docs.rs/crate/generator_extensions/0.1.0/builds/321146

**Additional details:**
[INFO] [stderr] Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

**Comment by nwsharp** [comment]
Looks like this is happening for other crates as well. It appears to have started with https://docs.rs/crate/concordium-std-derive/0.1.0/builds/321136.

**Comment by nwsharp** [comment]
Issue was tackled by @pietroalbini. Crates are backfilling now. Will leave this issue open for the docs.rs team to close when they think impact is fully resolved for all crates (or whatever they choose).

**Comment by pietroalbini** [comment]
All the crates failing to build because of this are now rebuilt! Closing the issue.
