### ISSUE TITLE
Falcon fails to build (capstone3 -> capstone4)

### ISSUE THREAD

**Issue by endeav0r** [rust-lang/docs.rs#1198]
**Crate name:** Falcon
**Build failure link:** https://docs.rs/crate/falcon/0.5.0/builds/321516

**Additional details:**
Falcon used to use capstone 3, but now uses capstone 4 by default. These errors look like errors when Falcon is built against capstone 3. Can the dependency for this crate be upgraded to capstone 4?

Capstone is an opensource library for disassembling binary code: http://www.capstone-engine.org/

**Comment by Kixiron** [comment]
Dependencies are only upgraded if you publish a new release that uses the new version, I'd just make a 0.5.1 release that uses the required version of capstone

**Comment by Nemo157** [comment]
To clarify, this is the native dependency `libcapstone`? <https://github.com/rust-lang/crates-build-env/blob/775e47f80ba6111a6c2ca6c0958f4a8c2c4847ab/packages.txt#L157-L158>

It appears that `ubuntu:focal` doesn't have `libcapstone4` available:

```console
> docker run --rm ubuntu:focal /bin/sh -c 'apt update && apt search capstone'
...
capstone-tool/focal 4.0.1+really+3.0.5-1build1 amd64
  lightweight multi-architecture disassembly framework - command line tool

libcapstone-dev/focal 4.0.1+really+3.0.5-1build1 amd64
  lightweight multi-architecture disassembly framework - devel files

libcapstone3/focal 4.0.1+really+3.0.5-1build1 amd64
  lightweight multi-architecture disassembly framework - library

python-capstone/focal 4.0.1+really+3.0.5-1build1 amd64
  lightweight multi-architecture disassembly framework - Python bindings

python3-capstone/focal 4.0.1+really+3.0.5-1build1 amd64
  lightweight multi-architecture disassembly framework - Python bindings
```

**Comment by jyn514** [comment]
@endeav0r are you planning to work on this?

**Comment by endeav0r** [comment]
We have dropped another version, 0.5.1.

https://docs.rs/crate/falcon/0.5.1/builds/375762

I'm not entirely sure what remains to be done here. I can give this another look this week, but I believe the answer here will be Falcon doesn't build for doc.es anymore.

**Comment by syphar** [comment]
It looks like recent versions build successfully : 

https://docs.rs/falcon/0.5.5/falcon/
