### ISSUE TITLE
(mobile) module item names are word-wrapped instead of narrowing the summary

### ISSUE THREAD

**Issue by dullbananas** [rust-lang/docs.rs#1200]
![image](https://user-images.githubusercontent.com/47706471/101124533-7f3cab80-35b4-11eb-8fbb-a052e09e4c93.png)

**Comment by jyn514** [comment]
I think this is a rustdoc bug. What crate and version were you visiting? If you see the same results locally with `cargo doc --open`, that means docs.rs can't do anything about it and rustdoc needs to be fixed instead.
