### ISSUE TITLE
#1164 introduces weird navbar item focus behavior

### ISSUE THREAD

**Issue by cynecx** [rust-lang/docs.rs#1201]
After https://github.com/rust-lang/docs.rs/pull/1164 I am seeing:

![Peek 2020-12-09 00-18](https://user-images.githubusercontent.com/5961244/101552963-12f6e900-39b4-11eb-8dce-917fefbd750e.gif)

caused by:

https://github.com/rust-lang/docs.rs/blob/b728426b65e67dc84c568da6bab4ebe59c4ad9cc/templates/style/_navbar.scss#L47-L52

**Comment by jyn514** [comment]
@cynecx do you have a suggestion to make this not flicker on hover while still keeping the old behavior for other menus? We can revert https://github.com/rust-lang/docs.rs/pull/1164 but I'd prefer to fix both issues if possible.

**Comment by cynecx** [comment]
Hm, I didn’t have the time to actually look into the PR and the issue here except that disabling those css rules fixes the weird behavior. I am also very short on time right now. Perhaps @pickfire? Though, I might look into it tomorrow or so.

**Comment by pickfire** [comment]
Ah, that PR fixed something but I didn't know it causes regression, I didn't check on the light theme.

**Comment by pickfire** [comment]
I believe it is caused by both activating at the same time, one taking from `focus` (`color`) and one from `hover` (`background-color`).
