### ISSUE TITLE
Rebuild request: one-of 0.2.2

### ISSUE THREAD

**Issue by figsoda** [rust-lang/docs.rs#1202]
**Crate name:** `one-of`
**Build failure link:** https://docs.rs/crate/one-of/0.2.2/builds

**Additional details:** It was simply due to the incompatibility between nightly versions. Now that rust nightly toolchain is updated on docs.rs, the build should pass.

**Comment by jyn514** [comment]
Requeued and rebuilt! https://docs.rs/one-of/0.2.2/one_of/
