### ISSUE TITLE
flag -fallow-argument-mismatch

### ISSUE THREAD

**Issue by tungli** [rust-lang/docs.rs#1204]
**Crate name: lsode 0.2.8**
**Build failure link: https://docs.rs/crate/lsode/0.2.8/builds/323718**

**Additional details:**

Version 0.2.7 compiled without the flag fine.
Adding the flag resolved compilation issues on my machine but causes build failure on docs.rs

My rustc version is:
```
rustc 1.46.0 (04488afe3 2020-08-24)
```

**Comment by jyn514** [comment]
Here is `cc --version` in the `rustops/crates-build-env` docker image: `cc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0` (which I think is GCC).

You should write your code to be compatible with that compiler (not sure which you have locally). If the flag is only present in later versions of GCC you can make a PR updating crates-build-env: https://forge.rust-lang.org/docs-rs/add-dependencies.html

**Comment by tungli** [comment]
Thanks for the quick response.
The bug is in the version of gfortran
[9.3](https://gcc.gnu.org/onlinedocs/gcc-9.3.0/gfortran/Option-Summary.html#Option-Summary) vs [10.2](https://gcc.gnu.org/onlinedocs/gcc-10.2.0/gfortran/Option-Summary.html#Option-Summary).

Not sure yet how to solve this.

You guys plan to upgrade to 10.2 anytime soon?

**Comment by jyn514** [comment]
@tungli like I said, you can make a PR to crates-build-env upgrading it: https://forge.rust-lang.org/docs-rs/add-dependencies.html

You might want to consider making your crate backwards-compatible with gcc 9 though, if docs.rs ran into this I expect your users will too. I still have 9 and not 10 on my personal laptop for instance.

**Comment by tungli** [comment]
Making a PR like that is a bit beyond my skill and time right now.

I have 'cargo yank'-ed the version, reverting to the version which compiles fine with gfortran 9.2, and added a comment to the build.rs for now.
Thanks for your help! I think this issue may be closed now.
