### ISSUE TITLE
Broken toolbar layout with long crate names + 'go to latest version'

### ISSUE THREAD

**Issue by jnqnfe** [rust-lang/docs.rs#1205]
Long-ish crate names, especially combined with the presence of the 'go to latest version' link, breaks the toolbar layout:

![docsrs_toolbar](https://user-images.githubusercontent.com/33935229/101911318-19ee4900-3bb8-11eb-8e3c-c73e68b77bf1.png)

**Comment by jyn514** [comment]
Hmm, maybe we should be switching to the narrow layout sooner: 
![image](https://user-images.githubusercontent.com/23638587/101935826-a5aea800-3bad-11eb-87c2-a13aae35c88e.png)

Not sure how to write that in CSS but I expect it wouldn't be too hard to add.

A related bug is that sometimes we switch over to the narrow view for only the right items and switch the left items too late:

![image](https://user-images.githubusercontent.com/23638587/101935904-c5de6700-3bad-11eb-9f79-a0547994d233.png)

**Comment by pietroalbini** [comment]
I think we could also consider moving the "source" and "feature flag" links in the dropdown.

**Comment by jyn514** [comment]
@pietroalbini why only those two, what makes them different from `Platform`?

**Comment by pietroalbini** [comment]
The impression I get is that "platform" is something you need to switch between while reading the documentation, while both the source code and the feature flags are extra crate "metadata".

**Comment by Nemo157** [comment]
"Source" is sorta confusing up there since it's a tab on the crate details view as well, we could maybe get rid of it and just make you go through the crate details page to get there.

**Comment by jyn514** [comment]
@Nemo157 I'm ok with that for 'Source', but the problem with moving 'Features' is that no one visits the crate details page, so if we move it no one will know it's there.

**Comment by arusahni** [comment]
This sounds like something that could be tackled incrementally. If just moving `Source` is sufficient (as it looks to be in the screenshot), then `Features` can remain where it is until that real estate is needed.

Additionally, if no-one has laid claim to this issue just yet, I'd love to take it on.

**Comment by jyn514** [comment]
@arusahni go for it! Just moving Source for now sounds like a good approach.

**Comment by jnqnfe** [comment]
I noticed the other day that for yanked versions even more space is eaten up:

![docsrs](https://user-images.githubusercontent.com/33935229/103239856-ab92e000-4946-11eb-9a1b-424c36482a77.png)

**Comment by arusahni** [comment]
Yeah, I've been experimenting, and it seems like there are a few decision points to be made. 

On a listing with just the "Go to latest version" link present, moving *just* the "Source" link into the crate menu isn't quite enough to address the overflow bug. I'm experimenting with selectively collapsing buttons at various breakpoints.

![Screen Shot 2020-12-28 at 21 54 14](https://user-images.githubusercontent.com/139487/103255473-6fb44680-4957-11eb-9a0b-f3ce95b61961.png)

Would this suffice? The tooltips still display, so they're not necessarily indecipherable. If so, what would we consider to be the appropriate priorities for collapsible buttons? I'm leaning towards having the "Old version" and "Yanked version" buttons collapse at a medium breakpoint, as well as "Feature flags".

As an aside, I think a yanked version is a higher severity notice, so it might be worth presenting different than we do the old version message (e.g., red, with a circled x). Thoughts?

**Comment by jyn514** [comment]
@arusahni I would rather collapse 'About/Releases/Rust' than the warning bar - you see those on almost every page, so you'd know what they mean after a while, and they're also less important than the version being out of date IMO. The warning is bright yellow because we want people to look at it, and if it's collapsed it's more effort on their part.

**Comment by arusahni** [comment]
Cool :+1: I'll prioritize those breakpoints. If we need more navbar space, then which buttons would we prefer to collapse next? Presumably "Feature flags" then "Platform"?

**Comment by jyn514** [comment]
Maybe Platform before Feature flags? At that point the screen is already pretty small and I'd expect it to switch all of them to icons tbh, I'd test it to make sure you actually need another breakpoint.

**Comment by arusahni** [comment]
I still need to test with the yanked warning, but here's what things can look like with just adjusting the menu on the right.

![Peek 2020-12-28 22-40](https://user-images.githubusercontent.com/139487/103257145-071c9800-495e-11eb-9305-89637b709319.gif)

I think this works. Worst case, when the wider "yanked" message is present, we define a different set of breakpoints.

**Comment by arusahni** [comment]
Alright! I think I have something that works. [Give it a spin](https://github.com/arusahni/docs.rs/commit/116ef80c11518bb795c32b43cb526aa26c9047b5) and let me know what you think. If it passes the smoke test, I'll file a PR.

What I did to test:

```
# add two versions of a crate with a long name
cargo run -- build crate air-interpreter-wasm 0.0.33                                                                                                                                                                   
cargo run -- build crate air-interpreter-wasm 0.0.35

# Start the webserver
cargo run -- start-web-server --reload-templates

# From the web UI, verify that the breakpoints are correctly hit for the latest version
<browse to http://localhost:3000/air-interpreter-wasm/0.0.35/air_interpreter_wasm/index.html >
# From the web UI, verify that the breakpoints are correctly hit for an older version
<browse to http://localhost:3000/air-interpreter-wasm/0.0.33/air_interpreter_wasm/index.html >

# Now, yank both versions
psql postgresql://cratesfyi:password@localhost:15432 -c "UPDATE releases SET yanked = false FROM  crates WHERE releases.crate_id = crates.id AND crates.name = 'air-interpreter-wasm'"

# From the web UI, verify that the breakpoints are correctly hit for the latest version
<browse to http://localhost:3000/air-interpreter-wasm/0.0.35/air_interpreter_wasm/index.html >
# From the web UI, verify that the breakpoints are correctly hit for an older version
<browse to http://localhost:3000/air-interpreter-wasm/0.0.33/air_interpreter_wasm/index.html >
```

**Comment by jyn514** [comment]
@arusahni could you open the PR directly? It's easier for me to review that way; what you have already looks good though :)

**Comment by arusahni** [comment]
@jyn514 sure thing, PR filed! #1232
