### ISSUE TITLE
[feature] package.metadata.docs.rs to redirect to https://docs.rs/about/metadata

### ISSUE THREAD

**Issue by lopopolo** [rust-lang/docs.rs#1210]
I naively pasted package.metadata.docs.rs from a `Cargo.toml` file I found on GitHub into the Google Chrome omnibar to learn about what values are valid in this TOML section. The browser treated this as a a URL instead of a search term, which makes Google Chrome show a _This site can’t be reached_ error page because no DNS entry exists for this domain.

I think it would be a nice usability win for http://package.metadata.docs.rs/ and https://package.metadata.docs.rs/ to redirect to https://docs.rs/about/metadata.

**Comment by jyn514** [comment]
@pietroalbini how hard would that be to set up?

**Comment by namibj** [comment]
@jyn514 The proxy/server (if nginx or apache or so) should allow that easily.

**Comment by jyn514** [comment]
@namibj first there has to be DNS pointing to docs.rs in the first place, it doesn't matter how virtual hosting is configured if there's no request coming in.

**Comment by pietroalbini** [comment]
This is now up! [package.metadata.docs.rs](https://package.metadata.docs.rs) now redirects to the about page :)

[Link to the changes to AWS due to this](https://github.com/rust-lang/simpleinfra/commit/2093ba2d3add5cd85e66d7ece4689e9fedba888d).

**Comment by lopopolo** [comment]
Thank you! This is great.
