### ISSUE TITLE
Top menu is too narrow for popular crates

### ISSUE THREAD

**Issue by lnicola** [rust-lang/docs.rs#1218]
Like `tokio`:

![image](https://user-images.githubusercontent.com/308347/103033312-db1ea280-456a-11eb-978e-67102cd6a3fc.png)

(the issue count ends up on the next line)

**Comment by jyn514** [comment]
I think we should just show 'Repository' there instead honestly, the github logo doesn't stand out enough to make it clear that it's a link.

**Comment by lnicola** [comment]
That works for me, I don't particularly care for those numbers, and if it sidesteps the GitLab integration issue, that's even better.

**Comment by jyn514** [comment]
Mentoring instructions:

Remove the first `{% if %}` in https://github.com/rust-lang/docs.rs/blob/df489659d0de9baa5f23896dbc9260a00206f633/templates/rustdoc/topbar.html#L61-L79
so that 'Repository' is shown whether or not this crate is hosted on github.

**Comment by GuillaumeGomez** [comment]
It was done in https://github.com/rust-lang/docs.rs/pull/1242.
