### ISSUE TITLE
docs build failure due to missing optional c++ dependency

### ISSUE THREAD

**Issue by donkeyteethUX** [rust-lang/docs.rs#1220]
**Crate name:** abow
**Build failure link:** https://docs.rs/crate/abow/0.1.0/builds/328808

**Additional details:** Failed because rust bindings for opencv are an (optional) dependency, and opencv (a large c++ library for computer vision) is not installed in build environment. Do I need to get opencv installed in the build environment or is there an easier workaround? I have looked at the instructions for adding dependencies, it just seems like overkill here. The dependency is optional anyway.

**Comment by jyn514** [comment]
If the dependency is optional, you can change your crate not to require it in the docs.rs build environment: https://docs.rs/about/builds, https://docs.rs/about/metadata

**Comment by donkeyteethUX** [comment]
Done and worked. Thanks and happy holidays!
