### ISSUE TITLE
'I am feeling lucky' gives an internal error

### ISSUE THREAD

**Issue by neetdai** [rust-lang/docs.rs#1225]
when i use https://docs.rs/releases/search?query=&i-am-feeling-lucky=0, will found

```
    db error: ERROR: column "github_stars" does not exist 
```

**Comment by jyn514** [comment]
This is a regression from https://github.com/rust-lang/docs.rs/pull/1208. cc @pietroalbini, do you have time to do the follow-up work?

**Comment by pietroalbini** [comment]
Opened https://github.com/rust-lang/docs.rs/pull/1227 to fix this.
