### ISSUE TITLE
Broken source code rendering

### ISSUE THREAD

**Issue by CasualX** [rust-lang/docs.rs#1231]
My crate [obfstr](https://docs.rs/obfstr/0.2.1/obfstr/index.html)'s source code rendering is broken _when you click on the **src**_ button.

Eg. When going to the [`hash!` macro](https://docs.rs/obfstr/0.2.1/obfstr/macro.hash.html) doc page I click the [src] link. I expect to be linked to the macro's source code. Instead it doesn't go to the right place in the source code and I also see some errant newlines between the doc comments in the source code.

Note that the page rendered by the [_source_ tab](https://docs.rs/crate/obfstr/0.2.1/source/src/lib.rs) does not appear to suffer from this issue.

Randomly clicking through recently published crates do not suffer from this issue, perhaps it is already fixed? If so would it be possible to rerender my crate's doc pages?

**Comment by jyn514** [comment]
Queued and rebuilt, the link seems to work now.
