### ISSUE TITLE
Collecting GitHub stats for new repositories is broken

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/docs.rs#1234]
In the logs, this message appears:

```
docs_rs::docbuilder::rustwide_builder: failed to collect GitHub stats: error serializing parameter 3: cannot convert between the Rust type `core::option::Option<chrono::naive::datetime::NaiveDateTime>` and the Postgres type `timestamptz`
```

Possibly a fallout of the switch to timestamptz.

**Comment by syphar** [comment]
yes, it's related to the `timestamptz` migration. Seems like it wasn't covered with tests. 

I also found the place which needs to be fixed, only unsure how to test it the best way
