### ISSUE TITLE
new favicon sizes not added as hashed essential files. 

### ISSUE THREAD

**Issue by syphar** [rust-lang/docs.rs#1240]
I'm seeing these 404 errors: 
![image](https://user-images.githubusercontent.com/540890/103650980-22d8fd00-4f61-11eb-9e1a-4a51d4522bb9.png)

when accessing for example the [itertools docs](https://docs.rs/itertools/0.10.0/itertools/). 

I guess it's related to `ESSENTIAL_FILES_VERSIONED` and `add-essential-files`, but I couldn't make it work quickly and don't know the build-process good enough yet.

**Comment by syphar** [comment]
I created this issue so I don't forget it, and perhaps someone else with more knowledge of the build will give a hint or do it. 

Otherwise I'll be coming back to this at some point

**Comment by jyn514** [comment]
@syphar I think you would add it to ESSENTIAL_FILES_VERSIONED, the same as other versioned files: https://github.com/rust-lang/docs.rs/pull/1301. You may want to wait for the discussion in https://github.com/rust-lang/docs.rs/pull/1312 to die down, though.
