### ISSUE TITLE
Crate fails because of a dependency that otherwise builds

### ISSUE THREAD

**Issue by bamilab** [rust-lang/docs.rs#1246]
**Crate name:** browser-window
**Build failure link:** https://docs.rs/crate/browser-window/0.5.1/builds/336681

**Additional details:**
I'm trying to upload a new version of my crate _browser-window_.
It depends on `browser-window-core`, which depends on `browser-window-c`.
Both have been uploaded successfully now.
`browser-window-c` has some C files inside that it will generate an FFI interface for with `bindgen`.
Interestingly enough, when `browser-window` is trying to build, its build script generates this error:
```
[INFO] [stderr]   ./src/err.h:8:10: fatal error: 'stdlib.h' file not found
[INFO] [stderr]   ./src/err.h:8:10: fatal error: 'stdlib.h' file not found, err: true
[INFO] [stderr]   thread 'main' panicked at 'Unable to generate FFI bindings!: ()', /opt/rustwide/cargo-home/registry/src/github.com-1ecc6299db9ec823/browser-window-c-0.0.3/build.rs:208:21
```
This error would usually occur when you try to build `browser-window-c`, but haven't installed `clang`, or haven't installed it correctly (which is what `bindgen` requires). It is very strange the build fails at this point because `browser-window-c` is able to build fine. (See here: https://docs.rs/crate/browser-window-c/0.0.3/builds/336677)

Keep in mind that I've made the `build.rs` script of `browser-window-c` in such a way that  only when on the docs.rs environment, certain lines of code are not activated. This is done because the C source files contained within it depend on another C library that is just not available on the docs.rs system it builds on. So it doesn't actually build the C source files, and this something I've done for a while without issue.

**Comment by jyn514** [comment]
The error is very strange - `stdlib.h` should be available in the build environment. Can you change the build script to show what command line it's running with clang? That would let you test in https://github.com/rust-lang/crates-build-env whether the build succeeds.

See also https://forge.rust-lang.org/docs-rs/add-dependencies.html, which has instructions on testing your build with docs.rs locally.

**Comment by jyn514** [comment]
I'm going to close this due to inactivity; feel free to reopen if you're still having trouble and have time to debug things.
