### ISSUE TITLE
Streampager build failure due to flaky dependency failure

### ISSUE THREAD

**Issue by markbt** [rust-lang/docs.rs#1247]
**Crate name:** streampager
**Build failure link:** https://docs.rs/crate/streampager/0.9.2/builds/336810

**Additional details:**

Version 0.9.2 failed to build, despite this being a minor cfg-attribute change over 0.9.1 which built fine.

It looks like the problem was during building of the `pest_meta` 2.1.3 dependency, which built fine in the previous version, and also [built fine itself](https://docs.rs/pest_meta/2.1.3/pest_meta/).

**Comment by jyn514** [comment]
SIGKILL most likely means your crate ran out of memory when compiling. How much memory does it take to compile `streampager` locally with `cargo doc`? The default limit is 3 GB.

**Comment by markbt** [comment]
Max RSS from `time` says it uses about 1.3GB.  It's not a particularly complex library, so I'd be surprised if it hit any limits.

The failure actually happens before it even gets to the `streampager` library - it was killed compiling a dependency.   The previous version (0.9.1) also compiled fine (and the only difference between the two is a missing `cfg` attribute).

I suspect some noisy neighbour caused the build to fail (perhaps by exhausting host memory), and if you tried the build again it would work fine.  I don't know if you can kick off another build.  It seems the only way I could do it myself would be to release 0.9.3.

**Comment by Nemo157** [comment]
I tested building locally and saw the same spike and SIGKILL happen. The crate which I saw spike the most was `vtparse`, testing just that it's hitting 3.6GB resident memory running `cargo check`, interestingly it only takes 290MB while runnning `cargo doc`, so this only affects dependers of it.

**Comment by markbt** [comment]
Ok. So it looks like it's a bit non-deterministic depending on what happens in parallel.  For example 0.9.1 (https://docs.rs/crate/streampager/0.9.1/builds) built fine despite being essentially the same code.

I noticed that wezterm has a 5GB limit rather than the default 3GB.  Maybe streampager needs a higher limit, too?  Can that be changed?

Alternatively we could build fewer things in parallel.  Is there a setting I can change for that?

**Comment by jyn514** [comment]
I would rather fix this upstream in rustc rather than having to special case every crate that depends on wezterm. I opened https://github.com/rust-lang/rust/issues/81124.

**Comment by jyn514** [comment]
> Alternatively we could build fewer things in parallel. Is there a setting I can change for that?

docs.rs currently always uses -j2; since `cargo check` uses so much memory I wouldn't expect less parallelism to help much. It's weird that 0.9.1 built successfully.

**Comment by jyn514** [comment]
Requeued and rebuilt: https://docs.rs/streampager/0.9.2/streampager/

I guess the memory improvements are working :)
