### ISSUE TITLE
The features page shows dependencies as empty features

### ISSUE THREAD

**Issue by arniu** [rust-lang/docs.rs#1266]
Take [tokio features](https://docs.rs/crate/tokio/1.1.0/features) for example, `memchr`, `once_cell` are rendered as empty features.

**Comment by Nemo157** [comment]
All optional crates _are_ technically features you could externally activate.

We need some kind of heuristical detection of which features are intended to be used by consumers, or some explicit way for crates to tell us how to render the features (as not ever all the explicit features are intended for consumers in all cases).

**Comment by arniu** [comment]
Features are public API of a crate, while dependencies are not.

**Comment by Kixiron** [comment]
As Nemo said, optional dependencies *are* features, and are often used without a supplementary feature flag. The best route is what Nemo gave, adding a section to the metadata that allows enabling/disabling what features are displayed

**Comment by Nemo157** [comment]
As a direct example of an optional dependency being public API: `log` [documents `serde` as a public feature flag](https://docs.rs/log/0.4.14/log/#crate-feature-flags), while [only having it as an optional dependency](https://docs.rs/crate/log/0.4.14/source/Cargo.toml.orig).

**Comment by arniu** [comment]
Yes, you're right. I was shocked that optional dependencies are public API.

**Comment by jyn514** [comment]
It sounds like this isn't a bug. Happy to hear suggestions for how we can improve the heuristics, but I don't think this is actionable currently.
