### ISSUE TITLE
Show Advisory DB status for each crate

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/docs.rs#1270]
We could be pulling data from https://github.com/RustSec/advisory-db and displaying it somewhere, maybe similar to the yanked warnings, to improve broadcasting of known security issues to potentially impacted users.

This might not be possible because the advisory db is maintained outside the Rust Project, unless its links through wg-secure-code make it official enough.

**Comment by jyn514** [comment]
Should this be part of docs.rs? I'd expect to see this on crates.io maybe, I don't know if it fits here.

**Comment by Nemo157** [comment]
I feel like it's more likely for someone to be looking at docs for a crate that they're already using than going to that crate's crates.io page. It's something that should probably be displayed in _both_ locations really.

**Comment by pietroalbini** [comment]
I would avoid doing so unless crates.io also starts displaying that information.

**Comment by Nemo157** [comment]
Thinking about it more this _is_ probably something that needs wider discussion, and really would be best to integrate in both crates.io and docs.rs, so I'll bring up docs.rs on the more upstream issue https://github.com/rust-secure-code/wg/issues/16 in case that makes it to RFC at some point (and at least now we have an issue search result for "advisory" to follow 😁).
