### ISSUE TITLE
Paddings in about page

### ISSUE THREAD

**Issue by MisterFISHUP** [rust-lang/docs.rs#1273]
I was using Docs.rs and came across the about page. I think it might be nice to add some paddings/margins for the contents of tabs about, badges, builds, etc :)

**Comment by Liberatys** [comment]
@jyn514 I'd like to work on this if possible?

**Comment by jyn514** [comment]
@Liberatys sounds great! The relevant HTML is in `templates/about` and the CSS is in [`templates/style`](https://github.com/rust-lang/docs.rs/tree/master/templates/style).

**Comment by jyn514** [comment]
Fixed by https://github.com/rust-lang/docs.rs/pull/1275 (but not deployed yet, it's waiting on #1278).
