### ISSUE TITLE
The top-bar triangles are too small

### ISSUE THREAD

**Issue by mcclure** [rust-lang/docs.rs#1276]
Hello, I am new to Rust. I had a suboptimal very-first-user-visit on docs.rs. I typed "luajit rust" into google and this turned up a docs.rs page for a crate, [https://docs.rs/luajit/0.1.1/luajit/](https://docs.rs/luajit/0.1.1/luajit/). Once I got to the page I wanted to find the source for the crate. The correct way to do this is to click "luajit-0.1.1", which brings down a menu with all kinds of helpful content like a link to crates.io and a link to the gitlab repository. However, I did not realize that this was a menu. It didn't jump out to me as a menu or even interactable, and it didn't occur to me (maybe because it was in the top bar with the whole-site navigation "stuff" and not below with the crate "stuff") that "luajit-0.1.1" would show me crate-specific material. I had to ask for help on "Twitter".

Now, given, I *did* get help, and now that I've gotten help I know where to look and I won't make that mistake on docs.rs again. So maybe it is on me for spacing out and not really looking at the site UI, and maybe there is not really anything wrong with your layout. But, I think there is one thing you could/should change. This is a screenshot of docs.rs on Windows 10 on Chrome.

![image](https://user-images.githubusercontent.com/277318/107887747-39666280-6ed6-11eb-96f5-297175ea052d.png)

If you expand this image, you might realize that the triangles, the only thing indicating that text at the top is a drop down menu and not a label or link, barely look like triangles at all.

![image](https://user-images.githubusercontent.com/277318/107887844-ee008400-6ed6-11eb-8eb9-a095af36c72c.png)

I have also a Macbook with a Retina screen. If I look at this same page on the Retina screen, also in Chrome, the triangles are clearly legible as triangles. But on a 1x monitor they are more like small smudges.

"Expected behavior": I think you should consider making those triangles bigger. In the current design they are not only so unobtrusive they are possible to overlook, they are arguably illegible on 1x monitors. (Another solution might be to use CSS to detect non-retina/1x resolution and use a slightly different, clearer graphic there, if that is possible.)

**Comment by Nemo157** [comment]
I agree, a quick glance at it it appears to come from the `pure` css, using a [BLACK DOWN-POINTING SMALL TRIANGLE▾](https://www.fileformat.info/info/unicode/char/25be/index.htm). I edited the css on site to use [BLACK DOWN-POINTING TRIANGLE ▼](https://www.fileformat.info/info/unicode/char/25bc/index.htm) instead and it looked much better to me. Adding an override for that to our css should be pretty easy.

**Comment by chansuke** [comment]
I'd be happy to work on this

**Comment by jyn514** [comment]
@chansuke go for it! The css mostly lives in `templates/style`, feel free to ask questions here or [on Discord](https://discord.gg/f7mTXPW).

**Comment by jyn514** [comment]
> Once I got to the page I wanted to find the source for the crate. The correct way to do this is to click "luajit-0.1.1", which brings down a menu with all kinds of helpful content like a link to crates.io and a link to the gitlab repository.

Note that you can also click '[src]' on the right hand side; that's rustdoc's source browser, so it only shows rust files and not things like Cargo.toml, but it doesn't require clicking any dropdown menus.
