### ISSUE TITLE
docs.rs is returning 502s and cloudflare errors

### ISSUE THREAD

**Issue by lopopolo** [rust-lang/docs.rs#1277]
Hi folks, I have a couple of crates in the build queue on docs.rs and I noticed the site is having a hard time.

https://github.com/stm32-rs/stm32-rs pushed ~10 or 15 crates into the queue with their 0.13.0 release and while docs.rs is building them, the site has been kicking off 502s and sometimes giving cloudflare errors.

I'm not sure what's going on, but thought y'all would appreciate a heads up if your monitoring didn't catch it already.

**Comment by jyn514** [comment]
Thanks for the heads up. We've since fixed the proximate issue and the site should be back up. I'm working now on a PR to fix the underlying cause and describe what went wrong.
