### ISSUE TITLE
Dependency fails with "the feature `doc_cfg` has already been declared"

### ISSUE THREAD

**Issue by pka** [rust-lang/docs.rs#1289]
**Crate name:** geozero
**Build failure link:** https://docs.rs/crate/geozero/0.7.2/builds/355163

**Additional details:**
geozero has the following Cargo.toml entry:
```
[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"] 
```

`cfg(docsrs)` is required for a doc.rs build of the dependency `gdal`: https://github.com/georust/gdal/blob/master/build.rs#L3

The failing `tokio-stream` crate does in fact set a feature twice based on `docsrs`: https://github.com/tokio-rs/tokio/blob/master/tokio-stream/src/lib.rs#L17-L23

But a local doc build is successful!

**Comment by jyn514** [comment]
This should be reported upstream to Tokio, we can't fix it on our end.

> But a local doc build is successful!

Local builds don't pass --cfg docsrs by default.

**Comment by Nemo157** [comment]
There is a bug somewhere here since `tokio-stream` successfully built its docs, and it appears to activate the cfg for its build. Maybe `rustdoc` allows duplicate features, while `rustc` doesn't?

**Comment by pka** [comment]
> This should be reported upstream to Tokio, we can't fix it on our end.

PR: https://github.com/tokio-rs/tokio/pull/3561

> 
> > But a local doc build is successful!
> 
> Local builds don't pass --cfg docsrs by default.

I tried to imitate docs.rs build with
`cargo +nightly doc --all-features --config 'build.rustflags=["--cfg", "docsrs"]' -Z unstable-options`

Am I missing something?

**Comment by Nemo157** [comment]
I've opened https://github.com/rust-lang/rust/issues/82588 for the rustdoc bug that allowed `tokio-stream`'s docs to succeed.

Using `cargo +nightly doc --all-features --config 'build.rustflags=["--cfg", "docsrs"]' -Z unstable-options` on a crate that depends on `tokio-stream` I get the build failure, but at least on my machine I had to override `CARGO_HOME` for it to avoid loading my `~/.cargo/config`, which sets `target.x86_64-unknown-linux-gnu.rustflags` overriding the `build.rustflags` config.

**Comment by pka** [comment]
So nothing else to be done here, I think. Thanks @jyn514 and @Nemo157 for looking into it!
