### ISSUE TITLE
failed to build libloading

### ISSUE THREAD

**Issue by lovasoa** [rust-lang/docs.rs#1294]
**Crate name:** good_lp
**Build failure link:** https://docs.rs/crate/good_lp/0.3.6/builds/356172

**Additional details:**
It looks like it failed to build clang-sys. Building locally on linux x86_64 with the latest rust nightly succeeds.

**Comment by jyn514** [comment]
Hmm, I can't replicate this locally, I'll retry the build and see if it succeeds.

>  It looks like it failed to build clang-sys. Building locally on linux x86_64 with the latest rust nightly succeeds.

This is https://github.com/rust-lang/cargo/issues/8977, it's libloading that failed to build.

**Comment by jyn514** [comment]
I'm going to close this since the latest version of good_lp built successfully; feel free to reopen if you're still having trouble :)
