### ISSUE TITLE
`audit` action ignores lockfile

### ISSUE THREAD

**Issue by jyn514** [rust-lang/docs.rs#1296]
cc @Kixiron - the audit action just started failing in https://github.com/rust-lang/docs.rs/runs/2006983845?check_suite_focus=true, but it should have been failing a long time earlier: https://github.com/rust-lang/docs.rs/pull/1295.

**Comment by Nemo157** [comment]
Looks like https://github.com/actions-rs/audit-check/issues/163

**Comment by jyn514** [comment]
Thanks, I'll close this in favor of the upstream issue then.
