### ISSUE TITLE
Better search

### ISSUE THREAD

**Issue by ticki** [rust-lang/docs.rs#13]
Upgrade the searching algorithm to something more flexible, like [Eudex](https://github.com/ticki/eudex).

**Comment by onur** [comment]
Thanks for suggestion.

Did you see any issue in current search? I am using Postgres' [full text search](https://www.postgresql.org/docs/9.4/static/textsearch.html). It is fast and I believe I only need to adjust weights for ranking results better.

**Comment by mjkillough** [comment]
It would be nice if exact matches appeared at the top. If I search for "serde" it is the 15th entry in the results list, which means it can take a little while to find.

**Comment by ticki** [comment]
@mjkillough https://github.com/onur/docs.rs/issues/144

**Comment by Kixiron** [comment]
Fixed by #721, crate searching is now well-ordered and more accurate
