### ISSUE TITLE
Search within crate is broken: "Uncaught TypeError: crates is undefined"

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/docs.rs#1300]
https://docs.rs/syn/1.0.61/syn/?search=Expr fails to load, with the following in the JS console. In comparison, https://docs.rs/syn/1.0.60/syn/?search=Expr works fine as before. https://github.com/rust-lang/rust/pull/82310 seems relevant. @jsha

---

![Screenshot from 2021-03-04 19-58-25](https://user-images.githubusercontent.com/1940490/110065454-fef92400-7d23-11eb-935b-8343a5b18d1e.png)

**Comment by jyn514** [comment]
Hmm, I rebuilt syn 1.0.61 after deploying https://github.com/rust-lang/docs.rs/pull/1301, but it didn't seem to help. I think the list of essential files might only be calculated once per toolchain version?

**Comment by jyn514** [comment]
This has been fixed.

There have been a lot of changes to essential files recently, but the most recent ones were https://github.com/rust-lang/docs.rs/issues/1302 and https://github.com/rust-lang/docs.rs/pull/1329. I rebuilt syn 1.0.61 after 1329, but because the new file has the same name as the old one, some CDNs have cached the old version even though I invalidated the CloudFlare cache. You might run into the search showing no results until that cache expires, but there's nothing we can do about it on our end.

**Comment by jyn514** [comment]
Also, if I could ask a favor, could you please avoid linking directly to docs.rs issues in the changelog for big crates like syn? Normally I don't mind, but since depend-a-bot includes the changelog in its PRs it leads to lots of github spam, which makes it hard to see what's actually relevant.

**Comment by puzzlewolf** [comment]
Hi, I think I'm seeing the same issue for `sequoia-openpgp`. https://docs.rs/sequoia-openpgp/1.1.0/sequoia_openpgp/?search=foo is stuck at "Loading search results...", with the following in the console:

```
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. sequoia_openpgp
GEThttps://docs.rs/crates-20210304-1.52.0-nightly-45b3c2851.js
[HTTP/2 404 Not Found 188ms]

Loading failed for the <script> with source “https://docs.rs/crates-20210304-1.52.0-nightly-45b3c2851.js”. sequoia_openpgp:3:1
Uncaught TypeError: crates is undefined
    addSidebarCrates https://docs.rs/main-20210304-1.52.0-nightly-45b3c2851.js:1
    setupSearchLoader https://docs.rs/main-20210304-1.52.0-nightly-45b3c2851.js:8
    <anonymous> https://docs.rs/main-20210304-1.52.0-nightly-45b3c2851.js:8
    <anonymous> https://docs.rs/main-20210304-1.52.0-nightly-45b3c2851.js:8
main-20210304-1.52.0-nightly-45b3c2851.js:1:37088
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). utils.js:35:9

```
@jyn514 Could you please rebuild sequoia-openpgp, too? Or do you think this is something else? I'll be happy to open a new issue in that case :)

**Comment by jyn514** [comment]
Sure thing, rebuilt: https://docs.rs/sequoia-openpgp/1.1.0/sequoia_openpgp/?search=abc
