### ISSUE TITLE
Determine which files are "essential" automatically

### ISSUE THREAD

**Issue by jyn514** [rust-lang/docs.rs#1302]
Rustdoc occasionally adds or removes generated files. This often leads to breakage like https://github.com/rust-lang/docs.rs/issues/1300, and is a pain to update manually. It would be better to determine automatically which files are essential so that docs.rs doesn't have to be updated whenever rustdoc changes.

**Comment by jyn514** [comment]
cc https://github.com/rust-lang/rust/pull/80705, https://github.com/rust-lang/rust/pull/82732

**Comment by GuillaumeGomez** [comment]
How do you propose to do that?

**Comment by jyn514** [comment]
Rustdoc only adds the `resource-suffix` to essential files. We can copy all files containing the resource suffix.

```
$ rustdoc -Z unstable-options --resource-suffix=-xxx example.rs 
$ ls doc/*-xxx*
doc/ayu-xxx.css    doc/down-arrow-xxx.svg     doc/light-xxx.css      doc/rustdoc-xxx.css      doc/settings-xxx.js       doc/theme-xxx.js
doc/brush-xxx.svg  doc/favicon-16x16-xxx.png  doc/main-xxx.js        doc/rust-logo-xxx.png    doc/source-files-xxx.js   doc/wheel-xxx.svg
doc/crates-xxx.js  doc/favicon-32x32-xxx.png  doc/normalize-xxx.css  doc/search-index-xxx.js  doc/source-script-xxx.js
doc/dark-xxx.css   doc/favicon-xxx.svg        doc/noscript-xxx.css   doc/settings-xxx.css     doc/storage-xxx.js
```

**Comment by jyn514** [comment]
Hmm, that only works for versioned files, though. I don't know if there's a way to do it for unversioned files.

**Comment by jyn514** [comment]
@GuillaumeGomez could we add a `--print=unversioned-files` or something to rustdoc?

**Comment by GuillaumeGomez** [comment]
We could add an option to rustdoc which would list such files. The big question will be: how to do it so that the essential files are always in there without requiring manual changes from rustdoc side every time.

**Comment by jyn514** [comment]
> We could add an option to rustdoc which would list such files. The big question will be: how to do it so that the essential files are always in there without requiring manual changes from rustdoc side every time.

Oh that bit's not hard, I have a PR that's half working. Will send it out shortly.

**Comment by GuillaumeGomez** [comment]
Awesome! (Just confess: you created this issue to show off right? :stuck_out_tongue_closed_eyes: )

**Comment by jyn514** [comment]
> Just confess: you created this issue to show off right?

Actually I thought of the idea soon after you asked :laughing: it was helpful to bounce ideas :)

**Comment by GuillaumeGomez** [comment]
It was haha.
