### ISSUE TITLE
`go run` fails

### ISSUE THREAD

**Issue by joshlf** [rust-lang/docs.rs#1303]
**Crate name:** mundane
**Build failure link:** https://docs.rs/crate/mundane/0.4.4/builds/357678

**Additional details:** Based on the following log output, I believe what's happening is that, since the `GOCACHE` environment variable is not set, `go run` is defaulting to `$HOME/.cache`, and I'm guessing that `$HOME` is set to `/`. This means that `go run` tries creating `/.cache`, which it doesn't have permission to do. See [here](https://golang.org/cmd/go/#hdr-Build_and_test_caching) for more details on Go's build cache.

```text
[INFO] [stderr]   cd /opt/rustwide/workdir/boringssl/boringssl/crypto/err && /usr/bin/go run err_data_generate.go > /opt/rustwide/target/debug/build/mundane-6275d256bd1e392c/out/boringssl/build_1/crypto/err_data.c
[INFO] [stderr]   failed to initialize build cache at /.cache/go-build: mkdir /.cache: permission denied
```

**Comment by jyn514** [comment]
Most of the build environment is read-only. You could try setting GOCACHE to a subdirectory of the target directory in your build script.

**Comment by joshlf** [comment]
My thinking is that it would make sense to set GOCACHE to some reasonable value for all docs.rs builds; I can't think of a reason that it would need to be specific to Mundane?

**Comment by jyn514** [comment]
Hmm, I wonder if it makes sense rather than fixing GOCACHE specifically to set HOME to a temporary directory.

**Comment by joshlf** [comment]
That makes sense too, although I'd be worried about that having more wide-ranging implications (much more software uses `HOME` than `GOCACHE`), so I feel like just setting `GOCACHE` would be safer.

**Comment by jyn514** [comment]
Note that this is blocked on a rustwide update one way or another: https://github.com/rust-lang/docs.rs/pull/1278

**Comment by joshlf** [comment]
I'm not sure I understand why the change we're discussing here is blocked on #1278? Is it just that all docs.rs deployments are blocked on it?

**Comment by jyn514** [comment]
Docs.rs doesn't set any of these variables itself, they're set through rustwide. Rustwide 0.12 has switched to tokio 1.0, and I'm not willing to have over 600 dependencies just to fix this bug.

**Comment by joshlf** [comment]
Ah, I understand, gotcha.

**Comment by jyn514** [comment]
@joshlf go fails even with `HOME` set to a writeable directory:
```
2021/03/24 12:21:02 [INFO] rustwide::cmd: [stderr]   [37/272] Generating err_data.c
2021/03/24 12:21:02 [INFO] rustwide::cmd: [stderr]   FAILED: crypto/err_data.c 
2021/03/24 12:21:02 [INFO] rustwide::cmd: [stderr]   cd /opt/rustwide/workdir/boringssl/boringssl/crypto/err && /usr/bin/go run err_data_generate.go > /opt/rustwide/target/debug/build/mundane-6275d256bd1e392c/out/boringssl/build_1/crypto/err_data.c
2021/03/24 12:21:02 [INFO] rustwide::cmd: [stderr]   go: golang.org/x/crypto@v0.0.0-20200622213623-75b288015ac9: Get https://proxy.golang.org/golang.org/x/crypto/@v/v0.0.0-20200622213623-75b288015ac9.mod: dial tcp: lookup proxy.golang.org on 10.3.0.1:53: dial udp 10.3.0.1:53: connect: network is unreachable
2021/03/24 12:21:02 [INFO] rustwide::cmd: [stderr]   [38/272] Generating cipher_extra/chacha20_poly1305_x86_64.S
2021/03/24 12:21:02 [INFO] rustwide::cmd: [stderr]   ninja: build stopped: subcommand failed.
```

**Comment by jyn514** [comment]
You could vendor the sources, but we will not lift the network restriction for any crate.

**Comment by jyn514** [comment]
@joshlf are you planning to follow up on this? I'm willing to set HOME, but only if it actually helps crates build, otherwise there doesn't seem to be much point.

**Comment by jyn514** [comment]
Closing this since this isn't something we can fix.
