### ISSUE TITLE
Publishing a crate without dependencies causes a `empty_library` dependency.

### ISSUE THREAD

**Issue by coastalwhite** [rust-lang/docs.rs#1313]
When publishing a no_std crate without dependencies, it will add an `empty_library` to the crates on [docs.rs].

Reproduction steps:
1. Publish a no_std library without dependencies.
2. The docs.rs page will now have a `empty_library` in the crates.

This seems like a rather awkward way to tell the reader the crate has no dependencies. Now if you click any deeper into the documentation, on the left (under the crates header) the empty_library will be a clickable link that leads to a dead link.

This is what I mean: [Link to CRC8-RS Docs](https://docs.rs/crc8-rs/1.0.0/crc8_rs/fn.fetch_crc8.html)

**Comment by Nemo157** [comment]
Not specific to `no-std` libraries, seems to have started happening within the last month or so, either a docs.rs, rustwide or rustdoc change. Skimming the docs.rs merge requests none stand out to me as potentially causing this.

**Comment by Nemo157** [comment]
More specifically it appears to have changed between

```
rustc 1.52.0-nightly (45b3c2851 2021-03-04) docsrs 0.6.0 (da1f362 2021-03-05)
```

and 

```
rustc 1.52.0-nightly (caca2121f 2021-03-05) docsrs 0.6.0 (918ee5d 2021-03-06)
```

(from comparing https://docs.rs/syn/1.0.62/syn/ and https://docs.rs/syn/1.0.61/syn/)

**Comment by Nemo157** [comment]
To confirm I went back through the release pages and found the exact builds which changed behaviour, <https://docs.rs/near-runtime/4.0.0-pre.1/near_runtime/> was the last build that didn't show `empty_library`, and <https://docs.rs/mangadex-api/0.2.4/mangadex_api/> was the first build that showed it (currently on page https://docs.rs/releases/recent/59, but will be moving further back as more builds happen). These were both with docs.rs `da1f362`, but the `rustc` version changed.

**Comment by coastalwhite** [comment]
Would this then be a `rustdoc` issue, and should I open one over there?

I am not getting this behaviour, when just normally compiling documentation on my local machine. It could be that there are some flags of `rustdoc` that are bugged.

**Comment by Nemo157** [comment]
It seems like it's a change in `rustdoc` behaviour, but it is docs.rs specific, we use `empty_library` as a dummy library. It might be that we need to change something here to workaround whatever changed rather than changing rustdoc. (I skimmed the PRs, and couldn't see anything that would have changed rustdoc's behaviour in that release :shrug:).

https://github.com/rust-lang/docs.rs/blob/65e946c0ecac3633846fd55c1f19bf3029fcf39b/src/docbuilder/rustwide_builder.rs#L59

**Comment by jyn514** [comment]
I'd expect this to be a regression from https://github.com/rust-lang/rust/pull/80845, cc @GuillaumeGomez. Do we maybe keep the artifacts from the `empty_library` crate around when documenting other crates?

**Comment by Nemo157** [comment]
Huh, weird that that PR doesn't appear in the compare view though? Looks like that would be in the 2021-03-06/07 nightly, not the 2021-03-05 one.

**Comment by GuillaumeGomez** [comment]
Checking what's wrong.

**Comment by GuillaumeGomez** [comment]
It's an interesting "bug" from rustdoc indeed. Sending a fix.

**Comment by GuillaumeGomez** [comment]
Actually no, it's not a bug from rustdoc. Here how it works for rustdoc: `crates.js` list the crates from `search-index.js`. Meaning that at some point, the file isn't empty as it should. The problem here is that the rustdoc update wasn't fully integrated into docs.rs.

**Comment by GuillaumeGomez** [comment]
So here, I see two possibilities:
1. We remove `crates.js` from the folder
2. We don't generate `crates.js` when the `--disable-per-crate-search` argument is passed in rustdoc.

Which solution do you prefer?

**Comment by GuillaumeGomez** [comment]
I precise that the second option seems unreliable considering that `crates.js` isn't only used for search but also to list crates in the sidebar.

**Comment by GuillaumeGomez** [comment]
I can't find where you clean/remove the `search-index.js` file. Any pointer maybe? :)
