### ISSUE TITLE
rust logo is missing in interface, but it exists and returns (2020-03-23) 

### ISSUE THREAD

**Issue by syphar** [rust-lang/docs.rs#1328]
<img width="203" alt="grafik" src="https://user-images.githubusercontent.com/540890/112103990-e190da80-8baa-11eb-883d-33677dd5026e.png">
<img width="690" alt="grafik" src="https://user-images.githubusercontent.com/540890/112104039-f1102380-8baa-11eb-9fc4-5effa1a6a5a2.png">

For example (randomly chosen from the recent builds) [here](https://docs.rs/konst/0.2.0/konst/). 

~~The really interesting thing is: **The 404 response actually returns the image, only sets the status-code to 404. ** :)~~ (my mistake, early morning confusion)

A short local build was fine, so I'm not sure where the problem is.

**Comment by Nemo157** [comment]
I don't see an image returned, for `https://docs.rs/rust-logo-20210322-1.53.0-nightly-5d04957a4.png` I get an HTML response "no crate found".

Seems likely to be related to #1324, it's not falling back from the `rustdoc_redirect_handler` to the rustdoc-shared-file handler correctly for `.png`.

**Comment by syphar** [comment]
> I don't see an image returned, for https://docs.rs/rust-logo-20210322-1.53.0-nightly-5d04957a4.png I get an HTML response "no crate found". 

my mistake, I was seeing the logo in the preview in the dev-tools, and assumed it is only the logo, while it's the whole 404 page 😆

**Comment by syphar** [comment]
I had a short look and could not reproduce it locally (with fresh crate builds on the same nightly, but only with the small local db I have). 

Not sure if the file just wasn't copied at night.

**Comment by syphar** [comment]
at some point I need to find out why I could not reproduce this locally :)
