### ISSUE TITLE
Link does not work

### ISSUE THREAD

**Issue by vks** [rust-lang/docs.rs#133]
https://docs.rs/xsv/0.12.1 does not work, but https://docs.rs/crate/xsv/0.12.1 does. Other crates don't seem to have that problem, for example https://docs.rs/fst/0.2.3 works.

**Comment by onur** [comment]
Thanks for reporting.

When I first started developing docs.rs rust was only able to build documentation for only libraries but looks like this has changed. Docs.rs is currently skipping non-lib crates, this needs to be fixed.

**Comment by jyn514** [comment]
@vks your first link is now working. Building documentation for binaries is #238 .
