### ISSUE TITLE
Show when the build was completed on releases page

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/docs.rs#1337]
Currently it looks like docs.rs stopped building crates an hour ago:

![image](https://user-images.githubusercontent.com/81079/112814721-dc86cc00-907f-11eb-9b22-87b35c146bad.png)

But the "58 minutes ago" there (and the homepage) is based on when that version was released on crates.io, the docs were just built but the queue is running an hour behind. I think for our purposes it would be more useful to have this show time since latest build, so that users don't believe the builder is stuck, but still sorted by release date to choose what to display (so rebuilds don't reappear in the list).

**Comment by Darksonn** [comment]
Alternatively you could add a line of text at the top that says "x crates in build queue, last build completed y minutes ago" or similar.
