### ISSUE TITLE
Please rebuild mbedtls

### ISSUE THREAD

**Issue by jethrogb** [rust-lang/docs.rs#1346]
**Crate name:** mbedtls
**Build failure link:**
https://docs.rs/crate/mbedtls/0.8.0
https://docs.rs/crate/mbedtls/0.7.1
https://docs.rs/crate/mbedtls/0.7.0
https://docs.rs/crate/mbedtls/0.6.4
https://docs.rs/crate/mbedtls/0.6.3
https://docs.rs/crate/mbedtls/0.6.2
https://docs.rs/crate/mbedtls/0.6.1
https://docs.rs/crate/mbedtls/0.6.0

**Additional details:**
`mbedtls` depends on `mbedtls-sys-auto` which used to not build on docs.rs. Now that it [does](https://docs.rs/mbedtls-sys-auto/2.26.0/mbedtls_sys/), could you please rebuild the somewhat recent versions of mbedtls listed above?

**Comment by jyn514** [comment]
@jethrogb the build fails even with the new toolchain - did you upload a cargo.lock maybe? Docs.rs will respect that and use the old versions. https://docs.rs/crate/mbedtls/0.8.0/builds/373735

**Comment by jethrogb** [comment]
Ah, too bad. Then is there any way to fix this without publishing a new version?

**Comment by jyn514** [comment]
Unfortunately not, sorry.
