### ISSUE TITLE
wasmcloud-host failed nightly build, succeeds stable build

### ISSUE THREAD

**Issue by brooksmtownsend** [rust-lang/docs.rs#1348]
**Crate name:** wasmcloud-host
**Build failure link:** https://docs.rs/crate/wasmcloud-host/0.17.0/builds/375602

**Additional details:**
Our crate, `wasmcloud-host`, builds successfully on the latest stable version of Rust `1.51.1`. We're not entirely sure why docs.rs is using this nightly build, but it appears to cause issues and fail to build our project. Could we retry this docs.rs build with a stable version of Rust?

Thank you!

**Comment by jyn514** [comment]
> We're not entirely sure why docs.rs is using this nightly build, but it appears to cause issues and fail to build our project.

Because some crates only build on nightly, so building with stable will break them instead.

> Could we retry this docs.rs build with a stable version of Rust?

Unfortunately not: https://github.com/rust-lang/docs.rs/issues/506. I did build clang-sys 0.29.3 locally without issues, so not sure what's breaking. Looking into it now.

**Comment by brooksmtownsend** [comment]
Makes sense @jyn514, thanks for looking into it

**Comment by Nemo157** [comment]
It's a nightly regression https://github.com/rust-lang/rust/issues/84162

**Comment by autodidaddict** [comment]
Does that mean this docs build can be re-queued once the regression is over?

**Comment by jyn514** [comment]
@autodidaddict yes, I can queue a build once it's fixed.

**Comment by jyn514** [comment]
Queued and rebuilt: https://docs.rs/wasmcloud-host/0.17.0/wasmcloud_host/

**Comment by brooksmtownsend** [comment]
Thanks @jyn514 🔥
