### ISSUE TITLE
Search functionality broken for casper-types crate

### ISSUE THREAD

**Issue by Fraser999** [rust-lang/docs.rs#1354]
Trying to search in the docs for casper-types yields no results when it should not, or else a broken link to an `empty_library`.  This appears to affect all versions after and including 0.9.4.

For example, [searching for `account` in 0.9.3](https://docs.rs/casper-types/0.9.3/casper_types/?search=account) yields correct results (I need to click inside the search box to actually display the search results after following this link), whereas [the same search in 0.9.4 does not](https://docs.rs/casper-types/0.9.4/casper_types/?search=account).

[A search for `a` in 0.9.4](https://docs.rs/casper-types/0.9.4/casper_types/?search=a) yields the link to `empty_library`.

There were no changes to the casper-types crate between versions 0.9.3 and 0.9.4 other than the version bump in its manifest and in `#![doc(html_root_url = "https://docs.rs/casper-types/0.9.4")]` in lib.rs.

**Comment by zie1ony** [comment]
The same for other `casper-*` crates:
https://docs.rs/casper-client/1.1.0/casper_client/
https://docs.rs/casper-contract/1.1.0/casper_contract/
https://docs.rs/casper-node-macros/1.1.0/casper_node_macros/
https://docs.rs/casper-execution-engine/1.1.0/casper_execution_engine/

**Comment by jyn514** [comment]
This is https://github.com/rust-lang/docs.rs/issues/1336. I requeued a build for the crates you mentioned.

**Comment by zie1ony** [comment]
Thank you @jyn514. Have a great day :)

**Comment by jyn514** [comment]
Requeued and rebuilt: https://docs.rs/casper-types/0.9.4/casper_types/?search=account. Let me know if I missed any crates.
