### ISSUE TITLE
Failed to build doc for datachannel 0.5.1

### ISSUE THREAD

**Issue by lerouxrgd** [rust-lang/docs.rs#1355]
**Crate name:** datachannel
**Build failure link:** https://docs.rs/crate/datachannel/0.5.1/builds/376560

**Additional details:** Usually it works fine, 0.5.1 is just a minor bug fix for 0.5.0

**Comment by jyn514** [comment]
This is https://github.com/rust-lang/rust/issues/84162. I queued a rebuild for datachannel.

**Comment by jyn514** [comment]
Requeued and rebuilt: https://docs.rs/datachannel/0.5.1/datachannel/

**Comment by lerouxrgd** [comment]
thank you !
