### ISSUE TITLE
Rebuild for crate: bdk 0.6.0

### ISSUE THREAD

**Issue by notmandatory** [rust-lang/docs.rs#1356]
**Crate name:** bdk
**Build failure link:** https://docs.rs/crate/bdk/0.6.0/builds

**Additional details:** 
I've verified our docs will build correctly with the latest nightly 2021-04-15, our docs were impacted by https://github.com/rust-lang/rust/issues/84162, fixed by https://github.com/rust-lang/rust/pull/84130

**Comment by jyn514** [comment]
I added it to the queue.

**Comment by notmandatory** [comment]
Docs rebuilt successfully. Thanks again!
