### ISSUE TITLE
Rebuild for crates opensubdiv-petite, opensubdiv-petite-sys

### ISSUE THREAD

**Issue by virtualritz** [rust-lang/docs.rs#1364]
Crate names: `opensubdiv-petite`/`opensubdiv-petite-sys`
Build failure links:
- https://docs.rs/crate/opensubdiv-petite/0.1.0/builds/
- https://docs.rs/crate/opensubdiv-petite-sys/0.1.0/builds

Additional details:
I've verified our docs will build correctly with the latest nightly 2021-04-15, our docs were impacted by rust-lang/rust#84162, fixed by rust-lang/rust#84130.

**Comment by jyn514** [comment]
Requeued and rebuilt: https://docs.rs/opensubdiv-petite/0.1.0/opensubdiv_petite/. opensubdiv-petite-sys should finish building shortly.
