### ISSUE TITLE
The search box is hard to access with the Tab key

### ISSUE THREAD

**Issue by Azorlogh** [rust-lang/docs.rs#1366]
Whenever I want to access the search box, I use the Tab key to give it focus.
However, the focus first has to go through all the items on the left of the page before I get to the search box.
On crates with lots of items (which is when the search box is most useful!), it takes a very long time to get there.

I can think of two solutions to this problem:
- A keyboard shortcut to focus the search box
- Make a small box appear when Tab is pressed, offering buttons to focus different parts of the page (similar to Google)

**Comment by jyn514** [comment]
When you say the search box, are you asking about docs.rs search, or about rustdoc search? This is docs.rs:
![image](https://user-images.githubusercontent.com/23638587/115159381-dd989100-a060-11eb-9476-29023f663d0e.png)
and this is rustdoc: 
![image](https://user-images.githubusercontent.com/23638587/115159391-e5583580-a060-11eb-91ab-b6b245c295c3.png)

Rustdoc already has a keyboard shortcut.

**Comment by Azorlogh** [comment]
My bad, I'm not sure how I managed to miss the question mark...
