### ISSUE TITLE
Broken search for crate `x86_64` v0.14.0

### ISSUE THREAD

**Issue by phil-opp** [rust-lang/docs.rs#1369]
The search for the [`x86_64` crate](https://docs.rs/x86_64/0.14.0/x86_64/index.html) (version 0.14.0) is broken and only returns an `empty_library` result. This seems to be related to https://github.com/rust-lang/docs.rs/issues/1354 and https://github.com/rust-lang/docs.rs/issues/1336. Could you requeue a build for the crate please?

**Comment by jyn514** [comment]
Queued and rebuilt: https://docs.rs/x86_64/0.14.0/x86_64/?search=align

**Comment by phil-opp** [comment]
Thanks a lot!
