### ISSUE TITLE
Adding the Rust Cookbook to the "Rust" dropdown

### ISSUE THREAD

**Issue by lilianmoraru** [rust-lang/docs.rs#137]
I think that the [`rust-cookbook`](https://rust-lang-nursery.github.io/rust-cookbook/) should also be added in the `Rust` dropdown(where you have links to the reference manual, std...).
It probably falls in the same ballpark as `Rust by Example`

**Comment by jyn514** [comment]
Mentoring instructions:

In https://github.com/rust-lang/docs.rs/blob/master/templates/navigation.hbs#L17, add a `<li>` tag that has a link to the cookbook.
