### ISSUE TITLE
Search broken for hecs 0.5.1, various iterations of rapier 0.8.0

### ISSUE THREAD

**Issue by Ralith** [rust-lang/docs.rs#1370]
Searches in these crates return no results. Related to https://github.com/rust-lang/docs.rs/issues/1369?

**Comment by Ralith** [comment]
cpal 0.13.3 is also affected.

**Comment by jyn514** [comment]
The issue is we uploaded all files with the resource-suffix for a few releases:
```
$ aws s3 ls s3://rust-docs-rs | grep search-index.*js
2021-03-21 20:50:08        120 search-index-20210321-1.53.0-nightly-f82664191.js
2021-03-22 21:00:32        120 search-index-20210322-1.53.0-nightly-5d04957a4.js
2021-03-23 21:17:49        120 search-index-20210323-1.53.0-nightly-673d0db5e.js
2021-03-24 20:52:42        120 search-index-20210324-1.53.0-nightly-07e0e2ec2.js
2021-04-12 20:52:24        120 search-index-20210412-1.53.0-nightly-d0695c908.js
```
When I reverted https://github.com/rust-lang/docs.rs/pull/1324 in https://github.com/rust-lang/docs.rs/pull/1340, they broke search for all crates built by that toolchain. I don't have permissions to remove those files myself, but @pietroalbini should.

**Comment by pietroalbini** [comment]
Removed those files!

**Comment by Nemo157** [comment]
hecs search is still broken, it may be that the CDN needs invalidating too.

**Comment by jyn514** [comment]
@Nemo157 it's not enough to invalidate the path of the shared files, each individual crate has to be invalidated since we give precedence to global files over local ones.

**Comment by jyn514** [comment]
I wonder if it makes sense to add a search query to the global resources with the version of docs.rs they were built by. Then we wouldn't have to keep sending cache invalidations.

**Comment by jyn514** [comment]
Oh wait, that requires rustdoc support :/ maybe we could generate a redirect from the page rustdoc links to? Like redirect `crates-2021-03-24.js` -> `crates-2021-04-20.js?docsrs_version=2021-04-01`

**Comment by jyn514** [comment]
We just did a mass invalidation, this should fixed.
