### ISSUE TITLE
docs for cognitive-services-speech-sdk-rs failing to build

### ISSUE THREAD

**Issue by adambezecny** [rust-lang/docs.rs#1376]
**Crate name:** cognitive-services-speech-sdk-rs
**Build failure link:** https://docs.rs/crate/cognitive-services-speech-sdk-rs/0.1.1/builds/380044

**Additional details:**
failing to build because custom build script is trying to download native dependencies (MS Speech SDK) from github. I originally had these dependencies in lib directly but then I was not able to publish lib to crates.io since it allows only 10 MB in total per lib. 

Please advise how to proceed to build documentation for this crate. I cannot include libs directly due to 10 MB limitation and I cannot download them due to docs.rs buildsend box limitation.

**Comment by jyn514** [comment]
You might be able to use #593 if it's ever finished. I don't have suggestions other than that.

**Comment by jyn514** [comment]
I don't know what you mean by "load these files directly" - do you mean compile the docs on your own and upload them? That's https://github.com/rust-lang/docs.rs/issues/93.

I think I'd recommend hosting your own documentation on a separate website and linking to that in the readme. Docs.rs defaults to showing the readme if the documentation didn't build: https://docs.rs/deno_runtime.

**Comment by jyn514** [comment]
@adambezecny are you planning to work on this? If not there's not much point in us tracking it ... the features you've requested are already tracked elsewhere.

**Comment by adambezecny** [comment]
hi, working on what exactly? docs.rs has very sever limitations, like build cannot download any external dependencies, file system is read only. Makes very hard to build docs for crates which are using these things. I had to host documentation somewhere else. I guess this can be closed than. thx

**Comment by jyn514** [comment]
Got it. Sorry for the trouble.
