### ISSUE TITLE
Search not functioning for newest version of z3

### ISSUE THREAD

**Issue by GreenBeard** [rust-lang/docs.rs#1377]
The search never finishes for version 0.10.0 but works fine for 0.9.0.

https://docs.rs/z3/0.10.0/z3/index.html

**Comment by Nemo157** [comment]
Probably related to https://github.com/rust-lang/docs.rs/issues/1370, https://docs.rs/z3/0.10.0/search-index-20210322-1.53.0-nightly-5d04957a4.js gets a 404.

**Comment by jyn514** [comment]
This looks like a different problem, the search file is missing altogether instead of being the wrong version. I queued a rebuild, I don't think it's worth too much time investigating.

**Comment by jyn514** [comment]
The search works fine after a rebuild.
