### ISSUE TITLE
My crate ruspiro-boot shall build for target aarch64-unknown-linux-gnu but fails with "unknown CC/CC not installed"

### ISSUE THREAD

**Issue by 2ndTaleStudio** [rust-lang/docs.rs#1378]
**Crate name:** ruspiro-boot
**Build failure link:** https://docs.rs/crate/ruspiro-boot/0.5.2/builds/381675

**Additional details:** The build is expected to succeed for the `aarch64-unknown-linux-gnu` target with a custom build script that compiles some assembly for this target.

Thx in advance for your support.

**Comment by Nemo157** [comment]
Do you require the assembly to be compiled to generate docs? You could guard the compilation with `if std::env::var("DOCS_RS").is_none()` or similar to skip it. Otherwise `aarch64-linux-gnu-gcc` needs to be [added to the build-environment](https://forge.rust-lang.org/docs-rs/add-dependencies.html).

**Comment by 2ndTaleStudio** [comment]
Well, this is a good hint. I'll try this. As the assembly build is not required to build the documentation. The only drawback I could think of would be a binary crate that depends on this one and would also like to build documentation. This would fail than during linking as the required symbols are not build from the assembly. However, I treat this as kind of very unlikely to happen for the time being and try your approach.
