### ISSUE TITLE
Shorthand for searching?

### ISSUE THREAD

**Issue by matthiasbeyer** [rust-lang/docs.rs#1381]
Hi,

it would be nice to have a shorthand for searching, E.G.:

```
docs.rs/clap/App
```

To search for `"App"` in the docs for the `clap` crate. Most of the times I know which type I want to look at, so this would reduce my search-time by 50% (two page loads -> one page load).

Would such a thing be feasible?

**Comment by Nemo157** [comment]
`docs.rs/clap?search=App` works already to go directly to the search results. There is https://github.com/rust-lang/rust/issues/84214 which would make `docs.rs/clap?search=clap::App` go directly to the type, though it'd still be two page loads since the search is client-side.

**Comment by matthiasbeyer** [comment]
Yeah that's just really long to type :smile:

**Comment by Nemo157** [comment]
To specifically help with that rustdoc could support bare searches in the query, `docs.rs/clap?App` (are there any non-search parameters that rustdoc supports now?)

It is also sorta plausible that docs.rs could parse the search-index server-side and do some form of "I'm feeling lucky" redirect to avoid the double page load; but that'd require making the search-index format stable, so that rustdoc doesn't change it under us in the future.

**Comment by jyn514** [comment]
I don't think docs.rs/clap?App is a good approach, that means adding any query parameter ever will be a breaking change. I would be ok with /clap/App since version numbers and identifiers can't overlap, but it might be tricky to implement.

**Comment by jyn514** [comment]
Also I'm confused by the rationale - search is all client side so this won't affect load times whatsoever.

**Comment by matthiasbeyer** [comment]
> search is all client side so this won't affect load times whatsoever.

Yeah, I misphrased a bit: It's not the load times as in "browser loading" but as in "brain loading" that I mean. Right now, the workflow is `<Ctrl-T>docs.rs/clap<Enter>SApp<Enter>`, after that it would be `<Ctrl-T>docs.rs/clap/App<Enter>`, which is way shorter and less resource intensive on my brain, as I can keep the current Code I'm working on in memory! :laughing:

**Comment by Nemo157** [comment]
> I don't think docs.rs/clap?App is a good approach, that means adding any query parameter ever will be a breaking change.

Sure, but is there actually any reason to ever add a new query parameter? It wouldn't actually be a breaking change if only a query-string without `=` is treated as a search parameter, a new query parameter without value would be `docs.rs/clap?app=`.

**Comment by syphar** [comment]
This is solved since (october?) last year, 

one can now use `https://docs.rs/clap::App` to end up in the search for `App` in the `clap` docs.
