### ISSUE TITLE
Sidebar links don't open collapsed sections

### ISSUE THREAD

**Issue by dodomorandi** [rust-lang/docs.rs#1385]
I found this issue on `syn`. Open [this page](https://docs.rs/syn/1.0.71/syn/struct.Attribute.html) on the documentation, and click on one of the methods (i.e.: `parse_meta`).

[`impl Attribute`](https://docs.rs/syn/1.0.71/syn/struct.Attribute.html#impl) section is collapsed by default in this case, and clicking on one of the methods does not expand the section. Moreover, it does not even scroll the page to the collapsed element, making navigation a bit annoying.

If possible, I think that automatically expanding the relative collapsed section is the expected behavior. If this solution tricky, at least the page should be scrolled to the collapsed section.

**Comment by jyn514** [comment]
This is fixed on nightly. https://github.com/rust-lang/rust/pull/84552

**Comment by dodomorandi** [comment]
Sorry for the issue -- searched for the wrong terms :disappointed:

**Comment by jyn514** [comment]
No worries! docs.rs is in kind of a weird situation where it depends on lots of external tools.
