### ISSUE TITLE
Search is broken for minifb

### ISSUE THREAD

**Issue by john01dav** [rust-lang/docs.rs#1386]
When I attempt to search for an item via the search bar in any crate on docs.rs, I get the following failure mode:
![Demonstration of issue where it simply hangs on "Loading search results..." and the search bar is empty](https://user-images.githubusercontent.com/3982497/116739567-701e2600-a9b9-11eb-9b4f-2dbd1ba181fc.png)

In the Javascript console the following error message is present:
```
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“default-src”). storage-change-detection.html:11:1
```
They appear to be related, and possibly related to #1333, or #234. This error takes place in Firefox 88.0 on Fedora Linux. It does not take place with locally-generated rustdocs.

**Comment by john01dav** [comment]
> The script in `storage-change-detection.html` should be unrelated, that just means the docs.rs header/footer doesn't change theme when you change it in rustdoc instantly.
> 
> For `minifb 0.19.3` I see another error in the console:
> 
> ```
> GEThttps://docs.rs/minifb/0.19.3/search-index-20210322-1.53.0-nightly-5d04957a4.js
> [HTTP/2 404 Not Found 363ms]
> ```
> 
> Probably related to #1377/#1370.

I just tested with some random crates, and they seem to work. It seems like it doesn't work on all the crates I've been using recently, so I thought that it was more broad than it is.

**Comment by jyn514** [comment]
https://docs.rs/minifb/0.19.3/search-index-20210322-1.53.0-nightly-5d04957a4.js is missing for some reason. I'll rebuild the crate.

**Comment by jyn514** [comment]
Requeued and rebuilt: https://docs.rs/minifb/0.19.3/minifb/?search=menu
