### ISSUE TITLE
Accept `[package.metadata."docs.rs"]`

### ISSUE THREAD

**Issue by WaffleLapkin** [rust-lang/docs.rs#1396]
I was recently confused by docs.rs not using the provided [configuration](https://docs.rs/about/metadata) from the `Cargo.toml`:
```toml
[package.metadata."docs.rs"]
# Configuration ...
```

Turns out only `[package.metadata.docs.rs]` works (note: no `""`). Not sure why I've written `"docs.rs"` in the first place, but it would be nice to support this too.

**Comment by jyn514** [comment]
If there are both versions of the config I guess we should have `package.metadata.docs.rs` take precedence? I'd like to show a warning in that case but it will show up to readers of the docs too so not sure how useful it is.

**Comment by WaffleLapkin** [comment]
I don't think that somebody will actually have 2 docs.rs metadata sections in their `Cargo.toml`, so maybe showing a warning to readers isn't that bad?

**Comment by chansuke** [comment]
I would like to have a try on this issue.

**Comment by jyn514** [comment]
@chansuke take a look at https://github.com/rust-lang/docs.rs/blob/503fa4dbb9b752bc5635ce3c29c6df4e3470de28/crates/metadata/lib.rs#L303 - you should be able to do all your work just in that crate, and the compile times for it alone are very good.

**Comment by chansuke** [comment]
@jyn514 Sorry, I'd like to have some advice to solve the issue.
I simply thought that create another table and 

```
        let table_one = &manifest
            .and_then(|t| table(t, "package"))
            .and_then(|t| table(t, "metadata"))
            .and_then(|t| table(t, "docs"))
            .and_then(|t| table(t, "rs"));

        let table_second = &manifest
            .and_then(|t| table(t, "package"))
            .and_then(|t| table(t, "metadata"))
            .and_then(|t| table(t, "\"docs"))
            .and_then(|t| table(t, "rs\""));
```

Add a condition for `metadata` but I can't solve the type error. I think my approach is not good...

```
        let mut metadata = if let Some(table) = table_one {
            Value::Table(table).try_into()?   // expected struct `toml::map::Map`, found reference
        } else if let Some(table) = table_second {
            Value::Table(table).try_into()?   // expected struct `toml::map::Map`, found reference
        } else {
            Metadata::default()
        };
```

**Comment by jyn514** [comment]
@chansuke the problem is you use `&manifest`, so the first tables are now a borrow instead of an owned value. I would solve it by cloning the manifest I think, that should avoid the borrow error without adding a type error instead: `manifest.and_then(...).clone()`.

**Comment by ratijas** [comment]
Why would we have two almost-similar ways to do the same thing though? It would only confuse new users, leaving them wondering if one of two forms is outdated. As OP stated they weren't even sure why they wrote it that way with quotes, despite linked documentation page clearly provides an example to copy-paste.

**Comment by chansuke** [comment]
@jyn514 Thank you for the comment!! I will take a look!!

**Comment by ratijas** [comment]
>            .and_then(|t| table(t, "\"docs"))
>            .and_then(|t| table(t, "rs\""));

That's not even a double quoted string, that's a fake made of two separate nested table names. ~~Accepting code like that would only contribute to confusion, reinforcing wrong assumptions about overall TOML format. So, you say in theory it would be possible to write this?~~

```toml
[package.metadata."docs]
'rs"' = {
  # Configuration ...
}
```

Actually, ignore all of the above. The [official format](https://toml.io/en/v1.0.0#keys) specifies dotted and double-quoted keys, and even gives an example of them being used together. So, if this is really what it takes to parse `[package.metadata."docs.rs"]`, then the parser must be broken.
