### ISSUE TITLE
Cross-crate windows only links are broken

### ISSUE THREAD

**Issue by Darksonn** [rust-lang/docs.rs#1397]
Consider the following page:

https://docs.rs/tokio-stream/0.1.5/x86_64-pc-windows-msvc/tokio_stream/wrappers/struct.CtrlBreakStream.html

The links to `CtrlBreak` are broken because they link to the unix docs of the `tokio` crate, but the type is only available on windows.

**Comment by jyn514** [comment]
Original discussion: https://discord.com/channels/442252698964721669/541978667522195476/840892995199827988

**Comment by jyn514** [comment]
I think the proper fix is to add `{target}` to the `--extern-html-root-url` we pass to rustdoc.
