### ISSUE TITLE
Crates with docs built by the broken 2021-04-24 nightly should be rebuilt

### ISSUE THREAD

**Issue by lf-** [rust-lang/docs.rs#1399]
There was a bug fixed here: https://github.com/rust-lang/rust/pull/84552 where impl blocks were closed by default, breaking links from search and making it hard to see struct methods. It was fixed a couple of days later, although there was no nightly for a week starting slightly before the fix was merged since rustfmt had a build breakage.

It appears that docs.rs has built some crates with this broken nightly version, for instance, chalk-ir: see this broken page https://docs.rs/chalk-ir/0.66.0/chalk_ir/struct.ConcreteConst.html and the crate builds page https://docs.rs/crate/chalk-ir/0.66.0/builds

These should be rebuilt :)

**Comment by jyn514** [comment]
See also https://github.com/rust-lang/docs.rs/issues/464.

This is possible but it will be a lot of crates:
```
cratesfyi=> select count(*) from releases where doc_rustc_version like '%2021-04-24%>
 count 
-------
  4078
(1 row)
```

**Comment by ratijas** [comment]
I wonder, if this is still relevant few months later

**Comment by lf-** [comment]
Are there any crates where the latest version was built with the broken nightly?

**Comment by jyn514** [comment]
@lf- yes
```
cratesfyi=> select count(*) from releases inner join crates on releases.id = crates.latest_version_id where doc_rustc_version like '%2021-04-24%';
 count 
-------
  1065
(1 row)
```

**Comment by syphar** [comment]
541 latest releases remained that were built this this nightly version. 

I just queued the rebuilds for these, with very low priority.
