### ISSUE TITLE
Horizontal scroll oddness in docs.rs documentation

### ISSUE THREAD

**Issue by TheDutchMC** [rust-lang/docs.rs#1400]
Hi there.

The horizontal scroll bar seems to behave a bit oddly in code examples on docs.rs in Microsoft Edge:
https://user-images.githubusercontent.com/28569170/118153113-cd809100-b415-11eb-8e5c-3b3d27a4db48.mp4

On Chrome and Firefox it behaves like a normal scrollbar. I'm unsure if this is an issue at Microsoft's side though.

**Platform information**
OS: Windows 10 64-bit
Browser: MS Edge Version 90.0.818.56 (As of the time of writing, this is the latest stable version)

I've noticed this on the crate [espocrm-rs](https://docs.rs/espocrm-rs/0.2.0/espocrm_rs/), but have not checked others.

**Comment by syphar** [comment]
Hi, 
I see the same issue when using firefox and chrome here, though it changed with the new version of your crate. 
To me since it also happens when running `cargo doc`  locally, this is very likely an issue with rustdoc, not with docs.rs. 

perhaps @GuillaumeGomez can shed some light?

**Comment by GuillaumeGomez** [comment]
Sorry, even after seeing the video, I don't understand the problem... What should it do that it's not doing (or the opposite: what is it doing that it shouldn't)?

**Comment by TheDutchMC** [comment]
If you look at the horizontal scrollbar closely, you'll see that the 'thumb' of the scrollwheel is shaded the opposite of what it is in most other places on docs.rs (Light for the thumb, dark for the rest of the scrollbar), compared to here (dark for the thumb, light for the scrollbar), which makes it look like the scrollbar is sortof wrapping around the scrollbar, rather than going on the scrollbar 'track' itself.

It may be intentional design though, if that is the case, this issue can be closed. It looks weird to me though

**Comment by GuillaumeGomez** [comment]
It looks exactly identical to the vertical sidebar on the right, which is why I'm confused. The "scroller" is supposed to be darker.

**Comment by TheDutchMC** [comment]
Check. I'll close this issue then.

For some sidenote though as to why I thought this was a bug. On most pages (including github) the scrollthumb is white, though fair enough everyone their own design. I think it's mostly that the lighter track takes the attention, rather than the darker thumb.
