### ISSUE TITLE
Restart crate build: `linked_list_allocator` build failed because of nightly mismatch

### ISSUE THREAD

**Issue by phil-opp** [rust-lang/docs.rs#1401]
**Crate name:** `linked_list_allocator`
**Build failure link:** https://docs.rs/crate/linked_list_allocator/0.9.0/builds/383672

**Additional details:** The crate was updated in https://github.com/phil-opp/linked-list-allocator/pull/50 to work with rust nightly `2021-04-30` (and newer), but docs.rs still used nightly `2021-04-24` at that point. According to https://docs.rs/about/builds docs.rs now uses nightly `2021-05-11`, so restarting the build should fix the issue. Could you do that or do I need to release a new version? Thanks!

**Comment by jyn514** [comment]
Queued and rebuilt: https://docs.rs/linked_list_allocator/0.9.0/linked_list_allocator/

**Comment by phil-opp** [comment]
Thanks a lot!
