### ISSUE TITLE
method links broken

### ISSUE THREAD

**Issue by 89z** [rust-lang/docs.rs#1404]
If I go to this page:

https://docs.rs/pico-args/latest/pico_args/struct.Arguments.html

I see a method on the left called `finish`, but if I click it, it doesnt do anything:

https://docs.rs/pico-args/latest/pico_args/struct.Arguments.html#method.finish

**Comment by jyn514** [comment]
I assume you meant 0.4.1, this is fixed in the latest version. This is a duplicate of https://github.com/rust-lang/docs.rs/issues/1399; I'm not going to rebuild 0.4.1 for now since the latest version works.
