### ISSUE TITLE
Web3 build failed

### ISSUE THREAD

**Issue by asmita-mf** [rust-lang/docs.rs#1405]
I am working on substrate-node-template (https://github.com/substrate-developer-hub/substrate-node-template).
Integrate web3 as dependency in pallet/cargo.toml file .
Getting error named as sys not defined in this scope. similar more build errors are there, souch as socket.. error.
![image](https://user-images.githubusercontent.com/82894750/118602572-80633d00-b7d0-11eb-9279-c3e0548b451a.png)

Can you suggest me the reason, How I can use this web3 in my code

**Comment by jyn514** [comment]
Docs.rs is not a general support site. You can ask for help on users.rust-lang.org or on the community discord.
