### ISSUE TITLE
load keys with json

### ISSUE THREAD

**Issue by asmita-mf** [rust-lang/docs.rs#1407]
let tx = contract.call("sum", (number), accounts[0], Options::default()).await?;

As above code performing contract signed call with default accounts availble with eth,
Is there a another way to do contract call with my private own keys. As storing private keys is not safe , so I want to do samne trasaction by loading my account from a json & sign transaction
How can I achieve this in rust.

**Comment by syphar** [comment]
Hello, 

docs.rs is not a general support site, this repo is about the [docs.rs](https://docs.rs/) platform. 

You can ask for help on https://users.rust-lang.org/ or on the community discord.
