### ISSUE TITLE
An Internal Server Error occurs if the request URI has two forward slashes after the crate name

### ISSUE THREAD

**Issue by HTG-YT** [rust-lang/docs.rs#1409]
An unexpected `HTTP 500 Internal Server Error` response is returned if the request URI has to forward slashes after the crate name, for example:

`https://docs.rs/winapi//`

![image](https://user-images.githubusercontent.com/39023054/120091872-74b53600-c141-11eb-946a-acb8d205ebfa.png)

Tested on both Google Chrome and Firefox on Windows 21H1.

Thanks to Legorooj#2455 for bringing this up in the Rust Programming Language Community Server.

**Comment by syphar** [comment]
thank you for the report! 

the actual error when I reproduce this locally is: 
```
[ERROR] docs_rs::web: No error page for status Some(MovedPermanently); The request had a trailing slash.
```

**Comment by Legorooj** [comment]
I'd attempt to reproduce this myself locally if literally every option for how to run docs.rs locally in the README fails. Docker ports won't bind, can't find reference `refs/remotes/origin/master`, etc.
