### ISSUE TITLE
Building crates that work only on some platforms

### ISSUE THREAD

**Issue by Boddlnagg** [rust-lang/docs.rs#141]
Crates such as https://docs.rs/crate/core-foundation/0.4.1/builds fail to build on platforms other than macOS. In this case, it fails with `error: native frameworks are only available on macOS targets`, but the crate would build correctly on macOS targets ... docs.rs doesn't seem to even try to build on macOS, however, after this error.

Could it be changed in such a way that docs.rs tries to build on all platforms and later only show the subset of platforms where it succeeded to build?

**Comment by onur** [comment]
This is a known limitation of docs.rs.

Docs.rs is only using a Linux host machine right now. I can implement building on OSX if someone donates an OSX server.

**Comment by Boddlnagg** [comment]
Huh? But I changed `coremidi-sys` in such a way that it would be cfg'ed out if the target is not macOS, so it would not result in the linking error, but instead just build an empty crate. This worked, I can see the documentation for macOS: https://docs.rs/coremidi-sys/2.0.2/x86_64-apple-darwin/coremidi_sys/

So this means that somehow building for macOS target _does_ work, and docs.rs should do that even if the build for other targets fails.

**Comment by onur** [comment]
Ahh I see, I thought OSX targeted crates requires an OSX host machine, but looks like they are like [winapi](https://docs.rs/winapi/0.2.8/x86_64-pc-windows-gnu/winapi/) crates and rust-std for OSX is enough to build this type of crates.

Yes, I agree docs.rs should try to build crates for all targets and decide default-target itself. This is a neat idea and thanks for suggestion. I'll see what I can do.

**Comment by Boddlnagg** [comment]
Thanks, that sounds great! 👍

**Comment by jrmuizel** [comment]
I've run into this as well. What would be the best way to implement this?

**Comment by quadrupleslap** [comment]
Can I do anything to help get this implemented? I haven't looked too closely, but it looks like `src/docbuilder/chroot_builder.rs` is the only file that needs to be changed.

**Comment by jyn514** [comment]
I'm actually hoping to go the other way and _only_ build one target unless requested otherwise, see https://github.com/rust-lang/docs.rs/pull/532.

Would setting `default-target` to `x86_64-apple-darwin` fix your problem?

**Comment by jrmuizel** [comment]
Yes. I think that should work.
