### ISSUE TITLE
docs.rs shows crate version that doesn't exist on crates.io

### ISSUE THREAD

**Issue by soenkehahn** [rust-lang/docs.rs#1412]
I recently uploaded the first version of the crate `cradle` to crates.io: https://crates.io/crates/cradle. The versions tab correctly shows that there is only one version (`0.0.0`). On the corresponding docs.rs link (https://docs.rs/cradle/0.0.0/cradle/) I found that at the top it says 'Go to latest version', which links to a version `0.1.1` of the `cradle` crate that I didn't upload: https://docs.rs/crate/cradle/0.1.1. That version does not exist on crates.io.

(The text in that version seems to be an attempt at putting pressure on the crates.io team for handling crate squatting differently. I'd like to point out that I didn't write that text. I think the crates.io team is great!)

I thought it wasn't possible to delete crates from crates.io, so I'm not sure how this situation can happen. But more importantly: Can this be fixed somehow? I'd love to have documentation for my crate hosted on docs.rs that doesn't nudge users to see a 'latest version' of the docs that shouldn't be there.

Thanks a lot!

**Comment by jyn514** [comment]
This is https://github.com/rust-lang/docs.rs/issues/765, see https://github.com/rust-lang/docs.rs/issues/766.

**Comment by jyn514** [comment]
The fix is for me to run https://github.com/rust-lang/docs.rs/pull/898.

**Comment by soenkehahn** [comment]
Thanks @jyn514! So the fix is a manual repair on the docs.rs db, that you can run? If so, could you please perform that repair? And could you ping me when it's done? Thanks a lot!

**Comment by jyn514** [comment]
I deleted cradle 0.1.1 and updated the owner info so it only shows you. I haven't run a general command to fix all problems of this type.

**Comment by soenkehahn** [comment]
Awesome, thanks a lot!
