### ISSUE TITLE
Metadata to build on windows was ignored

### ISSUE THREAD

**Issue by HEnquist** [rust-lang/docs.rs#1413]
### Crate name

wasapi

### Build failure link

https://docs.rs/crate/wasapi/0.1.1/builds/396727

### Additional details

After a first failed attempt with my new crate for windows, I added a [package.metadata.docs.rs] section in my manifest:
```
[package.metadata.docs.rs]
default-target = "x86_64-pc-windows-msvc"
targets = ["x86_64-pc-windows-msvc"]
```
But that didn't change anything. It's not working but I don't see anything wrong. What should I do? Grateful for any hints.

**Comment by jyn514** [comment]
```
[INFO] [stderr]    Compiling wasapi v0.1.1 (/opt/rustwide/workdir)
[INFO] [stderr] error: linking with `cc` failed: exit status: 1
[INFO] [stderr]   |
[INFO] [stderr]   = note: /usr/bin/ld: cannot find -lOLE32
[INFO] [stderr]           /usr/bin/ld: cannot find -lKERNEL32
[INFO] [stderr]           /usr/bin/ld: cannot find -lOLEAUT32
[INFO] [stderr]           /usr/bin/ld: cannot find -lKERNEL32
[INFO] [stderr]           collect2: error: ld returned 1 exit status
```

This is because docs.rs cross-compiles from linux to windows, those libraries aren't available except on a windows host.

**Comment by HEnquist** [comment]
Ok thanks! Is there any way around this, other than making dummy implementations of everything for the cross-compile? I guess any crate relying on the `windows` crate will have the same problem.

**Comment by jyn514** [comment]
I don't think so, no. Docs.rs would need a Windows host machine which we don't have the infra to support.

**Comment by HEnquist** [comment]
Got it! Thanks you.
