### ISSUE TITLE
"Source" title is missing from the dropdown

### ISSUE THREAD

**Issue by jyn514** [rust-lang/docs.rs#1422]
![image](https://user-images.githubusercontent.com/23638587/122268818-8705d280-ceaa-11eb-9185-203505bfd693.png)

**Comment by syphar** [comment]
ah, I was confused for a second. 

It's only hidden on small screens with small menu items

**Comment by jyn514** [comment]
As usual, this is caused by interactions with rustdoc.css :facepalm: 
![Uploading image.png…]()

**Comment by jyn514** [comment]
I think we can just remove `class="title"` and be ok? I'm not sure what that class actually does.

**Comment by jyn514** [comment]
Fixed in https://github.com/rust-lang/docs.rs/pull/1437.
