### ISSUE TITLE
Panic calculating redirect page

### ISSUE THREAD

**Issue by jyn514** [rust-lang/docs.rs#1425]
```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/web/rustdoc.rs:525:54
```

https://github.com/rust-lang/docs.rs/blob/7b80116656ee31d3f518c90e447309ffbb1273a2/src/web/rustdoc.rs#L525

There are a whole bunch of these in the server logs.

**Comment by jyn514** [comment]
Oh, well, I'm dumb, not all source files are rust files 😆

**Comment by syphar** [comment]
> Oh, well, I'm dumb, not all source files are rust files 😆

Not only you 😆 
since I missed this too, even though I should have know better :)
