### ISSUE TITLE
enchant build failure

### ISSUE THREAD

**Issue by jtojnar** [rust-lang/docs.rs#1439]
### Crate name

enchant

### Build failure link

https://docs.rs/crate/enchant/0.2.0/builds/161584

### Additional details

Hi, could you please trigger a rebuild for the enchant crate. The dependency should have been installed in https://github.com/rust-lang/crates-build-env/pull/85.

**Comment by jyn514** [comment]
Queued and rebuilt: https://docs.rs/enchant/0.2.0/enchant/
