### ISSUE TITLE
Add a way to collapse the sidebar in docs.rs' source view

### ISSUE THREAD

**Issue by jyn514** [rust-lang/docs.rs#1445]
This is not a great UI: 
![image](https://user-images.githubusercontent.com/23638587/125467542-209259ce-d2fa-4dd5-bb14-578d45ff137e.png)

especially since horizontal scrolling only scrolls within that box:
![image](https://user-images.githubusercontent.com/23638587/125467602-ddf23b0d-f8bd-4991-983f-2d299890cf09.png)

**Comment by GuillaumeGomez** [comment]
Something like we have in rustdoc source code pages? :)

**Comment by jyn514** [comment]
Sure, that would work.

**Comment by GuillaumeGomez** [comment]
Going to do it tomorrow then.
