### ISSUE TITLE
tokio-vsock 0.3.1 failed to build

### ISSUE THREAD

**Issue by Tim-Zhang** [rust-lang/docs.rs#1446]
### Crate name

tokio-vsock

### Build failure link

https://docs.rs/crate/tokio-vsock/0.3.1/builds/392463

### Additional details

error: Unrecognized option: 'resource-suffix'

**Comment by jyn514** [comment]
```
[INFO] [stderr]  Documenting tokio-vsock v0.3.1 (/opt/rustwide/workdir)
[INFO] [stderr] thread 'rustc' panicked at 'index out of bounds: the len is 42 but the index is 42', compiler/rustc_metadata/src/creader.rs:137:21
```
This should be fixed on nightly by https://github.com/rust-lang/rust/pull/85749.

**Comment by Tim-Zhang** [comment]
@jyn514 Can you help to trigger the build again?

**Comment by jyn514** [comment]
Added it to the queue: https://docs.rs/releases/queue

**Comment by Tim-Zhang** [comment]
Thank you!

**Comment by jyn514** [comment]
You're welcome! :)

It's been rebuilt: https://docs.rs/tokio-vsock/0.3.1/tokio_vsock/
