### ISSUE TITLE
rg3d 0.21 failed to build

### ISSUE THREAD

**Issue by mrDIMAS** [rust-lang/docs.rs#1449]
### Crate name

rg3d

### Build failure link

https://docs.rs/crate/rg3d/0.21.0/builds/410520

### Additional details

It is strange that docs for `xcb 0.8.2` is successfully built, but dependent rg3d's docs has failed to build.

**Comment by jyn514** [comment]
```
[INFO] [stderr]     File "/opt/rustwide/cargo-home/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.2/rs_client.py", line 114, in writeout
[INFO] [stderr]       with open(path, 'w') as f:
[INFO] [stderr]   OSError: [Errno 30] Read-only file system: '/opt/rustwide/cargo-home/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.2/src/ffi/selinux.rs'
```
The docs.rs sandbox blocks writing to the source directory. This is fixed in the latest version of xcb, you just need to update.

> It is strange that docs for xcb 0.8.2 is successfully built, but dependent rg3d's docs has failed to build.

It was built before we started sandboxing builds.

**Comment by mrDIMAS** [comment]
Thank you! I contacted the author of the crate that use outdated `xcb` (it is `clipboard` crate) few days ago, but he still haven't answered. The repo even has a PR that fixes the issue - https://github.com/aweinstock314/rust-clipboard/pull/76 . I'll wait a bit more, and if it won't be fixed in the repo, I'll just make a fork and fix everything manually. I think this issue can be closed now, I need to publish a new version of the crate anyway to fix the issue and docs.rs will rebuild the docs.
