### ISSUE TITLE
ttrpc 0.5.1 failed to build

### ISSUE THREAD

**Issue by Tim-Zhang** [rust-lang/docs.rs#1451]
### Crate name

ttrpc

### Build failure link

https://docs.rs/crate/ttrpc/0.5.1

### Additional details

[INFO] [stderr] thread 'rustc' panicked at 'index out of bounds: the len is 52 but the index is 52', compiler/rustc_metadata/src/creader.rs:137:21

**Comment by jyn514** [comment]
Queued and rebuilt: https://docs.rs/ttrpc/0.5.1/ttrpc/

(This was caused by https://github.com/rust-lang/rust/issues/84738, which has since been reverted.)
