### ISSUE TITLE
rebuild request

### ISSUE THREAD

**Issue by jnqnfe** [rust-lang/docs.rs#1454]
### Crate name

libpulse-binding

### Build failure link

https://docs.rs/crate/libpulse-binding/2.24.0/builds/416491

### Additional details

I made a mistake in version 1.19.0 of `libpulse-sys`, which I fixed in version 1.19.1. The following sibling crates that all depend upon it also of course failed and need a rebuild:

 - `libpulse-simple-sys` (1.19.0)
 - `libpulse-mainloop-glib-sys` (1.19.0)
 - `libpulse-binding` (2.24.0)
 - `libpulse-simple-binding` (2.24.0)
 - `libpulse-glib-binding` (2.24.0)

thanks, and appologies for the mess.

**Comment by jyn514** [comment]
Unfortunately you have `libpulse-sys 1.19.0` in Cargo.lock: https://docs.rs/crate/libpulse-simple-sys/1.19.0/source/Cargo.lock so this won't work even if I queue a rebuild. You'll have to publish a new version with an updated lockfile.
