### ISSUE TITLE
wgpu failure due to downstream crate

### ISSUE THREAD

**Issue by cwfitzgerald** [rust-lang/docs.rs#1469]
### Crate name

wgpu

### Build failure link

https://docs.rs/crate/wgpu/0.10.0/builds/424835

### Additional details

This was an issue in a dependency which has now been fixed. Just needs to be re-build

**Comment by jyn514** [comment]
Unfortunately you checked-in your Cargo.lock, so a rebuild won't help, it will use the same broken version of the dependency: https://docs.rs/crate/wgpu/0.10.0/source/Cargo.lock
You'll need to publish a new version of wgpu.

**Comment by cwfitzgerald** [comment]
Ahhh, didn't realize we erroneously shipped that. Thanks for the quick response!
