### ISSUE TITLE
Detecting docs.rs from build.rs?

### ISSUE THREAD

**Issue by kornelski** [rust-lang/docs.rs#147]
I have a crate that requires complicated system dependencies to build. However, the real functionality is not actually needed for docs, so I think I could fake it just for doc generation. 

Can I somehow detect docs.rs and build my crate differently for docs?

**Comment by onur** [comment]
Thanks for the neat idea, currently there is no way to check this.

We can setup an environment variable and you can check presence of this env var to detect if build machine is docs.rs. What do you think?

**Comment by pornel** [comment]
Yes, that would work.

**Comment by waywardmonkeys** [comment]
Is there any update on this or something that I can do to help out?

**Comment by epage** [comment]
As a terrible workaround, what about creating a `docs-rs` feature that stubs out your `-sys` dependencies?  You can then use the `package.metadata.docs.rs.features` table in `Cargo.toml` to enable that feature.

**Comment by kornelski** [comment]
There could be docs.rs-specific solution (e.g. the site could set a feature or env var), but ideally this could be built-in into Rust. 

For example tests get `cfg(test)`, so perhaps docs should get `cfg(docs)`? 

If there was an officially blessed solutions, then it would help convincing crates like `pkg-config-rs` to solve the problem for all crates (e.g. it could ignore pkg-config errors when `cfg(docs)`).

**Comment by pkgw** [comment]
See [@nickbabcock's comment in #191](https://github.com/onur/docs.rs/issues/191#issuecomment-389375388) for a clever-but-hacky workaround:

```toml
[package.metadata.docs.rs]
rustc-args = ["--cfg",  "<name>_docs_rs"]
rustdoc-args = ["--cfg", "<name>_docs_rs"]
```
 Then in `build.rs` you can do things like:

```rust
if cfg!(<name>_docs_rs) { ... }
```

**Comment by kornelski** [comment]
I wasn't aware of the metadata table!

[package.metadata.docs.rs]
features = [ "docs-rs" ]

That would work for me.

**Comment by ogoffart** [comment]
The `[package.metadata.docs.rs] features = [ "docs-only" ]` Did not work for me while attempting a generic solution for the cpp crate  (https://github.com/mystor/rust-cpp/pull/57 )
The first problem is that i forgot to add a `[feature] docs-only=[]` then the compilation of the cpp_build failed in https://docs.rs/crate/cpp_build/0.5.2/builds/165974  I did not know this was required. But that's easy to fix.

A more complicated problem is that it seems that this `package.metadata.docs.rs] ` only work when generating the documentation for the crate itself, but not when compiling the dependencies.
So a crate that depends on cpp_build did not try to compile it with the feature, as this can be seen in https://docs.rs/crate/qmetaobject/0.1.0/builds/165979 :

```
   Compiling cpp_build v0.5.2
```

This succeed, while it should have failed (because of the  missing `[feature]` section in cpp-build)  Therefore showing that the feature was not passed to the crate.

Any idea how to solve this?

**Comment by jyn514** [comment]
`cfg(doc)` is now native to rustdoc, would that solve your issue?

**Comment by retep998** [comment]
Can that be detected by build scripts?

**Comment by jyn514** [comment]
Hmm, I don't think so. I'll see if we can add an environment variable.

**Comment by jyn514** [comment]
Mentoring instructions:

- In [`execute_build`](https://github.com/rust-lang/docs.rs/blob/master/src/docbuilder/rustwide_builder.rs#L495), set an environment variable when calling cargo (maybe `DOCS_RS=1`?). It would be nice to add a link to this issue as a comment as well.
- Add documentation to [`templates/about.hbs`](https://github.com/rust-lang/docs.rs/blob/master/templates/about.hbs), maybe near the top where we mention the version of `rustc` being used.

See also the [contributing guidelines](https://github.com/rust-lang/docs.rs/#development). Feel free to reach out here or on the Discord [`#docs-rs`](https://discord.gg/f7mTXPW) channel if you need help!

**Comment by jyn514** [comment]
docs.rs now sets `DOCS_RS=1` when compiling crates.

**Comment by thewh1teagle** [comment]
> docs.rs now sets `DOCS_RS=1` when compiling crates.

Can we detect it also when invoking `cargo doc`?

**Comment by syphar** [comment]
> > docs.rs now sets `DOCS_RS=1` when compiling crates.
> 
> How can we detect it also when invoking `cargo doc`?

@thewh1teagle I don't know of any environment variable that is set, more idiomatically you can use `#[cfg(doc)]` and `#[cfg(not(doc))]`

**Comment by jyn514** [comment]
if you need to detect docs.rs specifically you can use `package.metadata.docs.rs.features = [“my-special-feature”]`. that will also let other people reuse the code when they depend on your crate, although they still have to know the feature exists at all.

**Comment by epage** [comment]
The docs.rs documentation has a page on this topic: https://docs.rs/about/builds#detecting-docsrs

**Comment by syphar** [comment]
> if you need to detect docs.rs specifically you can use `package.metadata.docs.rs.features = [“my-special-feature”]`. that will also let other people reuse the code when they depend on your crate, although they still have to know the feature exists at all.

[the last question here](https://github.com/rust-lang/docs.rs/issues/147#issuecomment-2561709668) was about detecting `cargo doc`, **not** detecting docs.rs

**Comment by epage** [comment]
The issue for detecting `rustdoc` is rust-lang/cargo#8811
