### ISSUE TITLE
"Hide files" toggle should be fixed so it isn't hidden after scrolling

### ISSUE THREAD

**Issue by jyn514** [rust-lang/docs.rs#1474]
The "Hide files" button doesn't scroll with the content, so you can end up having to scroll back up to the top to collapse the sidebar:
![image](https://user-images.githubusercontent.com/23638587/130333505-43c65eb4-c7b7-401f-a95e-8b77eb6eea04.png)

Rustdoc does this by making the sidebar scrolling independent from the content scrolling, maybe we could copy that? Or would you prefer to leave that for a follow-up?

cc @GuillaumeGomez
_Originally posted by @jyn514 in https://github.com/rust-lang/docs.rs/issues/1464#issuecomment-903169839_

**Comment by GuillaumeGomez** [comment]
I also think the scrolling should be independant (in case we count votes haha).
