### ISSUE TITLE
Provide documentation on the docs.rs specific metadata

### ISSUE THREAD

**Issue by retep998** [rust-lang/docs.rs#148]
docs.rs recently added support for its own custom metadata to dictate how documentation is built, however there is no documentation on the metadata, making it rather difficult to use. If there *is* documentation, then the issue is that the documentation can't be found easily.

**Comment by waywardmonkeys** [comment]
There is some in https://github.com/onur/docs.rs/blob/master/src/docbuilder/metadata.rs

**Comment by jyn514** [comment]
This is now documented in https://docs.rs/about#metadata.
