### ISSUE TITLE
Docs.rs uses old rustc

### ISSUE THREAD

**Issue by korken89** [rust-lang/docs.rs#1482]
### Crate name

panic-halt

### Build failure link

https://docs.rs/crate/panic-halt/0.2.0

### Additional details

From what I can see it has tried to build the crate using rustc 1.28, in which `#[panic_handler]` was not available.
This has built before, so not sure what has happened. 
No releases of this crate has happened for a long time.

Thanks for your assistance!

**Comment by Nemo157** [comment]
The last build for `panic-halt` was at 2018-09-09, at that point 1.28 was the latest stable version, I guess `panic-halt` was nightly only then. @jyn514 can queue another build for it if it will build on the current compiler.

**Comment by jyn514** [comment]
I queued a rebuild: https://docs.rs/releases/queue

**Comment by jyn514** [comment]
Rebuilt: https://docs.rs/panic-halt/0.2.0/panic_halt/
