### ISSUE TITLE
Can’t build webrtc with rustc nightly, but GitHub Actions does

### ISSUE THREAD

**Issue by rainliu** [rust-lang/docs.rs#1483]
### Crate name

webrtc

### Build failure link

https://docs.rs/crate/webrtc/0.0.8/builds/432195

### Additional details

GitHub Actions uses /usr/share/rust/.cargo/bin/rustup toolchain install nightly
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
info: latest update on 2021-09-06, rust version 1.57.0-nightly (e30b68353 2021-09-05)

it can successfully build it.
https://github.com/webrtc-rs/webrtc/runs/3522171884?check_suite_focus=true

but docs.rs fails to build it with the same # rustc version
rustc 1.57.0-nightly (e30b68353 2021-09-05)

Looks like GitHub Actions uses the latest version of dependent crate num-bigint
Compiling num-bigint v0.4.2

But docs.rs still uses old dependent crate num-bigint v0.4.0.

**Comment by Nemo157** [comment]
docs.rs uses the [`Cargo.lock`](https://docs.rs/crate/webrtc/0.0.8/source/Cargo.lock) distributed with the library to determine which versions of dependencies to use, that specifies to use exactly `num-bigint 0.4.0` to build with.

**Comment by rainliu** [comment]
Got it. Let me try to update Cargo.lock
