### ISSUE TITLE
Rebuild request

### ISSUE THREAD

**Issue by eadf** [rust-lang/docs.rs#1485]
### Crate name

centerline

### Build failure link

https://docs.rs/crate/centerline/0.6.0/builds/432231

### Additional details

Same error as #1483, but my library does *not* include a Cargo.lock file.
cargo doc works on rustc 1.56.0-nightly (0035d9dce 2021-08-16) (latest on M1 Mac)

**Comment by Nemo157** [comment]
Unfortunately `cargo publish` by default generates and publishes the `Cargo.lock` file, using [`cargo-download`](https://crates.io/crates/cargo-download) I can see that there is definitely a `Cargo.lock` in the package (I'm unsure whether docs.rs' source view takes the files before the point where it might generate a local `Cargo.lock` for the build, but you can [see that it is there too](https://docs.rs/crate/centerline/0.6.0/source/Cargo.lock)).

**Comment by eadf** [comment]
Any suggestions on how to solve this?
Do i have to wait until  rustc 1.57.0-nightly hits the M1 platform and re-publish?
