### ISSUE TITLE
Add GUI tests

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/docs.rs#1494]
crates.io has GUI tests using percy: https://percy.io/crates-io/crates.io/builds/11597533/changed/652575280

We had a lot of UI regressions so it'd be nice to have a GUI testsuite to make it easier to spot them (and to know where they happen more precisely).

Things to be tested:

 * position of the footer (always at the bottom of the page)
 * icons in the topbar depending on the width of the screen
 * ...

**Comment by syphar** [comment]
duplicate of #996 ( I think)

**Comment by GuillaumeGomez** [comment]
Ah inedeed. Sorry about that.
