### ISSUE TITLE
Missing file from a cloned crate

### ISSUE THREAD

**Issue by MrElectrify** [rust-lang/docs.rs#1495]
### Crate name

mmap-loader

### Build failure link

https://docs.rs/crate/mmap-loader/0.3.1/builds/435235

### Additional details

The [`ring`](https://docs.rs/ring/0.16.20/ring/index.html) crate linked by `rustls` includes some native C code for AES routines at the path `ring-0.16.20/crypto/fipsmodule/aes/aes_nohw.c`, and the file does not exist in the docs.rs build environment. Is this a possible issue with cloning? Or possibly an issue with ring's build script?

**Comment by Nemo157** [comment]
I think the error is actually that `x86_64-w64-mingw32-gcc` doesn't exist:

```console
> docker run --rm ghcr.io/rust-lang/crates-build-env/linux:latest which x86_64-w64-mingw32-gcc
```

**Comment by MrElectrify** [comment]
Looks like you are 

> 
> 
> I think the error is actually that `x86_64-w64-mingw32-gcc` doesn't exist:
> 
> ```
> > docker run --rm ghcr.io/rust-lang/crates-build-env/linux:latest which x86_64-w64-mingw32-gcc
> ```

Good catch, my mistake. On to figure out cross-compiling without these C files. Thanks
