### ISSUE TITLE
Feature request: Add an endpoint which serves the raw source of rust files, with permissive CORS headers

### ISSUE THREAD

**Issue by mstange** [rust-lang/docs.rs#1496]
Let's say I want to read the source code of `src/macros/scoped_tls.rs` of the crate `tokio` version `1.6.1`.

docs.rs has a viewer for this source code in two places:
 - https://docs.rs/crate/tokio/1.6.1/source/src/macros/scoped_tls.rs
 - https://docs.rs/tokio/1.6.1/src/tokio/macros/scoped_tls.rs.html

However, both of these endpoints wrap the source code in an HTML template.
Is there a way to get the raw source code? If not, would you be open to adding an endpoint for this?

Background:
I'm working on the Firefox profiler, which is a web app. I'm planning to make it usable for profiling local Rust applications. Here's an example profile: https://share.firefox.dev/3AiTMkJ
I'm also planning to give it an inline source viewer which displays timing costs on a per-line basis. Furthermore, profiles from this profiler can be shared and viewed on other people's machines. It would be great if, for Rust dependencies, I could request the raw source file from the internet.
At the moment, the profiles I'm capturing contain absolute paths that are only valid on the original machine, for example `/Users/mstange/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.6.1/src/macros/scoped_tls.rs`. It would be great if I could just translate this path into, say, `https://docs.rs/crate/tokio/1.6.1/rawsource/src/macros/scoped_tls.rs` before profile upload, so that any user could access that profile and see the source code, without the code having to be embedded inside the profile.

There is in fact an existing URL where the raw source of this file can be obtained: `https://raw.githubusercontent.com/tokio-rs/tokio/1baea398c4ee9361c72dc7829331366ed1d1c7f0/tokio/src/macros/scoped_tls.rs` .
However, not all published crates have their code on github. And it's not always easy to find the correct path in the github repo, if the repository uses a cargo workspace (as is the case here for tokio).

**Comment by jyn514** [comment]
>  Is there a way to get the raw source code? If not, would you be open to adding an endpoint for this?

This is not something docs.rs should be doing IMO. You can get the source code from crates.io instead (there's even a helpful wrapper: https://crates.io/crates/cargo-download).
