### ISSUE TITLE
Link to docker docs on how to start the service

### ISSUE THREAD

**Issue by Nilirad** [rust-lang/docs.rs#1502]
Followup of #1501.

Many users that never used docker before could get stuck because they forget to start the docker service.

Therefore I think it's better to add in README.md an appropriate link to the docker documentation where it says to ensure that the docker service is running.

Unfortunately I can't do it myself because I don't know where to link to (I never used docker before), so I'm opening this issue.

**Comment by jyn514** [comment]
Hmm, I'm not sure if there's docs on https://docs.docker.com/; this is pretty specific to how you've installed docker. On most linux systems it will be `sudo systemctl start docker`, but that won't work on Mac/Windows/any system not using systemd.

**Comment by jyn514** [comment]
I'm going to close this as unactionable; if you have trouble starting docker, feel free to join the discord so I or another member of the team can help you out.
