### ISSUE TITLE
Rebuild request

### ISSUE THREAD

**Issue by sunshowers** [rust-lang/docs.rs#1510]
Hi there!

Wondering if you could issue a rebuild request for the following crates:
* [guppy 0.11.1](https://docs.rs/crate/guppy/0.11.1)
* [determinator 0.6.0](https://docs.rs/crate/determinator/0.6.0)
* [hakari 0.5.0](https://docs.rs/crate/hakari/0.5.0)

All of these failed due to https://github.com/rust-lang/rust/issues/89393, which (I've verified) has been fixed in `rustc 1.57.0-nightly (f03eb6bef 2021-10-02)`. Thanks!

**Comment by jyn514** [comment]
They've finished building.
