### ISSUE TITLE
`librclone-sys` fails due to golang build dependency

### ISSUE THREAD

**Issue by trevyn** [rust-lang/docs.rs#1515]
### Crate name

librclone-sys

### Build failure link

https://docs.rs/crate/librclone-sys/0.1.0/builds/444138

### Additional details

This `-sys` crate runs a golang build, which fails at:

`failed to initialize build cache at /.cache/go-build: mkdir /.cache: permission denied`

**Comment by jyn514** [comment]
See also https://github.com/rust-lang/docs.rs/issues/1303.

**Comment by trevyn** [comment]
Ah. Due to the way Go does builds, I do not expect that this will work with a network restriction. Is there a way to get self-built docs onto docs.rs?

**Comment by jyn514** [comment]
@trevyn no, see https://github.com/rust-lang/docs.rs/issues/93

**Comment by jyn514** [comment]
If there's a way to vendor your dependencies into the published crate so Go doesn't try to download them, that could work.
