### ISSUE TITLE
big crates are slow to use with new archive-storage

### ISSUE THREAD

**Issue by syphar** [rust-lang/docs.rs#1528]
For crates with many files we have a performance regression. 

Example is [`stm32ral`](https://docs.rs/stm32ral/0.7.0/stm32ral/), which has 1.2 Million files in the archives. 

Currently we are reading the whole index from disk for every _file-exists_ or _get-from-archive_ request, which might take too much time.

**Comment by jyn514** [comment]
Current status for 99th percentile: 
![image](https://user-images.githubusercontent.com/23638587/141646931-fdf66423-f922-460f-9444-1632d00496ea.png)

The deploy of https://github.com/rust-lang/docs.rs/pull/1541 happened at 13:38 and the spike at 14:05 is me testing https://docs.rs/stm32ral/0.7.0/stm32ral/.

**Comment by syphar** [comment]
After: 
- #2068
- #2154
- migrating the old indexes this week (01.08./02.08.) 

this is solved. 

#2179 will drop the old code
