### ISSUE TITLE
Consider splitting crate name on spaces and `::`

### ISSUE THREAD

**Issue by jyn514** [rust-lang/docs.rs#1531]
Right now, `!drs tokio::spawn` takes you to https://docs.rs/tokio%3A%3Aspawn, which gives a 404. Ideally, duckduckgo would fix this on their end, but I looked at https://duckduckgo.com/newbang and they don't have any way to split the search string, only paste it literally. So it might be worth doing on our end instead and rewriting `/tokio::spawn` to https://docs.rs/tokio/?search=spawn.

**Comment by joshtriplett** [comment]
I would *love* to see this, as well.
