### ISSUE TITLE
My crate called toy-arms was failed to build by docs

### ISSUE THREAD

**Issue by s3pt3mb3r** [rust-lang/docs.rs#1544]
### Crate name

toy-arms

### Build failure link

https://docs.rs/crate/toy-arms/0.7.1

### Additional details

it uses winapi and thiserr crates as a dependency

**Comment by jyn514** [comment]
```
[INFO] [stderr]  Documenting toy-arms v0.7.1 (/opt/rustwide/workdir)
[INFO] [stderr] error[E0433]: failed to resolve: could not find `shared` in `winapi`
[INFO] [stderr]  --> src/internal.rs:2:13
[INFO] [stderr]   |
[INFO] [stderr] 2 | use winapi::shared::minwindef::HMODULE;
[INFO] [stderr]   |             ^^^^^^ could not find `shared` in `winapi`
```
I think you need to set the targets to a windows platform, docs.rs builds for linux by default. See how winapi does it: https://docs.rs/crate/winapi/0.3.9/source/Cargo.toml.orig
```
[package.metadata.docs.rs]
default-target = "x86_64-pc-windows-msvc"
targets = ["aarch64-pc-windows-msvc", "i686-pc-windows-msvc", "x86_64-pc-windows-msvc"]
```

**Comment by s3pt3mb3r** [comment]
Thank you so much it must be the thing.
I'll try correct it by replicating the winapi one.

**Comment by s3pt3mb3r** [comment]
Yes, actually i succeeded to eliminate the entire errors. Thanks for the kind support.
