### ISSUE TITLE
rocket_prometheus 0.9.0 failed to build

### ISSUE THREAD

**Issue by sd2k** [rust-lang/docs.rs#1549]
### Crate name

rocket_prometheus

### Build failure link

https://docs.rs/crate/rocket_prometheus/0.9.0/builds/448701

### Additional details

This was due to a bug in rustc nightly, see https://github.com/SergioBenitez/Rocket/issues/1948. It's resolved now and should build on the current version used by docs.rs, so I think a rebuild should solve it.

Thanks!

**Comment by jyn514** [comment]
Requeued and rebuilt: https://docs.rs/rocket_prometheus/0.9.0/rocket_prometheus/
