### ISSUE TITLE
Trailing whitespace lead to no matches

### ISSUE THREAD

**Issue by Boscop** [rust-lang/docs.rs#156]
On mobile devices, auto complete often inserts a trailing space after selecting a word.
When searching for "cratename " on docs.rs, it doesn't find the crate named "cratename" which is frustrating...
It would be helpful if the search could be made more forgiving by e.g. trimming the trailing whitespace.

**Comment by bluss** [comment]
I ran across this bug today. The message that is given for no matches is "The requested resource does not exist", which is also not quite clear, it gives the impression that there was an error, not just that no results matched the search.

[Test url for search 'ndarray '](https://docs.rs/releases/search?query=ndarray+)

**Comment by jyn514** [comment]
Fixed in #721
