### ISSUE TITLE
build-std not properly supported

### ISSUE THREAD

**Issue by Lokathor** [rust-lang/docs.rs#1561]
### Crate name

gba

### Build failure link

https://docs.rs/crate/gba/0.5.2/builds/466267

### Additional details

It appears that if build-std is used for a tier3 target, docs.rs still tries to download the target (which doesn't exist) and then aborts on the download failure.

**Comment by jyn514** [comment]
Currently blocked on https://github.com/rust-lang/cargo/issues/10127.

**Comment by syphar** [comment]
Is this still an issue? 

I see that recent builds of the crate succeeded, but with a different target than the one mentioned in the build logs here.

**Comment by jyn514** [comment]
Yes, this is still blocked on rustwide support.
