### ISSUE TITLE
Cross-crate links are not always present

### ISSUE THREAD

**Issue by vberger** [rust-lang/docs.rs#157]
Example, my crate wayland-window exposes in its API some types from wayland-client.

Some are properly linked to the appropriate doc in wayland-client, for example `StateToken` and `EventQueueHandle` here: https://docs.rs/wayland-window/0.9.0/wayland_window/fn.init_decorated_surface.html

However, some are not, for example the `Resize` type here https://docs.rs/wayland-window/0.9.0/wayland_window/enum.Configure.html should be linked to this page: https://docs.rs/wayland-client/0.10.1/wayland_client/protocol/wl_shell_surface/struct.Resize.html

**Comment by onur** [comment]
Thanks for reporting.

This is an issue in rustdoc. It skips adding links to some types for some reason. If you build your documentation with `cargo doc --no-deps` you will get the same result. I am not sure what is causing this in rustdoc.

**Comment by jyn514** [comment]
The issue was that docs.rs wasn't passing `--extern-html-root-url` (I think because the crate was built long enough ago it didn't exist then). I rebuilt https://docs.rs/wayland-window/0.13.3/ and the links are working now.
