### ISSUE TITLE
Build Failed for ki18n-rs

### ISSUE THREAD

**Issue by Ayush1325** [rust-lang/docs.rs#1570]
### Crate name

ki18n-rs

### Build failure link

https://docs.rs/crate/ki18n-rs/0.1.3/builds/470615

### Additional details

The build fails due to the absence of libkf5i18n-dev.
I have already merged the required package to crates-build-env in [this](https://github.com/rust-lang/crates-build-env/pull/92#event-5698478671) pull request.
So I was wondering when the latest image will be used.
Also, I wanted to know if there was any way to trigger a docs build without publishing a new version.

**Comment by jyn514** [comment]
I started a download for the new image just now and queued a new build so you don't have to publish a new version: https://docs.rs/releases/queue.

>  Also, I wanted to know if there was any way to trigger a docs build without publishing a new version.

Not for crate authors, no - see https://github.com/rust-lang/docs.rs/issues/301#issuecomment-558256524

**Comment by jyn514** [comment]
Queued and rebuilt: https://docs.rs/ki18n-rs/0.1.3/ki18n_rs/
