### ISSUE TITLE
generating files

### ISSUE THREAD

**Issue by sbechet** [rust-lang/docs.rs#1572]
Hello,

Related to [ibm437](https://crates.io/crates/ibm437) crates.

I understand i can't write in default `target/` directory because directory is RO inside docker and you change default target path.

But i have no solution for my case:

What i want:

1. Extract 3 fonts from original file using `build.rs`: for that, i must write somewhere so i think why not in `std::env::var("OUT_DIR")`...
2. Import generated files in _nostd_ `lib.rs` using `include_bytes!()` macro.

It seems it's impossible because i can't access std inside nostd module so i can't know OUT_DIR value...

Any idea? Can i use ` /tmp`? other idea?

**Comment by Nemo157** [comment]
You can use `core::env!("OUT_DIR")` in your code to read the `OUT_DIR` value to use with `include_bytes!`.

**Comment by sbechet** [comment]
Incredible i can use ENV VAR using core :-) Thx!

All ok now (see [ibm437](https://docs.rs/ibm437/0.2.3/ibm437/)).
