### ISSUE TITLE
Recent docs build renders the left column oddly

### ISSUE THREAD

**Issue by Lokathor** [rust-lang/docs.rs#1574]
https://docs.rs/imagine/0.0.6/imagine/

The gray background of the left column doesn't go all the way to the edge of the window.

**Comment by cynecx** [comment]
Caused by https://github.com/rust-lang/rust/pull/91356.

cc @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
I have a fix for it in https://github.com/rust-lang/docs.rs/pull/1579.
