### ISSUE TITLE
font-awesome-as-crate appears to be incorrectly licensed

### ISSUE THREAD

**Issue by wesleywiser** [rust-lang/docs.rs#1578]
At least, based on [the current licensing page for font-awesome](https://fontawesome.com/v4.7/license/), the package appears to be licensed as MIT for code, SIL-OFL-1.1 for the fonts/icons themselves and CC-BY-3.0 for the documentation. I'm not exactly sure what pieces this crate repackages (or what version of font-awesome it's based on) but it seems like the correct license should be `"CC-BY-3.0 AND MIT AND OFL-1.1"` (or perhaps `"MIT AND OFL-1.1"` if the documentation is not included). 

https://github.com/rust-lang/docs.rs/blob/6e354ec15c6652660afd8a071b3d09b3b8eb6b68/crates/font-awesome-as-a-crate/Cargo.toml#L1-L7

**Comment by Nemo157** [comment]
The crate is based off the svgs distributed as part of _Font Awesome Free for the Web_, not the font files. From the `LICENSE.txt` distributed in the package:

https://github.com/rust-lang/docs.rs/blob/6e354ec15c6652660afd8a071b3d09b3b8eb6b68/crates/font-awesome-as-a-crate/fontawesome-free-5.14.0-web/LICENSE.txt#L8-L10

**Comment by skade** [comment]
Note that while I believe for consistency reasons, the crate should declare the license of the thing it wraps, CC-BY 3.0 things can be shipped as CC-BY 4.0, as the licenses are explicitly forward-compatible. https://wiki.creativecommons.org/wiki/License_Versions#License_Suite_Versions

**Comment by Nemo157** [comment]
Font Awesome v5 has updated to CC-BY 4.0 itself: <https://fontawesome.com/license/free>, and I assume it's not backwards-compatible to mark it as CC-BY 3.0.

**Comment by wesleywiser** [comment]
Thanks for the clarification! That seems correct to me then.
