### ISSUE TITLE
crlibm doc build fails with ReadOnlyFilesystem

### ISSUE THREAD

**Issue by Chris00** [rust-lang/docs.rs#1584]
### Crate name

crlibm

### Build failure link

https://docs.rs/crate/crlibm/0.1.0/builds/485412

### Additional details

The build stops with
```
Error: Os { code: 30, kind: ReadOnlyFilesystem, message: "Read-only file system" }
```
and `cargo doc` generates the doc fine on my machine.

**Comment by Nemo157** [comment]
See <https://docs.rs/about/builds#read-only-directories>. The issue is likely
```rust
{ let mut file = File::create(tmp_file)?;
      write!(file, "#include \"{}.h\"\nint main() {{ return 0; }}\n", name)?; }
```
this is trying a file to the current directory instead of using the `OUT_DIR` where temporary files must be written.

**Comment by Chris00** [comment]
Spot on!  Thanks!
