### ISSUE TITLE
use core::arch::asm; for asm!

### ISSUE THREAD

**Issue by meesokim** [rust-lang/docs.rs#1585]
### Crate name

ruspiro-interrupt = "0.5.0"

### Build failure link

https://github.com/rust-embedded/rust-raspberrypi-OS-tutorials

### Additional details

error: cannot find macro `asm` in this scope
   --> /home/msx/.cargo/registry/src/github.com-1ecc6299db9ec823/ruspiro-lock-0.4.3/src/sync/spinlock.rs:100:7
    |
100 |       asm!(
    |       ^^^
    |
    = note: consider importing this macro:
            core::arch::asm

**Comment by meesokim** [comment]
lib.rs, interface.rs

**Comment by syphar** [comment]
@meesokim could you elaborate which problem you are having? 
It with https://docs.rs/ ? or `ruspiro-interrupt`? Or [`rust-raspberrypi-OS-tutorials`](https://github.com/rust-embedded/rust-raspberrypi-OS-tutorials)? 

This repository is about the https://docs.rs/ platform which builds and hosts package documentation.

**Comment by syphar** [comment]
I'm closing this issue now, 

feel free to reopen if the problem still persists.
