### ISSUE TITLE
Paging support/not all results returned

### ISSUE THREAD

**Issue by matthewkmayer** [rust-lang/docs.rs#159]
The [Rusoto project](https://github.com/rusoto/rusoto/) has a lot of crates we generate with the style of `rusoto_SERVICENAME`.  When searching for `rusoto_` not all crates matching are returned: https://docs.rs/releases/search?query=rusoto_ .  For example, on that page I don't see `rusoto_sqs` but [a search for that](https://docs.rs/releases/search?query=rusoto_sqs) shows it.

Ideally all results that match would be returned, whether in a single big page or paging with a subset of the results.  For example, matches 1-20, then 21-30, etc...

Rusoto issue for switching to docs.rs instead of generating our own: https://github.com/rusoto/rusoto/issues/754 .

Thanks!

**Comment by matthewkmayer** [comment]
Any more info I can supply to help get Rusoto onto this excellent project? 😄

**Comment by syphar** [comment]
this is already solved
