### ISSUE TITLE
gdal crate failing to compile

### ISSUE THREAD

**Issue by spadarian** [rust-lang/docs.rs#1591]
### Crate name

map-engine

### Build failure link

https://docs.rs/crate/map-engine/0.1.0/builds/491073

### Additional details

Happy new year to everyone and thanks for your amazing work.

I just published my first crate ([map-engine](https://crates.io/crates/map-engine)) and I'm having problems generating the docs due to a dependency that fails to compile.

The dependency is [gdal](https://github.com/georust/gdal) which has an external dependency ([GDAL](https://gdal.org/)). I checked if it was possible to make a PR to crates-build-env but the problem is that Ubuntu 18.04 has a very old version of GDAL.

Is there any recommended way of dealing with this?
* I can generate my docs locally, is there any way to upload those?
* The gdal crate has a [custom build.rs](https://github.com/georust/gdal/blob/master/gdal-sys/build.rs#L65) that seems to deal with this. Does the build system use that or should I write my own build.rs?

Thanks!

**Comment by spadarian** [comment]
The error comes from this conditional compilation in [gdal](https://github.com/georust/gdal/blob/master/build.rs#L3):

```rust
#[cfg(docsrs)]
pub fn gdal_version_info(_key: &str) -> String {
    "GDAL 3.2.0, released 2222/02/22".to_string()
}

#[cfg(not(docsrs))]
pub fn gdal_version_info(key: &str) -> String {
    let c_key = std::ffi::CString::new(key.as_bytes()).unwrap();

    unsafe {
        let res_ptr = gdal_sys::GDALVersionInfo(c_key.as_ptr());
        let c_res = std::ffi::CStr::from_ptr(res_ptr);
        c_res.to_string_lossy().into_owned()
    }
}
```

They do provide a flag in their [Cargo.toml](https://github.com/georust/gdal/blob/master/Cargo.toml#L39):
```toml
[package.metadata.docs.rs]
rustc-args = ["--cfg", "docsrs"]
```
But the building system seems to ignore it (you can see `"--config" "build.rustflags=[\"--cfg\", \"docsrs\"]" ` in the [build log](https://docs.rs/crate/map-engine/0.1.0/builds/491073)).

**Comment by syphar** [comment]
@Nemo157 could you have a look here?

**Comment by syphar** [comment]
@Nemo157 was this solved with the resolved cargo issue?

**Comment by Nemo157** [comment]
I think it should have been, I've queued a rebuild and we'll see what happens.

**Comment by Nemo157** [comment]
Rebuild succeeded 🎉
