### ISSUE TITLE
Nested markdown lists are not rendered as nested list

### ISSUE THREAD

**Issue by lo48576** [rust-lang/docs.rs#1594]
# Summary

Nested markdown lists as below are not rendered as nested lists, but as single-level lists.

Source: 

```markdown
//! * foo
//!     + bar
//!     + baz
```

Expected output:

* foo
    + bar
    + baz

Actual output:

* foo + bar + baz

# Reproduced example

[This section in `iri-string` v0.5.0-beta.1](https://docs.rs/iri-string/0.5.0-beta.1/iri_string/index.html#std-and-alloc-support).

On docs.rs:
![screenshot-2022-01-16-080732+0900](https://user-images.githubusercontent.com/1246590/149640494-e239ba17-f204-4a2c-a675-898dc2e8ff4b.png)

Local `cargo doc`:
![screenshot-2022-01-16-080835+0900](https://user-images.githubusercontent.com/1246590/149640516-11f543a7-678d-4c0a-99b6-b86da98d3d4b.png)

**Comment by syphar** [comment]
docs.rs [uses the nightly compiler to build the docs](https://docs.rs/about/builds). 

When I use nightly locally with `cargo doc`, I can reproduce the issue you are seeing. 

So this looks like a bug / changed behaviour in rustdoc, or am I missing something? 

cc @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
This is a regression. Please open an issue on the rust repository and I'll try to fix it as soon as possible.

**Comment by lo48576** [comment]
Thank you. Reported at rust-lang/rust repository.
