### ISSUE TITLE
Footer links not clickable

### ISSUE THREAD

**Issue by jsha** [rust-lang/docs.rs#1599]
Steps to reproduce:

 1. Visit any recently built docs.rs page, e.g. https://docs.rs/rushterm/0.5.2/rushterm/.
 2. Scroll to the bottom of the page.
 3. Click "About docs.rs", "Privacy policy", or "Build queue".

Expected result: navigate somewhere else.

Actual result: no navigation.

Chrome 97.0.4692.71 (Official Build) (64-bit) on Linux.

**Comment by syphar** [comment]
@GuillaumeGomez could this be related to #1579 ? Or something else?

**Comment by Nemo157** [comment]
The footer is before the main div and on new docs the main div padding extends down over it. Looks like either moving the footer down below the main div, or adding a high `z-index` to it, fixes it for both old and new docs. (Or maybe there's a way to not have the padding extend down over it on the new docs too, the old docs appear to have it stop significantly above the footer somehow).

**Comment by GuillaumeGomez** [comment]
I think changing the z-index is the right fix here (other fixes might be much more complicated).
