### ISSUE TITLE
Layout tweaks for mobile-topbar changes

### ISSUE THREAD

**Issue by jsha** [rust-lang/docs.rs#1600]
In https://github.com/rust-lang/rust/pull/92692, I plan to change the CSS for the rustdoc hamburger menu / topbar. Previously, the hamburger menu was a child of `.sidebar`. Now it's part of a separate `<nav class="mobile-topbar">`.

Right now there's an override for `.sidebar.mobile` that bumps down the hamburger menu to make room for docs.rs' own topbar: https://github.com/rust-lang/docs.rs/blob/a9d9025f84537aa47d2aedac2862b57d99d4807d/templates/style/rustdoc-common.scss#L75-L91. After https://github.com/rust-lang/rust/pull/92692 lands, we'll need to update that to include `.mobile-topbar` (for new docs), while also still selecting `.sidebar.mobile` (for old docs).

**Comment by syphar** [comment]
@jsha do we still need to do anything here?

**Comment by jsha** [comment]
Nope, I think it's all good.
