### ISSUE TITLE
My crate's documentation is not getting built / shown by docs.rs

### ISSUE THREAD

**Issue by cpu-runtime** [rust-lang/docs.rs#1602]
### Crate name

derivenum

### Build failure link

https://docs.rs/crate/derivenum/latest

### Additional details

My crate's documentation builds as intended on my local machine (running debian 11) and also opens correctly when using `cargo doc --open`. I've uploaded other crates already, their documentation works correctly.

**Comment by Nemo157** [comment]
It appears that cargo accepts either `proc-macro` or `proc_macro` despite only documenting `proc-macro` as a key in https://doc.rust-lang.org/nightly/cargo/reference/cargo-targets.html#configuring-a-target. We have to parse for this to do the build slightly differently for proc-macros and only check for the `proc-macro` form in

https://github.com/rust-lang/docs.rs/blob/a9d9025f84537aa47d2aedac2862b57d99d4807d/crates/metadata/lib.rs#L349

**Comment by syphar** [comment]
Thanks for checking this out! 

That means it could be a workaround for the package to change `proc_macro` into `proc-macro`

**Comment by cpu-runtime** [comment]
> Thanks for checking this out!
> 
> That means it could be a workaround for the package to change `proc_macro` into `proc-macro`

Yeah thanks, I did that and now I'm waiting for docs.rs to show version 0.1.1.

**Comment by cpu-runtime** [comment]
Ok, I got it fixed by changing `proc_macro` to `proc-macro` in `Cargo.toml` under `[lib]`.
Thanks for the help and have a great day!
