### ISSUE TITLE
Top navbar display is broken on older crates

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/docs.rs#1608]
Example on chrono:

![Screenshot from 2022-01-18 14-19-13](https://user-images.githubusercontent.com/3050060/149945018-7a5d1108-462f-48f3-8598-68d1bed48114.png)

I think this regression comes from https://github.com/rust-lang/docs.rs/pull/1597.

cc @jsha

**Comment by jsha** [comment]
Thanks for flagging. I'll take a look.
