### ISSUE TITLE
Restore default colours for enums (green) and type definitions (orange-ish)

### ISSUE THREAD

**Issue by glts** [rust-lang/docs.rs#1612]
Recently docs built on docs.rs use the same purple colour for struct types, enum types, and type definitions.

Compare when building docs locally: only struct types are purple, enum types are green, and type definitions are orange.

Any reason for this change? Types in different colours are helpful when scanning signatures etc. Please revert to different colours for different types if possible.

**Comment by syphar** [comment]
@glts docs.rs [is using nightly to build the docs](https://docs.rs/about/builds), so this is probably a recent change to nightly. 

cc @GuillaumeGomez ?

**Comment by glts** [comment]
@syphar Thank you. Pity, but I will get used to it.

**Comment by GuillaumeGomez** [comment]
I can't find the PR and issue for this change. Do you have them by any chance @jsha ?

**Comment by Xiphoseer** [comment]
Personally, I think it's a significant part of the API whether the main way to interact with a type is using `match val` or `val.field`. So to be able to visually distinguish between enums and structs on pages like <https://docs.rs/serde_json/latest/serde_json/value/fn.to_value.html> for related types like `Value` has been useful to me in the past.

**Comment by GuillaumeGomez** [comment]
Please open an issue on the rust repository and tag me and @jsha so we can discuss it.
