### ISSUE TITLE
Crate fails to build despite no exraordinary code additions

### ISSUE THREAD

**Issue by cpu-runtime** [rust-lang/docs.rs#1624]
### Crate name

mongodb-ext

### Build failure link

https://docs.rs/crate/mongodb-ext/latest

### Additional details

I updated my code from version `2.1.0` to `3.1.0` and did not add any code that should obviously fail (for example depending on network access).
I recompiled locally (Debian 11) using 3GB RAM and it finished successfully in under 15min.
([GitHub](https://github.com/cpu-runtime/mongodb-ext))

**Comment by Nemo157** [comment]
```
[INFO] [stderr] error: internal compiler error: compiler/rustc_mir_transform/src/generator.rs:755:13: Broken MIR: generator contains type ClientOptionsParser in MIR, but typeck only knows about {ResumeTy, impl AsRef<str>, std::option::Option<resolver_config::ResolverConfig>, bool, client::options::ClientOptions, [closure@/opt/rustwide/cargo-home/registry/src/github.com-1ecc6299db9ec823/mongodb-2.1.0/src/client/options/mod.rs:1100:69: 1100:90], impl futures_util::Future<Output = std::result::Result<SrvResolver, error::Error>>, (), SrvResolver, &Vec<client::options::ServerAddress>, Vec<client::options::ServerAddress>, usize, &client::options::ServerAddress, client::options::ServerAddress, &str, impl futures_util::Future<Output = std::result::Result<ResolvedConfig, error::Error>>} and [impl AsRef<str>, std::option::Option<client::options::resolver_config::ResolverConfig>]
```

Looks to be a bug in the last two nightlies fixed by https://github.com/rust-lang/rust/pull/93165, we can try to rebuild the docs after the next nightly with that fix is released.

**Comment by cpu-runtime** [comment]
Thanks for your fast answer, I'll check again tomorrow!

**Comment by Nemo157** [comment]
Rebuilt and it succeeded.
