### ISSUE TITLE
azure_svc_synapse memory

### ISSUE THREAD

**Issue by cataggar** [rust-lang/docs.rs#1626]
### Crate name

azure_svc_synapse

### Build failure link

https://docs.rs/crate/azure_svc_synapse/0.1.0/builds/498821

### Requested RAM limit

~6 GB~ 8 GB

### Requested timeout

~30 minutes~

### Why your crate needs the resource increases

It is a generated that contains several API versions as features. We need all of the documented. Let me know how we can help. This isn't going to be the only crate. https://github.com/Azure/azure-sdk-for-rust/issues/634

**Comment by Nemo157** [comment]
6 GB is gonna be close, I tested building these docs locally and got 5.995 GB peak memory usage.

The time extension shouldn't be necessary, they only take 1:23 to build on my machine and the runner should be less than 10x slower.

**Comment by cataggar** [comment]
How much RAM should it be given? How much is available? 😃

**Comment by Nemo157** [comment]
Good question, we have existing overrides at 8GB so I think that should be fine do to. I've bumped the limit and queued up another build.

**Comment by cataggar** [comment]
That fixed this one.
