### ISSUE TITLE
azure_mgmt_compute memory

### ISSUE THREAD

**Issue by cataggar** [rust-lang/docs.rs#1628]
### Crate name

azure_mgmt_compute

### Build failure link

https://docs.rs/crate/azure_mgmt_compute/0.1.0/builds/499048

### Requested RAM limit

8 GB

### Why your crate needs the resource increases

Like #1626, it is running out of memory. https://github.com/Azure/azure-sdk-for-rust/issues/634

**Comment by syphar** [comment]
I increased the limit and queued a rebuild
