### ISSUE TITLE
azure_mgmt_cosmosdb memory

### ISSUE THREAD

**Issue by cataggar** [rust-lang/docs.rs#1629]
### Crate name

azure_mgmt_cosmosdb

### Build failure link

https://docs.rs/crate/azure_mgmt_cosmosdb/0.1.0/builds/499078

### Requested RAM limit

8 GB

### Why your crate needs the resource increases

Like #1626, it is running out of memory. https://github.com/Azure/azure-sdk-for-rust/issues/634

**Comment by syphar** [comment]
I increased the limit and queued a rebuild
