### ISSUE TITLE
azure_mgmt_compute 16 GB

### ISSUE THREAD

**Issue by cataggar** [rust-lang/docs.rs#1633]
### Crate name

azure_mgmt_compute 

### Build failure link

https://docs.rs/crate/azure_mgmt_compute/0.1.0/builds/499048

### Requested RAM limit

16 GB

### Why your crate needs the resource increases

It failed with 8 GB. https://github.com/rust-lang/docs.rs/issues/1628

**Comment by syphar** [comment]
@cataggar 16 GB is definitely over what we can provide with the current build-server setup. 
Could you please measure what you actually need for to build this package? 

With that data we can see what's possible then.

**Comment by cataggar** [comment]
Any suggestions on how to figure out how much is needed? Or to measure and/or performance tune memory for Rust applications?

```
cargo doc -p azure_mgmt_compute --all-features --open
```
Finishes in 13 minutes on my Windows 10 laptop. Task Manager reported about 65% memory usage before I started and it climbed up to near 99% when it was running.

I found this blog.
https://rust-analyzer.github.io/blog/2020/12/04/measuring-memory-usage-in-rust.html

**Comment by Nemo157** [comment]
On linux you can use `/usr/bin/time -v cargo doc -p azure_mgmt_compute --all-features --no-deps` and check the `Maximum resident set size (kbytes)`.

**Comment by syphar** [comment]
@cataggar another argument for using less memory in the build: currently you would expect of every user of your library to have this much free memory.

>  it climbed up to near 99% when it was running 

This actually sounds as if your build is already swapping, so the usage numbers won't tell the whole truth. 

> I found this blog. https://rust-analyzer.github.io/blog/2020/12/04/measuring-memory-usage-in-rust.html

The limit we're talking about here is about the memory used in the build process, while this blog article only talks about memory usage of the program itself. 

That being said, you will get help by more people [in the chat/forum communities](https://www.rust-lang.org/community).

**Comment by cataggar** [comment]
> another argument for using less memory in the build: currently you would expect of every user of your library to have this much free memory.

A typical user will use 1 of these features, which is the default. Some users will use two or more. No one is going to use all of them, but we would like to publish docs for all of the features. 3 GB is working for 220 crates, but not for 12  of them.

Using `azure_mgmt_cosmosdb`, this number of features did not work at 3 GB, but did at 8 GB.

https://docs.rs/azure_mgmt_cosmosdb/0.1.0/azure_mgmt_cosmosdb/

1. package_2014_04	
2. package_2015_04	
3. package_2015_11	
4. package_2016_03_19	
5. package_2016_03_31	
6. package_2019_08	
7. package_2019_08_preview	
8. package_2019_12	
9. package_2020_03	
10. package_2020_04	
11. package_2020_06_preview	
12. package_2020_09	
13. package_2021_01	
14. package_2021_03	
15. package_2021_03_preview	
16. package_2021_04	
17. package_2021_04_preview	
18. package_2021_05	
19. package_2021_06	
20. package_2021_07_preview	
21. package_2021_10	
22. package_preview_2021_04	
23. package_preview_2021_10	

Often increasing resources is an easy fix. If we are unable to, I can limit the number of features that are documented to top 10 or something like that.

**Comment by jyn514** [comment]
Another alternative is to investigate why rustdoc is using so much memory, and either opening a bug or changing the code to workaround it. `-Ztime-passes` has some info about memory usage, or if you build from source you can use `heaptrack` (nightly won't work because it links to jemalloc).

**Comment by jyn514** [comment]
`time-passes` shows 11 GB being used just for macro expansion and resolution, so there's probably not a lot rustdoc can do to improve this. It might be possible to improve the memory usage of the AST though.
```
$ cargo rustdoc --all-features -- -Ztime-passes -Zself-profile
 Documenting azure_mgmt_compute v0.1.0 (/home/jnelson/rust-community/azure_mgmt_compute-0.1.0)
time:   0.001; rss:   55MB ->   58MB (   +3MB)	parse_crate
time:   0.000; rss:   58MB ->   58MB (   +0MB)	attributes_injection
time:   0.000; rss:   58MB ->   58MB (   +0MB)	plugin_loading
time:   0.000; rss:   58MB ->   58MB (   +0MB)	plugin_registration
time:   0.000; rss:   60MB ->   60MB (   +0MB)	crate_injection
time: 124.246; rss:   60MB -> 8430MB (+8370MB)	expand_crate
time:   0.002; rss: 8430MB -> 8430MB (   +0MB)	check_unused_macros
time: 124.248; rss:   60MB -> 8430MB (+8370MB)	macro_expand_crate
time:   0.000; rss: 8430MB -> 8430MB (   +0MB)	maybe_building_test_harness
time:   1.053; rss: 8430MB -> 8430MB (   +0MB)	AST_validation
time:   0.000; rss: 8430MB -> 8430MB (   +0MB)	maybe_create_a_macro_crate
time:   0.229; rss: 8430MB -> 8549MB ( +119MB)	finalize_imports
time:   0.182; rss: 8549MB -> 8556MB (   +7MB)	resolve_access_levels
time:   0.532; rss: 8556MB -> 8588MB (  +32MB)	finalize_macro_resolutions
time:  13.406; rss: 8588MB -> 11742MB (+3154MB)	late_resolve_crate
time:   0.000; rss: 11742MB -> 11742MB (   +0MB)	resolve_main
time:   0.727; rss: 11742MB -> 11743MB (   +1MB)	resolve_check_unused
time:   0.000; rss: 11743MB -> 11743MB (   +0MB)	resolve_report_errors
time:   0.644; rss: 11743MB -> 11743MB (   +0MB)	resolve_postprocess
time:  15.720; rss: 8430MB -> 11743MB (+3313MB)	resolve_crate
time:   0.729; rss: 11743MB -> 11743MB (   +0MB)	complete_gated_feature_checking
time: 141.750; rss:   58MB -> 11743MB (+11685MB)	configure_and_expand
```

**Comment by jyn514** [comment]
Max RSS was above 16 GB, so definitely not something we can accomodate in docs.rs right now.

**Comment by cataggar** [comment]
Limiting the crate to 5 tags worked.
https://docs.rs/azure_mgmt_compute/latest/azure_mgmt_compute/
