### ISSUE TITLE
azure_mgmt_web 8 GB

### ISSUE THREAD

**Issue by cataggar** [rust-lang/docs.rs#1642]
### Crate name

azure_mgmt_web

### Build failure link

https://docs.rs/crate/azure_mgmt_web/0.1.0/builds/499635

### Requested RAM limit

8 GB

### Why your crate needs the resource increases

Ran out of memory at 3 GB. https://github.com/Azure/azure-sdk-for-rust/issues/634

**Comment by syphar** [comment]
@cataggar 

I saw you were requesting higher memory limits for a bunch of crates. In that amount this can be a problem for our build-system and I'm asking you to try to reduce memory usage in the build first. If the build itself cannot be optimized you might find a solution by optimizing just the build for docs.rs (see [the docs.rs build](https://docs.rs/about/builds) and [the metadata](https://docs.rs/about/metadata)). You might also find help on the discord servers or in zulip. 

As a last option, some packages resort to building and hosting the docs themself.
