### ISSUE TITLE
Please change the warning: "Be careful when using this code, it's not being tested!"

### ISSUE THREAD

**Issue by sunjay** [rust-lang/docs.rs#165]
I think I understand the intention behind this warning, but its current wording can be pretty misleading. The warning shows up if a code block is set to `ignore` in the documentation.

I have such code in the documentation for my crate [here](https://docs.rs/turtle/1.0.0-alpha.6/turtle/rand/index.html#generating-random-values):

> Using `random()` often requires you to specify a type that you want to generate. For example,
> if you run the following, the compiler will tell you that it needs you to give it more
> information about the type that you want to generate:
> 
> ```rust
> let mut turtle = Turtle::new();
> turtle.set_speed(random());
> ```
> 
> This will produce an error that looks something like the following:
> 
> ```text
> error[E0283]: type annotations required: cannot resolve `_: std::convert::Into<turtle::Speed>`
>  --> src/rand.rs:5:8
>   |
> 5 | turtle.set_speed(random());
>   |        ^^^^^^^^^
> ```

This code intentionally doesn't compile so that I can show the reader an error case. I marked it with ignore so that it would still pass the tests. Rust doesn't provide a mechanism yet for doctests that aren't meant to compile.

This has the effect of producing the following for anyone reading [the documentation on docs.rs](https://docs.rs/turtle/1.0.0-alpha.6/turtle/rand/index.html#generating-random-values):

![screenshot from 2017-11-15 00-52-34](https://user-images.githubusercontent.com/530939/32821046-6dd0ec8c-c99f-11e7-8f56-0ca45453aa62.png)

**Seeing this warning immediately makes this code seem untrustworthy when it is in fact correct.**

## Possible Solution

It would be great if we could completely disable enhancements like this to the documentation on a per-crate basis. These don't show up with just regular `cargo doc`, so they're hard to find unless you go look on docs.rs. (This is optional but would be really great to have.)

As for this warning, I think we should change its wording and its icon. Instead of warning, let's use the [information symbol](http://www.fileformat.info/info/unicode/char/1f6c8/index.htm) since it's quite possible that there may be nothing to warn about in the first place. Then, it would be great to change the wording of the message to something more mild and informative instead of the cautious and negative tone used now.

Instead of "&#9888; Be careful when using this code, it's not being tested!"
We could have: "&#128712; This code is not automatically tested by the documentation tests of this crate."

The second note is both very accurate and doesn't imply that the code may not be correct. I'd be happy to open a PR for this if you're okay with this message.

I'm open to other messages too. It's just important that people aren't misled into thinking that the documentation they are reading may not be correct. For well written docs (which we're all aiming for), that will most often be the exception to the rule, not the most common case to account for.

**Comment by onur** [comment]
Thanks for reporting, this warning is generated by rustdoc and I believe it is removed in recent versions. Updating rustc on docs.rs should fix this issue and remove the warning. I had some setback for building rustc on OSX but it is about to get fixed as well.

**Comment by jyn514** [comment]
Closing as this has been fixed in rustdoc for a while now.
