### ISSUE TITLE
rp2040-pac failed to build (nightly bug?)

### ISSUE THREAD

**Issue by jonathanpallant** [rust-lang/docs.rs#1656]
### Crate name

rp2040-pac

### Build failure link

https://docs.rs/crate/rp2040-pac/0.3.0/builds/501717

### Additional details

I think I fell over https://github.com/rust-lang/rust/issues/93428.

**Comment by Nemo157** [comment]
Queued a new build, but from comments in #1632 it sounds like there are potentially other sources of this ICE that might not have been fixed.

**Comment by Nemo157** [comment]
Since the source looks so related I'm gonna merge this in with #1632
