### ISSUE TITLE
Support /crate/alpha URL

### ISSUE THREAD

**Issue by stepancheg** [rust-lang/docs.rs#1658]
I have two branches: stable 2 and alpha 3.

`/crate/latest` redirect to the latest version in branch 2 (which is correct).

There's no way to link to the latest version in branch 3.

It would be great if docs.rs could link to either:

`/crate/3` — latest version of branch 3
`/crate/alpha` — latest version including unstable

This is similar to https://github.com/rust-lang/docs.rs/issues/169.

**Comment by syphar** [comment]
Crates.io and docs.rs are purely based on the releases you publish, and don't know anything about the repo or branches, apart from the URL. 

Which release would `alpha`? 

Docs.rs itself relies on [semantic version queries you can use](https://docs.rs/about/redirections). Perhaps this already helps you?

**Comment by stepancheg** [comment]
I did not know that. Thank you very much!

> Which release would alpha?

Something like 3.0.0-alpha-2.

And I can use query `>=3.0.0-alpha`.
