### ISSUE TITLE
A Documentation Build Failed Due To An ICE

### ISSUE THREAD

**Issue by TheDarkula** [rust-lang/docs.rs#1666]
### Crate name

themelio-stf

### Build failure link

https://docs.rs/crate/themelio-stf/0.9.7/builds/502388

### Additional details

Relevant snippet from the build log:
```
[INFO] [stderr] error: internal compiler error: unexpected panic
[INFO] [stderr] 
[INFO] [stderr] error: Unrecognized option: 'extern-html-root-url'
[INFO] [stderr] 
[INFO] [stderr] error: could not document `themelio-stf`
```

**Comment by syphar** [comment]
this is #1632 

@TheDarkula I'll add your release to the list of failures.

**Comment by TheDarkula** [comment]
Thank you :)
