### ISSUE TITLE
Creates fails to build due to compiler error

### ISSUE THREAD

**Issue by TommyCpp** [rust-lang/docs.rs#1668]
### Crate name

opentelemetry-otlp

### Build failure link

https://docs.rs/crate/opentelemetry-otlp/0.10.0/builds/497287

### Additional details

The repo is published around Jan, 22. I believed there was an issue with nightly version that prevent tonic from compiling. 

The error in the build log is 
```
error: internal compiler error: compiler/rustc_mir_transform/src/generator.rs:755:13: Broken MIR: generator contains type
```

It looks the same as the one in https://github.com/rust-lang/docs.rs/issues/1624. Can we get a rebuild? Thanks in advance.

**Comment by syphar** [comment]
I requeued the build (see https://docs.rs/releases/queue ). 

@TommyCpp it would be awesome if you could ping me (or @Nemo157 ) again if the build doesn't fix it. Thank!

**Comment by syphar** [comment]
the new build passed, I'm closing this issue. 

https://docs.rs/crate/opentelemetry-otlp/0.10.0/builds
