### ISSUE TITLE
Crate docs build failed for both releases.

### ISSUE THREAD

**Issue by ligmitz** [rust-lang/docs.rs#1671]
### Crate name

rimcol

### Build failure link

https://docs.rs/crate/rimcol/0.1.1/builds

### Additional details

The build completes successfully on the local machine. Not sure why the limit is exceeded as shown in build logs.

**Comment by syphar** [comment]
@ligmitz 
How much memory do you need to build this crate on your machine? We can increase the 3GB limit to a certain extend. 

It also looks like the [tensorflow doc build itself fails too, with the same error](https://docs.rs/crate/tensorflow/0.17.0/builds/)

**Comment by syphar** [comment]
Thanks @Nemo157 ! 

I'm closing this issue then, since this has to be solved in `tensorflow-sys`. 

( also, we never enable network access for any crate, see [here](https://docs.rs/about/builds#hitting-resource-limits))

**Comment by ligmitz** [comment]
Thanks for the breakdown, I'll try to convey the issue to the `tensorflow/rust` maintainers and see if they have a potential solution soon.
