### ISSUE TITLE
build failed for the `tauri` crate

### ISSUE THREAD

**Issue by lucasfernog** [rust-lang/docs.rs#1679]
### Crate name

tauri

### Build failure link

I don't have the link :( default target is Linux

### Additional details

The tauri crate uses A LOT of dependencies, so I'm not sure which one is failing to build. We build documentation for Linux, macOS and Windows (see https://github.com/tauri-apps/tauri/blob/a1882b84b7ab5d6ca08040a2aea33c29f414e93a/core/tauri/Cargo.toml#L37) but only Linux is showing on the docs.rs page.

**Comment by jyn514** [comment]
Recording the missing logs is https://github.com/rust-lang/docs.rs/issues/787. I suggest cross-compiling from linux to windows locally and seeing what the error is.

**Comment by lucasfernog** [comment]
I'll investigate on our end, thanks.

**Comment by lucasfernog** [comment]
> Do you know if `mono` is installed on the runner? I couldn't find that info on the build env repo and we'll need that on our next release ([wravery/webview2-rs#cross-compilation](https://github.com/wravery/webview2-rs#cross-compilation)).

**Comment by syphar** [comment]
@lucasfernog you will find more info [on this page](https://docs.rs/about/builds). In short: this is the build environment: https://github.com/rust-lang/crates-build-env which includes [the package list](https://github.com/rust-lang/crates-build-env/blob/master/linux/packages.txt). 

You can create PRs to the env if something is missing.
