### ISSUE TITLE
Build failing when it should not be

### ISSUE THREAD

**Issue by sgrif** [rust-lang/docs.rs#168]
After releasing Diesel 0.99.0, I noticed that https://docs.rs/crate/diesel_migrations/0.99.0 failed to build. Looking at the build log, it can't link to SQLite and MySQL, which is surprising to me because `diesel` itself built, which was able to link against those libraries.

**Comment by onur** [comment]
Hi @sgrif, thanks for reporting.

Looks like sqlite and mysqlclient development libraries were missing, I fixed the issue and rebuilt diesel_migrations. Is there anything else affected by this?

**Comment by sgrif** [comment]
Yes, `diesel_infer_schema` was also affected. I'm confused how diesel was able to build with those libraries missing since it should have tried to link against them too?

**Comment by sgrif** [comment]
@onur Is there anything I can do to get the build for `diesel_infer_schema` fixed?

**Comment by onur** [comment]
Hi @sgrif.

`diesel_infer_schema` [is failing](https://docs.rs/crate/diesel_infer_schema/1.0.0-beta1/builds/78352) because there is no feature specified for it's dependency `infer_schema_internals`. You can tell docs.rs to build all available features by adding following metadata to `Cargo.toml`:

```toml
[package.metadata.docs.rs]
all-features = true
```

**Comment by sgrif** [comment]
Doh! Thanks!

**Comment by jyn514** [comment]
This seems to be fixed, I'm going to close it. Feel free to comment and I'll reopen if you're still having trouble.
