### ISSUE TITLE
rocket_prometheus 0.10.0-rc.1 failed to build due to ICE

### ISSUE THREAD

**Issue by sd2k** [rust-lang/docs.rs#1680]
### Crate name

rocket_prometheus

### Build failure link

https://docs.rs/crate/rocket_prometheus/0.10.0-rc.1/builds/507359

### Additional details

This was due to a now-resolved bug in rustc nightly, see https://github.com/rust-lang/rust/issues/93831. I think a rebuild should work now.

Thanks!

**Comment by syphar** [comment]
I just queued a build for this release, see https://docs.rs/releases/queue 

Feel free to reopen this issue it it fails again.
