### ISSUE TITLE
Alpha version selector broke

### ISSUE THREAD

**Issue by stepancheg** [rust-lang/docs.rs#1682]
URL like this:

https://docs.rs/protobuf/%3E=3.0.0-alpha

worked [two weeks ago](https://github.com/rust-lang/docs.rs/issues/1658).

Now it doesn't work.

<img width="680" alt="image" src="https://user-images.githubusercontent.com/28969/154821838-5fb27cef-8c7a-4f38-97fc-a07f795fb775.png">

If this is intentional, then, is there a way to specify the latest alpha version from `3.0.0-alpha.N`?

**Comment by Nemo157** [comment]
Will be related to <https://github.com/rust-lang/docs.rs/pull/1657>. Looks like it missed the case for semver matching of prerelease versions.

**Comment by syphar** [comment]
> Looks like it missed the case for semver matching of prerelease versions. 

[I thought I took care of that... ](https://github.com/rust-lang/docs.rs/blob/ae08be0a31f928f652adc145535163b35dc6613a/src/web/mod.rs#L360-L372). 

I will have a look

**Comment by syphar** [comment]
@Nemo157 I prepared a fix in https://github.com/rust-lang/docs.rs/pull/1684

**Comment by syphar** [comment]
#1684 is merged an deployed, the link in the issue description seems to work again. 

I'm closing this issue, please reopen if it still doesn't work.

**Comment by stepancheg** [comment]
Thank you!
