### ISSUE TITLE
Regenerate docs that were built incorrectly

### ISSUE THREAD

**Issue by Skeletonxf** [rust-lang/docs.rs#1685]
Hi, a month ago I reported an [issue](https://github.com/rust-lang/rust/issues/93309) that I encountered where the documentation docs.rs built for versions 1.8.1, 1.7.1 and 1.6.2 of [my crate](https://docs.rs/easy-ml/1.8.1/easy_ml/) had a lot of bullet points that weren't part of the docs. That issue was fixed, and I have verified locally that with rust version 1.61.0-nightly (45e2c2881 2022-02-20) the docs are built correctly again. However, they're still wrong on docs.rs, so is it possible to regenerate them please?

Thanks

**Comment by syphar** [comment]
I queued a rebuild for all three releases, see https://docs.rs/releases/queue
