### ISSUE TITLE
Docs.rs is generating external dependency links

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/docs.rs#1686]
The `source` link for <https://docs.rs/rand/latest/rand/trait.SeedableRng.html#method.seed_from_u64> links to <https://rust-random.github.io/rand/src/rand_core/lib.rs.html#306> instead of <https://docs.rs/rand_core/0.6.3/src/rand_core/lib.rs.html#306-335>; and <https://docs.rs/rand_mt/4.1.1/rand_mt/struct.Mt19937GenRand32.html#impl-RngCore> links to <https://rust-random.github.io/rand/rand_core/trait.RngCore.html> instead of <https://docs.rs/rand_core/0.6.3/rand_core/trait.RngCore.html>.

IIRC there was some plan on changing how `--extern-html-root-url` worked when a crate specified its own `html_root_url`, but there was going to be a flag for docs.rs to keep the previous override behavior.

**Comment by jyn514** [comment]
This is https://github.com/rust-lang/docs.rs/pull/1473, I haven't had time to work on it.
