### ISSUE TITLE
docs.rs search should link to "latest" URL

### ISSUE THREAD

**Issue by ericseppanen** [rust-lang/docs.rs#1691]
If I search for a crate via the search form on docs.rs, I get a page of results like <https://docs.rs/releases/search?query=serde>, which provides links to crate documentation of the form, e.g.

`https://docs.rs/serde/1.0.136/serde/`

I think it would probably be better choice for this link to take one of the "latest" URL formats, e.g.

`https://docs.rs/serde/latest/serde/`

My reasoning is that I often search for crate docs, then copy/paste the link into an email, blog post, or markdown documentation. 99% of the time I want that link to always go to the latest version in the future. It looks like third-party search engines now mostly link to a non-version-specific URL (and I'm assuming this was a deliberate change by docs.rs) , so I think this is also more consistent with how searches work from other sites.

**Comment by syphar** [comment]
Resolved with #2239
