### ISSUE TITLE
Keyboard shortcut triggers even when the search field is focused

### ISSUE THREAD

**Issue by hrxi** [rust-lang/docs.rs#1696]
URL: https://docs.rs/tracing-subscriber/latest/tracing_subscriber/
Browser: Firefox 98.0 on Arch Linux.

Enter "Layer" into the search box.
Expected result: End up on https://docs.rs/tracing-subscriber/latest/tracing_subscriber/index.html?search=Layer
Actual result: End up on https://docs.rs/tracing-subscriber/0.3.9/tracing_subscriber/index.html?search=Layer because they keyboard shortcut "y" to canonicalize the path is triggered.

**Comment by hrxi** [comment]
Couldn't find an existing issue that described this problem, but I also wasn't quite sure how to search for it.

**Comment by syphar** [comment]
I'm not sure who introduced this, was it @jsha ? Or @GuillaumeGomez

**Comment by jsha** [comment]
I added the 'y' keyboard shortcut. Thanks for the report! I've confirmed it.
