### ISSUE TITLE
Issue using private crate registry

### ISSUE THREAD

**Issue by gregvirgin** [rust-lang/docs.rs#1699]
https://github.com/rust-lang/docs.rs/blob/539cd8a1aabdaa6afa536432768356f620103c99/dockerfiles/entrypoint.sh#L31

This line should probably respect the `REGISTRY_URL` environment variable. When I was unable to get a new private crate registry to work, changing this line to `git clone ${REGISTRY_URL:-https://github.com/rust-lang/crates.io-index} "${DOCSRS_PREFIX}/crates.io-index"` got it working.

**Comment by jyn514** [comment]
Happy to take a PR fixing this :) no one on the docs.rs team uses a private registry so it's unlikely we'll fix registry related bugs unless someone else writes the code for it.
