### ISSUE TITLE
/crate/:crate/latest/builds.json strips the .json suffix

### ISSUE THREAD

**Issue by suhr** [rust-lang/docs.rs#170]
This may be useful for external badge services like [shields.io](https://shields.io/).

See also: https://github.com/badges/shields/issues/1382

**Comment by paulmelnikow** [comment]
Hi! Just wanted to mention again that a JSON endpoint with build info would be really helpful! I'd be happy to help design a schema based on the other endpoints you have, if it would be helpful!

**Comment by jyn514** [comment]
@paulmelnikow What are you looking for from the JSON API? What info do you need that builds.json doesn't currently provide? Do you want to be able to get the info from the latest version? https://docs.rs/crate/cargo/latest/builds.json doesn't currently work (it strips the JSON suffix), but I consider that a bug and I'd be happy to fix it.

**Comment by jyn514** [comment]
For context, builds.json is a mostly undocumented feature I wish we didn't have, we introduced it so crates.io knows whether it can link to docs.rs (i.e. whether the build succeeded). I don't mind expanding that endpoint to be more useful, but I don't want to introduce other endpoints if possible.

**Comment by calebcartwright** [comment]
> Do you want to be able to get the info from the latest version? https://docs.rs/crate/cargo/latest/builds.json doesn't currently work (it strips the JSON suffix), but I consider that a bug and I'd be happy to fix it.

Putting my Shields hat on... I do think this would suffice for the use case. IIUC the only option available today would require a badge be pinned to a specific version which would be of limited use, whereas being able to have a badge that dynamically reflected the build status for the latest version of a crate seems like it'd be useful for folks.
