### ISSUE TITLE
update-informer v0.5.0 build failure

### ISSUE THREAD

**Issue by mgrachev** [rust-lang/docs.rs#1703]
### Crate name

update-infomer

### Build failure link

https://docs.rs/crate/update-informer/0.5.0/builds/531236

### Additional details

Issues:
* https://github.com/briansmith/ring/issues/1469
* https://github.com/rust-lang/rust/issues/95267

The problem in the last `1.61.0-nightly (2022-03-23)` build, because `1.61.0-nightly (2022-03-22)` works fine.

**Comment by mgrachev** [comment]
The same problem https://github.com/rust-lang/docs.rs/issues/1705.

**Comment by syphar** [comment]
@mgrachev sorry for the delay here, I see that https://github.com/rust-lang/rust/issues/95267 is closed now. 

Can you give it a try with nightly and ping me if it works? then I can requeue your build.

**Comment by mgrachev** [comment]
I've just tried and everything works.

**Comment by syphar** [comment]
I just enqueued a new build for this release (see https://docs.rs/releases/queue ). 

Since it takes some time until it's done it would be awesome if you could close this issue when it works. Thanks!

**Comment by mgrachev** [comment]
<img width="1180" alt="Screenshot 2022-03-30 at 10 45 21" src="https://user-images.githubusercontent.com/700998/160779214-ff88ea69-c286-40e0-93f7-8b5d2c0defde.png">

<img width="1180" alt="Screenshot 2022-03-30 at 10 44 55" src="https://user-images.githubusercontent.com/700998/160779196-3ee9d131-cbd3-4fe8-9339-4366ffea0616.png">

I don't see any changes.

**Comment by Nemo157** [comment]
Looks like syphar copied the spelling mistake from the issue title when queueing. I've now scraped all our recent failures with this error and queued them up at low priority, I see that `update-informer 0.5.0` is definitely in there (and I've bumped its priority above the others).

**Comment by mgrachev** [comment]
The problem was solved. Thanks a lot 💚
