### ISSUE TITLE
CSS looks quite bad on widescreen monitor

### ISSUE THREAD

**Issue by jkaye2012** [rust-lang/docs.rs#1704]
I recently purchased a new monitor and have come to learn that the CSS for generated documentation looks quite poor. Here's an example:

![image](https://user-images.githubusercontent.com/4085244/160246504-5200bc2b-8b7e-4b8b-83b4-f9151be6fb9a.png)

I did a little digging, and by entirely disabling the `min-width` property on the `main` element, things look a lot better:

![image](https://user-images.githubusercontent.com/4085244/160246576-102b93e8-690a-44c6-918a-e3f356e2d9aa.png)

I wasn't quite sure if this belongs here or somehow is related to the doc generation within cargo - please let me know if I should move it elsewhere!

**Comment by jsha** [comment]
Thanks for reporting! I believe this is a duplicate of #1669. I recommend closing in favor of that issue.

**Comment by jkaye2012** [comment]
Yep, I think you're right. Thanks.
