### ISSUE TITLE
6 GB for azure_svc_servicefabric 

### ISSUE THREAD

**Issue by cataggar** [rust-lang/docs.rs#1709]
### Crate name

azure_svc_servicefabric

### Build failure link

https://docs.rs/crate/azure_svc_servicefabric/0.2.0/builds/536375

### Requested RAM limit

6 GB

### Why your crate needs the resource increases

I limited all of the generated service crates to 5 tags. In this case, it is 5 API versions. That has worked for most of the other crates, but this one is big. 

https://github.com/Azure/azure-sdk-for-rust/tree/main/services/svc/servicefabric

An alternative would be to keep reducing the number of tags until it fits in 3 GB.

**Comment by syphar** [comment]
I see that the latest version of this crate is built and the docs work. 

I'll close this issue now. 

Please feel free to reopen it if you still need changes here.
