### ISSUE TITLE
Build Failure for KConfig

### ISSUE THREAD

**Issue by Ayush1325** [rust-lang/docs.rs#1712]
### Crate name

kconfig

### Build failure link

https://docs.rs/crate/kconfig/0.1.0/builds/539380

### Additional details

I think this should have been fixed with my merge request https://github.com/rust-lang/crates-build-env/pull/101 in crates-build-env. So I was just wondering how can I find which version of crates-build-env was my built using?

Also is there any way to manually trigger a rebuild of docs for my crate?

**Comment by syphar** [comment]
@Ayush1325 sorry, I didn't come to updating the docs.rs build-server yet after merging https://github.com/rust-lang/crates-build-env/pull/101. 

I just updated it and requeued the build: 
https://docs.rs/releases/queue

**Comment by Ayush1325** [comment]
@syphar Thanks. The build succeeded. Closing this now.
