### ISSUE TITLE
The menu that should appear below the navigation bar is not displayed

### ISSUE THREAD

**Issue by trrk** [rust-lang/docs.rs#1714]
Pressing the crate name or "platform" in the navigation bar brings up a menu. I noticed that this is not working correctly in the current docs.rs.

![image](https://user-images.githubusercontent.com/13601547/162607851-aa3e0a69-e115-438c-a675-2920efb6df0e.png)

**Comment by syphar** [comment]
@trrk thank you for the report, I can reproduce this. it could be related to #1711, I'll see if reverting this change helps
