### ISSUE TITLE
Ring+nightly issue

### ISSUE THREAD

**Issue by CriesofCarrots** [rust-lang/docs.rs#1721]
### Crate name

solana-client, but other crates also affected.

### Build failure link

https://docs.rs/crate/solana-client/1.10.4, https://docs.rs/crate/solana-client/1.9.14

### Additional details

Solana monorepo v1.9.14 and v1.10.4 docs were affected by this issue: https://github.com/briansmith/ring/issues/1469
Is there a way we can go through and queue the failures for rebuild?

**Comment by syphar** [comment]
@CriesofCarrots I just queued both releases, see https://docs.rs/releases/queue .

@Nemo157 was scraping the logs for failures ( see https://github.com/rust-lang/docs.rs/issues/1703#issuecomment-1082887581 ) and somehow this slipped through.

**Comment by CriesofCarrots** [comment]
Great, thank you, @syphar and @Nemo157 !
I think some of the other `solana-` crates may be affected, but I haven't audited yet. May I comment them here as I find them?

**Comment by syphar** [comment]
> May I comment them here as I find them? 

Yeah, that I can definitely do

**Comment by CriesofCarrots** [comment]
It looks like most of the crates in our v1.9.14 and v1.10.4 releases were affected, but here are the ones I'm most interested in having rebuilt, if possible:
solana-cli
solana-core
solana-geyser-plugin-interface
solana-geyser-plugin-manager
solana-gossip
solana-ledger
solana-program-test
solana-rpc
solana-test-validator
solana-validator

It looks like there's a different docs build issue with the v1.9.15 and v1.10.7+ versions of most of those crates; I assume it's our bug.

Anyway, thank you!

**Comment by syphar** [comment]
@CriesofCarrots I just queued both versions for all these crates, see https://docs.rs/releases/queue

**Comment by syphar** [comment]
I assume the builds are fine now. 

Feel free to reopen this issue if not.
