### ISSUE TITLE
Menus are cramped, dependencies wrap badly

### ISSUE THREAD

**Issue by lilyball** [rust-lang/docs.rs#1725]
Recently the dropdown menus have started to look cramped, as though there's some padding missing at the bottom of each section and of the menu itself.

Additionally, I'm seeing dependencies getting wrapped without providing space for the wrapping, thus causing the wrapped portion to overlap the next dependency. Dependencies are also being wrapped more aggressively on Safari than on Firefox (likely due to there being a custom permanent scrollbar in Safari but Firefox on macOS is still using the system-provided overlay scrollbar), but I can still get a wrapped dependency with e.g. the `assert_matches` dependency on https://docs.rs/futures/latest/futures/.

Here's a screenshot taken in Safari that demonstrates both issues:

<img width="353" alt="Screenshot showing the menu for Futures. Multiple dependencies are wrapped and overlap the next dependency, and the menu looks cramped." src="https://user-images.githubusercontent.com/714/163630930-c3541f2d-10d6-444c-b7cc-529b58ce5ad6.png">

Also in that screenshot you can see a subtle misalignment on the "Docs.rs crate page" link, presumably due to having an icon that's larger than the ones on the surrounding lines.

**Comment by syphar** [comment]
@GuillaumeGomez @jsha is this something that would be solved with #1720 or #1719 ?

**Comment by syphar** [comment]
Ah I'm stupid, this _is_ what is described in #1719. 
So it will be fixed by this PR

**Comment by syphar** [comment]
fixed and deployed in https://github.com/rust-lang/docs.rs/pull/1719
