### ISSUE TITLE
pcan-basic-sys - documentation build failure

### ISSUE THREAD

**Issue by tsabelmann** [rust-lang/docs.rs#1728]
### Crate name

pcan-basic-sys

### Build failure link

https://docs.rs/crate/pcan-basic-sys/2.0.0/builds/545409

### Additional details

This crate is intended to be used only on Windows.

**Comment by syphar** [comment]
Hello @tsabelmann , 

[docs.rs uses cross-compilation for non-linux targets](https://docs.rs/about/builds#cross-compiling).

half related is #795 which could help solving this on docs.rs side, until then you have to adapt your crate to be cross-compilable. Checking other pure windows crates might help (see https://docs.rs/windows-sys/latest/windows_sys/ )
