### ISSUE TITLE
windows-sys crate build failure

### ISSUE THREAD

**Issue by riverar** [rust-lang/docs.rs#1729]
### Crate name

windows-sys

### Build failure link

https://docs.rs/crate/windows-sys/0.36.0/builds/548347

### Additional details

Memory usage is peaking locally around 3.5GB. So short term, I think we could use a boost to perhaps 5GB. Would like to also brainstorm options with the team on how we move forward with `windows` and `windows-sys`. (I'll jump on Discord.)

**Comment by syphar** [comment]
@riverar I just increased the memory limit for the `windows-sys` crate to 5 GB. 

Also I triggered a rebuild for the failed version, see https://docs.rs/releases/queue . It's lowest priority but will be handled when the other recent releases are finished. 

There was some discussion about reducing memory usage in https://github.com/rust-lang/docs.rs/issues/1633, related to [other issues about azure library builds](https://github.com/rust-lang/docs.rs/issues?q=is%3Aissue+author%3Acataggar+)

**Comment by riverar** [comment]
@syphar Great, thanks!

I reviewed the discussion and sadly nothing there applies. `windows` and `windows-sys` are just edge case extremely large crates (the Windows API surface is huge). We're going to have to huddle up across rustdoc, docs.rs, and windows teams and figure out a way forward.
