### ISSUE TITLE
rebuild aws-config after https://github.com/rust-lang/rust/pull/96447 lands

### ISSUE THREAD

**Issue by rcoh** [rust-lang/docs.rs#1731]
### Crate name

aws-config

### Build failure link

https://docs.rs/crate/aws-config/0.11.0/builds/550519

### Additional details

caused by https://github.com/rust-lang/rust/issues/96429

**Comment by syphar** [comment]
@rcoh I'm watching the PR and will trigger the rebuild when it's merged and landed in nightly. 

For the case that I miss it you can just ping me and then I'll do it.

**Comment by syphar** [comment]
@rcoh I just rebuilt the release and it seemed to have succeeded. 

I'm closing this issue, don't hesitate to reopen if I'm mistaken :)

**Comment by rcoh** [comment]
Thanks!!
