### ISSUE TITLE
feature(test) Compile failure during build noria-server

### ISSUE THREAD

**Issue by magazinebrute** [rust-lang/docs.rs#1738]
### Crate name

assert_infrequent v0.1.0

### Build failure link

not sure

### Additional details

`#![feature]` may not be used on the stable release channel
 --> C:\Users\rudyh\.cargo\registry\src\github.com-1ecc6299db9ec823\assert_infrequent-0.1.0\src\lib.rs:1:12
  |
1 | #![feature(test)]
  |            ^^^^
![image](https://user-images.githubusercontent.com/2176542/169670549-a8a4b6bb-e9d3-44c0-b809-2d63c9525d2a.png)

**Comment by jyn514** [comment]
I don't know why you think this is related to docs.rs, but that's a local build of a crate, not a docs.rs build of a published crate. This is not a support channel for rust in general.
