### ISSUE TITLE
Update `protoc` version in build image

### ISSUE THREAD

**Issue by ppodolsky** [rust-lang/docs.rs#1741]
### Crate name

summa

### Build failure link

https://docs.rs/crate/summa/0.7.1/builds/567648

### Additional details

Hi guys!
I use prost-build to build proto files in `build.rs` and in its turn it uses system proto compiler. There are some fileds in my proto files that marked as `optional`. The `optional` has been added in proto 3.12 and stabilized in 3.15. So it seems that build machines/images contains outdated `protoc`

**Comment by syphar** [comment]
@ppodolsky the image being used is defined in https://github.com/rust-lang/crates-build-env , see also https://docs.rs/about/builds#missing-dependencies . 

Any package in ubuntu focal can be added, so you can just create a PR to the repo. 

( I'll review and deploy then)

**Comment by syphar** [comment]
( looking at https://github.com/rust-lang/crates-build-env/blob/master/linux/packages.txt it looks like we only have `libprotoc17` in there currently)

**Comment by ppodolsky** [comment]
Yep, as usual I've found these pages immediately after had posted questions here :)

Looks like there is no an easy way because even 22.04 has too outdated `protoc`. The hackery way is to delete `protoc` binary before build and it will lead to building of vendored `protoc` in `prost-build` crate. But it is such a waste of resources and against the good sense.

**Comment by syphar** [comment]
until we have #315 your options are probably vendoring (as you stated), or [conditional compilation](https://docs.rs/about/builds) if you don't need protoc for the docs.
