### ISSUE TITLE
docs build for fui crate gets read-only error

### ISSUE THREAD

**Issue by ghost** [rust-lang/docs.rs#1744]
### Crate name

fui

### Build failure link

https://docs.rs/crate/fui/2.1.0/builds/573748

### Additional details

Related to `xcb` library, see

```shell
error: failed to run custom build command for `xcb v0.8.2`
```

I assume `xcb v0.8.2` works, since the docs exist on https://docs.rs/xcb/0.8.2/xcb/index.html

Similar error for `fui 2.0.0`, see https://docs.rs/crate/fui/2.0.0/builds/346152

**Comment by Nemo157** [comment]
`xcb` attempting to write into its source directory is a bug, it must use the `OUT_DIR` variable it is passed by cargo. (I wish cargo itself would make the source directories read only to reduce bugs like this...)

**Comment by jyn514** [comment]
You need to update to xcb 1.0.

**Comment by xliiv** [comment]
Thanks for hints @Nemo157 & @jyn514 i'm following them now.. and got confused because 2 commands give me different versions

```shell
> cargo publish --dry-run 2>&1|rg xcb
   Compiling xcb v0.8.2
> cargo tree|rg xcb
│       └── xcb v1.1.1
```

`cargo tree` version is also in the lock file
```shell
> cat Cargo.lock |rg -iC5 xcb
name = "x11-clipboard"
version = "0.6.1"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "6a7468a5768fea473e6c8c0d4b60d6d7001a64acceaac267207ca0281e1337e8"
dependencies = [
 "xcb",
]

[[package]]
name = "xcb"
version = "1.1.1"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "b127bf5bfe9dbb39118d6567e3773d4bbc795411a8e1ef7b7e056bccac0011a9"
dependencies = [
 "bitflags",
```

Would you have thought?

**Comment by jyn514** [comment]
You depend on `clipboard 0.5`. That depends on https://docs.rs/x11-clipboard/0.3.3/x11_clipboard/, which depends on xcb 0.8.

**Comment by xliiv** [comment]
Not to my check, but I can be wrong, so here's what i do

1. https://github.com/xliiv/fui/blob/aa34a98c6b3f0daaff8768700e0549e108e37e57/Cargo.toml#L17
![image](https://user-images.githubusercontent.com/298994/173158396-f0cfa20c-093d-4268-aa42-2cf48384ab7e.png)
2. https://github.com/xliiv/rust-clipboard/blob/71089e792fd5e52f05d5b22c54bd2d206d20ec0d/Cargo.toml#L19
![image](https://user-images.githubusercontent.com/298994/173158609-9ff94b84-2fca-46d9-a1c9-be7b1f70b430.png)

3. https://docs.rs/crate/x11-clipboard/0.6.1/source/Cargo.toml 
![image](https://user-images.githubusercontent.com/298994/173158503-1e782900-aa05-4df2-a311-f5a0a7c763d0.png)

Anyway, I'll spend more time to figure it out, once I know something I will put it here.

**Comment by jyn514** [comment]
Oh, I see what's going on - `git =` is ignored when publishing, you can't publish a crate with a git dependency so cargo falls back to the version from crates.io.

**Comment by xliiv** [comment]
https://crates.io version of `rust-clipboard` seems abandoned, see

![image](https://user-images.githubusercontent.com/298994/173159459-8ac81fc3-bcac-4ce2-9d63-bc16cd3f24d2.png)

from https://crates.io/crates/clipboard

Does it mean, I need to publish own fork of `rust-clipboard` to https://crates.io with changed name?

Or maybe there is a better way?

**Comment by syphar** [comment]
Yep, a fork would be the open source way of doing things, if a PR to the repo isn't accepted. 
Or find a replacement library. 

I'll close this issue here, feel free to reopen if needed.
