### ISSUE TITLE
Show dev-dependencies separately

### ISSUE THREAD

**Issue by bluss** [rust-lang/docs.rs#175]
Under dependencies for a crate, both dev-dependencies and dependencies are listed together.

It would be good to mark dev-dependencies separately: pulling in too many dependencies isn't always popular, and a crate's dev-dependencies do not become your own dependencies, when you use the crate, so they should be distinguished.

**Comment by spk** [comment]
This can be closed I guess its on production cf https://docs.rs/pyo3/0.6.0-alpha.4/pyo3/

**Comment by onur** [comment]
Yes, thank you @spk!
