### ISSUE TITLE
Split metrics between service metrics and instance metrics

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/docs.rs#1755]
Now that we're approaching the point where we deploy the docs.rs frontend on ECS, it would be good to split "instance" metrics with "service" metrics. Instance metrics are all thosse metrics that are specific to the current process (like the number of requests served), while service metrics are about docs.rs itself (like the number of crates in the queue).

The split would allow our monitoring to collect service metrics only from one server while collecting instance metrics from all servers.

**Comment by syphar** [comment]
To clarify for me: 
- this means there should be a separate endpoint for instance & service metrics, right? 
- do we also need to change the namespace for the service metrics?

**Comment by pietroalbini** [comment]
> this means there should be a separate endpoint for instance & service metrics, right?

Yes.

> do we also need to change the namespace for the service metrics?

It would be nice if we were starting from scratch, but it doesn't cause any issue to have both in the same namespace and it'd be a pain to change all queries.

**Comment by syphar** [comment]
closing this issue since #2038 is merged & deployed
