### ISSUE TITLE
Compiler bug on build of `rsonpath`

### ISSUE THREAD

**Issue by V0ldek** [rust-lang/docs.rs#1769]
### Crate name

rsonpath

### Build failure link

https://docs.rs/crate/rsonpath/0.1.0/builds/593800

### Additional details

The crate failed to build when with an internal compiler error:

```
thread 'rustc' panicked at 'index out of bounds: the len is 1 but the index is 2', compiler/rustc_builtin_macros/src/format.rs:1001:28

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.
```

I think a rebuild should fix this, looks like a transient error.

**Comment by jyn514** [comment]
Can you confirm this works ok for you on the most recent nightly, and fails on the version used in that link? If not, you should report this upstream to rust-lang/rust or it'll just fail again when rebuilt.

**Comment by V0ldek** [comment]
> Can you confirm this works ok for you on the most recent nightly, and fails on the version used in that link? If not, you should report this upstream to rust-lang/rust or it'll just fail again when rebuilt.

Right, probably should've mentioned that. Yes, it succeeds in my [pipeline](https://github.com/V0ldek/rsonpath/runs/7358690494?check_suite_focus=true) and on my local machine.

**Comment by V0ldek** [comment]
It failed with the same error, I am filing an issue to `rust-lang`.

**Comment by Nemo157** [comment]
I opened a meta-issue (#1771) since this is causing quite a number of failures, we can list all affected crates and rebuild them all once it's fixed.
