### ISSUE TITLE
`poem` crate failing to compile

### ISSUE THREAD

**Issue by sunli829** [rust-lang/docs.rs#1770]
### Crate name

poem

### Build failure link

https://docs.rs/crate/poem/1.3.35/builds/594096

**Comment by syphar** [comment]
The error looks like the same error as in #1769 , so   https://github.com/rust-lang/rust/issues/99261 or https://github.com/rust-lang/rust/issues/99261. 

I'll leave this issue open so we remember to requeue the builds when the issue is fixed, feel free to ping me if I miss it.

**Comment by Nemo157** [comment]
I opened a meta-issue (#1771) since this is causing quite a number of failures, we can list all affected crates and rebuild them all once it's fixed.
