### ISSUE TITLE
Doc Build Failure: `ICE: index out of bounds: the len is 1 but the index is 2`

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/docs.rs#1771]
Current nightly has an ICE that hits a widely used dependency (`time`), causing over half of the recent build failures. Once this is fixed we will rebuild all crates affected. First affected nightly was `rustc 1.64.0-nightly (c2f428d2f 2022-07-14)`.

 * Issue: https://github.com/rust-lang/rust/issues/99261
 * Fix: https://github.com/rust-lang/rust/pull/99263

**Comment by syphar** [comment]
@Nemo157 it looks like the ICE was fixed in the meantime, does it? 

Which would be the first fixed nightly , coming from the merge time of the fix? 

Then I could just query all failed builds for these and requeue them. 

Or were you planning on grepping the logs?

**Comment by Nemo157** [comment]
Yep, it should be fixed in the `2022-07-17` toolchain. I'm running my [`scrape-recent-failures 2022-07-13 "index out of bounds: the len is 1 but the index is 2', compiler/rustc_builtin_macros"`](https://gist.github.com/Nemo157/f35784c5ae2577894d38505f7ac5db7c) script right now to grab all the builds affected by this. (I should add a similar command to the binary so we can do the check on the server and queue them straight away instead of going over the web, though I guess it still needs to hit S3 for each build-log).

**Comment by Nemo157** [comment]
Queued new builds for:

```
salvo 0.27.0
salvo_extra 0.27.0
salvo_core 0.27.0
aim 1.5.2
pooly 0.2.1
orly 0.1.3
tracing-init 0.1.0
release_plz_core 0.2.18
clyde 0.1.0
disarray 0.1.11
poem-dbsession 0.3.35
poem-openapi 2.0.5
poem 1.3.35
wasmbus-rpc 0.9.3
rsonpath 0.1.0
wasmcloud-test-util 0.4.1
wasmcloud-control-interface 0.16.2
rsonpath 0.1.0
datapack 2.0.1
cobble-core 0.4.1
mungos 0.2.12
```
