### ISSUE TITLE
remove footer; change Rust menu to "About"

### ISSUE THREAD

**Issue by jsha** [rust-lang/docs.rs#1775]
Right now docs.rs adds a footer as well as a header to each page. This is a frequent source of layout bugs, as it interacts in a complicated way with rustdoc's CSS. It contains:

- [About docs.rs](https://docs.rs/about)
- [Privacy policy](https://foundation.rust-lang.org/policies/privacy-policy/#docs.rs)
- [Build queue](https://docs.rs/releases/queue)

I propose that we eliminate the footer, and move these links to the topbar. If we rename the "Rust" menu to "About", I think they would fit well there. This would also make them more visible and easier to reach. I think many people never notice the footer all the way at the bottom of the page (I didn't for years, until I saw a bug report about it :-D).

**Comment by jyn514** [comment]
> I think many people never notice the footer all the way at the bottom of the page (I didn't for years, until I saw a bug report about it :-D).

we actually added it fairly recently (~10 months ago?). I don't feel strongly about it, happy to move to the header instead.
cc @pietroalbini who added the footert

**Comment by pietroalbini** [comment]
I'm not sure if putting them in a dropdown is going to make them more visible, and my intuition would say the opposite (still, I'm not that good at UI/UX). The only thing I think is critical to have visible in the page is the privacy policy link, but having it as an item (outside the dropdown) in the header feels excessive.

(btw I'm pretty sure I wasn't the one adding the footer?)

**Comment by syphar** [comment]
for the record: initial PR was #1367

**Comment by jsha** [comment]
Thanks for tracking down the PR!

Where does the requirement come from that the privacy link cannot be in a
menu?

**Comment by pietroalbini** [comment]
That's my understanding, but I'm not a lawyer and I'm probably wrong. We should check with the foundation about it.

**Comment by jsha** [comment]
I checked with the foundation, via our community advocate @sgrif, and got feedback from a lawyer that it is fine to put in the header. 👍🏻
