### ISSUE TITLE
Intra-doc links that rely on dev-dependencies don't work

### ISSUE THREAD

**Issue by jplatte** [rust-lang/docs.rs#1783]
[This section](https://docs.rs/axum/0.5.13/axum/middleware/index.html#commonly-used-middleware) of axum's documentation contains a bunch of broken intra-doc links, mostly to `tower-http` ([bug report](https://github.com/tokio-rs/axum/issues/1180)). It looks like the culprit here is that somehow, dev-dependencies are excluded when docs.rs builds the docs, which means that most of `tower-http`'s features aren't activated, so the modules we want to link to don't exist and rustdoc just inserts the intra-doc link verbatim.

**Comment by Nemo157** [comment]
dev-dependencies are never active when building docs. What may be happening to make your local doc build work is intra-workspace feature leakage; one of your other crates activates a feature that then allows the links to resolve. If I delete the workspace `Cargo.toml` then try building the docs in `axum/axum` I get unresolved link warnings. (For some reason `cargo tree --edges=features` doesn't show any differences though...)

**Comment by Nemo157** [comment]
Ok, no, somehow the dev-dependencies features are getting activated _when it is in a workspace_. This seems like some kind of cargo bug.

**Comment by jplatte** [comment]
I thought intra-workspace feature leakage would only affect `cargo` commands ran from the workspace root? I made sure to also test when inside the `axum` directory.

So if this is expected behavior, is there a suggested workaround? I guess we could declare a `__docs` feature that also enables the needed features on tower(-http).

**Comment by Nemo157** [comment]
> I guess we could declare a `__docs` feature that also enables the needed features on tower(-http).

Yeah, that's what I would probably do.

**Comment by jplatte** [comment]
Alright. Are you going to report this weird behavior to Cargo? If yes, can you then link it here? If not I'll work on making a small repro so I know I understand the problem and raise a bug report myself some time soon.

In any case, there doesn't seem to be anything to track here.

**Comment by Nemo157** [comment]
Reported in https://github.com/rust-lang/cargo/issues/10909

**Comment by Nemo157** [comment]
And relevant upstream issue to improve the support for this: https://github.com/rust-lang/cargo/issues/8905
