### ISSUE TITLE
azure_devops_rust_api build failure due to RAM limit

### ISSUE THREAD

**Issue by johnbatty** [rust-lang/docs.rs#1784]
### Crate name

azure_devops_rust_api

### Build failure link

https://docs.rs/crate/azure_devops_rust_api/0.1.3/builds/602073

### Requested RAM limit

5GB

### Why your crate needs the resource increases

The crate is a large autogenerated crate.

The build failure reason is not clear from the logs, but if I run cargo doc locally I can see that RAM usage appears to be over the 3GB limit (~3.6GB):
```
$ /usr/bin/time -v cargo doc --all-features --no-deps
    Finished dev [unoptimized + debuginfo] target(s) in 2m 40s
        Command being timed: "cargo doc --all-features --no-deps"
        User time (seconds): 271.75
        System time (seconds): 19.01
        Percent of CPU this job got: 181%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 2:40.54
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 3612064
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 72
        Minor (reclaiming a frame) page faults: 2875316
        Voluntary context switches: 19928
        Involuntary context switches: 41128
        Swaps: 0
        File system inputs: 608
        File system outputs: 1333952
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
```

Please could you increase the RAM limit to 5GB for this crate.

**Comment by syphar** [comment]
I increased the limit for this crate and requeued the build, see https://docs.rs/releases/queue 

Feel free to reopen this issue if the build still fails.

**Comment by syphar** [comment]
build was successful now: 

https://docs.rs/azure_devops_rust_api/latest/azure_devops_rust_api/

**Comment by johnbatty** [comment]
@syphar Many thanks!
