### ISSUE TITLE
Request for rebuild of `teloxide v0.10.1`

### ISSUE THREAD

**Issue by WaffleLapkin** [rust-lang/docs.rs#1790]
### Crate name

teloxide

### Build failure link

https://docs.rs/crate/teloxide/0.10.1/builds/597656

### Additional details

See the rust issue: https://github.com/rust-lang/rust/issues/99663, it have been fixed by https://github.com/rust-lang/rust/pull/99666, so now the doc build should succeed.

**Comment by Nemo157** [comment]
Rebuild has been queued.

**Comment by WaffleLapkin** [comment]
Rebuild succeeded :3

**Comment by WaffleLapkin** [comment]
Can rebuild be done again? Specifically to fix the result of the https://github.com/rust-lang/rust/issues/100204 regression.

**Comment by Nemo157** [comment]
Queued it again.
