### ISSUE TITLE
Self-Host Docs outdated?

### ISSUE THREAD

**Issue by jbenz1** [rust-lang/docs.rs#1791]
Hello, it appears that the self-hosted docs found at https://forge.rust-lang.org/docs-rs/self-hosting.html doesn't work. A lot of the commands in the Postgresql section don't work. In particular, the subcommands aren't recognized. What is the recommended way to self-host a docs.rs instance? Is it safe to follow the step found in the github for this case?

**Comment by syphar** [comment]
yes, the self-hosted docs are definitely outdated, sorry about that. 

The readme is definitely up-to-date for dev-environments and the resulting environment is usable for builds and serving the docs.

**Comment by jbenz1** [comment]
No worries, I'm sure it's not a very popular use case. Thanks, I'll checkout the dev environment.
