### ISSUE TITLE
Crate reached sandbox limits, gives ReadOnly error

### ISSUE THREAD

**Issue by hjaffe22** [rust-lang/docs.rs#1793]
### Crate name

libgunslinger-sys

### Build failure link

https://docs.rs/crate/libgunslinger-sys/0.1.5/builds/610059

**Comment by jyn514** [comment]
@hjaffe22 you can't write to the source directory. If you need to generate bindings, you can write them to OUT_DIR instead, which is set by Cargo and we guarantee is writable.

**Comment by hjaffe22** [comment]
oh mb, thanks alot for the help!
