### ISSUE TITLE
shellfirm failed to build

### ISSUE THREAD

**Issue by kaplanelad** [rust-lang/docs.rs#1803]
### Crate name

shellfirm

### Build failure link

https://docs.rs/crate/shellfirm/0.2.2/builds/602772

### Additional details

Couldn't understand why the build is failed, can you please help me to understand how can I solve this issue?

**Comment by jyn514** [comment]
```
[INFO] [stderr]   process didn't exit successfully: `/opt/rustwide/target/debug/build/shellfirm-bb5a33254cf5943e/build-script-build` (exit status: 1)
[INFO] [stderr]   --- stderr
[INFO] [stderr]   Error: could not find repository from '/opt/rustwide/workdir'; class=Repository (6); code=NotFound (-3)
```
Looks like your build script expects to be run in a git directory. We build crates from the tarball distributed by crates.io, so there's no git history available. You'll need to change your build script to account for this case.

Note that this is also true for anyone who tries to use your library as a dependency, cargo doesn't package the git history.

**Comment by kaplanelad** [comment]
Thanks @jyn514, for your fast response! i'll try to change it!

**Comment by kaplanelad** [comment]
Thanks @jyn514 it works for me
