### ISSUE TITLE
Menus are detached if scrolled down

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/docs.rs#1810]
![image](https://user-images.githubusercontent.com/81079/187555073-1456e741-b0ab-40e7-8912-cbb61dde7d46.png)

To reproduce, scroll down _slightly_ then open a top-menu, the further you scroll the further down it goes and eventually goes off screen.

Happens for me on Firefox 103.0.1 and 103.0.2 on Windows, but not on Edge.

**Comment by syphar** [comment]
@euphemism could this be a bug in #1782 ? cc @GuillaumeGomez

**Comment by euphemism** [comment]
Oh, huh. Sorry about that. Not something I had come across when poking around with my changes.
