### ISSUE TITLE
Restore/Update `badge` crate

### ISSUE THREAD

**Issue by vbrandl** [rust-lang/docs.rs#1813]
The [`badge` crate](https://crates.io/crates/badge) has been removed in https://github.com/rust-lang/docs.rs/commit/94f3bba6815412bc4672621c4690a93e656486c7, but there are projects [depending on it](https://crates.io/crates/badge/reverse_dependencies).

The crate depends on [`rusttype`](https://crates.io/crates/rusttype), which is [unmaintained](https://gitlab.redox-os.org/redox-os/rusttype/-/issues/148) and produces [RUSTSEC warnings](https://github.com/vbrandl/hoc/issues/488).

Is ist possible to restore the crate and update the dependencies, or should I take the last version from https://github.com/rust-lang/docs.rs/commit/94f3bba6815412bc4672621c4690a93e656486c7, create a fork and publish it as a new crate?

**Comment by syphar** [comment]
I'm not sure I follow. 

https://github.com/rust-lang/docs.rs/commit/94f3bba6815412bc4672621c4690a93e656486c7 that you are referring to removed a sub-crate of docs.rs and replaced its usage with a redirect to shields.io. 

This is not the same crate as on crates.io, so nothing could depend on it. 

Where are you missing the crate? The docs for the [crates.io crate](https://crates.io/crates/badge) [look fine](https://docs.rs/badge/latest/badge/)

**Comment by vbrandl** [comment]
The removed subcrate is the one published to crates.io. Since the code has been removed from this project, there will be no new versions on crates.io.

I'm asking if it is possible to publish an update to crates.io with updated dependencies that won't trigger RUSTSEC warnings (e.g. by creating a fork and transferring maintainership on crates.io) or if I should create a fork and publish it under a new name on crates.io

**Comment by syphar** [comment]
> The removed subcrate is the one published to crates.io. Since the code has been removed from this project, there will be no new versions on crates.io.

ah sorry, I wasn't aware of that.

**Comment by jyn514** [comment]
@Nemo157 suggests publishing an "unmaintained" advisory to rustsec, which seems fine to me, but I probably won't personally have time for in the near future.

**Comment by vbrandl** [comment]
I created an issue to mark the crate as unmaintained: https://github.com/rustsec/advisory-db/issues/1401

I guess I will create a fork based on the last version of the source code and publish it to crates.io. Would you be willing to transfer ownership of the name `badge` on crates.io or should I use another name?

**Comment by jyn514** [comment]
I'll get back to you on that, we need to discuss it with @rust-lang/infra

**Comment by vbrandl** [comment]
Ok so I created a fork of the repository: https://github.com/vbrandl/badgers

I replaced the `rusttype` crate, fixed everything to have passing tests again and added Github Actions for CI, audit (and later publishing to crates.io)

Were you able to discuss transferring ownership of the `badge` crate? Otherwise I think I'll go with `badgers`, publish to crates.io and create a rustsec advisory.

**Comment by jyn514** [comment]
Unfortunately we're not able to transfer ownership of crates owned by the rust project outside the project: https://rust-lang.github.io/rfcs/3119-rust-crate-ownership.html#transitions-and-new-crates

Glad to see your fork is working for you :)
