### ISSUE TITLE
.: no such file or directory: .env

### ISSUE THREAD

**Issue by liby** [rust-lang/docs.rs#1817]
I see that in the `remove dotenv dependency` [commit](https://github.com/rust-lang/docs.rs/commit/6703c1b808829df3bfe8b5550af7524570faa668), step `. .env` is added, but I get an error on macOS
```
docs.rs [master][📦 v0.6.0][🦀 v1.65.0-nightly]
❯ ll | grep "env"
-rw-r--r--   1 bryan  staff   368B Sep  2 16:19 .env
-rw-r--r--   1 bryan  staff   368B Sep  2 16:18 .env.sample

docs.rs [master][📦 v0.6.0][🦀 v1.65.0-nightly]
❯ . .env
.: no such file or directory: .env
```
 and use the `source .env` command to get an error at a later step
```
configuration variable DOCSRS_PREFIX is missing
```

PTAL @syphar

**Comment by jyn514** [comment]
@liby you need to run `cp .env.sample .env`; I think we have that somewhere in the docs but don't remember where.

**Comment by liby** [comment]
> @liby you need to run `cp .env.sample .env`; I think we have that somewhere in the docs but don't remember where.

I've already done it. `ll` is an alias to `ls -alFh`.
<img width="510" alt="image" src="https://user-images.githubusercontent.com/38807139/188179205-0d73dd92-d352-44f4-90bd-63bf8f9e6a93.png">

**Comment by jyn514** [comment]
oh, right, this is a bash thing - use `. ./.env` so it doesn't look in PATH

**Comment by liby** [comment]
> oh, right, this is a bash thing - use `. ./.env` so it doesn't look in PATH

It works, thank you, do you need me to help create PR?
<img width="465" alt="image" src="https://user-images.githubusercontent.com/38807139/188180199-3bcb31d8-f7b3-4916-b035-8a66aeec00e6.png">

**Comment by jyn514** [comment]
that would be great, thanks!
