### ISSUE TITLE
(can't reproduce) top-bar dropdowns do not open on some libraries (Firefox, Linux)

### ISSUE THREAD

**Issue by adsick** [rust-lang/docs.rs#1818]
the crate I have issues with: https://docs.rs/rug/latest/rug/struct.Float.html try opening dropdown menus here.

Suddenly found myself trying to open dropdown menus from the top-bar and they do not open!
Look: [Screencast from 02-09-22 13:34:23.webm](https://user-images.githubusercontent.com/24528839/188123359-bac0ec78-bb80-4ee4-9346-51c0a4d3cc12.webm)

Checked it on my android smartphone (in Chrome browser) and there it's fine, but on my laptop they're broken!

Fedora Linux 36, Firefox 104

**Comment by adsick** [comment]
screencast is kinda broken too, sorry for that, I don't know the reason

**Comment by adsick** [comment]
upd: whoa, I continued to try and got this results
![image](https://user-images.githubusercontent.com/24528839/188123876-a7981846-7e6b-4c24-bf96-91f4d65d2622.png)

and some times it works as expected:
![image](https://user-images.githubusercontent.com/24528839/188123983-6e1ff5e1-8179-48b1-8d06-1755879f8054.png)

**Comment by Nemo157** [comment]
You're probably hitting #1810, it's fixed but not yet deployed.

**Comment by syphar** [comment]
I just deployed #1810
