### ISSUE TITLE
method links broken

### ISSUE THREAD

**Issue by 89z** [rust-lang/docs.rs#1821]
If I go to this page:

https://docs.rs/tinyjson/latest/tinyjson/struct.JsonParser.html

I see a method on the left called `parse`, but if I click it, it doesn't do anything:

https://docs.rs/tinyjson/latest/tinyjson/struct.JsonParser.html#method.parse

**Comment by Nemo157** [comment]
For some reason the implementation block was unexpanded by default. I've rebuilt the docs and it seems to be fixed, so probably some old rustdoc bug.
