### ISSUE TITLE
Crate fails to build and need clarification on when OUT_DIR is or should be defined

### ISSUE THREAD

**Issue by vectronic** [rust-lang/docs.rs#1823]
### Crate name

flowscripter_template_deno_rust_library

### Build failure link

https://docs.rs/crate/flowscripter_template_deno_rust_library/1.0.9/builds/624001

### Additional details

This is caused by an attempted write by a `deno_bindgen` macro to a read-only directory as per the info:

_Most of the sandbox is a read-only file system, including the source directory of your crate and its dependencies. If your build.rs generates files that are relevant for documentation, consider writing to the [cargo output directory](https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-crates), passed in the environment variable OUT_DIR._

Based on the above I submitted a patch to `deno_bindgen` which now checks for the `OUT_DIR` env var and uses that when outputting a `bindings.json` file as part of the build.

Change is here: https://github.com/denoland/deno_bindgen/pull/82/files#diff-6894d37ad1be13438ddf87f7ca5e444601fd2a3ad62196b5044885b89c0ec730R35

This change is in `deno_bindgen` 0.6.0 which I am now using. 

However the problem still persists...

It looks like `OUT_DIR` is not defined when the `deno_bindgen` macro is run as part of the `cargo doc` build but I am clueless as to whether I should expect it to be set or whether I should somehow set it...?

I have followed local test procedures documented here:

https://blog.rust-lang.org/2019/09/18/upcoming-docsrs-changes.html

and by setting the `OUT_DIR` env var as follows:

```
export OUT_DIR=target
time cargo doc --no-deps
```

 I can see the `bindings.json` file is written to the `target` folder instead of the base folder of the build which causes the error.

**Comment by Nemo157** [comment]
`OUT_DIR` is configured for build scripts, not proc-macros. There is afaik no intended way for proc-macros to output anything other than the token stream they return (because of the compilation model side-effects from proc-macros are not guaranteed).

**Comment by vectronic** [comment]
Thank you very much for your prompt reply. 

Your explanation made perfect sense and led me to find this discussion:

https://github.com/rust-lang/cargo/issues/9084

(It seems like I am not the only one using tooling that relies on procedural macros which output auxiliary information to the filesystem.)

Based on that discussion, I tried again with an empty build.rs and this did the trick:

https://docs.rs/crate/flowscripter_template_deno_rust_library/latest

It's a bit of a hacky workaround but I think it is the only option I have. 

Again thanks.
