### ISSUE TITLE
Use 301 redirect for crate -> crate/latest

### ISSUE THREAD

**Issue by jsha** [rust-lang/docs.rs#1833]
In the Google Search console reports, one of the common URL types that gets "Duplicate without user-selected canonical" is https://docs.rs/crate/clippy-sarif/latest. Inspecting a few of these shows that Google is selecting https://docs.rs/clippy_sarif as canonical.

https://docs.rs/clippy_sarif redirects to https://docs.rs/crate/clippy-sarif/latest with a 302 (temporary redirect):

```
$ curl -I https://docs.rs/crate/clippy_sarif
HTTP/2 302 
content-length: 0
location: https://docs.rs/crate/clippy_sarif/latest
server: nginx/1.14.0 (Ubuntu)
date: Thu, 15 Sep 2022 18:00:30 GMT
expires: Thu, 15 Sep 2022 18:00:30 GMT
content-security-policy: default-src 'none'; base-uri 'none'; img-src 'self' https:
x-cache: Miss from cloudfront
via: 1.1 6bdc2963c9ed59b475ec36c35e5932a4.cloudfront.net (CloudFront)
x-amz-cf-pop: SEA19-C3
x-amz-cf-id: SQixpMaYDweGeQaeXJa-kTBUeZnkJgiDoFzGf2SzDPsK-fT5dOLndw==
```

We should make this a 301 (permanent redirect) so Google and other search engines pick up that https://docs.rs/crate/clippy_sarif/latest is the canonical URL.

**Comment by Nemo157** [comment]
That assumes that `clippy-sarif` won't ever have docs in the future. If at some point it does the redirect will change location.

**Comment by syphar** [comment]
it can get docs when it will switch from being a bin to lib, 

or if it was a build error through a rebuild.

**Comment by jsha** [comment]
Ohh I was misreading these URLs. For some reason I was thinking https://docs.rs/crate/clippy-sarif was getting selected as the canonical. And indeed `https://docs.rs/crate/clippy-sarif` -> `https://docs.rs/crate/clippy-sarif/latest` could be made permanent, but since that's not one of the URLs confusing the search engines, it's not particularly important.

I think that makes this WONTFIX. Google selecting `docs.rs/clippy-sarif` as canonical for this URL is actually what we want. It's a shame it clutters up our "Duplicate without user-selected canonical" report but that's no big deal; we'll just expect that to never reach zero.
