### ISSUE TITLE
Attempting to browse inside a failed doc-build could redirect to the crate page

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/docs.rs#1834]
Going to https://docs.rs/tealr/0.9.0-alpha2/tealr/ just shows a 404 because the docs failed to build for this version. We could instead redirect to https://docs.rs/crate/tealr/0.9.0-alpha2. We have internal links like this from https://docs.rs/tealr/0.8.2/tealr/ in the crate drop-down. (We should probably have the `target-redirect` handler also do a direct redirect to the crate page when the build had failed so the internal link wouldn't make it to this page, but it would be good to support both locations).

**Comment by syphar** [comment]
It looks like this was already solved in https://github.com/rust-lang/docs.rs/commit/3c0281c7bb8c81f9b896ebe7e466e6f749e69bc3
