### ISSUE TITLE
Doc links to cfg(doc) items do not work

### ISSUE THREAD

**Issue by sffc** [rust-lang/docs.rs#1839]
(this is a rustdoc issue; is this the right place to post it?)

I sometimes use `#[cfg(doc)]` modules to add additional long-form documentation. However, it seems that if I try to link to such a module, I don't get a rustdoc error, but the link does not render in clickable blue text. I can only get this to reproduce across crates.

Steps to reproduce:

1. Make a crate `foo` with a `#[cfg(doc)]` module named `extra_docs` declared in its lib.rs file
2. Make a crate `bar` that depends on `foo` with the following docs link: `/// [foo::extra_docs]`

Expected behavior: The link should show up in the HTML output.

Actual behavior: It renders as "[foo::extra_docs]" without a link.

CC @Manishearth

**Comment by jyn514** [comment]
cfg(doc) only applies to the crate currently being documented, not your dependencies. You can either use a cargo feature instead, remove the cfg altogether, or special case the DOCS_RS environment variable.
