### ISSUE TITLE
could not find `shared` in `winapi`

### ISSUE THREAD

**Issue by MrTitanHearted** [rust-lang/docs.rs#1844]
I don't know why it is not documenting my crate dgews. It uses winapi as an external package. And here is the link of the errors in docs.rs: https://docs.rs/crate/dgews/0.0.6/builds/631333

**Comment by jyn514** [comment]
You need to set your default target to Windows; we use linux to see if a crate can be documented by default. See package.metadata.docs.rs.

**Comment by MrTitanHearted** [comment]
Ok thanks

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

________________________________

**Comment by syphar** [comment]
I'm closing this issue under the assumption that the question was answered. 

Feel free to reopen it if that isn't the case.
