### ISSUE TITLE
unpublished public crates

### ISSUE THREAD

**Issue by 89z** [rust-lang/docs.rs#1848]
For example, this crate:

https://github.com/k-nasa/tumekiri/blob/bdb0546f/Cargo.toml

is not currently published:

https://crates.io/crates/tumekiri

but you can use it:

~~~
> cargo add --git https://github.com/k-nasa/tumekiri
    Updating git repository `https://github.com/k-nasa/tumekiri`
    Updating git repository `https://github.com/k-nasa/tumekiri`
      Adding tumekiri (git) to dependencies.
~~~

it would be nice if we could get public documentation for these crates. For example, other languages host public documentation from arbitrary Git repos:

- https://godocs.io/github.com/valyala/fasthttp
- https://pkg.go.dev/github.com/valyala/fasthttp

**Comment by Nemo157** [comment]
Go-lang does so because git repositories are how you publish code for it. It does not have a central package repository like crates.io.

It looks like godocs.io works out which packages to document by people searching for the packages. It will then periodically poll for updates and has a refresh button to force a new poll. It also looks like it only documents "published versions" of the packages (i.e. tags that match `v{semver-version}`).

It does seem plausible to implement something similar. But given that crates.io is the expected way to publish crates I'm not sure whether there's much value. The example crate would not get documented as it has no version tags, and I would assume that once it does get tagged that will also be published to crates.io.

**Comment by 89z** [comment]
Thanks for the reasoned response.

> Go-lang does so because git repositories are how you publish code for it.

One could make the same argument for Rust. Doing this:

~~~
cargo add --git https://github.com/k-nasa/tumekiri
~~~

in a way makes crates.io redundant. Dont get me wrong, I think crates.io is valuable. But from a minimalist viewpoint, you could decide to never publish to crates.io, and still have your crate publicly available via some Git repository.

> It does not have a central package repository like crates.io.

This is more or less true, but by default, a command like this:

~~~
go get go.dog/breeds
~~~

does actually pull from a [central repository][1].

[1]://go.dev/blog/module-mirror-launch

> But given that crates.io is the expected way to publish crates I'm not sure whether there's much value.

Hard disagree here. Bunch of crates I am interested in, that aren't published. Some do get fixed:

- https://github.com/Puellaquae/rust-json/issues/2
- https://github.com/Plecra/uri/issues/10

but then some get ignored:

- https://github.com/Geal/generic-http-client/issues/2
- https://github.com/Keksoj/uri_parser/issues/1
- https://github.com/Shinyaigeek/konnnyaku/issues/4
- https://github.com/abrahum/uri-reader/issues/1
- https://github.com/alexmaco/json_stream/issues/1
- https://github.com/andelf/rust-httpc/issues/2
- https://github.com/deependapp/quick-json/issues/1
- https://github.com/divinerapier/url/issues/2
- https://github.com/gtolle/rest_client/issues/10
- https://github.com/k-nasa/tumekiri/issues/1
- https://github.com/ntalbs/rust-uri/issues/1
- https://github.com/psychoss/rust-url-parser/issues/1
- https://github.com/rohankumardubey/uriparse-rs/issues/1
- https://github.com/serbe/uri/issues/1
- https://github.com/shkumagai/url/issues/1
- https://github.com/wolfsack/uri_parser/issues/1

or outright refused:

- https://github.com/alexgibson/rust-parse-url/issues/2
- https://github.com/anonrig/url/issues/5
- https://github.com/lohxx/httprs/issues/1
- https://github.com/mikedilger/rust-uri/issues/1
- https://github.com/rhymu8354/HttpClient/issues/2

With Go, I don't need to even contact the author, I can just request new package from the sites I listed in the original post.

> The example crate would not get documented as it has no version tags, and I would assume that once it does get tagged that will also be published to crates.io.

This is a weird requirement as well, as other languages can do documentation for arbitrary commits:

- https://godocs.io/golang.org/x/sys@v0.0.0-20220915200043-7b5979e65e41
- https://pkg.go.dev/golang.org/x/sys@v0.0.0-20220915200043-7b5979e65e41

**Comment by jyn514** [comment]
We do not have the resources to document every crate that's on GitHub.

**Comment by jyn514** [comment]
As an alternative, you could have a CI job that runs cargo doc and publishes the output to github pages.

**Comment by 89z** [comment]
> We do not have the resources to document every crate that's on GitHub.

This isn't whats being asked.

The way the other sites work, is they only generate docs **if someone requests it**, or if the site is above some threshold in terms of popularity.

I would like to take another chance to thank @Nemo157, because they seems to be willing to actually have a discussion. This is contrasted with @jyn514 response, which is the typical "read halfway, then close with short remark" kind of response.
