### ISSUE TITLE
Silent failure to build with wrong metadata

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/docs.rs#1849]
https://crates.io/crates/roslibrust/0.5.0 was published with `package.metadata.docs.rs.features = "all"` (this needs to be an array of strings). When attempting to build it we attempted to build 5 times, with no error message emitted to the logs or recorded to S3.

Will probably be fixed along with https://github.com/rust-lang/docs.rs/issues/797, we should just make sure that the recorded error message is useful for the crate author to diagnose.

**Comment by syphar** [comment]
solved with #2467
