### ISSUE TITLE
refine CDN invalidations after build

### ISSUE THREAD

**Issue by jsha** [rust-lang/docs.rs#1861]
Following up on https://github.com/rust-lang/docs.rs/pull/1825:

I notice there are a few `?` operators that come after the build happens, but before the CDN invalidation. For instance, purging the build dir and the local cache:

https://github.com/rust-lang/docs.rs/pull/1825/files#diff-b06b44e6583254ce69af8cedabc04a73a97599d593676e1bbad7ee442240ccf1R502-R506

In the unlikely event one of these fails, we would fail to invalidate. Probably the CDN invalidation should happen regardless of those errors.

Relatedly: Right now it looks like we'll do a CDN invalidation even for a build that failed. But a failed build won't affect any page except `/crate/<name>/<version>/builds`. Depending on how frequent failed builds are, we could save some money on invalidations by making /builds max-age=0, and not invalidating cache on builds.

**Comment by Nemo157** [comment]
Failed builds affect the version list in the crate dropdown (at least without #1772).

**Comment by syphar** [comment]
invaliding when we use `?` is definitely a gap in the current logic, I would fix this after we merged #1856, 
but _before_ we introduce the default TTL ( = before we actually start caching)

**Comment by syphar** [comment]
@jsha perhaps I'm missing something because of the early morning, but: 
is this here still an issue? The diff-link above doesn't show me any example I need, perhaps it became invalid because of some force-pushes. 

I'm mostly talking about the `?` piece where we would not create the needed invalidation in certain error situations.

**Comment by syphar** [comment]
correction: I just see I might have solved it myself in #1864 , so this doesn't block increasing the TTL any more.
