### ISSUE TITLE
not generating windows docs?

### ISSUE THREAD

**Issue by dherman** [rust-lang/docs.rs#187]
Hi there! I've published a Windows-specific crate ([winfolder](https://docs.rs/winfolder)) and can't seem to get docs.rs to generate Windows docs for it (there are no Windows targets listed in the Platforms menu). Is there a configuration option I need to use, or is this a bug?

If it's a missing configuration item maybe it would be good to document it in the README or the "About docs.rs" page.

**Comment by jyn514** [comment]
@dherman It looks like this is fixed on the latest version of winfolder, probably fixed by #407.
