### ISSUE TITLE
remove user's releases page in favor of corresponding crates.io page

### ISSUE THREAD

**Issue by jsha** [rust-lang/docs.rs#1872]
docs.rs has a page that lists releases by a given user, for instance https://docs.rs/releases/@jsha. The content found on this page can also be found on crates.io (https://crates.io/users/jsha), and fits better there, since crates.io is about crate ownership and publishing rather than documentation.

Also, navigation-wise, the user releases page doesn't fit in: it's part of a tab set, but if you navigate to any of the other tabs in the set, it disappears.

![image](https://user-images.githubusercontent.com/220205/193993137-adc6848c-76e3-4c4a-a259-edd3e94f22aa.png)

If we do this, we should of course set up a redirect from the old URLs to their equivalent on crates.io.

**Comment by syphar** [comment]
I would love some feedback on this from @rust-lang/docs-rs , 

I remember @Nemo157 reporting an issue on this page, so that could be a sign that it's used?

**Comment by Byron** [comment]
I am in favor of the proposition if the expected gain is lowered maintenance burden.

To this feature is entirely new and I wouldn't know how to discover it, which fuels my hopes that the removal wouldn't affect too many users especially if they get something similar on `crates.io`. 

The removal might break existing non-human users, but I wonder if their use-case could be better served if there was a different way to access that data, should they exist.

**Comment by Byron** [comment]
I am in favor of the proposition if the expected gain is lowered maintenance burden.

To this feature is entirely new and I wouldn't know how to discover it, which fuels my hopes that the removal wouldn't affect too many users especially if they get something similar on `crates.io`. 

The removal might break existing non-human users, but I wonder if their use-case could be better served if there was a different way to access that data, should they exist.

**Comment by syphar** [comment]
> To this feature is entirely new and I wouldn't know how to discover it, which fuels my hopes that the removal wouldn't affect too many users especially if they get something similar on `crates.io`.

@Byron this feature is definitely _not_ new :) ( -> https://github.com/rust-lang/docs.rs/pull/39 )

**Comment by Byron** [comment]
This comment of mine is full of bugs :D, I edited it adding `me` in a crucial place. The purpose is to show of I (considering myself to be a casual user) didn't know this feature existed nor did I discover it during my casual strolls through the page. Maybe I am not alone with that so users wouldn't be too upset if it would be removed as proposed here.

**Comment by Nemo157** [comment]
> I remember @Nemo157 reporting an issue on this page, so that could be a sign that it's used?

It's used in that I sometimes check it when implementing a feature that touches it like #1835. Other than that I also basically never use it. According to grafana it's at ~1.5 requests/minute over the last month, but that could be entirely search crawlers.
