### ISSUE TITLE
Change usage of serif fonts to sans-serif

### ISSUE THREAD

**Issue by ahmedkabd** [rust-lang/docs.rs#1895]
Usage of serif fonts is detrimental to the clarity of the text overall, and even distracting. This is especially true for something as technical as documentation.

**Comment by syphar** [comment]
Docs.rs is mostly "only" building & hosting the documentation generated by rustdoc, so this request belongs there. 

A short search gave me https://github.com/rust-lang/rust/issues/59845, which also seems to include using a sans serif font. 

So I'm closing the issue on this repo. 

Still, good idea 😄

**Comment by ahmedkabd** [comment]
Honestly, I've yet to use rustdoc, so with a quick search in this repo (in the dir templates/styles) I found two files mentioning the serif font, so I thought it belonged here.

Makes me sad the issue is from 2019, but thanks for the clarification.

**Comment by Nemo157** [comment]
We are using a serif font in a couple places ourselves. The crate description in the releases lists, the rendered readme on the crate-details page, the body of the about pages.

In general we follow the lead of rustdoc in styling of the pages (and especially we use the same font selections afaik), if it changes on the rustdoc side then we should also change to match; but it sounds like there's not any plans for that.
