### ISSUE TITLE
Improve source file rendering speed

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/docs.rs#1904]
After deploying #1842 we have a few high spikes in the `/crate/:name/:version/source/*` 90th percentile response time

![image](https://user-images.githubusercontent.com/81079/201540355-bf3381e2-f99c-40b1-86c5-bb60360edcf1.png)

I was able to track down one of these from the access logs, `https://docs.rs/crate/opus-sys/0.1.2/source/libopus/Makefile.in` took 12.25s till first byte when I loaded it. It's surprisingly slow, `https://docs.rs/crate/opus-sys/0.1.2/source/libopus/src/opus_encoder.c` took <1s and is a similar size.

I'll try and find some time to look into it soon.

**Comment by syphar** [comment]
@Nemo157 do you think this is still an issue after the change to the other regex engine? 

Looking at the 99th in grafana now I don't see any of these peaks any more?

**Comment by Nemo157** [comment]
Agreed this seems to be basically resolved, over the last week the highest spike was 1s

![image](https://github.com/rust-lang/docs.rs/assets/81079/4ee3c6a5-1e9c-43f1-953b-9abf68a0fc7e)
