### ISSUE TITLE
crates don't show feature flags

### ISSUE THREAD

**Issue by light4** [rust-lang/docs.rs#1905]
for example https://docs.rs/once_cell/1.16.0/once_cell/

![once_cell](https://user-images.githubusercontent.com/1318472/201546488-4319084c-e87a-41c5-b2ee-b7aa9f76b5b5.png)

**Comment by Nemo157** [comment]
That drop-down is presumably the one injected by the Rust Search Extension, docs.rs has a separate page for feature flags which has them for `once-cell`: https://docs.rs/crate/once_cell/1.16.0/features

**Comment by light4** [comment]
I just forgot I installed the `Rust Search Extension`.
