### ISSUE TITLE
Inconsistent style compared to rustdoc

### ISSUE THREAD

**Issue by cynecx** [rust-lang/docs.rs#1907]
I've noticed some inconsistencies about the docs.rs rendered page compared to the original rustdoc rendered pages:

1. `h1, h2, ...` tags are styled differently.

<img width="1478" alt="image" src="https://user-images.githubusercontent.com/5961244/201749945-b8705a52-93ea-48db-8f60-72495d4b2bd4.png">

https://docs.rs/bevy/latest/bevy/

You can see that the actual rustdoc style is overwritten by the vendored purecss styles (rustdoc: `1.5rem` -> purecss: `2em`).

2. The monospace font has changed from `Source Code Pro` to `Courier`.

<img width="1443" alt="image" src="https://user-images.githubusercontent.com/5961244/201750568-9f0812cd-fd1f-42af-9560-290b40bee670.png">

Same issue as 1.) here. It would seem like the purecss css is overwriting the rustdoc styles.

**Comment by cynecx** [comment]
I seriously don't know what is happening here:

<img width="1526" alt="image" src="https://user-images.githubusercontent.com/5961244/201754054-968a2f6d-4f4f-4d0a-86bb-7c8a96245f30.png">

That doesn't look right to me. It probably be there once and ideally after normalize and before rustdoc. This might be the issue here.

**Comment by Nemo157** [comment]
Ah, this is because the path now contains `rustdoc.static` for all rustdoc css and we detect `href*='rustdoc'` to find where to insert the stylesheet. I'll work on a fix.

https://github.com/rust-lang/docs.rs/blob/33d17e43393c6dd66f0308e8ca6fdb31e632ec48/src/utils/html.rs#L72
