### ISSUE TITLE
"Flat Square" badges

### ISSUE THREAD

**Issue by spacekookie** [rust-lang/docs.rs#192]
Could you support alternative styles for the doc badges? For example, shields.io has this style:

![](https://camo.githubusercontent.com/c71adf9416edc222ac4ce4b789b990d98e88bf77/68747470733a2f2f696d672e736869656c64732e696f2f6372617465732f762f7468756e6465722e7376673f7374796c653d666c61742d737175617265)

Alternatively, I found this issue: https://github.com/badges/shields/issues/1382

Has there been any progress on enhancing the API maybe?

**Comment by Kixiron** [comment]
Triage: `badges` could be helpful in other ways, [badge-maker](https://github.com/badges/shields/tree/master/badge-maker/lib) has some great ideas that could be used to update [our badges](https://github.com/rust-lang/docs.rs/tree/master/src/web/badge)

**Comment by Nemo157** [comment]
Personally I feel like moving badge rendering to shields.io would make a lot of sense, we could quite easily add the small API they need to get the status, then setup redirects from the existing badge routes to their urls.

**Comment by jyn514** [comment]
shields.io now supports docs.rs: https://img.shields.io/docsrs/regex/latest?style=flat-square

I think we should consider getting rid of the badges on docs.rs.
