### ISSUE TITLE
New

### ISSUE THREAD

**Issue by dusty1977** [rust-lang/docs.rs#1924]
*.py[cod] 
  
 test.db 
 test.txt 
 sina.html 
  
 # C extensions 
 *.so 
  
 # Packages 
 *.egg 
 *.egg-info 
 dist 
 build 
 eggs 
 parts 
 bin 
 var 
 sdist 
 develop-eggs 
 .installed.cfg 
 lib 
 lib64 
 __pycache__ 
  
 # Installer logs 
 pip-log.txt 
  
 # Unit test / coverage reports 
 .coverage 
 .tox 
 nosetests.xml 
  
 ###################### 
 # OS generated files # 
 ###################### 
 .DS_Store 
 .DS_Store? 
 ._* 
 .Spotlight-V100 
 .Trashes 
 Icon? 
 ehthumbs.db 
 Thumbs.db 
 dist 
 MANIFEST 
  
 # Translations 
 *.mo

**Comment by syphar** [comment]
I assume this was an accidentally created issue. Feel free to reopen when this wasn't the case.
