### ISSUE TITLE
Rstest failed to build due a nightly compiler bug

### ISSUE THREAD

**Issue by la10736** [rust-lang/docs.rs#1936]
### Crate name

rstest 

### Build failure link

https://docs.rs/crate/rstest/0.16.0/builds

### Additional details

This is due to a nightly compiler bug rust-lang/rust#104815

I've opened this issue just to link it to the compiler bug.

Can we run build again when the bug will be fixed?

**Comment by syphar** [comment]
Thank you for reporting this! 

Yes, when the nightly is fixed, released and on our build server (max a day later), we can totally requeue the build for your release.

I also subscribed to the issue, but if I miss it please just ping me here and I'll do it.

**Comment by la10736** [comment]
Should be fixed now.

**Comment by syphar** [comment]
I queued the rebuild. 

I'm also closing this issue, please don't hesitate to reopen if the rebuild doesn't fix it.

**Comment by la10736** [comment]
Sorry, but seams that something wrong on queuing rebuild.... https://docs.rs/crate/rstest/latest

**Comment by la10736** [comment]
THX!

Il giorno gio 1 dic 2022 alle ore 09:21 Denis Cornehl <
***@***.***> ha scritto:
