### ISSUE TITLE
Published version does not appear on docs.rs

### ISSUE THREAD

**Issue by zh217** [rust-lang/docs.rs#1941]
This is the published version on crates.io: https://crates.io/crates/cozo/0.2.1

It seems that docs.rs did not build docs for it: https://docs.rs/crate/cozo/latest/builds

Neither the queue nor the failures page has anything related to this version.

**Comment by zh217** [comment]
Looks like a similar issue to #1912

**Comment by syphar** [comment]
yeah, it's probably that issue. 

We merged a bigger fix around this just now: #1935, will be deployed soon. 
Until then I'll manually queue your build.

**Comment by zh217** [comment]
It's now in the queue, but it has a very low priority and hasn't really progressed after many hours. Doesn't look like it is going to complete in days.

Is this the expected behaviour?

**Comment by syphar** [comment]
> Is this the expected behaviour?

In short: no, it's not :) 

We currently have only limited build capacity, which is a problem especially when owners with many crates (like `swc_` and `azure_`, and some others) release many releases at once. Right now even worse, all the `swc_` crates were released **13 times**. 

We're working on this on multiple angles to fix this, but not nothing deployed yet. 

I increased the priority for your rebuild, should be done soon.

**Comment by zh217** [comment]
Thanks for the hard work!

The build disappears again. On further investigation, it seems the published crate is flawed due to a problem in a script on my side. But leaving no traces of any errors on docs.rs is a bit baffling.

I will publish a new version soon to see if the problem persists.

**Comment by syphar** [comment]
> The build disappears again. On further investigation, it seems the published crate is flawed due to a problem in a script on my side. But leaving no traces of any errors on docs.rs is a bit baffling.

what was the error in your crate? there are some error cases we need to fix: #1849 

> I will publish a new version soon to see if the problem persists.

it looks like the version was built now?

**Comment by zh217** [comment]
The new version was successfully built.

Basically the build script on my machine somehow got `--no-verify` added to it, and at the same time the crate specifies a dependency with an exact version that was incompatible with the version specification of an upstream crate. So version resolution fails. I guess this error occurred too early for docs.rs to pick up.

**Comment by syphar** [comment]
>  I guess this error occurred too early for docs.rs to pick up.

To be clear, it _should_ be shown, silently failing builds are confusing behaviour.
