### ISSUE TITLE
libvmaf-sys 0.2.2 build failing

### ISSUE THREAD

**Issue by ThatNerdUKnow** [rust-lang/docs.rs#1958]
### Crate name

libvmaf-sys

### Build failure link

https://docs.rs/crate/libvmaf-sys/0.2.2/builds/701631

### Additional details

My crate builds with the following dockerfile
```dockerfile
FROM ghcr.io/rust-lang/crates-build-env/linux:latest
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y
WORKDIR /app
COPY . .
RUN . $HOME/.cargo/env && cargo doc
```

I recently submitted a PR adding meson to `crates-build-env`:  https://github.com/rust-lang/crates-build-env/pull/117

My build script builds libvmaf from source via git submodule. This is done using the crate `meson-next` I made sure to include the submodule files in the crate

My repo: https://github.com/ThatNerdUKnow/libvmaf-sys

**Comment by syphar** [comment]
thank you for the report! 

I saw https://github.com/rust-lang/crates-build-env/pull/117 being merged, but didn't get to updating the image on the build-server (which is still manual ). 

I'm running the deploy now and will queue a rebuild for that release then

**Comment by syphar** [comment]
build is queued
