### ISSUE TITLE
Turn off -Zrustdoc-scrape-examples for proc macro crates

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/docs.rs#1965]
### Crate name

automod

### Build failure link

https://docs.rs/crate/automod/1.0.5/builds/703499

### Additional details

It would be extremely unusual for a proc macro crate's implementation to call its own macros. Until https://github.com/rust-lang/cargo/issues/11496 is fixed, or possibly even beyond that point, consider not passing `-Zrustdoc-scrape-examples` when the crate being documented is a proc macro.

**Comment by willcrichton** [comment]
This issue will be fixed in rust-lang/cargo#11497.

I would prefer to keep this flag on for all crates rather than special-casing it, since the goal is eventually to have it be a default code pathway within Rustdoc, and it should be robust enough to handle these cases.
