### ISSUE TITLE
No docs change / build started failing out of the blue / Works on my machine

### ISSUE THREAD

**Issue by zertyz** [rust-lang/docs.rs#1974]
### Crate name

big-o-test

### Build failure link

https://docs.rs/crate/big-o-test/0.2.5/builds

### Additional details

Hello, friends.

I just published a minor update to my crate -- with README.md changes and some minor wording improvements in the crates strings -- no changes at all to documentations.

The previous build worked all right, but this new one failed -- it says "error[E0432]: unresolved import `serial_test`".

Maybe it is a nightly thing? Or some newly added command line options (to rustdoc) are breaking the build...

On my machine (I use the stable Rust):
````
[luiz@GarudaTech big-O]$ rustc -V
rustc 1.66.0 (69f9c33d7 2022-12-12)
[luiz@GarudaTech big-O]$ cargo rustdoc
(...)
warning: `big-o-test` (lib doc) generated 17 warnings
    Finished dev [unoptimized + debuginfo] target(s) in 1.60s
````

Would it be possible to try to build the docs again in a few days (without having to publish a new crate's version)?
How could this be done?

-- update --
I mimicked all command-line options used by `docs.rs`, but removed the ones not accepted by the stable Rust:
````
cargo rustdoc --lib --all-features --config build.rustdocflags='["--cap-lints", "warn"]' --offline -j3 --target x86_64-unknown-linux-gnu
````

... and could reproduce the issue.

`--all-features` is breaking me here. I'll now check the documentations and see if I should fix anything on my side...

-- update 2 --

It seems using this old "dox" trick for including "unit tests documentation" is no longer needed -- https://stackoverflow.com/questions/58082156/is-there-some-way-to-build-rust-documentation-that-includes-the-test-documentati

Anyway, enabling a feature should not cause rustdoc to disregard all `dev-dependencies` when generating the documentation (this is why it fails)...

Anyway, I'm closing this and will update my projects

**Comment by Nemo157** [comment]
The reason that `--all-features` is now passed is the change to `Cargo.toml`:

```diff
--- big-o-test-0.2.4/Cargo.toml
+++ big-o-test-0.2.5/Cargo.toml
+
+[package.metadata.docs.rs]
+all-features = true
+rustdoc-args = [
+    "--cfg",
+    "dox",
+]
```

`dev-dependencies` have never been available for doc builds, you would have to instead have them as optional normal dependencies that get activated with the `dox` feature too.
