### ISSUE TITLE
Use nightly rustc?

### ISSUE THREAD

**Issue by sunchao** [rust-lang/docs.rs#198]
In the README it says this will use nightly rust compiler, but [mine](https://docs.rs/crate/parquet/0.2.0/builds/97194) was compiled with a dev version. Anyway to ask docs.rs to use nightly?

**Comment by cipriancraciun** [comment]
I have the same issue for [vonuvoli-scheme](https://docs.rs/crate/vonuvoli-scheme/0.0.5/builds/102280) where various dependent crates fail to compile due to `rustc` tool-chain being too old.

**Comment by sadikovi** [comment]
@cipriancraciun you can have a look at how we have set up building and publishing docs on Travis instead of docs.rs as an alternative in [parquet-rs](https://github.com/sunchao/parquet-rs) repository.

**Comment by QuietMisdreavus** [comment]
Update: Docs.rs has been using a manually-updated nightly for a few months now. If your crate is failing to build, please post in https://github.com/rust-lang/docs.rs/issues/23.
