### ISSUE TITLE
Broken settings on crossbeam-0.8.2

### ISSUE THREAD

**Issue by namibj** [rust-lang/docs.rs#1992]
`crossbeam::channel` settings are broken. https://docs.rs/crossbeam/0.8.2/crossbeam/channel/index.html

Reproduce:
> click on https://docs.rs/crossbeam/0.8.2/crossbeam/channel/index.html,
> then click on the settings wheel right of the rustdoc search bar;
> observe infinite spinning.

In Chromium Devtools I can reproduce a 404 from it attempting to load `https://docs.rs/crossbeam/0.8.2/settings-20220722-1.64.0-nightly-848090dcd.js`.

**Comment by syphar** [comment]
Thank you for the report!

I believe this is a regression from a big internal migration, see also #1979. 

I added the filename to our workaround, see #1993.

**Comment by syphar** [comment]
the fix is deployed now
