### ISSUE TITLE
https://docs.rs/libtest-mimic/latest/libtest_mimic/ shows up broken for me, but OK for maintainer (Broken CDN?)

### ISSUE THREAD

**Issue by DanielJoyce** [rust-lang/docs.rs#2005]
Permalink Version ( Also borked ): https://docs.rs/libtest-mimic/0.6.0/libtest_mimic/index.html

More context here:

https://github.com/LukasKalbertodt/libtest-mimic/issues/22

I tried filing a ticket, but the maintainer says everything looks okay on his end. I've tried multiple browser, devices, clearing the cache, etc. I live in WA state on the west coast ( in case docs.rs has regional servers/cdn ). I am not using any vpn, I've tried wifi and 5g. Android phone, and Chrome and Firefox on Linux. 

For me, this file results in a 404:

https://docs.rs/-/rustdoc.static/normalize-20221104-1.67.0-nightly-09508489e.css

**Comment by DanielJoyce** [comment]
Asked coworkers to look at the url, and so far it appears broken for those who live in:

* AZ
* CA
* TX

**Comment by DanielJoyce** [comment]
a request fails with the following response

```
Request URL: https://docs.rs/-/rustdoc.static/normalize-20221104-1.67.0-nightly-09508489e.css
Request Method: GET
Status Code: 404 
Remote Address: 65.8.66.4:443
Referrer Policy: strict-origin-when-cross-origin
alt-svc: h3=":443"; ma=86400
cache-control: max-age=0
content-encoding: gzip
content-security-policy: default-src 'none'; base-uri 'none'; img-src 'self' https:; style-src 'self'; font-src 'self'; script-src 'nonce-19Po/gjqVR8OO+mWT8K9qVnQ3Br9IS05vUXqxJhtTRJlvXoP'
content-type: text/html; charset=utf-8
date: Thu, 19 Jan 2023 03:07:43 GMT
server: nginx/1.14.0 (Ubuntu)
vary: Accept-Encoding
via: 1.1 71e7943ea0729c284a06faa05a567236.cloudfront.net (CloudFront)
x-amz-cf-id: kEQEUheUsZM3fG6c9_Ut1vB7tUx04xkI_HGZhabkktayTRMK2Xkcrw==
x-amz-cf-pop: YVR50-C1
x-cache: Error from cloudfront
:authority: docs.rs
:method: GET
:path: /-/rustdoc.static/normalize-20221104-1.67.0-nightly-09508489e.css
:scheme: https
accept: text/css,*/*;q=0.1
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9
dnt: 1
referer: https://docs.rs/libtest-mimic/latest/libtest_mimic/
sec-ch-ua: "Not?A_Brand";v="8", "Chromium";v="108", "Google Chrome";v="108"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Linux"
sec-fetch-dest: style
sec-fetch-mode: no-cors
sec-fetch-site: same-origin
user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
```

**Comment by syphar** [comment]
Hi @DanielJoyce , 

this is an issue on our side, see also [this thread on zulip](https://rust-lang.zulipchat.com/#narrow/stream/356853-t-docs-rs/topic/bytemuck.20doc.20failing). 

I queued a rebuild, which will fix the issue for this specific release

**Comment by DanielJoyce** [comment]
Okay I'll check this again tomorrow and see if it's fixed. It is still broken for me right now but I don't know how long a rebuild will take.

Also odd that it only seemed to affect some people.

**Comment by syphar** [comment]
> Okay I'll check this again tomorrow and see if it's fixed. It is still broken for me right now but I don't know how long a rebuild will take.

the queue is relatively full currently, so it can take a day or so: https://docs.rs/releases/queue 

> Also odd that it only seemed to affect some people.

this is related to an internal rustdoc / docs.rs change, combined with a webserver migration, so it affects all releases build on a certain day.

**Comment by msrd0** [comment]
@syphar The docs are still broken for me. These two urls fail to load with a 404:

 - https://docs.rs/-/rustdoc.static/storage-20221104-1.67.0-nightly-09508489e.js
 - https://docs.rs/-/rustdoc.static/light-20221104-1.67.0-nightly-09508489e.css

The CSS on the site is only partially loaded, and most javascript functionality like the search is not working at all.

**Comment by syphar** [comment]
thank you for fixing this!
