### ISSUE TITLE
Docker container environment failure (Re-run requested)

### ISSUE THREAD

**Issue by ngundotra** [rust-lang/docs.rs#2007]
### Crate name

spl-account-compression

### Build failure link

https://docs.rs/crate/spl-account-compression/0.1.8/builds/724602

### Additional details

Looks like docker applying some filter that broke the docs.rs process.

Running `cargo doc --open` works fine locally with this crate's latest version & previous docs for previous build worked fine.

**Comment by syphar** [comment]
We don't apply any filter on the source code. 

Seeing the error (missing files in `bytemuck`) and the used `bytemuck` version (1.12.4, which is **yanked**), I'm guessing that this is a problem with that specific bytemuck version. 

I queued a rebuild so the fixed version can be picked up.
