### ISSUE TITLE
Do not show pre-release versions by default

### ISSUE THREAD

**Issue by dhardy** [rust-lang/docs.rs#201]
E.g. going to https://docs.rs/crate/rand/ currently shows the doc for 0.5.0-pre.1, which is a pre-release (unstable and not widely used). It would be more helpful to show the doc for the last stable release by default; currently this is https://docs.rs/crate/rand/0.4.2

**Comment by jyn514** [comment]
Duplicate of https://github.com/rust-lang/docs.rs/issues/223
