### ISSUE TITLE
Building tensorflow-sys causes failure to run custom build script in sandbox

### ISSUE THREAD

**Issue by Corallus-Caninus** [rust-lang/docs.rs#2016]
### Crate name

Brains

### Build failure link

https://docs.rs/crate/Brains/0.2.0/builds/727641

### Additional details

I believe I can request more resources but am unsure if this is what causes the failure. I can build the tensorflow-sys dependency on my local machine so I suspect it is in the custom Build script (which fetches and unpacks binaries) or a resource timeout (memory). I am willing to build my documentation locally and publish but cannot find any documentation on how to do so. Is the constrained build environment the only way to upload to docs.rs?

**Comment by syphar** [comment]
There is currently no way for you to push your self-built documentation to docs.rs (see also #93 )

In general the build doesn't have any access to the network, which means you also can't download any binaries in your build-script. See also https://docs.rs/about/builds. 

Looking at `tensorflow-sys` you can also see an example how to make the docs still build: 
https://github.com/tensorflow/rust/blob/3f3f618678ffb42677366ee820d34b3772f18281/tensorflow-sys/Cargo.toml#L17-L19
