### ISSUE TITLE
Open External Links in new Tabs

### ISSUE THREAD

**Issue by SajeevanJSPY** [rust-lang/docs.rs#2020]
When we click external links like github.com, and crates.io, creating a new tab is good
# Example
```
<a href="github.com/*" target="_blank">GITHUB Link</a>
```

**Comment by syphar** [comment]
Hi, 

could you elaborate more which exact links you mean? Do you have an example?

**Comment by SajeevanJSPY** [comment]
When we click up an external link (from other domains) opens a new tab instead of the current tab.
![extern links](https://user-images.githubusercontent.com/108508613/216824857-addfdd1d-188d-4b0e-b3d4-7dc766c487c5.png)

**Comment by syphar** [comment]
I see that I never answered here, sorry about that. 

These specific links you provided here are coming from the readme of the syn-crate, which means they would need to be changed in there. 

There are probably places in the generated rustdoc pages with external links, these would need to be changed there. 

But, we _do_ have other links where docs.rs actually links to crates.io or github (in the dropdown menu for example), where I could imagine the a change to `target=_blank` would improve the user experience.

**Comment by linyihai** [comment]
@syphar I could take over this issue if wanted :)
