### ISSUE TITLE
Please rebuild crates depending on rlottie

### ISSUE THREAD

**Issue by msrd0** [rust-lang/docs.rs#2028]
### Crate name

rlottie, rlottie-sys, lottieconv, mstickerlib

### Build failure link

https://docs.rs/crate/rlottie-sys/0.2.4/builds/651006

### Additional details

These crates were previously unable to build as the system library rlottie wasn't installed. The library is now available (https://github.com/rust-lang/crates-build-env/pull/124#issuecomment-1416685736), so they should compile now.

**Comment by Nemo157** [comment]
A rebuild for all 4 have been queued.

**Comment by syphar** [comment]
😆

**Comment by syphar** [comment]
I just did the same

**Comment by msrd0** [comment]
Thanks
