### ISSUE TITLE
Sandbox limits increase request for `icrate`

### ISSUE THREAD

**Issue by madsmtm** [rust-lang/docs.rs#2032]
### Crate name

`icrate`

### Build failure link

https://docs.rs/crate/icrate/0.0.2/builds/738837

### Requested RAM limit

6GB

### Requested timeout

N/A

### Requested number of targets

N/A

### Why your crate needs the resource increases

`icrate` contains automatically generated code for many of Apple's libraries/frameworks (the Apple-equivalent to `windows-sys`), and so takes a lot of RAM to build (in practice, each framework is feature-gated, users wouldn't actually enable all the frameworks at once).

In a local build on macOS I saw the RAM usage go up to about 4.3GB, but I suspect that as the number of frameworks I want to support goes up, so will this number - hence the request for 6GB for now.

Thanks for running `docs.rs`, it is a _very_ useful service!

**Comment by syphar** [comment]
I just increased the limit and queued a rebuild
