### ISSUE TITLE
Failed to build docs for cv-bridge v0.3.0

### ISSUE THREAD

**Issue by OmkarKabadagi5823** [rust-lang/docs.rs#2036]
### Crate name

cv-bridge

### Build failure link

https://docs.rs/crate/cv-bridge/latest

**Comment by syphar** [comment]
The error message from the logs says: 
```
[INFO] [stderr]   Error: Os { code: 30, kind: ReadOnlyFilesystem, message: "Read-only file system" }
```

From [documentation](https://docs.rs/about/builds#read-only-directories):

> Most of the sandbox is a read-only file system, including the source directory of your crate and its dependencies. If your build.rs generates files that are relevant for documentation, consider writing to the cargo output directory, passed in the environment variable OUT_DIR.


For hints how to solve this you can also check how other crates with C bindings do this, for example [the OpenCV one](https://crates.io/crates/opencv)?

I'll close this issue, feel free to reopen if this doesn't solve the problem.
