### ISSUE TITLE
efm32gg11b-pac memory limit leads to build failure

### ISSUE THREAD

**Issue by vpetrigo** [rust-lang/docs.rs#2044]
### Crate name

efm32gg11b-pac

### Build failure link

https://docs.rs/crate/efm32gg11b-pac/0.1.2/builds

### Requested RAM limit

4 Gb

### Why your crate needs the resource increases

Locally `doc` build passed just fine:

```bash
$ cargo doc --features="rt,efm32gg11b110,efm32gg11b840" --target=thumbv7em-none-eabihf --open
# ...
 Documenting efm32gg11b-pac v0.1.2 (/home/vpetrigo/projects/rust/efm32-rs/efm32gg-pacs/pacs/efm32gg11b)
    Finished dev [unoptimized + debuginfo] target(s) in 3m 11s
     Opening /home/vpetrigo/projects/rust/efm32-rs/efm32gg-pacs/pacs/efm32gg11b/target/thumbv7em-none-eabihf/doc/efm32gg11b_pac/index.html
```

RAM consumption should be ~3.5 Gb according to my system measurements

**Comment by syphar** [comment]
I set the limit for this crate to 4 GB, and queued a rebuild for this release.
