### ISSUE TITLE
Rebuild request for `icu_datagen`

### ISSUE THREAD

**Issue by robertbastian** [rust-lang/docs.rs#2047]
### Crate name

icu_datagen

### Build failure link

https://docs.rs/crate/icu_datagen/1.1.1/builds/733463

### Additional details

We have fixed a bug in a dependency and the crate now builds at 1.1.1.

**Comment by Nemo157** [comment]
[Queued](https://docs.rs/releases/queue) a rebuild, but it'll be a while as the queue is quite full.
