### ISSUE TITLE
Optional dependencies that use the `dep:` syntax are listed as features

### ISSUE THREAD

**Issue by robertbastian** [rust-lang/docs.rs#2048]
For example: https://docs.rs/crate/icu_datagen/1.1.0/features

`simple_logger`, `eyre`, and `clap` are not features, because they are referenced by the `bin` feature using the `dep:` syntax. Any attempt to use them will result in a Cargo error. These should not be listed as features.

**Comment by Nemo157** [comment]
Oh nice, `cargo metadata` now normalizes optional-dependencies-as-features for us:

```console
> cargo new foo && cd foo
     Created binary (application) `foo` package
> cargo add serde --optional
    Updating crates.io index
      Adding serde v1.0.152 to optional dependencies.
             Features:
             + std
             - alloc
             - derive
             - rc
             - serde_derive
             - unstable
# it shows a feature for the implicit optional dependency feature
> cargo metadata --format-version 1 | jq -r '.packages[] | select(.name == "foo") | .features'
{
  "serde": [
    "dep:serde"
  ]
}
# when `dep:` is used it stops showing the implicit feature and only shows the explicit one
> echo '[features]\nserde2 = ["dep:serde"]' >> Cargo.toml
> cargo metadata --format-version 1 | jq -r '.packages[] | select(.name == "foo") | .features'
{
  "serde2": [
    "dep:serde"
  ]
}
```

We are already parsing the `cargo metadata` output, we just need to stop manually including optional dependencies (older cargo from before `dep:` was stabilized didn't do this normalization for us).

**Comment by robertbastian** [comment]
Could the database be cleaned up to fix existing crates?

**Comment by Nemo157** [comment]
If we do a rebuild for a release this data will be updated IIRC. Once it's deployed I will queue a rebuild for `icu_datagen 1.1.*`. (Feel free to mention if there are other crates that also need it).

**Comment by robertbastian** [comment]
We do in fact have a few more...
```
databake
icu_calendar
icu_capi
icu_casemapping
icu_collator
icu_collections
icu_compactdecimal
icu_datagen
icu_datetime
icu_decimal
icu_displaynames
icu_list
icu_locid
icu_locid_transform
icu_normalizer
icu_plurals
icu_properties
icu_provider
icu_provider_adapters
icu_provider_fs
icu_relativetime
icu_segmenter
icu_testdata
icu_timezone
yoke
zerofrom
zerovec
```

**Comment by syphar** [comment]
@Nemo157 I just deployed the change.

**Comment by syphar** [comment]
apart from rebuilding I could imagine there is a pure SQL way of fixing this, right? Or am I missing something?

**Comment by syphar** [comment]
( I'm happy to dig into it if that's the case)

**Comment by Nemo157** [comment]
Nope, we don't have enough build capacity to rebuild everything on every release. I think there should be a way to do this via sql, I'll try to come up with a script.

**Comment by Nemo157** [comment]
I didn't manage to come up with a sql script, but it looks like all the listed crates have had new releases themselves so the latest versions should be correct.
