### ISSUE TITLE
Rebuild request for `icu_testdata`

### ISSUE THREAD

**Issue by robertbastian** [rust-lang/docs.rs#2052]
### Crate name

icu_testdata

### Build failure link

https://docs.rs/crate/icu_testdata/1.1.1/builds/733462

### Additional details

We have fixed a bug in a dependency and the crate now builds at 1.1.1.

**Comment by syphar** [comment]
I gueued a rebuild, see [here](https://docs.rs/releases/queue). 

Just a general throught: 
when your package only works starting with a minimum version of a dependency, your `Cargo.toml` should reflect this.

**Comment by robertbastian** [comment]
Yeah there was an issue with a maximum version of a transitive dependency that didn't get caught.
