### ISSUE TITLE
`bevy_ui_bits` got a bad prioritization for its name

### ISSUE THREAD

**Issue by septum** [rust-lang/docs.rs#2054]
From what I gather in web discussions, crates with multiple inner dependencies with the main name prefixed are done in batches. So what I think is happening is that a new crate that I released (https://crates.io/crates/bevy_ui_bits) is waiting on more `bevy_` crates to start the batch. Can something be done about it?

Sorry if I may be incorrect about this assumption, feel free to close this issue if that's the case.

**Comment by syphar** [comment]
sorry for the delay. 

In general we have a deprioritzation logic, which, as you stated, uses simple string patterns to reduce priority for some crates that are often published in bulk. There are cases like yours where this logic also catches crates by other publishers in the same ecosystem.

Manually tweaking the priority of a single job is possible, but would have to happen each time. 


Better prioritization is possible, I found open issues in #1532 and #301, though I might have missed some. 

We're currently focusing on increasing build capacity with infra, and some build artifact caching first (#1757).

**Comment by septum** [comment]
Thank you for the response, I can understand the delay completely. 

Great, I'm glad to know the correct problem definition. I'll try to contribute to those listed issues.

I saw that the documentation for `bevy_ui_bits` is now online. Thanks again.
