### ISSUE TITLE
Feature request: support for building unreleased crates

### ISSUE THREAD

**Issue by pkgw** [rust-lang/docs.rs#206]
Some crates with system dependencies are a bit tricky to get their docs building in the docs.rs system. In several cases, I've needed to publish a series of "new" releases to crates.io to trigger new docs.rs builds to try to fix various problems with my docs.rs builds. This isn't the end of the world, but it's not great to have to cut new releases just to iterate on these problems.

This is the case even if you spin up your own docs.rs Vagrant image, since the underlying command still will only fetch crates from crates.io.

It would be great if `cratesfyi` could pick up a subcommand that would attempt a build on a crate stored 
locally. Something like

```
cargo run -- build local-crate /path/to/source
```

This would make it possible to iterate locally instead having to publish a new release for every attempted change.

**Comment by jyn514** [comment]
This was implemented in #460.

**Comment by pkgw** [comment]
Awesome, thanks!
