### ISSUE TITLE
docs.rs failed to build ssg-0.0.4

### ISSUE THREAD

**Issue by sebastienrousseau** [rust-lang/docs.rs#2082]
### Crate name

ssg

### Build failure link

https://docs.rs/crate/ssg/latest

**Comment by Nemo157** [comment]
From [the build log](https://docs.rs/crate/ssg/0.0.4/builds/767537) it looks like https://github.com/rust-lang/rust/issues/109209, which should be fixed in tomorrow's nightly release, we can queue a new build then.

**Comment by sebastienrousseau** [comment]
@Nemo157 Thanks this has been resolved 😃
