### ISSUE TITLE
Big types make compiler unhappy

### ISSUE THREAD

**Issue by FlixCoder** [rust-lang/docs.rs#2086]
### Crate name

fhir-sdk (/fhir-model)

### Build failure link

https://docs.rs/crate/fhir-sdk/0.1.0/builds

### Why your crate needs the resource increases

The crate makes heavy usage of TypedBuilder for many big types.

**Comment by syphar** [comment]
@FlixCoder could you elaborate what you are requesting? 

When you look at [our limits-description](https://docs.rs/about/builds#hitting-resource-limits), we can totally increase the RAM limit or the timeout, if that is what's needed. 

#2044 would be an example of a request for an increased RAM limit.

**Comment by FlixCoder** [comment]
Sorry, I was not sure what was necessary and suspected time, but I got to test it and it needs 8 GB of RAM (oof 🤐).

It feels weird that bare structs and types need that much time and resources. Maybe it is the plenty generics due to the TypedBuilder, but oof.

**Comment by syphar** [comment]
@FlixCoder no worries.

**Comment by syphar** [comment]
> It feels weird that bare structs and types need that much time and resources. Maybe it is the plenty generics due to the TypedBuilder, but oof. 

They typically don't, and `TypedBuilder` doesn't normally lead to this kind of memory usage. 

Having a short look at what FHIR is I could imagine that the issue is only partially your usage of typed-builder, but the amount of types that you have to generate. 

I increased the limit for both crates.

**Comment by syphar** [comment]
Also I queued a rebuild for both releases, though rebuilds are at the end of the queue priority.

**Comment by FlixCoder** [comment]
Alright, thanks!

**Comment by FlixCoder** [comment]
Hmm I am unsure why, but I think it still fails..

**Comment by syphar** [comment]
I see both builds still queued : 

https://docs.rs/releases/queue

**Comment by syphar** [comment]
A new build try would appear as separate build in the crate page you linked
