### ISSUE TITLE
build docs are fine but docs.rs are failing

### ISSUE THREAD

**Issue by patrickelectric** [rust-lang/docs.rs#2096]
### Crate name

rust-mavlink

### Build failure link

https://docs.rs/crate/mavlink/0.11.1/builds/781210

### Additional details

https://docs.rs/crate/mavlink/0.11.1
![image](https://user-images.githubusercontent.com/1215497/230659139-61d00e64-fa9a-4d73-ad47-fd290f8f399f.png)
![image](https://user-images.githubusercontent.com/1215497/230659432-ee540567-7553-49ec-8fe0-c8828d45bb27.png)

**Comment by syphar** [comment]
`SIGKILL` is mostly a sign for hitting resource limits, often memory. 

Could you check with a local build if you are hitting one of [our defined limits](https://docs.rs/about/builds#hitting-resource-limits)?

**Comment by patrickelectric** [comment]
@syphar thanks for informing, I did test and here it's using indeed almost 4GB of ram, but the build process is quick. 
Is it possible to provide more resource to for our crate ? Are there alternatives to how to fix it ? Maybe we building and providing the documentation to docs.rs ourselfs ? I'm right now publishing it via github pages: https://mavlink.github.io/rust-mavlink/mavlink/

**Comment by syphar** [comment]
4 GB isn't an issue, we probably can increase the limit for this crate to 5 GB, just to be safe. 

I'm travelling this weekend so I can't do it right now, I'll look into this when I'm back.

**Comment by syphar** [comment]
I increased the limit to  5GB and queued a rebuild for the most recent version of this crate, see https://docs.rs/releases/queue . 

Feel free to reopen this issue when the problem persists.

**Comment by patrickelectric** [comment]
Thank you very much @syphar! It's working!
