### ISSUE TITLE
proptest docs missing decl macros in latest release

### ISSUE THREAD

**Issue by tzemanovic** [rust-lang/docs.rs#2105]
Hello, the latest release of proptest crate seems to be missing declarative macros. See:

- https://docs.rs/proptest/1.1.0/proptest/index.html - missing macros section
- https://docs.rs/proptest/1.0.0/proptest/index.html

And e.g.:

- https://docs.rs/proptest/1.1.0/proptest/macro.prop_assert.html - 404
- https://docs.rs/proptest/1.0.0/proptest/macro.prop_assert.html

When I try to build the docs locally for v1.1.0 I cannot reproduce the issue. Is there a specific set of flags that docs.rs is using to build the docs that may reproduce it? The crate doesn't have any `[package.metadata.docs.rs]` set atm.

**Comment by Nemo157** [comment]
You can see the exact invocation and version used in the build logs <https://docs.rs/crate/proptest/1.1.0/builds/737523>. I can reproduce when using that old nightly version so I guess it was a rustdoc bug, I've [queued](https://docs.rs/releases/queue) a new build to fix it.

**Comment by Nemo157** [comment]
And it's done and appears fixed.
