### ISSUE TITLE
Theme: Option to prefer system UI theme in theme selector

### ISSUE THREAD

**Issue by prophet1996** [rust-lang/docs.rs#2108]

**Comment by jyn514** [comment]
Don't we already support this?
![image](https://user-images.githubusercontent.com/23638587/235572533-a698549e-c3f7-4374-876d-f73c2fd5aa07.png)

**Comment by jyn514** [comment]
Ok, I'm going to close this as a duplicate of https://github.com/rust-lang/docs.rs/issues/464 then
