### ISSUE TITLE
Frontend bug when opening display settings on crate page

### ISSUE THREAD

**Issue by feldroop** [rust-lang/docs.rs#2114]
When clicking on the settings icon next to the search bar, a settings menu opens. This menu does not seem quite right to me. 
The first checkbox ("Use system theme") works, all other settings don't. Instead, the broken settings window just closes. 

I tried this on Google Chrome version 112.0.5615.121 (Official Build) (64-Bit) and Firefox version 111.0.1 (64-Bit). Both should be auto-updated, most recent versions. The problem looked equivalent on both of these browsers.

![DocsRsBug](https://user-images.githubusercontent.com/62176388/232487691-1bd49c90-01f3-4023-955b-6b810816afc0.JPG)

**Comment by feldroop** [comment]
I did some more exploration and found out that this menu window looks very different for different crates. I found at least 4 different versions. One very nice one, two working but not as nice ones, and this broken one.

**Comment by syphar** [comment]
hi, 
thank you for reporting this! 

The difference in menus is coming from the fact that docs.rs will build each release with the current nightly version, and not rebuild any old release. 

Checking some of them, other releases built with the same nightly (`2022-05-29`) are broken too. 

I queued rebuilds for the affected releases when they are still the latest version (`parking_lot` among them), see https://docs.rs/releases/queue

**Comment by syphar** [comment]
rebuilding old crates is tracked in #464 , and currently blocked on build capacity and more caching

**Comment by feldroop** [comment]
Hey, the rebuild seems to be done, but the bug is still there.

**Comment by syphar** [comment]
this is odd, checking

**Comment by syphar** [comment]
strange, it seems like the rebuild for this specific crate wasn't queued, will dig deeper, but this issue here is solved now. 

https://docs.rs/parking_lot/latest/parking_lot/
