### ISSUE TITLE
API filter option for docs.rs

### ISSUE THREAD

**Issue by artech-git** [rust-lang/docs.rs#2115]
There are multiple APIs present under standard library and other crates listed under crates.io, having a filtering feature to segregate nightly APIs would be very helpful where there huge number of APIs present

**Comment by syphar** [comment]
Hi @artech-git, thank you for this idea! 

Could you help me understand more about what you are trying to achieve? 

Are you talking about standard-library docs? Or crate documentation? 

And for the filter-feature, do you mean in normal module lists or in the search? 

In general it is likely that this is actual an issue for rustdoc or the stdlib-docs, not for docs.rs, which is "just" hosting the docs generated by rustdoc. 

I also remember seeing a rustdoc issue about rendering nightly-only apis differently in search-results? ( cc @GuillaumeGomez )

**Comment by artech-git** [comment]
Well I was referring to this feature in general if it can be made available for both std docs and crates docs as well 

for the filter feature maybe we can have a label button under the interface, or perhaps what will be more powerful is to embed this feature directly in the search bar where we can filter the APIs using some prefix

**Comment by GuillaumeGomez** [comment]
I don't remember such a feature request. If the issue doesn't already exist, can you open one on the `rust-lang/rust` repository please?

**Comment by artech-git** [comment]
with pleasure 😊


> I don't remember such a feature request. If the issue doesn't already exist, can you open one on the `rust-lang/rust` repository please?

**Comment by syphar** [comment]
it would be awesome if you could link the rustdoc issue after it's created, then we can close this one. 

Thanks!
