### ISSUE TITLE
Search in top bar does not search crate documentation

### ISSUE THREAD

**Issue by alper** [rust-lang/docs.rs#2118]
I'm looking at the documentation for a crate and trying to find a specific function.

I type the name in the search bar on the top.

This gives me a list of crates.

Is there a way to scope the search to the crate at hand? If not there should be.

**Comment by syphar** [comment]
![image](https://user-images.githubusercontent.com/540890/233822662-601a9960-bc91-4513-bb2d-0aaef723482f.jpeg)

Hi, 

could you help me finding the search-field that doesn't work for you? 

For me, the "find crate" one finds crates, 
and the big one ("click or press S for search") searches inside the crate documentation.

**Comment by alper** [comment]
In my particular instance the "Find crate" was not displayed and the big search field was not visible.

So I confused the two as being "Search".
