### ISSUE TITLE
yew's doc build failed for missing PATH_SEPARATOR

### ISSUE THREAD

**Issue by huangjj27** [rust-lang/docs.rs#212]
Hi, I'm reporting [an issue about yew's online doc](https://github.com/DenisKolodin/yew/issues/241), which [log missing `PATH_SEPARATOR`](https://docs.rs/crate/yew/0.4.0/builds/103459):

```
Running `rustc --crate-name stdweb .cargo/registry/src/github.com-1ecc6299db9ec823/stdweb-0.4.6/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 --cfg 'feature="serde"' --cfg 'feature="default"' --cfg 'feature="serde_json"' -C metadata=41cb9810bf802137 -C extra-filename=-41cb9810bf802137 --out-dir /home/cratesfyi/cratesfyi/debug/deps -L dependency=/home/cratesfyi/cratesfyi/debug/deps --extern stdweb_derive=/home/cratesfyi/cratesfyi/debug/deps/libstdweb_derive-400531424ce6e256.so --extern-version stdweb_derive=stdweb-derive,0.4.0 --extern discard=/home/cratesfyi/cratesfyi/debug/deps/libdiscard-15517d8fed0389d8.rlib --extern-version discard=discard,1.0.3 --extern serde=/home/cratesfyi/cratesfyi/debug/deps/libserde-b1418846d651137e.rlib --extern-version serde=serde,1.0.66 --extern serde_json=/home/cratesfyi/cratesfyi/debug/deps/libserde_json-84d1f2e442610577.rlib --extern-version serde_json=serde_json,1.0.19 --cap-lints allow`
error: environment variable `PATH_SEPARATOR` not defined
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/stdweb-0.4.6/src/webcore/initialization.rs:20:43
   |
20 |     include!( concat!( env!( "OUT_DIR" ), env!( "PATH_SEPARATOR" ), "runtime.rs" ) );
   |                                           ^^^^^^^^^^^^^^^^^^^^^^^^
```

~~but when I check [the `stdweb v0.4.6`'s document](https://docs.rs/stdweb/0.4.6/stdweb/). it seems everything works well. Did I miss something?~~

I believe that it is the unconfigured environment variable in the docs.rs server that causes such this problem. What can we walk around this problem?

tracing in #23

**Comment by daboross** [comment]
I'm also seeing fail builds with this (https://docs.rs/crate/screeps-game-api/0.1.1/builds/115642), but I don't think it's a missing environment variable. `stdweb` should be defining the variable here: https://github.com/koute/stdweb/blob/ee32b7685cfe6439f87e0087eab6cc18321bf25f/stdweb-internal-runtime/build.rs#L45. I don't have `PATH_SEPARATOR` defined on my local machine, and docs build just fine.

Maybe there's something going wrong with build scripts and rustdoc environment variables in the version of rustc docs.rs is using?

**Comment by jyn514** [comment]
`yew`'s documentation has built successfully for several years in a row now, so I'm going to assume this problem was resolved. If you're still having trouble just comment and I'll re-open :)
