### ISSUE TITLE
Kayak UI - The platform you're compiling for is not supported by winit

### ISSUE THREAD

**Issue by StarArawn** [rust-lang/docs.rs#2120]
### Crate name

kayak_ui

### Build failure link

https://docs.rs/crate/kayak_ui/0.3.0/builds/793822

### Additional details

I haven't really done anything to cause this and bevy itself compiles fine:
https://docs.rs/crate/bevy/0.10.1/builds/780778

There are other crates outside of mine that have the same issue:
https://docs.rs/crate/bevy_vector_shapes/0.1.3/builds/801211

**Comment by syphar** [comment]
bevy itself sets the `x11` feature for the docs.rs build: 

https://github.com/bevyengine/bevy/blob/670f3f0dce2ced27388b10672d30594d399434e1/crates/bevy_winit/Cargo.toml#L44-L45

which then sets the `x11` feature on `winit`. 

The docs.rs metadata of depedencies currently isn't used for the crate that is built, so you likely have to do something similar to prevent `winit` try building windows.

**Comment by StarArawn** [comment]
> bevy itself sets the `x11` feature for the docs.rs build:
> 
> https://github.com/bevyengine/bevy/blob/670f3f0dce2ced27388b10672d30594d399434e1/crates/bevy_winit/Cargo.toml#L44-L45
> 
> which then sets the `x11` feature on `winit`.
> 
> The docs.rs metadata of depedencies currently isn't used for the crate that is built, so you likely have to do something similar to prevent `winit` try building windows.

Thank you! This makes sense. I'll close the issue now. 👍
