### ISSUE TITLE
Links to lastest are broken, if latest doesn't build

### ISSUE THREAD

**Issue by darklajid** [rust-lang/docs.rs#2124]
At the point of this writing, aide's latest version is broken on docs.rs

aide does link to the docs in their README using https://docs.rs/aide/latest/aide/

That leads to a "The requested resource does not exist" response and no way to navigate anywhere. Basically it gives the impression that the aide link is broken and docs.rs doesn't offer any "Hey, wanna check out a different version?" option either. It's a bad experience.

Manually going to https://docs.rs/crate/aide/ which redirects to https://docs.rs/crate/aide/latest I get

> docs.rs failed to build aide-0.11.0
> Please check the [build logs](https://docs.rs/crate/aide/0.11.0/builds) for more information.

and an option to look at the last version that built correctly instead (which is 0.10.0).

Selecting the last working version and clicking on documentation leads me to https://docs.rs/aide/0.10.0/aide/ i.e. the same link as used in their README with "latest" replaced with "0.10.0" and I can browse the documentation.

Inventing a version that doesn't exist - say https://docs.rs/aide/0.12.0/aide/ at the time of this writing - leads to the same experience as "latest" and gives me a page that is very unhelpful.

I'm still reasonably new to the Rust ecosystem, but at this point I believe that

* aide links to the "right" thing ("The most recent documentation")
* docs.rs is taking this a LITTLE to seriously (I'd argue that "The most recent documentation" is the latest that is .. actually available, not released but unable to build)
* docs.rs has a rather sad "Sorry, no idea what you want" experience when you try to access a version that doesn't exist. A "but we have the following versions to look at instead" drop-down would make improve this tremendously

**Comment by syphar** [comment]
sorry for the delay, I see that this seems odd behavior. 

I see that when I'm trying to access the version itself (https://docs.rs/aide/0.11.0/), we will redirect  to the crate-page showing the build failure. Same when we access the main entrypoint for the crate-docs (https://docs.rs/aide/). 
One of these is probably also the link that crate authors should link to. 

I definitely see that the same redirect would help when accessing https://docs.rs/aide/latest/aide/ or any other path for that matter. 

cc @Nemo157 @jyn514 am I forgetting anything?

**Comment by Nemo157** [comment]
No, that sounds like the correct solution, if the version failed to build we should just ignore the inner path and redirect to the crate-details page.

**Comment by syphar** [comment]
There is a potential fix in #2125
