### ISSUE TITLE
Settings not working

### ISSUE THREAD

**Issue by callym** [rust-lang/docs.rs#213]
Recently Rustdoc has started generating a Settings page, which works fine on the std website, but on docs.rs, never saves the settings.
The browser console gives this error:
`Uncaught SyntaxError: Unexpected token <`
But doesn't give any more information to track it down any further.

**Comment by pravic** [comment]
Same here. It has been broken for a while, but it's really annoying.

To reproduce:

* Go to https://docs.rs/kay/0.2.11/kay/struct.ActorSystem.html (as one of the recently updated crates)
* Click on Settings: https://docs.rs/kay/0.2.11/settings.html
* Here we go, there is an error.

While rustdoc itself works fine (or may be it has been fixed): 

https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html
https://doc.rust-lang.org/nightly/settings.html

**Comment by pravic** [comment]
No idea?

**Comment by onur** [comment]
Maybe @GuillaumeGomez can help us with this.

**Comment by GuillaumeGomez** [comment]
I'll take a look.

**Comment by sunjay** [comment]
Any update on this? I ran into this today.

**Comment by whatisaphone** [comment]
Workaround:

1. Teach yourself javascript in 21 days
2. Go to https://doc.rust-lang.org/settings.html
3. Configure things as you like
4. Make a note of what's in localStorage
5. Go to https://docs.rs/futures-preview/0.3.0-alpha.13/futures/
6. Copy the localStorage entries over one by one

**Comment by GuillaumeGomez** [comment]
I didn't look yet. But I assume it comes from crates that have been generated with a previous rustdoc version.

> Teach yourself javascript in 21 days

That's a pretty bad joke  (if it's a joke).

**Comment by Nemo157** [comment]
It looks like (at least for some instances of this) the settings page JS file is missing, e.g. https://docs.rs/futures/0.1.26/settings.html tries to load https://docs.rs/futures/0.1.26/settings-20190318-1.35.0-nightly-0f88167f8.js which just returns a redirect to the futures homepage. Trying an absolute URL like the rest of the loaded resources (in this case https://docs.rs/settings-20190318-1.35.0-nightly-0f88167f8.js) returns a 404 instead.

**Comment by QuietMisdreavus** [comment]
@Nemo157 Great catch! It looks like we're not hosting that file. I ran a test on a dev server, and it looks like if we start loading that file in, the settings menu starts working. I've posted https://github.com/rust-lang/docs.rs/pull/332 to start adding that file in with new releases. I'll see what it will take to start hosting prior versions of that file, too.l
