### ISSUE TITLE
Fluvio failed to compile on docs.rs

### ISSUE THREAD

**Issue by morenol** [rust-lang/docs.rs#2134]
### Crate name

fluvio

### Build failure link

https://docs.rs/crate/fluvio/0.19.1/builds/824799

### Additional details

Seems to be related to some nightly failures

**Comment by Nemo157** [comment]
Your `Cargo.lock` specifies `value-bag 1.0.0-alpha.9`, that fails to build since it's about a year old and tries to use nightly features after doing compiler version detection (a terrible idea for this reason). If you update that it will work.

**Comment by Nemo157** [comment]
Actually, scratch that, there is no `Cargo.lock` in the package. I have no idea why it chose `1.0.0-alpha.9`, when I try building locally it chooses the latest `1.4.0` like it should 🤔.

**Comment by morenol** [comment]
unless that file is not uploaded to crates.io? maybe we can just retrigger the build?

**Comment by morenol** [comment]
it seems that it is there: https://docs.rs/crate/fluvio/0.19.1/source/Cargo.lock

**Comment by Nemo157** [comment]
That one is I believe generated by docs.rs during the build, we record the source afterwards (...something I've long been meaning to fix), when I download and inspect the package locally it doesn't have it:

```console
> cargo dl -e fluvio
                         crates.io index   updated
                                  fluvio   extracted fluvio 0.19.1 to fluvio-0.19.1

> ls fluvio-0.19.1
build.rs  Cargo.toml  Cargo.toml.orig  LICENSE-APACHE  README.md  src/  test-data/
```

**Comment by Nemo157** [comment]
Yes, I've just queued a new build.
