### ISSUE TITLE
gpiocdev 0.4.3 failed to build

### ISSUE THREAD

**Issue by warthog618** [rust-lang/docs.rs#2143]
### Crate name

gpiocdev

### Build failure link

https://docs.rs/crate/gpiocdev/0.4.3

### Additional details

The failing build pulled in value-bag v1.0.0-alpha.9 and failed on errors from that, but when I build locally, including in a docs.rs build environment, it pulls in the latest - value-bag 1.4.0 and the build passes.

**Comment by syphar** [comment]
The error is the same we saw in #2134, 

I queued a rebuild: https://docs.rs/releases/queue

**Comment by warthog618** [comment]
Thanks - that build worked.
