### ISSUE TITLE
Feature Request: search predicates like `after:<DATE>`.

### ISSUE THREAD

**Issue by nathan-at-least** [rust-lang/docs.rs#2151]
I love https://docs.rs btw! Thanks to everyone who's contributed to it.

I've noticed whenever I do crate searches on https://docs.rs I almost always filter by the date stamp on the right hand side, and I rarely look at packages that haven't been updated this year (currently 2023).

That made me wonder if there were search predicates, so I can do a search like `json-rpc after:2023-01-01` or the like. I didn't see any mention of this kind of feature at https://docs.rs/about nor on the a quick search of open and closed tickets here with a query of `search`.

I could imagine a variety of predicates I'd like to use. For example, I also rarely use a crate that doesn't have pub items documented, so I'd be tempted to do a search like `grpc after:2022 lint-deny:missing_docs` to quickly find recent crates that have all documented APIs.

I realize this is a large umbrella feature, and also there may be simpler ways to get what I want. I'll file tickets for those other approaches (namely date sorting).

**Comment by syphar** [comment]
Also taking into account my other comments ( https://github.com/rust-lang/docs.rs/issues/2153#issuecomment-1594166936 and https://github.com/rust-lang/docs.rs/issues/2152#issuecomment-1594169742): 

docs.rs is using the crates.io search, and should continue doing so. 

So feature requests like this would be better suitet to the crates.io repository. 
That being said, crates.io search is pending a big rewrite, where requirements like this _could_ be taken into account. 

So in regards to purely docs.rs, this feels like "crate discovery" again, which is not a use-case for docs.rs. Also if crates.io would start supporting this syntax, we would directly benefit from this feature.
