### ISSUE TITLE
Feature Request: sort results by date

### ISSUE THREAD

**Issue by nathan-at-least** [rust-lang/docs.rs#2152]
Typically when searching for crates, I tend to avoid those which haven't been updated in a while. I basically scan, by eye, for only "2023" updated crates.

It would simplify my searches if I could sort by my-to-least recently updated.

BTW- this recency is just the easiest approximation available on https://docs.rs for "maintenance reliability". For example, a crate which hasn't been updated in a year _might_ be a really mature solid simple crate that's widely relied on. In that case, I'd consider using it, but that's hard to see from the search results.

I filed a more sophisticated request for search predicates in #2151. I would guess adding results sorting may be simpler and gives me 70% of the value I'd get from that more sophisticated feature.

**Comment by syphar** [comment]
Docs.rs is internally using just the `crates.io` search API. 

So while we would duplicate a part of the crates.io interface/logic, I would be fine with a PR that adds the sorting-dropdown from the crates.io search to our search results. 

Similar to adding columns to the result where we already get the information from the crates.io API. 

<img width="231" alt="grafik" src="https://github.com/rust-lang/docs.rs/assets/540890/3c1f34be-d01d-4c3d-b005-105c93a9e734">

**Comment by linyihai** [comment]
May be need some time, I will take on look on this.

**Comment by syphar** [comment]
Thank you, awesome! 

Feel free to ask any questions here on the issue, or on zulip.
