### ISSUE TITLE
Feature request: link to other crates in a workspace

### ISSUE THREAD

**Issue by xxchan** [rust-lang/docs.rs#2157]
Some project has many sub-crates, e.g., arrow-rs: https://github.com/apache/arrow-rs  / https://docs.rs/arrow/41.0.0/arrow/

Users usually need to browse related crates together, but it's inconvenient to jump between them on docs.rs.

![image](https://github.com/rust-lang/docs.rs/assets/37948597/67bf75e0-1969-4e59-a73a-2f1c1d59c336)

Currently the solution is deploy `cargo doc --no-deps --workspace` separately e.g., to GitHub Pages.

It would be nice if docs.rs can natively display all crates similarly. Alternatively, maybe allowing the author to specify some metadata for related crates also makes some sense.

![image](https://github.com/rust-lang/docs.rs/assets/37948597/78b3fe11-77d7-4c9c-a3a4-8a440eb31f0c)

**Comment by syphar** [comment]
@xxchan this seems like a duplicate of #2021, or am I missing something?

**Comment by xxchan** [comment]
Yes, it looks like the same. I searched "workspace" but not found it. 😄
