### ISSUE TITLE
Unable to build crate in docs.rs due to a missing library, available through optional features

### ISSUE THREAD

**Issue by sagarp-patel** [rust-lang/docs.rs#2160]
### Crate name

cephalon

### Build failure link

https://docs.rs/crate/cephalon/0.0.2/builds/843039

### Additional details

Hi, after searching around for a few hours, I pin pointed the issue to the libtorch library. The library is needed by a dependency tch-rs to be able run a sentence embedding model in rust. The thing is I am using an optional feature download-libtorch for tch, that should download the library if it is missing. However, on docs.rs, and installing via crate on crates.io it does not download the missing library. However, if I just use my local copy it seems to be working completely fine, and downloading the missing library. The library itself is around 4GB, so maybe that's why, but it doesn't make sense as to why when I try to install the crate onto my system it would not install it, unless there is a limit to downloading libraries with huge file size.  

I am using a windows 11, and Rust version 1.69. My friend tried it on his mac, and it is the same issue. 

Any help would be appreciated!

**Comment by Nemo157** [comment]
I'm not sure why `download-libtorch` doesn't appear to be attempting to download the library, but if it did that would also fail because [docs.rs does not provide network access](https://docs.rs/about/builds#hitting-resource-limits).

`tch`/`libtorch-sys` also have a `doc-only` feature that avoids depending on the native library at all, you will have to activate it only when building on docs.rs, something like:

```toml
[features]
doc-only = ["tch/doc-only"]

[package.metadata.docs.rs]
features = ["doc-only"]
```

**Comment by Nemo157** [comment]
Ah, I see why it doesn't log the download, for annoying reasons the build log we record is actually the _second_ build attempt, the `torch-sys` build script has some state that means if it fails to download once it will just skip attempting to download a second time, might be worth you opening an upstream issue to let them know:

```rust
if !libtorch_dir.exists() {
  fs::create_dir(&libtorch_dir).unwrap_or_default();
  ...
  download(&libtorch_url, &filename)?;
  ...
}
```

**Comment by sagarp-patel** [comment]
Hi, Thank you again for all the help! I really appreciate it! I was able to get the build done on docs.rs today! I will go ahead and create an upstream issue to help with the tch repo as well.  Can you elaborate on the issue?? so I can make sure I understand it fully!

**Comment by sagarp-patel** [comment]
Closing, the issue is fixed. Thanks again! :)
