### ISSUE TITLE
aws-throwaway: needs 5GB ram

### ISSUE THREAD

**Issue by rukai** [rust-lang/docs.rs#2169]
### Crate name

aws-throwaway

### Build failure link

https://docs.rs/crate/aws-throwaway/0.1.0/builds/862981

### Requested RAM limit

5GB

### Why your crate needs the resource increases

The aws-sdk-ec2 dependency is huge and causing the issue.
On my machine memory usage of peaks at 3.3GB for `cargo doc --no-deps`
So 4 or 5 GB should be enough to get it over the line.

I'm really hoping https://github.com/awslabs/aws-sdk-rust/issues/113 gets resolved one day, otherwise many projects will continue to face this issue. :/

**Comment by syphar** [comment]
I increased the limit to 5 GB and queued a rebuild of the release. 

Feel free to reopen the issue if this doesn't work / isn't enough.
