### ISSUE TITLE
okta-jwt-verifier build fail

### ISSUE THREAD

**Issue by 06chaynes** [rust-lang/docs.rs#2174]
### Crate name

okta-jwt-verifier

### Build failure link

https://docs.rs/crate/okta-jwt-verifier/0.7.0/builds/873321

### Additional details

There was an error during the build that I was unable to reproduce locally. Can the build be triggered again? Hoping to see if this can be resolved without any further investigation.

**Comment by syphar** [comment]
I queued a rebuild for this release: https://docs.rs/releases/queue

**Comment by syphar** [comment]
( we can investigate further if this doesn't help, feel free to ping me)

**Comment by Nemo157** [comment]
You appear to have a published `Cargo.lock` containing `value-bag 1.0.0-alpha.9` (required via an old version of `log`) which doesn't build on more recent compilers. When building with the lockfile fails we should be deleting it and trying again, which works for me locally, I'm not sure why that is still failing.

**Comment by Nemo157** [comment]
#2175 should fix force-regenerating the lockfile, so a rebuild after that is deployed should succeed.

**Comment by 06chaynes** [comment]
Ah makes sense, thanks for digging into this!

**Comment by syphar** [comment]
I just deployed the change (https://github.com/rust-lang/docs.rs/pull/2175) and requeued a build for this release

**Comment by syphar** [comment]
It seems like the build worked: https://docs.rs/okta-jwt-verifier/0.7.0/okta_jwt_verifier/

thanks @Nemo157 for the investigation & fix!
