### ISSUE TITLE
Build failure -- error[E0463]: can't find crate for `deno_ops`

### ISSUE THREAD

**Issue by mmastrac** [rust-lang/docs.rs#2178]
### Crate name

deno_ops

### Build failure link

https://docs.rs/crate/deno_core/0.197.0/builds/870081

### Additional details

`deno_core` has been building successfully on docs.rs for a while, but failed to build 0.197.0.

We had a strange build failure with `deno_core`. It cannot find the `deno_ops` crate, but you can see that it should be looking for 0.75.0 from Cargo.toml here:

https://docs.rs/crate/deno_core/0.197.0/source/Cargo.toml

And deno_ops was published and successfully built 0.75.0 on docs.rs a few hours earlier:

https://docs.rs/crate/deno_ops/0.75.0/builds/870080

Any ideas why this might be? Could it be a temporarily glitch?

```
[INFO] [stderr] warning: Rustdoc did not scrape the following examples because they require dev-dependencies: http_bench_json_ops, panik, fs_module_loader, hello_world, schedule_task, ts_module_loader, disable_ops, eval_js_value, wasm
[INFO] [stderr]     If you want Rustdoc to scrape these examples, then add `doc-scrape-examples = true`
[INFO] [stderr]     to the [[example]] target configuration of at least one example.
[INFO] [stderr] warning: Target filter specified, but no targets matched. This is a no-op
[INFO] [stderr]  Documenting deno_core v0.197.0 (/opt/rustwide/workdir)
[INFO] [stderr] error[E0463]: can't find crate for `deno_ops`
[INFO] [stderr]   --> lib.rs:44:9
[INFO] [stderr]    |
[INFO] [stderr] 44 | pub use deno_ops::op;
[INFO] [stderr]    |         ^^^^^^^^ can't find crate
[INFO] [stderr] 
[INFO] [stderr] error[E0463]: can't find crate for `deno_ops`
```

**Comment by Nemo157** [comment]
I get the same result if I download `deno_core` and run `env DOCS_RS=1 cargo check` locally (the env-var to bypass `v8`'s attempt to download). So it's either a bug in the package or some upstream rustdoc/rustc issue unrelated to docs.rs' environment.

**Comment by Nemo157** [comment]
Yep, building rustc with some debug logs confirms that:

```
DEBUG rustc_metadata::creader Failed to load proc-macro `/home/nemo157/.cargo/shared-target/debug/deps/libdeno_ops-12e9f85671c1e8d6.so`: /home/nemo157/.cargo/shared-target/debug/deps/libdeno_ops-12e9f85671c1e8d6.so: undefined symbol: v8__String__kMaxLength
```

(It might be worth opening an issue about improving the diagnostics for this case, I had to even add an extra debug log to see this message).

**Comment by mmastrac** [comment]
Ah, that makes perfect sense now. This will be an interesting problem to solve.

**Comment by mmastrac** [comment]
I have a workaround for this for now...  I'll close this issue and open one for improved diagnostics. Thanks for the tip.
