### ISSUE TITLE
libscoop 0.1.0-beta.2 failed to build

### ISSUE THREAD

**Issue by chawyehsu** [rust-lang/docs.rs#2183]
### Crate name

libscoop

### Build failure link

https://docs.rs/crate/libscoop/0.1.0-beta.2/builds/876947

### Additional details

I added the [`default-target = "x86_64-pc-windows-msvc"`][1] config in this version which may be the reason it failed I guess. I searched and found https://github.com/rust-lang/docs.rs/issues/796#issuecomment-636923174 according to the keyword `lib.exe` in the build log. If `x86_64-pc-windows-msvc` does not currently work, may I ask how to rebuild it with a supported target without requiring me to publish a new version?

Thanks in advance.

[1]: https://github.com/chawyehsu/hok/commit/d38658ef8785df92189b29df7094dadfc609e14c#diff-761679222a515001e5edd159baa573c1cd1b802c478532ea445ce74df98b9f7eR14-R15

**Comment by Nemo157** [comment]
It's not possible to override the targets used for a build, we just rely on the package metadata to determine that, so you would have to publish a new version.
