### ISSUE TITLE
the latest version has landed to crates.io but can't see the build log on Docs.rs.

### ISSUE THREAD

**Issue by yihau** [rust-lang/docs.rs#2189]
Hi there, I noticed that

https://crates.io/crates/solana-sdk released v1.16.7 (6 days ago)

However, I couldn't find the build log on Docs.rs https://docs.rs/crate/solana-sdk/1.16.7/builds
Seems that the previous version is fine (https://docs.rs/crate/solana-sdk/1.16.6/builds)

how could I debug with this situation? Thank you!

**Comment by syphar** [comment]
Looking at our [build queue](https://docs.rs/releases/queue) I can see that the release is still queued. 

Sadly there is not much we can do right now, apart from waiting. 

We are working on making the builds faster and providing more build capacity, but both things are not ready yet.

**Comment by yihau** [comment]
ah! thank you for pointing this out! hope it can be built asap 😢

**Comment by yihau** [comment]
btw, how do you order the queue? I found some of crates are released later than solana-* but they are in the head 🤔

**Comment by syphar** [comment]
> btw, how do you order the queue? I found some of crates are released later than solana-* but they are in the head 🤔

Yeah, we are actively deprioritizing some crate workspaces that release many crates at once, so they don't block the queue for other crates. solana is one case, there are others like aws-sdk or gcloud SDK.
