### ISSUE TITLE
bacon-rajan-cc doesn't build because the version of rustc is too old

### ISSUE THREAD

**Issue by jrmuizel** [rust-lang/docs.rs#219]
bacon-rajan-cc builds with rustc-1.28-beta but the version on doc.rs is too old.
https://docs.rs/crate/bacon_rajan_cc/0.2.1/builds/108195

**Comment by gnzlbg** [comment]
Basically, if the rust toolchain isn't updated on every new release, something breaks. We have been having this problem for a very long time. Maybe it could be possible to automate that the latest version of the rust toolchain is always used somehow ?

**Comment by jyn514** [comment]
This was automated in #407 I think. It's certainly automated on master now.
