### ISSUE TITLE
automatically update build docker image

### ISSUE THREAD

**Issue by syphar** [rust-lang/docs.rs#2199]
currenty we have to restart the server process to force rustwide to do a `docker pull`, pulling any new image. 

We should do this automatically, daily should be good enough. 

From what I remember, rustwide will pull the image somewhere in the initialization process, triggered in `RustwideBuilder::init`.

**Comment by syphar** [comment]
( I'll add more details later )

**Comment by linyihai** [comment]
Hello, is this a good first issue for me, I want to make some effort for it.

**Comment by syphar** [comment]
This would be awesome to have, thank you already! 

This is a easy-to-medium issue, depending on previous knowledge. We have _some_ easier issues (pure template / interface, like #1691 or perhaps #1093 ). 

To give more context: 
- our builder (in `docbuilder::rustwide_builder::RustwideBuilder`) will create a `rustwide::Workspace` using the `rustwide::WorkspaceBuilder`, which then will pull the docker image. 
- we are already doing a toolchain update every time the nightly gets updated ( and running add-essential-files)
- at the same time we could also recreate the workspace, dropping old one. 

Feel free to hit me / us up in the [`t-docs-rs` stream](https://rust-lang.zulipchat.com/#narrow/stream/t-docs-rs) on zulip if you need more help.

**Comment by linyihai** [comment]
> This would be awesome to have, thank you already!
> 
> This is a easy-to-medium issue, depending on previous knowledge. We have _some_ easier issues (pure template / interface, like #1691 or perhaps #1093 ).
> 
> To give more context:
> 
> * our builder (in `docbuilder::rustwide_builder::RustwideBuilder`) will create a `rustwide::Workspace` using the `rustwide::WorkspaceBuilder`, which then will pull the docker image.
> * we are already doing a toolchain update every time the nightly gets updated ( and running add-essential-files)
> * at the same time we could also recreate the workspace, dropping old one.
> 
> Feel free to hit me / us up in the [`t-docs-rs` stream](https://rust-lang.zulipchat.com/#narrow/stream/t-docs-rs) on zulip if you need more help.

Thanks for you respond, i will try the issues you metion above and this issue.

**Comment by syphar** [comment]
this is completed now, configured to fetch the image every 6 hours. 

so changes from https://github.com/rust-lang/crates-build-env will get to docs.rs automatically, so much quicker :) 

Thanks @linyihai !

**Comment by linyihai** [comment]
I'm glad to hear that 😺
