### ISSUE TITLE
Support Generating Docs for the Latest Git Revision

### ISSUE THREAD

**Issue by severen** [rust-lang/docs.rs#22]
Would you be able to support generating documentation for the latest Git revision of crate?

This would be nice for many crates that are a work-in-progress, and as such don't have many of the latest features pushed up into a release on crates.io.

**Comment by onur** [comment]
Currently, I am not planning to build crates from git sources. I don't want to make false promises but I may add this in future.

**Comment by SShrike** [comment]
So that's a definite yes! :P

Jokes aside, thanks for considering it :)

**Comment by jyn514** [comment]
This is unlikely to be possible due to the number of Rust crates. Building published versions alone is a large undertaking, building every revision is just not feasible. If you have work-in-progress crates, you could publish a pre-release: https://semver.org/#spec-item-9
