### ISSUE TITLE
Add option to include implementors from other crates?

### ISSUE THREAD

**Issue by newpavlov** [rust-lang/docs.rs#220]
It could be useful to add list trait implementors from other crates with appropriate links. Probably it should be an opt-in feature, e.g. by manually listing crates which should be included in the `  [package.metadata.docs.rs]` section of `Cargo.toml` in a crate which defines traits.

**Comment by jyn514** [comment]
@newpavlov it's possible to do this if there's no direct dependency by adding an optional feature: https://github.com/tokio-rs/tokio/pull/3271. If you mean show *downstream* implementors, like show types from `tokio` that implement `Stream` in `futures`, that's not really possible, it would need fundamental changes to rustdoc.

**Comment by jyn514** [comment]
I'm going to close this since it's outside the control of docs.rs.
