### ISSUE TITLE
Does rust doc search support Regex expression

### ISSUE THREAD

**Issue by baoyachi** [rust-lang/docs.rs#2200]

**Comment by syphar** [comment]
I assume this is about searching inside documentation, not searching crates? 
Crate-search is built inside docs.rs, the search inside the documentation is inside rustdoc.

So this is either an already existing or new issue for https://github.com/rust-lang/rust ( where rustdoc issues are tracked), cc @GuillaumeGomez

**Comment by baoyachi** [comment]
I now want to search for objects in the document that contain the end of `Read`. How should I search
