### ISSUE TITLE
Need Documenetation Guide On How To Build Rust On Raspberry Pi With armv7-unknown-linux-musleabihf Platform

### ISSUE THREAD

**Issue by jerrychong25** [rust-lang/docs.rs#2201]
### Crate name

armv7-unknown-linux-musleabihf

### Build failure link

armv7-unknown-linux-musleabihf

### Additional details

Hi Rust Doc Team,

Good day.

I've have some errors in installing rust for Raspberry Pi using **armv7-unknown-linux-musleabihf** platform, which is not supported.

Could provide the full documentation so we could build on it successfully?

Similar Issue:
- https://github.com/rust-lang/rustup/issues/1665#issuecomment-1695156843

Thank you.

**Comment by syphar** [comment]
Hello @jerrychong25 , 

this repository is about docs.rs, which is hosting the documentation for rust crates, which is generated by rustdoc. 

For help installing the rust toolchain on any platform you can refer to [the community, for example our forum, or the chat platforms](https://www.rust-lang.org/community). When you suspect a bug in `rustup`, then the rustup repository you already linked above is the right place.

**Comment by jerrychong25** [comment]
Thanks @syphar .

Managed to resolve this issue via Rust Users Forum.

References:
- https://users.rust-lang.org/t/need-documenetation-guide-on-how-to-build-rust-on-raspberry-pi-with-armv7-unknown-linux-musleabihf-platform/99139/3
