### ISSUE TITLE
Increase allowed memory usage

### ISSUE THREAD

**Issue by FlixCoder** [rust-lang/docs.rs#2205]
### Crate name

fhir-sdk (/fhir-model)

### Build failure link

https://docs.rs/crate/fhir-sdk/0.3.0/builds / https://docs.rs/crate/fhir-sdk/0.4.0/builds 

### Requested RAM limit

12 GB

### Requested timeout

default

### Requested number of targets

default

### Why your crate needs the resource increases

There are a lot of types and the builders also have plenty of generics. This pumps up the memory usage (and build time).

**Comment by syphar** [comment]
I see the current limit for this crate is already 8 GB. 

We just upgraded our server size, and are in the process of discussing specifics of memory limits that we can allow on the new machine. Before the upgrade, 12 GB wouldn't have been possible, now it's a "perhaps". 

We'll come back to you when we finished that discussion. 

cc @Nemo157

**Comment by syphar** [comment]
btw, @FlixCoder the increase to 12 GB _feels_ arbitrary  (sorry if it's not), 
how much max memory did your test builds need locally? 

Why I'm asking: since 12 GB might be at or over the limit of what we can provide, there is a chance that lower numbers like 9/10/11 are possible.

**Comment by FlixCoder** [comment]
12 GB is indeed what it needed locally for me. However, I did not add a lot more types or change anything significantly and it somehow worked with 8 GB in 0.2.0. There is a chance it will work with 10 GB.

I tested plenty of things to try to reduce the memory usage, but unfortunatly, I could not find a way that does not compromise on usability. I could try disabling the builders for docs.rs, but that would be a non-trivial change in code complexity and would then not show the builders in the docs. Though I might add that feature anyway since build requirements are just high.
Anyway, it would be ok if it does not work dpcs.rs, I could find a way to host the documentation externally or work on the feature to disable builders.

**Comment by syphar** [comment]
Thank you for the detailed response! 

give us some days, then I can come back to your with more information here. 

My hunch would be that 12 GB are possible.

**Comment by Nemo157** [comment]
It's interesting that the majority of types seem to be re-exports from `fhir-model` which built successfully. It seems like re-exports should use _less_ memory as rustdoc is just loading pre-compiled metadata for them. Might be worth opening an issue on rust-lang/rust if there is a 4GB memory usage difference between the two crates.

**Comment by FlixCoder** [comment]
Oh, I didn't realize fhir-model succeeded. In that case it seems 10 GB would suffice, as they both needed the same amount for me locally. But indeed, I expected `fhir-sdk` to use less, but re-exported types seem to use the same amount of memory. Must be something in the library surface that needs that amount of memory.

**Comment by syphar** [comment]
I increased the limit & queued a rebuild.
