### ISSUE TITLE
Compiling aws crates hits timeout limit

### ISSUE THREAD

**Issue by exdx** [rust-lang/docs.rs#2207]
### Crate name

avalanche-types

### Build failure link

https://docs.rs/crate/avalanche-types/0.1.1/builds/899151

### Requested timeout

30

### Why your crate needs the resource increases

My crate has a dependency on the [official AWS API crate](https://github.com/awslabs/aws-sdk-rust) which is a massive library. I believe the build times out because it takes too long. In the logs its clear a SIGKILL was sent to the doc build process. If there is a way to pass `--no-deps` that would fix the issue I believe. Otherwise, increasing the timeout seems like the only other option.

**Comment by Nemo157** [comment]
`--no-deps` _is_ used (or an equivalent, we build via `cargo rustdoc` not `cargo doc`) but that still requires doing a check build of the dependency. It seems more likely to me that it's hitting a memory limit and getting killed that way, 15 minutes is a _loooong_ time for a crate to build for. We've actually just bumped the default memory limit up today so I've queued another build and hopefully that will work.

**Comment by Nemo157** [comment]
Yep, that did it, I think it's likely we'll keep this 6GB default limit moving forward, but if you notice a similar SIGKILL failure in the future and see that the limit (displayed on the build overview page <https://docs.rs/crate/avalanche-types/0.1.1/builds>) has decreased again we can add an override for this crate.

**Comment by exdx** [comment]
Wow thanks a lot! I'm really glad the build passes now. 🙏
