### ISSUE TITLE
Failed to build documentation of dicom-parser due to rustdoc bug

### ISSUE THREAD

**Issue by Enet4** [rust-lang/docs.rs#2208]
### Crate name

dicom-parser

### Build failure link

https://docs.rs/crate/dicom-parser/0.6.0/builds/868056

### Additional details

`dicom-parser` v0.6.0 tripped a regression in rustdoc ([rust#115179](https://github.com/rust-lang/rust/issues/115179)) that would lead to an ICE.

The regression has already been fixed as of `nightly-2023-09-02`, so the next build job should work. Triggering a rebuild of this crate would be much appreciated.

**Comment by Nemo157** [comment]
Done, and it's succeeded already 🎉
