### ISSUE TITLE
crate failed to build due to (now fixed) bug in rustdoc

### ISSUE THREAD

**Issue by GlenDC** [rust-lang/docs.rs#2215]
### Crate name

tower-async

### Build failure link

https://docs.rs/crate/tower-async/0.1.1/builds

### Additional details

Rustdoc had a bug related to async-trait related features that I use for my nightly-only crate,
`tower-async`, which is a fork of `tower`.

The issue was tracked at <https://github.com/rust-lang/rust/issues/113656#issuecomment-1709988487>.

It has since been fixed. Could you please retrigger a build for me? 🙏 Or teach me how I can do so myself?

**Comment by syphar** [comment]
I queued a rebuild: https://docs.rs/releases/queue
