### ISSUE TITLE
moxie-dom: retry ancient build from '19

### ISSUE THREAD

**Issue by emberian** [rust-lang/docs.rs#2221]
### Crate name

moxie-dom

### Build failure link

https://docs.rs/crate/moxie-dom/0.2.2/builds

### Additional details

this is sufficiently old, surely docs.rs supports the wasm32-unknown-unknown target by now: will a simple rerun get me docs?

**Comment by Nemo157** [comment]
Queued a new build, we'll see if it works in a couple minutes.

**Comment by Nemo157** [comment]
Looks like it's hitting compile errors in a dependency: https://docs.rs/crate/moxie-dom/0.2.2/builds/913387

**Comment by emberian** [comment]
Ah well, thanks @Nemo157 !
