### ISSUE TITLE
Build: windows-specific sdks

### ISSUE THREAD

**Issue by wmmc88** [rust-lang/docs.rs#2227]
### Crate name

wdk-sys

### Build failure link

https://docs.rs/crate/wdk-sys/0.1.0/builds/917967

### Additional details

I see there are instructions on adding dependencies for building docs for crates on a linux host image, but my situation is different. `wdk-sys` is a crate that provides bindings to the [Windows Driver Kit](https://learn.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk), but requires the WDK to be installed or a script from the eWDK environment must be run to set up the environment. What is the best course of action here? It seems like the windows image in this repository doesn't work, and the headers from the WDK will not be available from ubuntu 20.04 apt repo. Is there a way to tell docs.rs to fetch headers?

**Comment by syphar** [comment]
Currently we only have a linux build server, which of course limits windows specific builds. 

The typical approaches to solve this are: 
- vendor the header files, so include them in your crate 
- [use conditional compilation](https://docs.rs/about/builds) to make the docs build without the headers.

**Comment by syphar** [comment]
since we don't allow network access from the build-script, you can't download the headers in the build.

**Comment by wmmc88** [comment]
I had considered using the conditional compilation already, but since the library is a `-sys` crate, its main value is creating rust bindings via headers, so there wouldn't be much value without including the generated headers in the docs. 

In terms of vendoring files, is it sufficient to only vendor the header files? I was hoping to vendor only the header files (and not the `.lib` files required for linking), and only use the vendored headers for doc.rs documentation generation. When running `rustdoc`, does the linker ever actually get invoked?

**Comment by syphar** [comment]
From what I know it should be enough to vendor the header files, there is no linking when generating docs (to my knowledge). 

You can try this also by using our [`crates-build-env`](https://github.com/rust-lang/crates-build-env) container which is what we build the packages in.

**Comment by syphar** [comment]
Closing this issue, feel free to reopen if we find an issue with docs.rs itself. 

Currently we can't build natively on windows
