### ISSUE TITLE
Opening a crates versionless url links to prerelease versions

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/docs.rs#223]
I just pushed a test crate to https://docs.rs/nemo157, there was a `0.3.0` version published previously and I just added a `0.3.1-pre` version. I expected the versionless url to still redirect to the latest non-prerelease version, but instead it links to the prerelease version; and explicitly going to https://docs.rs/nemo157/0.3.0/nemo157/ shows a bright orange "Go to latest version" link.

I think for the purposes of promoting a stable ecosystem it would be best to treat prerelease versions as ineligible to be the latest version unless a crate has no normal versions available. Having them still listed under the versions for the crate and allowing them to be linked to directly would still be useful.

**Comment by udoprog** [comment]
If like to boost the signal in this a bit. It's causing a bit of a yanking party in tokio-rs/tokio#2036

**Comment by jyn514** [comment]
@Nemo157 the test crate makes this much faster to debug, thanks :)

**Comment by jyn514** [comment]
I'm going to try and also fix #221 at the same time.

**Comment by jyn514** [comment]
This is mostly fixed, I'm just trying to solve https://github.com/rust-lang/docs.rs/issues/395 at the same time. If I don't get it in the next half hour or so I'll just make a PR without.
