### ISSUE TITLE
Metric recording built documentation size

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/docs.rs#2238]
While discussing https://github.com/rust-lang/rust/issues/115718 I had a thought that being able to see historical "typical" documentation sizes could be useful, and docs.rs might be a good place to gather that.

It'll likely be a pretty varying metric depending on what crates are being built each day, maybe too variable to be useful, but I think it should be pretty easy to add and then we could see whether it seems to give useful data.

**Comment by camelid** [comment]
It'd be important to record the median in particular since it's less susceptible to outliers. Percentiles could be useful too.

**Comment by Nemo157** [comment]
Yeah, I was thinking recording as a histogram, we've been recording build durations that way for a while now which can give some idea of the sort of volatility from the different sorts of crates that get published each day (25th, 50th, 75th, 90th, 95th, 99th percentile lines):

![image](https://github.com/rust-lang/docs.rs/assets/81079/6bf1cab8-c428-480f-8117-89f3c9550e4f)

**Comment by syphar** [comment]
What's the use-case for this? It _sounds_ useful. 

Would "documentation size" rather be the amount of files? Megabytes? all targets? 

Depending on how exact / how often / how far back to the history we need the numbers, we could also store it in the database.

**Comment by syphar** [comment]
So, some thoughts here (aka, partial mentoring instructions). 

- when running the build, we have all the documentation for all targets in one folder. It might be possible to figure out target-specific doc sizes from that, though it's tricky for the default target which doesn't have a subfolder. 
- we have crates with a fairly big documentation (from what I remember [`stm32ral`](https://docs.rs/stm32ral/latest/stm32ral/) sums up to around 4 GiB compressed, with several million files, so we should perhaps at least benchmark the added build time to calculate sizes for the whole crate, or per target. 
- depending on the use-case I could imagine that just tracking size for all targets together is good enough. But also, when we start tracking _some_ data it might also be useful to directly start per-target. Or the average per target? 

generally we could store this in the database per release, and/or report it to prometheus to be able to add it to our dashboards.
