### ISSUE TITLE
Search box broken due to outdated cache not being updated

### ISSUE THREAD

**Issue by marcospb19** [rust-lang/docs.rs#2243]
It's been 2 days since I made a release of [`fs-tree`](https://docs.rs/fs-tree/latest/fs_tree) that introduced a method called `read_at`.

However, when I go to the `/latest/` documentation page, and search it, I get nothing:

https://docs.rs/fs-tree/latest/fs_tree/?search=fstree%3A%3Aread_at
![image](https://github.com/rust-lang/docs.rs/assets/38900226/5c668bc9-9e63-43b7-9ca6-8d405d042dd8)

In contrast, the `/0.5.5/` page search bar works as expected:

https://docs.rs/fs-tree/0.5.5/fs_tree/index.html?search=read_at
![image](https://github.com/rust-lang/docs.rs/assets/38900226/5418f67b-5576-4be5-bd43-d52ad67060d6)

---

This is specifically a problem with the search bar, since the method page can be seen in both versions:

https://docs.rs/fs-tree/latest/fs_tree/enum.FsTree.html#method.read_at
https://docs.rs/fs-tree/0.5.5/fs_tree/enum.FsTree.html#method.read_at

---

To be clear, the `latest` page shows that the version is indeed `0.5.5`.

![image](https://github.com/rust-lang/docs.rs/assets/38900226/41add047-bad2-4a75-8803-08feceabc431)

---

Problem is not found in local `rustdoc` pages.

**Comment by Nemo157** [comment]
It works for me which makes it likely to be a local caching issue. I think it might be because 0.5.4 and 0.5.5 were built with the same rustdoc version, and that's the only part of the `search-index-....js` filename that varies between builds.

**Comment by marcospb19** [comment]
You're absolutely right!

**Comment by syphar** [comment]
@Nemo157 IMO this is the last remaining case of #1593 , and only can happen when two releases are build with the same nightly version. 

I created an CDN invalidation for the crate. 

If the search is fine now for @marcospb19 I would close this issue in favor of #1593

**Comment by marcospb19** [comment]
I cannot re-test it, because I had to refresh the cache to confirm @Nemo157's point.

But I'm ok with closing it :) .
