### ISSUE TITLE
sqlx-sqlite 0.7.2 didn't get picked up

### ISSUE THREAD

**Issue by abonander** [rust-lang/docs.rs#2244]
The docs for `sqlx-sqlite 0.7.2` didn't get built, but it doesn't appear at all in the build queue or in the recent failures list: https://docs.rs/sqlx-sqlite/0.7.2

The strange part is, it appears that the rest of the crates got picked up even though I published them all at basically the same time: https://docs.rs/sqlx/0.7.2/sqlx/index.html

**Comment by Nemo157** [comment]
Another instance of https://github.com/rust-lang/docs.rs/issues/797

In this case, I assume the issue will be the circular exact version dev-depencency on `sqlx`, the queue is _too fast_ now and attempted to build `sqlx-sqlite` before `sqlx` was published. A rebuild should succeed (I don't have access right now to queue it up, hopefully @syphar can tomorrow).

We should maybe see if there's some way we could avoid this, there's the brute-force "delete `[dev-dependencies]` from `Cargo.toml`" but maybe there's something cleaner we could do (and I'm not sure how that interacts with `--scrape-examples`).

**Comment by abonander** [comment]
Is there anything we can do on our end to mitigate this in the future? The circular dependency is kinda necessary in order to have compile-tested examples using the facade in these lower APIs, though I suppose we could make a fake facade just for the examples.

**Comment by syphar** [comment]
for now the parallel builds are stopped until we solved another issue. 

After that I believe that you won't be the only case, so docs.rs should have a way to handle these cases. 

Otherwise, the solution would probably be to only release `sqlx-sqlite` when the needed version of `sqlx` is already on crates.io. ( assuming the error is what was decribed above)

**Comment by abonander** [comment]
The problem is that `sqlx` of course depends on `sqlx-sqlite` since the latter is included in the facade of the former.

**Comment by syphar** [comment]
in any case, the (simplest) solution on docs.rs side stays the same: retry the build :)

**Comment by syphar** [comment]
( apart from fixing #797)
