### ISSUE TITLE
`ibc-proto` v0.37.0 documentation returns a 404

### ISSUE THREAD

**Issue by romac** [rust-lang/docs.rs#2247]
### Crate name

ibc-proto

### Build failure link

https://docs.rs/crate/ibc-proto/0.37.0/builds/930108 (not actually failing I believe)

### Additional details

The [documentation](https://docs.rs/ibc-proto/0.37.0/ibc_proto/) for `ibc-proto` v0.37.0 returns a 404 "The requested resource does not exist" even though the [build appears to have succeeded](https://docs.rs/crate/ibc-proto/0.37.0/builds/930108), modulo a warning (see first line below):

```
[INFO] [stderr] warning: Target filter specified, but no targets matched. This is a no-op
[INFO] [stderr]  Documenting ibc-proto v0.37.0 (/opt/rustwide/workdir)
[INFO] [stderr]     Finished dev [unoptimized + debuginfo] target(s) in 5.65s
```

Status codes for latest/v0.37.0:

```
❯ curl -sI https://docs.rs/ibc-proto/latest/ibc_proto/ | head -n1
HTTP/2 404
❯ curl -sI https://docs.rs/ibc-proto/0.37.0/ibc_proto/ | head -n1
HTTP/2 404
```

Status code for previous version (v0.36.1):

```
❯ curl -sI https://docs.rs/ibc-proto/0.36.1/ibc_proto/ | head -n1
HTTP/2 200 
```

**Comment by syphar** [comment]
we had some server issues last night (around the build-time). 

I just queued a rebuild, when that's done we can recheck.

**Comment by romac** [comment]
Thank you for the prompt reaction! 🙏
