### ISSUE TITLE
Docs build and are avilable through /crate, but "no such resource" on direct URL

### ISSUE THREAD

**Issue by V0ldek** [rust-lang/docs.rs#2248]
I released a new version of my crate yesterday, and it all went as usual, the docs built:

https://docs.rs/crate/rsonpath-lib/0.8.3/builds/930053

If you go to the "raw" docs at https://docs.rs/crate/rsonpath-lib/0.8.3, you can see that it's all correct there and works normally. However, clicking the Documentation button or manually going to https://docs.rs/rsonpath-lib/0.8.3/rsonpath/ (or the latest counterpart, https://docs.rs/rsonpath-lib/latest/rsonpath/) gives a 404 "The requested resource does not exist".

The only relevant change between my crate's 0.8.2 and the bugged 0.8.3 is [this diff](https://github.com/V0ldek/rsonpath/commit/dd226b84f42ad44b73685b29b3a66c09b7d5de00#diff-c519384452cc40dc07252bbbe891f0fb6ca2de7403eefdfc1bcf458fc19e0129R129), where I added

```rust
#![doc(html_logo_url = "https://raw.githubusercontent.com/V0ldek/rsonpath/main/img/rsonquery-logo.svg")]
```

to the main `lib.rs`.

**Comment by syphar** [comment]
we had some server issues last night (around the build-time).

I just queued a rebuild, when that's done we can recheck.

**Comment by syphar** [comment]
( see also #2247 )

**Comment by V0ldek** [comment]
Yup, now works, thanks!
