### ISSUE TITLE
Requesting rebuild of `fj`

### ISSUE THREAD

**Issue by hannobraun** [rust-lang/docs.rs#2253]
### Crate name

fj

### Build failure link

https://docs.rs/crate/fj/0.47.0/builds/841909

### Additional details

The doc build fails due to errors from the `bytemuck` crate. The failure is caused by a bug in the nightly version that was used for the failing builds, and has been fixed in the meantime (see https://github.com/Lokathor/bytemuck/issues/197 and https://github.com/rust-lang/rust/issues/112831). Hopefully rebuilding with a more recent Rust version should help.

Thank you!

(Related issues: https://github.com/rust-lang/docs.rs/issues/2251, https://github.com/rust-lang/docs.rs/issues/2252)

**Comment by Nemo157** [comment]
Queued all three.

**Comment by hannobraun** [comment]
Thank you!

**Comment by hannobraun** [comment]
The rebuild worked, and the documentation is available now. Thank you!
