### ISSUE TITLE
blazesym 0.2.0-alpha.7 missing documentation

### ISSUE THREAD

**Issue by d-e-s-o** [rust-lang/docs.rs#2254]
### Crate name

blazesym

### Build failure link

https://docs.rs/crate/blazesym/0.2.0-alpha.7/builds

### Additional details

I am not really sure why, but the link to the [documentation](https://docs.rs/blazesym/0.2.0-alpha.7/blazesym/) for the `blazesym` crate version `0.2.0-alpha.7` just reports "The requested resource does not exist". I don't really see any hint of an error, nor do I think much has changed on the crate's end that could have caused issues (though I could be missing something).

Can someone help me understand what is going on, please?

**Comment by syphar** [comment]
we had some server issues in the last days that lead to partially broken builds. 

I just queued a rebuild, when that's done we can recheck.

**Comment by d-e-s-o** [comment]
> I just queued a rebuild, when that's done we can recheck.

Thank you, that seems to have solved the problem!
