### ISSUE TITLE
egui_dock 0.8.1 docs page not present

### ISSUE THREAD

**Issue by Adanos020** [rust-lang/docs.rs#2255]
### Crate name

egui_dock

### Build failure link

https://docs.rs/crate/egui_dock/0.8.1/builds/930474

### Additional details

The docs page doesn't exist: https://docs.rs/egui_dock/latest/egui_dock/

I managed to locally build the docs for my crate without any errors. All tests are also passing.

**Comment by syphar** [comment]
we had some server issues in the last days that lead to partially broken builds. 

I just queued a rebuild, when that's done we can recheck.

**Comment by Adanos020** [comment]
Thank you, looks like the page is back!
