### ISSUE TITLE
Documentation for `leptos_icons` v0.1.0 can't be opened

### ISSUE THREAD

**Issue by Carlosted** [rust-lang/docs.rs#2257]
The crate doesn't appear in the failed attempts list.

When searching for it in the search bar it appears to have succeeded: https://docs.rs/releases/search?query=leptos_icons,
but when opening the link I get a **no such resource** error: https://docs.rs/leptos_icons/0.1.0/leptos_icons/.

**Comment by syphar** [comment]
we had some server issues in the last days that lead to partially broken builds.

I just queued a rebuild, when that's done we can recheck.

**Comment by syphar** [comment]
build is finished, it looks like the docs are fine again. 

I'll close this issue now, but feel free to reopen if the issue isn't fixed for you.

**Comment by Carlosted** [comment]
Thank you so much for your quick help!
