### ISSUE TITLE
Crate Build Failure for my crate - finalytics 

### ISSUE THREAD

**Issue by Nnamdi-sys** [rust-lang/docs.rs#2258]
### Crate name

finalytics

### Build failure link

https://docs.rs/crate/finalytics/0.1.0/builds/935382

### Additional details

[INFO] [stderr] error: failed to run custom build command for `torch-sys v0.13.0`

**Comment by syphar** [comment]
It seems like `torch-sys` needs a C++ dependency, which we don't have in our build environment. 

Also see https://docs.rs/about/builds 

The typical approaches are: 
- vendor the needed headers / files 
- add a cargo feature for docs that doesn't need the headers. 

It seems like `torch-sys` (and also `rust-bert` and the others) solve this issue by having a `doc-only` feature, [and setting the docs.rs metadata to use it](https://github.com/LaurentMazare/tch-rs/blob/dca12b647ade36414c09359bade840d5092087d6/Cargo.toml#L54-L55 ).  

So the solution for you would be to follow a similar pattern: 
- add a feature (`doc-only` if you want to follow the naming pattern of your dependencies)
- set it in your docs.rs metadata
- make the feature set the `doc-only` feature in the dependencies that need it.

**Comment by Nnamdi-sys** [comment]
> It seems like `torch-sys` needs a C++ dependency, which we don't have in our build environment.
> 
> Also see https://docs.rs/about/builds
> 
> The typical approaches are:
> 
> * vendor the needed headers / files
> * add a cargo feature for docs that doesn't need the headers.
> 
> It seems like `torch-sys` (and also `rust-bert` and the others) solve this issue by having a `doc-only` feature, [and setting the docs.rs metadata to use it](https://github.com/LaurentMazare/tch-rs/blob/dca12b647ade36414c09359bade840d5092087d6/Cargo.toml#L54-L55).
> 
> So the solution for you would be to follow a similar pattern:
> 
> * add a feature (`doc-only` if you want to follow the naming pattern of your dependencies)
> * set it in your docs.rs metadata
> * make the feature set the `doc-only` feature in the dependencies that need it.

Thanks a lot!!!
