### ISSUE TITLE
How to jump to last version where docs built successfully?

### ISSUE THREAD

**Issue by Boscop** [rust-lang/docs.rs#226]
A lot of crates' docs don't build successfully but there are earlier versions that bbuilt successfully.
E.g.:
[failed] https://docs.rs/actix-web/0.7.2/actix_web/
[works] https://docs.rs/actix-web/0.6.4/actix_web/ (but is it the latest working version of docs? you'd have to click through the versions to find out)

[failed] https://docs.rs/yew/0.4.0/yew/
[works] https://docs.rs/yew/0.2.0/yew/

I don't see a way to jump to the latest working docs. There should be a button at the top, when the docs failed to build.

**Comment by Boscop** [comment]
The "Go to latest version" could still go to the docs of the most recent version, even if they failed to build.
There, it will show the button to "jump to latest version whose docs built successfully".

**Comment by jyn514** [comment]
This was added in https://github.com/rust-lang/docs.rs/pull/543 :) You can see it in action on e.g. https://docs.rs/crate/actix-web/0.7.2.
