### ISSUE TITLE
extism-convert docs are missing

### ISSUE THREAD

**Issue by zshipko** [rust-lang/docs.rs#2268]
### Crate name

extism-convert

### Build failure link

https://docs.rs/crate/extism-convert/0.1.0/builds/930160 and https://docs.rs/crate/extism-convert/0.2.0/builds/930381

### Additional details

It looks like the the builds may have passed, but the docs are missing.

Thanks!

**Comment by syphar** [comment]
Thank you for the report! 
Through a rebuild I fixed the crate. 

I have two hunches where the original problem might have been, and will dig into it separately.

**Comment by zshipko** [comment]
Thanks!
