### ISSUE TITLE
docs.rs - generates not working links for module documentation

### ISSUE THREAD

**Issue by kolbma** [rust-lang/docs.rs#2270]
For example...
https://docs.rs/rqlite_client/0.0.1-alpha.10/rqlite_client/response/index.html

Most of the links in the left menu bar are based on  
https://docs.rs/rqlite_client/0.0.1-alpha.10/rqlite_client/response/  
So the link for the same module is there  
https://docs.rs/rqlite_client/0.0.1-alpha.10/rqlite_client/response/response/index.html  
and so not found.

Also crate-level structs are based wrong...
https://docs.rs/rqlite_client/0.0.1-alpha.10/rqlite_client/response/struct.Connection.html  
Should be https://docs.rs/rqlite_client/0.0.1-alpha.10/rqlite_client/struct.Connection.html

**Comment by syphar** [comment]
initially I thought this it related to some builder-issues we had, but looking deeper it seems like that we generate broken links here. 

@Nemo157 @GuillaumeGomez was / is there a known rustdoc issue about this?

**Comment by syphar** [comment]
@GuillaumeGomez do you have any insight here?

**Comment by GuillaumeGomez** [comment]
Completely forgot about it. Seems like all links are generated correctly in the `0.0.1-alpha.15` version, so maybe it was an old rustdoc bug which has been solved in the meantime?
