### ISSUE TITLE
Clarify `rustc-args` vs `rustdoc-args` in cross-compiling section

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/docs.rs#2284]
> You can configure how your crate is built by adding [package metadata](https://docs.rs/about/metadata) to your Cargo.toml, e.g.:
> ```
> [package.metadata.docs.rs]
> rustc-args = ["--cfg", "docsrs"]
> ```
> —<https://docs.rs/about/builds#cross-compiling>

This may be a little confusing compared to the standard practice of `rustdoc-args = ["--cfg", "docsrs"]`, this section should clarify that this `cfg` is used for things like the `build.rs` or dependencies but not for the docs themselves.

**Comment by ChrisDenton** [comment]
I think the sentence after that also makes it sound more generally applicable then it is:

> Here, the compiler arguments are set so that `#[cfg(docsrs)]` (not to be confused with `#[cfg(doc)]`) can be used for conditional compilation.

Which I think may have confused me (though I don't quite remember).
