### ISSUE TITLE
docs.rs fails to build for r3bl_tui

### ISSUE THREAD

**Issue by nazmulidris** [rust-lang/docs.rs#2293]
### Crate name

r3bl_tui

### Build failure link

https://docs.rs/crate/r3bl_tui/0.3.7/builds

**Comment by Nemo157** [comment]
One of your (transitive) dependencies `xcb` attempts to modify its source directory. That is not allowed as Cargo assumes it is immutable. I would suggest you try to get that updated to the latest version as I think they've fixed that issue.

**Comment by nazmulidris** [comment]
@Nemo157 Thank you so much for your quick response. I will take a look a closer look at the `xcb` dep 👍🏽

**Comment by syphar** [comment]
it looks like the issue was fixed in newer versions of your package ( presumably with https://github.com/r3bl-org/r3bl-open-core/pull/179 ), so I'm closing this issue here. 

Feel free to reopen if my interepretation was wrong
