### ISSUE TITLE
"The requested version does not exist" for non-yanked crates

### ISSUE THREAD

**Issue by mo8it** [rust-lang/docs.rs#2308]
When you click on the "source" button in anything in the `migrate` module of `sqlx`, you get "The requested version does not exist":

https://docs.rs/sqlx/latest/sqlx/migrate/index.html

Link of "source":
https://docs.rs/sqlx-core/0.7.2/x86_64-unknown-linux-gnu/src/sqlx_core/lib.rs.html#84

**Comment by Nemo157** [comment]
`sqlx-core 0.7.2` was a casualty of https://github.com/rust-lang/docs.rs/issues/797, related to https://github.com/rust-lang/docs.rs/issues/2244. I'll queue a new build of it.

**Comment by Nemo157** [comment]
Link works now

**Comment by Nemo157** [comment]
(Though, other links within `sqlx::migrate` don't, because `sqlx-core` doesn't appear to activate the migration feature while building its docs, but that's up to the `sqlx` devs to configure).
