### ISSUE TITLE
Build errors in my crates (possibly due to 2018 edition?)

### ISSUE THREAD

**Issue by Kimundi** [rust-lang/docs.rs#231]
I'm getting [build errors](https://docs.rs/crate/greenwasm-binary-format/0.2.1/builds/115221) for a collection of crates a recently [published](https://docs.rs/releases/search?query=greenwasm). The errors seem to imply that doc.rs does not pick up the cargo feature for the 2018 Rust edition yet. 

Is this an not-yet-implemented bug of doc.rs, or is this considered functionality that will not be supported until its stable?

**Comment by Kimundi** [comment]
Update: The issue still exists, but I've worked around it for now by going back to the 2015 edition.

**Comment by Guoli-Lyu** [comment]
Yes, the rustdoc compiler version is 1.28. I think it is in stable channel, which miss rust 2018 support for the time being. Any idea how to force nightly rustc in docs.rs like 1.30?

**Comment by ethanboxx** [comment]
It would be good to see this working. 2018 is awesome and I want to use it with rustdoc

**Comment by dekellum** [comment]
Looks like its using a nightly, but its pinned to nightly-2018-06-03, prior to any edition support:

https://github.com/onur/docs.rs/blob/09d4ed5d49e6e7243320fa3888bdc6c6acde28b4/Vagrantfile#L50

**Comment by QuietMisdreavus** [comment]
Since https://github.com/rust-lang-nursery/docs.rs/pull/243 has been merged, docs.rs is using a version of Cargo that can use the `edition` feature and config item. I've also manually rebuilt greenwasm's docs for version 0.3.1: https://docs.rs/greenwasm/0.3.1/greenwasm/

**Comment by Kimundi** [comment]
Seems like this can be closed then, right?

**Comment by QuietMisdreavus** [comment]
Looks like it!
