### ISSUE TITLE
404 link to help.html

### ISSUE THREAD

**Issue by tdelmas** [rust-lang/docs.rs#2313]
The `?` at the right of the search field when consulting the docs of a crate: 
![image](https://github.com/rust-lang/docs.rs/assets/1955774/bc1112bb-c100-4f73-8f45-5c3c49e246b9)

links to a 404 with `help.html` in the url.

Ex: 
On https://docs.rs/snowboard/0.6.2/snowboard/
It links to (404) https://docs.rs/snowboard/0.6.2/help.html/snowboard/

**Comment by syphar** [comment]
thank you for the report! 

To me it looks like it's working? What browser are you using?

**Comment by tdelmas** [comment]
I can reproduce the bug on Firefox and Chrome.

:warning: It's not when you simply click on it (that correctly open a popin)

To reproduce it, you need to "right-click"+"open in a new tab" (or middle click). Sorry, I should have been more specific.

You can see when the mouse over the `?` icon, the (wrong) link displayed in the bottom. 

Either that button shouldn't be a link (best), or it should target `#` (I don't think there is a better place to link, is there?)

**Comment by syphar** [comment]
Ah, now I understand. 

I think this is a bug, I created a fix in #2318, now testing locally

**Comment by syphar** [comment]
the fix is released, and it seems to work now.

**Comment by tdelmas** [comment]
Yes, it works, thanks!
