### ISSUE TITLE
docs.rs/cratename redirect to version with failed build gives "The requested resource does not exist" and no links

### ISSUE THREAD

**Issue by huonw** [rust-lang/docs.rs#232]
The short-links like https://docs.rs/im seem to do a redirect to the latest published version of the crate (which is 12.0.0 for that crate at the time of filing, i.e. https://docs.rs/im/12.0.0/im/). If that version failed to build, then the page is rather useless: just "The requested resource does not exist". It would be nice to give more information, such as a link to the crate page (e.g. https://docs.rs/crate/im/12.0.0) which at least has info about build failures, and/or a link to the latest successful build.

(A more general form of this issue is arbitrary URLs that are invalid but still "obviously" referring to a specific crate, e.g. https://docs.rs/crate/im/100.0.0. These could also contain a link back to the crate they refer to.)

**Comment by dpc** [comment]
This is really bad user experience. Many of places all over the web have links like https://docs.rs/mycrate and then if the get "The requested resource does not exist" it's a big WAT. There are not even any pointers how to find last version that did work.

**Comment by eddyb** [comment]
I stumbled onto this and discussed it with @QuietMisdreavus - I would prefer a redirect from a version that failed to build, to the `crate/` page.
For the versionless link, I think it's fine for it to go to the last-known-good version, and the "go to the latest version" link would trigger the aforementioned redirect.
