### ISSUE TITLE
OpenDAL built failed for a broken upstream crate

### ISSUE THREAD

**Issue by Xuanwo** [rust-lang/docs.rs#2321]
### Crate name

opendal

### Build failure link

https://docs.rs/crate/opendal/0.42.0/builds/971792

### Additional details

`openssh-sftp-client` pushed a broken tag recently which lead to this build failed. This issue is fixed at https://github.com/openssh-rust/openssh-sftp-client/issues/112.

Can we trigger a rebuild for opendal 0.42 again?

**Comment by Nemo157** [comment]
Rebuild added to [the queue](https://docs.rs/releases/queue)

**Comment by Xuanwo** [comment]
Thanks a lot!

**Comment by Xuanwo** [comment]
> Rebuild added to [the queue](https://docs.rs/releases/queue)

I found the build is for `opendal v0.41.0`, but we expect `opendal v0.42.0`.

**Comment by Nemo157** [comment]
It was 0.42.0, it [failed again](https://docs.rs/crate/opendal/0.42.0/builds/981045) because you are excluding `tests/` from the published package but activating the `tests` feature via `package.metadata.docs.rs.all-features = true`.

**Comment by Xuanwo** [comment]
> It was 0.42.0, it [failed again](https://docs.rs/crate/opendal/0.42.0/builds/981045) because you are excluding `tests/` from the published package but activating the `tests` feature via `package.metadata.docs.rs.all-features = true`.

Thanks for the quick response. We will address the issue in next version.
