### ISSUE TITLE
Problem retrieving source files for rebuilt crate

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/docs.rs#2322]
When investigating why we just had the build queue locked I noticed a few errors like these in the logs:

```
Nov 18 19:08:14 docsrs cratesfyi[12087]: 2023-11-18T19:08:14.514737Z  WARN crate_details_handler{params=CrateDetailHandlerParams { name: "atuin", version: Some("17.0.1") } repository_stats_updater=Repo
Nov 18 19:08:14 docsrs cratesfyi[12087]: Caused by:
Nov 18 19:08:14 docsrs cratesfyi[12087]:     0: fetching Cargo.toml from atuin 17.0.1 (archive: true)
Nov 18 19:08:14 docsrs cratesfyi[12087]:     1: bzip2: bz2 header missing
```

Trying to browse the source files in this crate, many of them are not showing any content, like https://docs.rs/crate/atuin/17.0.1/source/Cargo.toml

Presumably this assumption is not correct

https://github.com/rust-lang/docs.rs/blob/62c620e51fcb2ef4f62571044aa510a3e16d9843/src/storage/mod.rs#L215

even though the contents of the archive don't change, we do upload a new source archive which may have different file offsets for many reasons.

**Comment by syphar** [comment]
@Nemo157 was this release rebuilt?

**Comment by syphar** [comment]
Yep, that's probably it. 

I removed the locally cached archive index, purged the CDN for this path, and that fixed it.
