### ISSUE TITLE
Crates using vulkano-shaders fail to build

### ISSUE THREAD

**Issue by marc0246** [rust-lang/docs.rs#2329]
We have a bit of a situation in that all crates that use vulkano-shaders fail to build on docs.rs, at least as of 0.33, for reasons that are beyond me. There's no metadata for docs.rs in vulkano-shaders or any of these crates, and documenting of course works locally.

The following crates are affected:
- [basalt](https://docs.rs/crate/basalt/0.20.0/builds/804199)
- [egui_winit_vulkano](https://docs.rs/crate/egui_winit_vulkano/0.26.0/builds/984877)
- [ilmenite](https://docs.rs/crate/ilmenite/0.14.0/builds/804196)

**Comment by Nemo157** [comment]
It may have been https://github.com/rust-lang/rust/pull/111461 giving a wrong error message, but not sure why it would have been erroring at all, I will queue a new build of those versions.

**Comment by Nemo157** [comment]
Hmmm, still failed with a more normal error message. I don't see why it's failing though, trying to do a local build using some of the options that docs.rs does doesn't cause any similar sort of failure, and there's no more useful data in the service logs. I can try and debug some more in a local docs.rs instance tomorrow.
