### ISSUE TITLE
Rebuild `sqlx` to fix rustdoc issue

### ISSUE THREAD

**Issue by abonander** [rust-lang/docs.rs#2340]
Search in docs for `sqlx 0.7.3` is currently broken due to: https://github.com/rust-lang/rust/issues/118242

The fix appears to have landed in nightly as a local docs build works fine now.

I'm not too worried about the constituent crates as I fixed the facade to inline the drivers, but it might be nice to rebuild `sqlx-core` as well for anyone developing their own database drivers.

**Comment by abonander** [comment]
Actually, on checking the driver crates it looks like search on those is working just fine so it's only necessary to rebuild `sqlx-core` and `sqlx` anyway.

**Comment by syphar** [comment]
I queued rebuilds for both releases, see https://docs.rs/releases/queue

**Comment by abonander** [comment]
Thanks!
