### ISSUE TITLE
Archived out-of-date libtest still found at https://docs.rs/libtest

### ISSUE THREAD

**Issue by cameronelliott** [rust-lang/docs.rs#2344]
The libtest crate has been archived and integrated into Rust stable.

**_But the old out-of-date documentation site is still searchable and found on docs.rs, and it is confusing_**

old libtest docs:  https://docs.rs/libtest/latest/libtest/
repo showing archival:  https://github.com/rust-lang/libtest

New test docs home: https://doc.rust-lang.org/stable/test/index.html

This is really confusing for people when they google for types from the Rust test library.

**I suggest https://docs.rs/libtest should show an error message or be removed**

**Comment by Nemo157** [comment]
It has now been yanked, since it was the only version the above link is now a 404, and I believe that should start letting search engines clean it up from their results as they re-crawl it.

**Comment by cameronelliott** [comment]
It's so wonderful when carefully documented issues are followed on.
Thank you
