### ISSUE TITLE
Request for rebuild of vulkano-shaders dependents

### ISSUE THREAD

**Issue by marc0246** [rust-lang/docs.rs#2348]
Follow-up to #2329, now that [a fix to shaderc's build script](https://github.com/google/shaderc-rs/pull/145) has been merged and released, I'd like to ask to please rebuild the following crates. I think I hunted down every one that's failing due to vulkano-shaders specifically including transitive dependencies. There may be other ones failing due to shaderc itself or dependents thereof.

- [autd3-geometry-viewer 14.2.0](https://docs.rs/crate/autd3-geometry-viewer/14.2.0/builds)
- [autd3-geometry-viewer 14.2.1](https://docs.rs/crate/autd3-geometry-viewer/14.2.1/builds)
- [autd3-geometry-viewer 14.2.2](https://docs.rs/crate/autd3-geometry-viewer/14.2.2/builds)
- [autd3-geometry-viewer 15.0.0](https://docs.rs/crate/autd3-geometry-viewer/15.0.0/builds)
- [autd3-geometry-viewer 15.0.2](https://docs.rs/crate/autd3-geometry-viewer/15.0.2/builds)
- [autd3-geometry-viewer 15.1.0](https://docs.rs/crate/autd3-geometry-viewer/15.1.0/builds)
- [autd3-geometry-viewer 15.1.1](https://docs.rs/crate/autd3-geometry-viewer/15.1.1/builds)
- [autd3-geometry-viewer 15.1.2](https://docs.rs/crate/autd3-geometry-viewer/15.1.2/builds)
- [autd3-simulator 14.2.0](https://docs.rs/crate/autd3-simulator/14.2.0/builds)
- [autd3-simulator 14.2.1](https://docs.rs/crate/autd3-simulator/14.2.1/builds)
- [autd3-simulator 14.2.2](https://docs.rs/crate/autd3-simulator/14.2.2/builds)
- [basalt 0.20.0](https://docs.rs/crate/basalt/0.20.0/builds)
- [cuberef_client 0.0.1](https://docs.rs/crate/cuberef_client/0.0.1/builds)
- [egui_winit_vulkano 0.24.0](https://docs.rs/crate/egui_winit_vulkano/0.24.0/builds)
- [egui_winit_vulkano 0.25.0](https://docs.rs/crate/egui_winit_vulkano/0.25.0/builds)
- [egui_winit_vulkano 0.26.0](https://docs.rs/crate/egui_winit_vulkano/0.26.0/builds)
- [ilmenite 0.14.0](https://docs.rs/crate/ilmenite/0.14.0/builds)
- [let-engine 0.1.0-alpha](https://docs.rs/crate/let-engine/0.1.0-alpha/builds)
- [let-engine 0.1.3](https://docs.rs/crate/let-engine/0.1.3/builds)
- [let-engine 0.1.4](https://docs.rs/crate/let-engine/0.1.4/builds)
- [let-engine 0.1.5](https://docs.rs/crate/let-engine/0.1.5/builds)
- [let-engine 0.1.6](https://docs.rs/crate/let-engine/0.1.6/builds)
- [let-engine 0.2.0](https://docs.rs/crate/let-engine/0.2.0/builds)
- [let-engine 0.2.1](https://docs.rs/crate/let-engine/0.2.1/builds)
- [let-engine 0.2.2](https://docs.rs/crate/let-engine/0.2.2/builds)
- [let-engine 0.2.3](https://docs.rs/crate/let-engine/0.2.3/builds)
- [let-engine 0.3.0](https://docs.rs/crate/let-engine/0.3.0/builds)
- [let-engine 0.3.1](https://docs.rs/crate/let-engine/0.3.1/builds)
- [let-engine 0.3.2](https://docs.rs/crate/let-engine/0.3.2/builds)
- [let-engine 0.3.3](https://docs.rs/crate/let-engine/0.3.3/builds)
- [let-engine 0.3.4](https://docs.rs/crate/let-engine/0.3.4/builds)
- [let-engine 0.4.0](https://docs.rs/crate/let-engine/0.4.0/builds)
- [let-engine 0.4.1](https://docs.rs/crate/let-engine/0.4.1/builds)
- [let-engine 0.4.2](https://docs.rs/crate/let-engine/0.4.2/builds)
- [let-engine 0.5.0](https://docs.rs/crate/let-engine/0.5.0/builds)
- [let-engine 0.6.0](https://docs.rs/crate/let-engine/0.6.0/builds)
- [let-engine 0.7.0](https://docs.rs/crate/let-engine/0.7.0/builds)
- [let-engine 0.8.0](https://docs.rs/crate/let-engine/0.8.0/builds)
- [perovskite_client 0.0.1](https://docs.rs/crate/perovskite_client/0.0.1/builds)
- [vera 0.2.0](https://docs.rs/crate/vera/0.2.0/builds)

Full disclosure: I'm not affiliated with any of these crates. I'm sure they won't mind having working docs though. That's also why there's such a backlog of failing versions: no one was doing anything about it and I was just now made aware of the issue by one of the crate's authors. I'm sorry for that.

**Comment by syphar** [comment]
Thank you for the initiative, and for gathering this list! 

I tested rebuilding `vera`, which then succeeded, 
then queued builds for the other releases.
