### ISSUE TITLE
The new sort-by select-box will switch to the default option when using the paging

### ISSUE THREAD

**Issue by linyihai** [rust-lang/docs.rs#2350]
## How do reproduct?
when you click the `Next Page`  Button in  https://docs.rs/releases/search?query=serde&sort=downloads , the sort by select box will switch to `Relevance`

## How to Fixed ?
when you click `Next Page` Button, the jump url is https://docs.rs/releases/search?paginate=P3E9c2VyZGUmc29ydD1kb3dubG9hZHMmcGVyX3BhZ2U9MzAmcGFnZT0y

the value of sort by select box named `sort` was base64ecode in the paginate value, you can see the paginate value `P3E9c2VyZGUmc29ydD1kb3dubG9hZHMmcGVyX3BhZ2U9MzAmcGFnZT0y` can be base64 decode as `?q=serde&sort=downloads&per_page=30&page=2`

**Comment by linyihai** [comment]
https://github.com/rust-lang/docs.rs/pull/2297/commits/3f37c6c00c2a7ff9713477545aa4a97c268efbd7#diff-c3796aac6c6b01cd1998b29108b5d32fe5113970a7f4558e799c18984307d73aR602

I suppose the `sort_by` var should be reassigned here.

**Comment by syphar** [comment]
yep, this is definitely a bug, thank you for reporting!
