### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by billy1624** [rust-lang/docs.rs#2351]
Hello, I was wondering is this a bug?

> Uncaught RangeError: Maximum call stack size exceeded ...

The faulty docs is [sea_orm v0.12.7](https://docs.rs/sea-orm/0.12.7/sea_orm/).

<img src="https://github.com/rust-lang/docs.rs/assets/30400950/77bd0a9b-77b1-4a77-941b-4eb82dc65547">

Many thanks!!

**Comment by syphar** [comment]
this seems to be a problem with rustdoc search, so  @GuillaumeGomez perhaps knows more?

**Comment by GuillaumeGomez** [comment]
I think this was fixed in https://github.com/rust-lang/rust/pull/118251. We should regenerate the docs for crates impacted.

**Comment by GuillaumeGomez** [comment]
No, it's something for docs.rs to do. Give us some time and we'll launch a rebuild.

**Comment by GuillaumeGomez** [comment]
It comes from https://github.com/rust-lang/rust/pull/116085 (in [this rollup](https://github.com/rust-lang/rust/pull/118134)). So it's broken in nightly between 21 and 25 of november (both included).

**Comment by syphar** [comment]
I'll try to remember closing the issue when the rebuilds are done

**Comment by GuillaumeGomez** [comment]
Thanks a lot!
