### ISSUE TITLE
owner link to team doesn't link to team

### ISSUE THREAD

**Issue by kzhui125** [rust-lang/docs.rs#2356]
https://docs.rs/aes/0.8.3/aes/

<img width="475" alt="image" src="https://github.com/rust-lang/docs.rs/assets/11925432/8191c00c-83b2-4790-ada0-1f8d6bc244f2">

<img width="416" alt="image" src="https://github.com/rust-lang/docs.rs/assets/11925432/d70ec2cf-2575-4b65-8a31-32e202bb0be5">

the repo is https://github.com/RustCrypto/block-ciphers

url is https://github.com/RustCrypto

**Comment by syphar** [comment]
this is actually a bug, it seems like we never started supporting teams with their proper links :) 

To wrap up how a solution would look like: 
- `RegistryApi::get_owners` has to be extended to fetch the `kind` (`team` or `user`) from the [crates.io API](https://crates.io/api/v1/crates/aes/owners) 
- the kind has to be stored in the database (can we write a migration to backfill the correct kind for existing owners?)
- based on the owner kind, we can render a different link in the dropdown 
-
