### ISSUE TITLE
Crate aliases cause doc build to fail

### ISSUE THREAD

**Issue by sagebind** [rust-lang/docs.rs#236]
```
thread 'main' panicked at 'Error(
    CargoError(
        ChainedError {
            error: failed to parse registry's information for: futures-util-preview,
            cause: Feature `compat` includes `futures01` which is neither a dependency nor another feature
        }
    ),
    State {
        next_error: None,
        backtrace: None
    }
)', src/bin/cratesfyi.rs:142:13
```

I have a crate that depends on `futures-preview` version 0.2.2, but docs.rs fails to build the docs for it because version 0.3.0-alpha.4 included a crate alias for `futures01`. I don't expect docs.rs to really handle crate aliases at this time, but it would be nice if it could ignore errors when parsing registry data for unrelated versions that are not actually depended on.

Full log: https://docs.rs/crate/chttp/0.2.0/builds/116754

**Comment by jyn514** [comment]
I think this was because we were using an old version of cargo. Since we now always depend on the latest version of cargo, it should never fail to parse the manifest. Feel free to re-open if you run into a similar issue!
