### ISSUE TITLE
docs.rs build of crate `zalgo-codec` fails due to an internal compiler error

### ISSUE THREAD

**Issue by JSorngard** [rust-lang/docs.rs#2367]
### Crate name

zalgo-codec

### Build failure link

https://docs.rs/crate/zalgo-codec/0.9.6/builds/1066812

### Additional details

I'm not quite sure what to make of it, all previous versions have built fine, and `cargo doc --all-features` works on my machine. 
It looks like an internal compiler error related to wayland on the linux docker image used to make the docs?

**Comment by JSorngard** [comment]
The related crates [zalgo-codec-common](https://docs.rs/zalgo-codec-common/latest/zalgo_codec_common/) and [zalgo-codec-macro](https://docs.rs/zalgo-codec-macro/latest/zalgo_codec_macro/) build without issue.

**Comment by JSorngard** [comment]
It looks like a rebuild should work if done on windows?

**Comment by syphar** [comment]
Hi, 
from the linked issue (-> https://github.com/rust-lang/rust/issues/119126 ) it looks like this is a compiler bug. 

While we _could_ rebuild, docs.rs [can only build on linux, and uses cross compilation for the other platforms](https://docs.rs/about/builds). 

You might be able to reproduce it using our [`crates-build-env`](https://github.com/rust-lang/crates-build-env), which is the docker image we're using the run the builds. 

Generally we have the ability to "freeze" the nightly version that docs.rs uses, so I fixed it to `2023-12-18`, which would be the last working version according to the bisect, and queued a rebuild of the release above. 


I'll leave this issue open until the rustc bug is fixed, and I can unfreeze the nightly version

**Comment by JSorngard** [comment]
It looks like a fix has been merged: rust-lang/rust/issues/119126.

**Comment by syphar** [comment]
yep, thanks! 

I unfroze the toolchain.
