### ISSUE TITLE
Clicking on a search result for a fully yanked crate takes you to a version not found page

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/docs.rs#2373]
https://docs.rs/releases/search?query=libtest shows the yanked `libtest-0.0.1` as a result. Clicking on that links to https://docs.rs/libtest/latest/libtest/ which says version not found (as we don't allow semver matches of yanked versions, and this is the only version). Going instead to https://docs.rs/libtest/0.0.1/libtest/ does show the docs. The search results should either exclude results where all versions are yanked, or link to the exact version number in those cases.

**Comment by syphar** [comment]
I lean towards still showing the crate, so the results match the results from crates.io. 

Fetching the yank-state for the releases will make the search a little slower, but IMO not that much, compared to the time spent in the API request to crates.io.
