### ISSUE TITLE
The rustc outdated so it fails to buld docs for some crates

### ISSUE THREAD

**Issue by katyo** [rust-lang/docs.rs#239]
For example, ordered-float docs is missing:
https://docs.rs/crate/ordered-float/1.0.1/builds/116706

**Comment by QuietMisdreavus** [comment]
The version of rustc on docs.rs has been updated since this issue was posted, and the `ordered-float` docs have been rebuilt: https://docs.rs/ordered-float/1.0.1/ordered_float/
