### ISSUE TITLE
Re-run near-sdk build

### ISSUE THREAD

**Issue by frol** [rust-lang/docs.rs#2392]
### Crate name

near-sdk

### Build failure link

https://docs.rs/crate/near-sdk/5.0.0-alpha.2/builds/1092817

### Additional details

It has failed due to the downstream dependency (near-primitives 0.20.0, which is now fixed in 0.20.1). Is it possible to re-run the build?

**Comment by syphar** [comment]
I queued the rebuild: https://docs.rs/releases/queue
