### ISSUE TITLE
Mark optional dependencies in the info dropdown

### ISSUE THREAD

**Issue by kpreid** [rust-lang/docs.rs#2397]
In the list of dependencies in the package info dropdown in the docs.rs top bar, build and dev dependencies are marked. This is useful for understanding what additional dependencies a package would bring with it (by knowing that build dependencies don't add code directly to the final binary, and dev dependencies aren't used at all when depending on the package).

However, optional dependencies are currently displayed just like required ones. Marking them too would be useful in the same way.

Illustration: In the following screenshot, `tokio` is an optional dependency, but nothing tells us that.

![image](https://github.com/rust-lang/docs.rs/assets/779501/406ad0f8-89ce-4081-95d5-639e4e38bc10)

**Comment by syphar** [comment]
@kpreid I like the idea in general :) 

One question comes to mind: how would you expect optional dependencies to show up when they are activated by the default features? Still as just optional?

**Comment by kpreid** [comment]
> how would you expect optional dependencies to show up when they are activated by the default features? Still as just optional?

Yes, I would say so. Such display cannot ever be _complete_ without listing all feature and dependency relationships (too much info for this context), so I think the most important thing to convey is not whether they are enabled by default, but whether it is _possible to disable them_ (whether that's via not enabling the relevant feature, or via writing `default-features = false`).

**Comment by syphar** [comment]
mentoring instructions: 
- we're storing the dependency information as JSON in the `releases.dependencies` field 
- its content is generated in `db::add_package::convert_dependencies` by using `utils::cargo_metadata::Package.dependencies`, which already includes the information if a dependency is optional 
- so `convert_dependencies` needs to be changed to _additionally_ include `optional` as boolean. 
- our own `CrateDetails` just passes on the contents as `serde_json::Value`, so no change needed. 
- in [`templates/rustdoc/topbar.html` we use this information to generate the dependency list](https://github.com/rust-lang/docs.rs/blob/142d4955af82e0134fd822225bf5a9576746e99f/templates/rustdoc/topbar.html#L115-L128), which is where we then just show the `optional` information in addition to the kind. 


To keep in mind: 
this _wont_ collect the information for old releases / builds, only for new builds. 
Doing a migration for old releases would mean fetching all manifests, parsing them again, and updating the information in the database.

**Comment by linyihai** [comment]
I'd like to take a shot.  Feel free to pick it up if i had no time to continue.

**Comment by syphar** [comment]
> I'd like to take a shot.  Feel free to pick it up if i had no time to continue.

that's awesome, thank you! 

Feel free to ask any questions here, or just hit us up on zulip.

**Comment by syphar** [comment]
first version done in #2406
