### ISSUE TITLE
Crate `polars-lazy` fails due to memory limits.

### ISSUE THREAD

**Issue by ritchie46** [rust-lang/docs.rs#2398]
### Crate name

`polars-lazy`

### Build failure link

https://docs.rs/crate/polars-lazy/0.37.0/builds/1104603

### Additional details

Can the memory limit be increased and a re-run triggered? Thanks!

**Comment by syphar** [comment]
@ritchie46 we can totally increase the limit fort your crate. 

Can you please test locally what your peak memory usage is?

**Comment by syphar** [comment]
I just checked your build-log, and the actual error is: 
> `[INFO] [stderr] error: none of the selected packages contains these features: horizontal_concat`

so it's actually not a memory limit problem. 

Looking at `Cargo.toml` it looks like you are referencing a non-existant feature (`horizontal_concat`) in your docs.rs metadata. 

I'm closing this issue, feel free to reopen if you still need the limit increase
