### ISSUE TITLE
Adding one more tab for crate's features

### ISSUE THREAD

**Issue by HosMercury** [rust-lang/docs.rs#2405]
I suggest adding one more tab for each crate to doc their features 

after versions tab or beside !!

Right now there is no good way to find every crate feature and their usage.  Organizing features will facilitate the finding and usefulness of a crate feature and how to use it.

**Comment by syphar** [comment]
Hi @HosMercury 

can you elaborate what's missing for you? 

We already have a menu template for features: 
![image](https://github.com/rust-lang/docs.rs/assets/540890/bae4c0da-2d4d-440c-9f62-f74a57f11bdc)

And some generated description around them: 

https://docs.rs/crate/itertools/latest/features

**Comment by HosMercury** [comment]
First time to know that 
Although each feature should be better documented. Right?

**Comment by syphar** [comment]
> Although each feature should be better documented. Right?

Yeah, that's true, which is why we added this comment: 
> There is very little structured metadata to build this page from currently. You should check the [main library docs](https://docs.rs/itertools/latest/itertools/), [readme](https://docs.rs/crate/itertools/latest/), or [Cargo.toml](https://docs.rs/crate/itertools/latest/source/Cargo.toml.orig) in case the author documented the features in them.

**Comment by Nemo157** [comment]
Also see https://github.com/rust-lang/rfcs/pull/3485 which we could eventually pull the data from (or deprecate our feature-flags page once rustdoc starts generating data based off it).
