### ISSUE TITLE
Increase sandbox limits for my crate(s) please

### ISSUE THREAD

**Issue by tmpfs** [rust-lang/docs.rs#2409]
### Crate name

sos-sdk

### Build failure link

https://docs.rs/crate/sos-sdk/0.10.0/builds

### Additional details

Just started failing on version 0.10.0 it was fine on 0.9.0 and I haven't made any big changes that should affect how the documentation is generated.

Also the same problem for the `sos` and `sos-net` crates, so if you could increase these too it would be appreciated:

https://docs.rs/crate/sos/0.10.0/builds
https://docs.rs/crate/sos-net/0.10.0/builds

Thanks very much 🙏

**Comment by syphar** [comment]
What kind of limit increase to you request? 

From what I see in the build failure, the problem is: 

> unknown feature `stdsimd` 

or am I missing something?

**Comment by tmpfs** [comment]
Ah sorry @syphar, I missed that error, this is first time I have come across this failure, however it's strange I can build the docs on MacOS and Linux locally.

Seems like [other people are having the same issue with ahash](https://github.com/tkaitchuck/aHash/issues/200).
