### ISSUE TITLE
docs.rs failed to build drink-0.9.0

### ISSUE THREAD

**Issue by pmikolajczyk41** [rust-lang/docs.rs#2410]
### Crate name

drink

### Build failure link

https://docs.rs/crate/drink/0.9.0/builds/1121750

### Additional details

Normal `cargo doc` works fine. My guess is that `stdsimd` feature was removed in the recent nightly that is used for building docs. Probably relevant errors reported recently: https://github.com/rust-lang/rust/issues/48556

**Comment by syphar** [comment]
This is an issue with `ahash`, see also https://github.com/tkaitchuck/aHash/issues/200 

I'm happy to trigger a rebuild if it's fixed.

**Comment by syphar** [comment]
@pmikolajczyk41 since `ahash` was fixed, I triggered a rebuild, now we're seeing another build failure. 

Can you check if there also happen locally for you?

**Comment by pmikolajczyk41** [comment]
@syphar again, locally works well, fails with `stdsimd` at `ahash`

**Comment by pmikolajczyk41** [comment]
oh, I was looking at the most recent version of library, i.e. `0.10.0`, where the problem with `ahash` persists (https://docs.rs/crate/drink/0.10.0/builds/1122573); locally, when I run `cargo doc` (for version `0.10.0`) it succeeds

**Comment by syphar** [comment]
I queued a rebuild, and we're now seeing another error, this time with `pallet-contracts`: 
https://docs.rs/crate/drink/0.10.0/builds/1129453

Interestingly, `pallet-contracts` itself also had this error : https://docs.rs/crate/pallet-contracts/27.0.0/builds/1099632 , and there is a new version that doesn't have it: https://docs.rs/crate/pallet-contracts/28.0.0/builds 

So it looks like upgrading `pallet-contracts` would be the next step to try
