### ISSUE TITLE
Clicking on old version in the topbar menus loads the name of the crate into the searchbar

### ISSUE THREAD

**Issue by zeenix** [rust-lang/docs.rs#2411]
I you visit https://docs.rs/event-listener/latest/event_listener/index.html and then click on the "4.0.3" link in the menu under the second menu in the top bar, you'll not only be taken to the "4.0.3" docs, but "event-listener" will be loaded in the search bar for you, leading to a cryptic error that will confuse you (since you didn't search for anything).

**Comment by GuillaumeGomez** [comment]
docs.rs should automatically update dashes to underscores in case the path was not found. I'll send a fix in the next days.

**Comment by zeenix** [comment]
> docs.rs should automatically update dashes to underscores in case the path was not found. I'll send a fix in the next days.

by why is the name of the crate being loaded in the searchbar at all? :thinking:

**Comment by Nemo157** [comment]
It looks like it's using the package name for the target redirect instead of the crate name as it should be.

**Comment by GuillaumeGomez** [comment]
Because the link is taking the crate name (from the package) and not as rust code, leading to a non-found path.
