### ISSUE TITLE
bevy_rand/bevy_turborand docs failed to build due to `web-time`

### ISSUE THREAD

**Issue by Bluefinger** [rust-lang/docs.rs#2420]
### Crate name

bevy_rand

### Build failure link

https://docs.rs/crate/bevy_rand/0.5.0/builds/1132356

### Additional details

My crates `bevy_rand` & `bevy_turborand` both failed their builds in the same way, unable to compile the `web-time` dependency. However, this dependency is part of bevy, specifically `bevy_utils`, which seemed to have built just fine here: https://docs.rs/bevy_utils/latest/bevy_utils/ so I wonder if there's something going on with the nightly build, though I'm not able to reproduce this build failure locally.

**Comment by Nemo157** [comment]
You have

```toml
[package.metadata.docs.rs]
rustc-args = ["--cfg", "docsrs"]
```

which applies to every crate and causes `web-time` to attempt to compile its `web` module even on a non-wasm target.

We now set `rustdoc-args = ["--cfg=docsrs"]` automatically (which only applies when building your docs, not to your dependencies), so you can remove both of these settings from your metadata.

**Comment by Bluefinger** [comment]
Does that also need the `all-features` part removed as well, or just the rustdoc-args being removed is needed?

**Comment by Nemo157** [comment]
`all-features` is good, it's just the `--cfg=docsrs` that got added https://github.com/rust-lang/docs.rs/pull/2390

**Comment by Bluefinger** [comment]
Confirmed that the[ build worked now](https://docs.rs/bevy_rand/latest/bevy_rand/), thanks a bunch!
