### ISSUE TITLE
Missing targets when requested from metadata

### ISSUE THREAD

**Issue by kpreid** [rust-lang/docs.rs#2424]
In https://docs.rs/wgpu/0.19.1/wgpu/index.html and https://docs.rs/wgpu/0.19.0/wgpu/index.html, the Platform menu lists only `x86_64-pc-windows-msvc` and `x86_64-unknown-linux-gnu`, even though the `Cargo.toml` contains

```rust
[package.metadata.docs.rs]
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-apple-darwin",
    "x86_64-pc-windows-msvc",
    "wasm32-unknown-unknown",
]
```

The prior version https://docs.rs/wgpu/0.18.0/wgpu/ does have `wasm32-unknown-unknown`, but still not `x86_64-apple-darwin`. It seems like in both cases certain targets are being silently ignored (even the build log has no info on this) and this has gotten worse between the two versions.

**Comment by Nemo157** [comment]
The issue will be that those targets failed to build, nothing being shown in the build logs is https://github.com/rust-lang/docs.rs/issues/787

Trying `cargo rustdoc --target wasm32-unknown-unknown` locally gives an explicit `compile_error!`:

```
error: webgpu feature used without web_sys_unstable_apis config:
       Here are some ways to resolve this:
       * If you wish to use webgpu backend, create a .cargo/config.toml in the root of the repo containing:
           [build]
           rustflags = [ "--cfg=web_sys_unstable_apis" ]
           rustdocflags = [ "--cfg=web_sys_unstable_apis" ]
       * If you wish to disable webgpu backend and instead use webgl backend, change your wgpu Cargo.toml entry to:
           wgpu = { version = "", default-features = false, features = ["webgl"] }
  --> src/backend/mod.rs:7:1
   |
7  | / compile_error!(
8  | |     "webgpu feature used without web_sys_unstable_apis config:
9  | | Here are some ways to resolve this:
10 | | * If you wish to use webgpu backend, create a .cargo/config.toml in the root of the repo containing:
...  |
16 | | "
17 | | );
   | |_^
```

while `x86_64-apple-darwin` appears to fail to cross-compile a dependency

```
warning: objc_exception@0.1.2: gcc: error: unrecognized command-line option ‘-arch’
warning: objc_exception@0.1.2: gcc: error: unrecognized command-line option ‘-mmacosx-version-min=10.7’

error: failed to run custom build command for `objc_exception v0.1.2`
```

(I've recently noticed that there's now <https://github.com/dtolnay/cargo-docs-rs> which could be used to test the docs build in CI _relatively_ similarly to how it will run on docs.rs)

**Comment by kpreid** [comment]
Thanks! I've copied this info to the `wgpu` issue tracker.

I assume there's no reason to keep this issue open.

**Comment by syphar** [comment]
triggered by this discussion I had another look at logging non-default build targets: https://github.com/rust-lang/docs.rs/pull/2427
