### ISSUE TITLE
docs.rs failed to build mostro-core = "0.4.6"

### ISSUE THREAD

**Issue by grunch** [rust-lang/docs.rs#2425]
### Crate name

mostro-core

### Build failure link

https://docs.rs/crate/mostro-core/0.4.6/builds/1122121

### Additional details

Normal cargo doc works fine. My guess is that stdsimd feature was removed in the recent nightly that is used for building docs. Probably relevant errors reported recently: https://github.com/rust-lang/rust/issues/48556

**Comment by Nemo157** [comment]
Queued a rebuild that should hopefully pick up the fixed ahash 0.7.8
