### ISSUE TITLE
Support for discovering cross crate implementation of a Trait for types present in a foreign crates.

### ISSUE THREAD

**Issue by artech-git** [rust-lang/docs.rs#2437]
This idea came to my mind while opening my 19th tab for searching a implementation of the trait in my current crate I was working with, here is basically what I thought.

let's say you have a crate `metrics`, this crate has a amazing trait named `Layer<R>` and with some method present inside of it.

now let's say I wish to discover crates which implement this trait on it self, therefore instead of manually scrounging docs.rs maybe we have a tiny little button which helps us do that, directly from the page of the crate itself, in my understanding this can save redundant tab spawning as well.

Let me know what you guys think.

**Comment by syphar** [comment]
Thank you for the idea, 

this sounds like #1467, or am I missing something?

**Comment by artech-git** [comment]
Hi @syphar my initial idea & #1467 are pretty close, what I think would be amazing to have if it can indexed on the docs.rs server itself and also to show a distinct filtering regarding whether the crate who are implementing this have it implemented internally or is it public in on the object types of the crate.

**Comment by syphar** [comment]
That's a tough one, but both would depend on the same JSON processing & similar storage requirements, so I would propose we merge these. 

Could you add a comment to #1467 description the additional feature idea? Then we can close this one.

**Comment by syphar** [comment]
moved the last point to #1467
