### ISSUE TITLE
[Build Failure]: index.crates.io not reachable

### ISSUE THREAD

**Issue by lexi-the-cute** [rust-lang/docs.rs#2454]
### Crate name

catgirl-engine

### Build failure link

https://docs.rs/crate/catgirl-engine/0.12.6/builds/1154979

### Additional details

index.crates.io not reachable

build failed for 0.12.4, 0.12.5, and 0.12.6 for catgirl-engine, catgirl-engine-client, and catgirl-engine-server. surprisingly catgirl-engine-utils built just fine on all 3 versions

**Comment by lexi-the-cute** [comment]
trying to build docs while blocking build-info-build causes compilation issues:

```rust
error: No BuildInfo data found!
 --> utils/src/setup.rs:2:1
  |
2 | / build_info::build_info!(
3 | |     /// Build info for crate
4 | |     pub fn build_info
5 | | );
  | |_^
  |
  = note: Did you call build_info_build::build_script() in your build.rs?
  = note: This crate expects version 0.0.36 of the BuildInfo data
  = note: Caused by: environment variable not found
  = note: this error originates in the macro `$crate::proc::build_info` which comes from the expansion of the macro `build_info::build_info` (in Nightly builds, run with -Z macro-backtrace for more info)
```

im going to need to figure out how to simulate your build environment to figure out why it used to work, but doesnt now

**Comment by lexi-the-cute** [comment]
what commit are y'all using at https://github.com/rust-lang/docs.rs? i'm trying to recreate the environment to help me debug this

**Comment by syphar** [comment]
> what commit are y'all using at https://github.com/rust-lang/docs.rs? i'm trying to recreate the environment to help me debug this. the latest commit fails to build due to lifetimes not matching

what error are you seeing? ( I'm working on the codecase nearly daily). 

>  i'm trying to recreate the environment to help me debug this.

we tried to add all necessary steps for this to the readme, feel free to also ask in the zulip stream if you need any help. 

But, coming from what @Nemo157 said, I believe you probably don't need to do this to find the issue. 

We are running `cargo fetch` on the host itself, and then run the `cargo doc` command [inside a docker container](https://github.com/rust-lang/crates-build-env) while forbidding network access. More info also [here](https://github.com/dtolnay/cargo-docs-rs). If our current assumption is correct, you will already see the error then. 

If not, there now is also [`cargo docs-rs`](https://github.com/dtolnay/cargo-docs-rs) that runs rustdoc as we are running it (only the specific arguments, not the docker / forbid network access thing)

https://github.com/dtolnay/cargo-docs-rs

**Comment by lexi-the-cute** [comment]
> > what commit are y'all using at https://github.com/rust-lang/docs.rs? i'm trying to recreate the environment to help me debug this. the latest commit fails to build due to lifetimes not matching
> 
> what error are you seeing? ( I'm working on the codecase nearly daily).
> 
> > i'm trying to recreate the environment to help me debug this.
> 
> we tried to add all necessary steps for this to the readme, feel free to also ask in the zulip stream if you need any help.
> 
> But, coming from what @Nemo157 said, I believe you probably don't need to do this to find the issue.
> 
> We are running `cargo fetch` on the host itself, and then run the `cargo doc` command [inside a docker container](https://github.com/rust-lang/crates-build-env) while forbidding network access. More info also [here](https://github.com/dtolnay/cargo-docs-rs). If our current assumption is correct, you will already see the error then.
> 
> If not, there now is also [`cargo docs-rs`](https://github.com/dtolnay/cargo-docs-rs) that runs rustdoc as we are running it (only the specific arguments, not the docker / forbid network access thing)
> 
> https://github.com/dtolnay/cargo-docs-rs

build steps i ran:

```bash
git clone https://github.com/rust-lang/docs.rs.git docs.rs
cd docs.rs
git checkout a82561c9 -b latest
cd .git/hooks && ln -s ../../.git_hooks/* . && cd ../..
git submodule update --init
mkdir -p ignored/cratesfyi-prefix/crates.io-index
cargo build
```

results of `cargo build`
```rust
warning: `/home/alexis/.exe/docs.rs/docs.rs/.cargo/config` is deprecated in favor of `config.toml`
note: if you need to support cargo 1.38 or earlier, you can symlink `config` to `config.toml`
   Compiling libc v0.2.153
   Compiling proc-macro2 v1.0.78
   Compiling unicode-ident v1.0.12
   Compiling cfg-if v1.0.0
   ...
      Compiling ipnet v2.9.0
   Compiling rustwide v0.16.0
   Compiling imara-diff v0.1.5
error[E0195]: lifetime parameters or bounds on type `Target` do not match the trait declaration
  --> /home/alexis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sharded-slab-0.1.7/src/tid.rs:32:1
   |
32 | / lazy_static! {
33 | |     static ref REGISTRY: Registry = Registry {
34 | |         next: AtomicUsize::new(0),
35 | |         free: Mutex::new(VecDeque::new()),
36 | |     };
37 | | }
   | |_^ lifetimes do not match type in trait
   |
   = note: this error originates in the macro `__lazy_static_internal` which comes from the expansion of the macro `lazy_static` (in Nightly builds, run with -Z macro-backtrace for more info)

   Compiling matchit v0.7.3
   Compiling font-awesome-as-a-crate v0.3.0 (/home/alexis/.exe/docs.rs/docs.rs/crates/font-awesome-as-a-crate)
error[E0609]: no field `free` on type `REGISTRY`
   --> /home/alexis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sharded-slab-0.1.7/src/tid.rs:150:14
    |
150 |             .free
    |              ^^^^ unknown field
    |
    = note: available field is: `__private_field`

error[E0609]: no field `next` on type `REGISTRY`
   --> /home/alexis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sharded-slab-0.1.7/src/tid.rs:161:35
    |
161 |                 let id = REGISTRY.next.fetch_add(1, Ordering::AcqRel);
    |                                   ^^^^ unknown field
    |
    = note: available field is: `__private_field`

error[E0609]: no field `free` on type `REGISTRY`
   --> /home/alexis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sharded-slab-0.1.7/src/tid.rs:191:42
    |
191 |             let mut free_list = REGISTRY.free.lock().unwrap_or_else(PoisonError::into_inner);
    |                                          ^^^^ unknown field
    |
    = note: available field is: `__private_field`

   Compiling strsim v0.11.0
   Compiling docsrs-metadata v0.1.0 (/home/alexis/.exe/docs.rs/docs.rs/crates/metadata)
   Compiling tar v0.4.40
   ...
   Compiling phf_codegen v0.11.2
   Compiling string_cache_codegen v0.5.2
   Compiling unic-ucd-segment v0.9.0
Some errors have detailed explanations: E0195, E0609.
For more information about an error, try `rustc --explain E0195`.
   Compiling cmake v0.1.50
   Compiling regex-automata v0.1.10
error: could not compile `sharded-slab` (lib) due to 4 previous errors
warning: build failed, waiting for other jobs to finish...
```

**Comment by syphar** [comment]
so, I'm not sure where this error is coming from, I just tried `cargo clean && cargo build` for both latest nightly & stable, and both work fine. Which version did you use? 

docs.rs itself is using stable, which I also made explicit now: #2456

**Comment by lexi-the-cute** [comment]
unfortunately, it builds locally on my system. even when fetching while connected and then disconnecting my wifi to run the doc generation command, so i probably will need to build the same environment to find the issue.

i've tried:
```bash
# Wifi On
rm -r .ra-target target ~/.cargo/registry ~/.cache/miri
cargo fetch

# Wifi Off
cargo doc # also cargo docs-rs
```

---

> so, I'm not sure where this error is coming from, I just tried cargo clean && cargo build for both latest nightly & stable, and both work fine. Which version did you use?
> 
> docs.rs itself is using stable, which I also made explicit now: https://github.com/rust-lang/docs.rs/pull/2456

okay, so i just realized that when trying to build for stable, i had overridden the rustflags in my .zshrc with `export RUSTFLAGS="-Z threads=`nproc --all`"`, which is why stable failed, and then tried to build for nightly. i've now commented it out and am currently building stable to set this up

**Comment by syphar** [comment]
I'm more or less guessing right now, but I can imagine that the `cargo metadata` call would just use the locally cached index when it exists locally? So you can try what you tried above but clear all cargo caches before trying to build?

**Comment by Nemo157** [comment]
Here's a way to reproduce it outside docs.rs using `bubblewrap` for network isolation:

```console
> cargo dl -e catgirl-engine
                          catgirl-engine   extracted catgirl-engine 0.12.7 to catgirl-engine-0.12.7

> cd catgirl-engine-0.12.7

> # Use an isolated cargo-cache directory so existing index entries don't affect the build
> export CARGO_HOME=$(mktemp -d)

> cargo fetch
    Updating crates.io index
    Updating crates.io index
  Downloaded cfg-if v1.0.0
  Downloaded adler v1.0.2
...
  Downloaded wayland-sys v0.31.1
  Downloaded 333 crates (79.8 MB) in 4.50s (largest was `windows` at 11.8 MB)

> mkdir target

> nix run pkgs#bubblewrap -- --ro-bind / / --dev /dev --tmpfs /tmp --ro-bind $PWD $PWD --ro-bind $CARGO_HOME $CARGO_HOME --bind $PWD/target $PWD/target --unshare-net -- cargo rustdoc
   Compiling compiler_builtins v0.1.108
   Compiling core v0.0.0 (/nix/store/cabkbj5ipghnp0l942s3s90rsdc7ak6k-rust-default-1.78.0-nightly-2024-03-12/lib/rustlib/src/rust/library/core)
...

error: failed to run custom build command for `catgirl-engine-client v0.12.7`

Caused by:
  process didn't exit successfully: `/tmp/scratch.rust.2024-03-13T09-20.kwhLWF/catgirl-engine-0.12.7/target/debug/build/catgirl-engine-client-ea8b9f3aaf3157a8/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at /tmp/nix-shell.r8wb7R/tmp.U8KRiZYftR/registry/src/index.crates.io-6f17d22bba15001f/build-info-build-0.0.36/src/build_script_options/crate_info.rs:101:10:
  called `Result::unwrap()` on an `Err` value: CargoMetadata { stderr: "    Updating crates.io index\nwarning: spurious network error (3 tries remaining): [7] Couldn't connect to server (Failed to connect to index.crates.io port 443 after 54 ms: Couldn't connect to server)\nwarning: spurious network error (2 tries remaining): [7] Couldn't connect to server (Failed to connect to index.crates.io port 443 after 0 ms: Couldn't connect to server)\nwarning: spurious network error (1 tries remaining): [7] Couldn't connect to server (Failed to connect to index.crates.io port 443 after 0 ms: Couldn't connect to server)\nerror: failed to get `build-info` as a dependency of package `catgirl-engine-client v0.12.7 (/tmp/nix-shell.r8wb7R/tmp.U8KRiZYftR/registry/src/index.crates.io-6f17d22bba15001f/catgirl-engine-client-0.12.7)`\n\nCaused by:\n  download of config.json failed\n\nCaused by:\n  failed to download from `https://index.crates.io/config.json`\n\nCaused by:\n  [7] Couldn't connect to server (Failed to connect to index.crates.io port 443 after 0 ms: Couldn't connect to server)\n" }
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/std/src/panicking.rs:645:5
     1: core::panicking::panic_fmt
               at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/core/src/panicking.rs:72:14
     2: core::result::unwrap_failed
               at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/core/src/result.rs:1654:5
     3: core::result::Result<T,E>::unwrap
               at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/core/src/result.rs:1077:23
     4: build_info_build::build_script_options::crate_info::read_manifest
               at /tmp/nix-shell.r8wb7R/tmp.U8KRiZYftR/registry/src/index.crates.io-6f17d22bba15001f/build-info-build-0.0.36/src/build_script_options/crate_info.rs:95:13
     5: build_info_build::build_script_options::BuildScriptOptions::drop_to_build_info
               at /tmp/nix-shell.r8wb7R/tmp.U8KRiZYftR/registry/src/index.crates.io-6f17d22bba15001f/build-info-build-0.0.36/src/build_script_options/mod.rs:66:7
     6: <build_info_build::build_script_options::BuildScriptOptions as core::ops::drop::Drop>::drop
               at /tmp/nix-shell.r8wb7R/tmp.U8KRiZYftR/registry/src/index.crates.io-6f17d22bba15001f/build-info-build-0.0.36/src/build_script_options/mod.rs:141:22
     7: core::ptr::drop_in_place<build_info_build::build_script_options::BuildScriptOptions>
               at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/core/src/ptr/mod.rs:515:1
     8: build_script_build::generate_build_info
               at ./build.rs:23:73
     9: build_script_build::main
               at ./build.rs:6:5
    10: core::ops::function::FnOnce::call_once
               at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/core/src/ops/function.rs:250:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by lexi-the-cute** [comment]
using this build script, i managed to isolate the problem to https://github.com/danielschemmel/build-info/blob/6039911685b74a543caf46fc5cfcbbf392f7efea/build-info-build/src/build_script_options/crate_info.rs#L101

```bash
#echo "Delete target directory"
#rm -r target

# Comment Out If Building From Source
rm -r catgirl-engine-*
echo "Downloading catgirl-engine"
# cargo install cargo-dl
cargo dl -e catgirl-engine
cd catgirl-engine-*

export CARGO_HOME=$(mktemp -d)
echo "CARGO_HOME is set to $CARGO_HOME"

echo "Fetching dependencies"
cargo fetch

echo "Creating blank target directory"
mkdir target

echo "Building project in isolation"
export RUST_BACKTRACE=full
export CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true
bwrap --ro-bind / / --dev /dev --tmpfs /tmp --ro-bind $PWD $PWD --ro-bind $CARGO_HOME $CARGO_HOME --bind $PWD/target $PWD/target --unshare-net -- cargo rustdoc
```

**Comment by lexi-the-cute** [comment]
im making sure to keep the build-info dev updated so they can hopefully resolve the issue https://github.com/danielschemmel/build-info/issues/21

**Comment by lexi-the-cute** [comment]
i tried using feature flags to disable this for DOCS_RS only, but it seems the DOCS_RS flag gets ignored when compiling a dependency reliant on build-info. https://docs.rs/crate/catgirl-engine-client/0.12.13/builds/1160595

https://github.com/lexi-the-cute/catgirl-engine/blob/e76353387c0a802cf2469f8edcd596ee63f6675c/Cargo.toml

**Comment by Nemo157** [comment]
You need `no-default-features = true` in the metadata to avoid the default-active feature flag.

**Comment by lexi-the-cute** [comment]
Thanks! I figured out I could just fake the build data until the offline mode feature is implemented into the crate

**Comment by lexi-the-cute** [comment]
Yeah. I guess it's resolved. I'm having to work around it with the fake BUILD_INFO data, but that part's out of the scope of docs.rs and I can build on docs.rs now. Thanks!
