### ISSUE TITLE
Bevy Engine docs aren't detailed

### ISSUE THREAD

**Issue by Blainegith** [rust-lang/docs.rs#2459]
The input struct `ButtonInput`'s docs page aren't contains usage examples of the input enum `KeyCode`.

https://docs.rs/bevy/latest/bevy/input/prelude/struct.ButtonInput.html

**Comment by Nemo157** [comment]
We just host the docs defined by the crates themselves, if you click the `bevy-0.13.0` menu in the top-bar that should open a dropdown with a link to their repository so you can create an issue there.
