### ISSUE TITLE
[Build Failure] cedar-local-agent 2.0.0

### ISSUE THREAD

**Issue by ShiromMakkad** [rust-lang/docs.rs#2460]
### Crate name

cedar-local-agent

### Build failure link

https://docs.rs/crate/cedar-local-agent/2.0.0/builds/1158175

### Additional details

I've published cedar-local-agent to crates.io, but it looks like the build is failing because of a compilation issue in a dependent crate. I've tried to reproduce this issue locally on my mac and on a RHEL linux server, but it compiles fine and generates docs with `cargo doc`. 

Strangely, I also published an update to avp-local-agent today which built just fine even though it depends on the same crate. Also, the dependent crate's docs built fine too and are published. 

A couple points from https://docs.rs/about/builds:
- We have no logic that runs specifically for docs.rs/doc generation
- We have no `build.rs`
- The build didn't fail due to a resource limitation, and the crate is small. It should build easily within the given constraints
- It doesn't depend on any non-rust dependencies (unless one of our dependencies does and somehow we didn't know because it's on every machine we've tried), and the build failure isn't related to a non-rust dependency. 

I see that doc.rs uses a nightly version of Rust to compile crates. Maybe our crate had a conflict with yesterday's version that's fixed today. Can you run a rebuild and see if that fixes it? Thanks.

**Comment by Nemo157** [comment]
Just queued a rebuild, it looks like cedar-policy got hit by a recent soundness fix and has released a new patch version that avoids the issue https://github.com/cedar-policy/cedar/pull/712

**Comment by Nemo157** [comment]
And it succeeded.

**Comment by ShiromMakkad** [comment]
Thank you!
