### ISSUE TITLE
big_space 0.5.0 Build Failed

### ISSUE THREAD

**Issue by Dreae** [rust-lang/docs.rs#2461]
### Crate name

big_space

### Build failure link

https://docs.rs/crate/big_space/0.5.0/builds

### Additional details

`big_space` is not my crate, but I took a look through the crate's Cargo.toml and the build log. There is no build.rs, the crate's only dependencies are `bevy` and `bevy_framepace` and the required versions of both have both been built successfully by docs.rs.

There were no errors in the build log, but there also doesn't seem to be any cargo/rustc output in the build log either

**Comment by syphar** [comment]
It's odd that the logs don't show errors. 

For now I queued a rebuild
