### ISSUE TITLE
[Android Doc Builds]: Fails to missing compiler

### ISSUE THREAD

**Issue by lexi-the-cute** [rust-lang/docs.rs#2463]
### Crate name

catgirl-engine

### Build failure link

https://docs.rs/crate/catgirl-engine/0.12.17/builds/1160654/aarch64-linux-android.txt

### Additional details

Android docs fail to build due to missing compiler. This affects catgirl-engine, catgirl-engine-utils, catgirl-engine-server, catgirl-engine-client for aarch64-linux-android, armv7-linux-androideabi, i686-linux-android, and x86_64-linux-android

**Comment by syphar** [comment]
I don't know much a out this specific target platform. 

[We're using cross compilation to build most platforms](https://docs.rs/about/builds), if the needed compiler has a ubuntu package, you [can add it to our build environment](https://github.com/rust-lang/crates-build-env). 

With C/C++ dependencies a way often used is to use conditional compilation to not compile the dependency for docs, of course this only works if the public interface of your library doesn't depend on the C/C++ code.

**Comment by lexi-the-cute** [comment]
Thanks! It does need a C compiler to build the android builds. Specifically the Android NDK. I'll have to find out if there's an Ubuntu package for it. I'm not sure how to build it without the C Compiler as the C Compiler is automatically invoked for me

**Comment by syphar** [comment]
@lexi-the-cute any update here? Can we close this issue?

**Comment by lexi-the-cute** [comment]
yee

**Comment by lexi-the-cute** [comment]
i gave up on it for now, so ill close the issue

**Comment by syphar** [comment]
ok, I understand, feel free to ping us again if we can help
