### ISSUE TITLE
Add links that point to crates.io

### ISSUE THREAD

**Issue by FoxtrotCZ** [rust-lang/docs.rs#2468]
Hi,
when I land on Docs.rs from Google I can read some info about the package but there is missing direct link to Crates.io.
Currently I have to manually search the package on Crates.io

Meanwhile simple direct link would make things much easier. You could just directly go to official crate page. No worry that you accidently mistyped and ended on different similarly named crate.

Every crate on Crates.io links to documentation on Docs.rs. So why shouldn't Docs.rs link to Crates.io.

Thanks.

**Comment by syphar** [comment]
Hi, 

We have a link to crates.io in the dropdown menu, is that what you mean? 

![image](https://github.com/rust-lang/docs.rs/assets/540890/1a387da0-0594-4c0a-9102-cca2d962660b)

**Comment by FoxtrotCZ** [comment]
I cant believe I missed this.
Thanks, this is it.
Closing.
