### ISSUE TITLE
Compile error occurs when the build target is x86_64-apple-darwin and using cross-compile dependency

### ISSUE THREAD

**Issue by libark** [rust-lang/docs.rs#2475]
### Crate name

core-media

### Build failure link

https://docs.rs/crate/core-media/0.1.6/builds/1174883

### Additional details

```warning: objc_exception@0.1.2: Compiler version doesn't include clang or GCC: "cc" "--version"
warning: objc_exception@0.1.2: cc: error: unrecognized command-line option '-arch'
warning: objc_exception@0.1.2: cc: error: unrecognized command-line option '-mmacosx-version-min=10.7'

error: failed to run custom build command for `objc_exception v0.1.2`

**Comment by Nemo157** [comment]
AFAIK https://github.com/rust-lang/docs.rs/issues/1957#issuecomment-1365862227 is still correct, there is no way we can ship the necessary sdk to properly support cross-compiling to apple targets. You will need to either avoid the `objc_exception` dependency when building on docs.rs or get them to detect docs.rs and skip trying to build the C code.

**Comment by syphar** [comment]
this sounds like
- the actual solution is #1957 (building on target platform + necessary SDKs) 
- until then, the crate authors can make the crate build via cross compilation with conditional compilation.
