### ISSUE TITLE
show "source file too big" when fetching source files that are bigger than our limit

### ISSUE THREAD

**Issue by syphar** [rust-lang/docs.rs#2481]
We regularly see errors in our source views where the file size extends our configured `Config::max_file_size` or `Config::max_file_size_html`. 

Since we're currently not streaming the content, and we do syntax hilighting on these files, we limit the size. 

In case of the respective error (`error::SizeLimitReached`), we could show a better error to the user instead of just "error fetching source file". Also we don't need this to be a server error and reported as such. 

This is an example file that is too big: `https://docs.rs/crate/qt_core/latest/source/ritual_db_v1.json`, we [have more in sentry](https://rust-lang.sentry.io/issues/5077161710/?environment=production&project=5499376&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=90d&stream_index=5)

**Comment by syphar** [comment]
- the respective handler is `web::source::source_browser_handler` 
- using `templates/crate/source.html` as template.

**Comment by shusann01116** [comment]
@syphar hi, I want to take a look into this issue as a newbie.

I couldn't find signature you have mentioned above searching entire code in this repo. Could you provide me with more specific suggestion about this?

**Comment by syphar** [comment]
this is awesome, thank you for the help! will look at the PR

**Comment by shusann01116** [comment]
I think this issue can be closed for now 😂 
I misused the closing keywords...

**Comment by syphar** [comment]
Very true, thanks!
