### ISSUE TITLE
Can't build crates that need to download C/C++ dependencies from github

### ISSUE THREAD

**Issue by yesint** [rust-lang/docs.rs#2500]
### Crate name

molar_powersasa, molar_gromacs

### Build failure link

https://docs.rs/crate/molar_powersasa/0.1.2/builds/1156669

### Additional details

These crates are wrappers over C/C++ code that is built with CMake. CMake fetches C++ libraries (such as Eigen) from github on the configuration stage. Since docs.rs docker containers have no access to the network the build fails.

**Comment by syphar** [comment]
Hello, 

we won't allow network access in the build for security reasons, so you'll have to find another solution. 

Typically folks do: 
- vendor the needed header or library files 
- use [conditional compilation](https://docs.rs/about/builds#detecting-docsrs) to detect docs.rs, and run a build that doesn't need this dependency. Often the docs don't actually need it.
