### ISSUE TITLE
Request to rebuild axum-login docs

### ISSUE THREAD

**Issue by maxcountryman** [rust-lang/docs.rs#2514]
### Crate name

axum-login

### Build failure link

https://docs.rs/crate/axum-login/0.15.2/builds

### Additional details

Builds had been succeeding previously and seem to succeed locally so I wonder if this is a transient failure.

**Comment by syphar** [comment]
Docs.rs is building with the nightly rust compiler. 

I can reproduce the error using nightly too, so a rebuild won't change anything here.
