### ISSUE TITLE
Features page: link dependent features

### ISSUE THREAD

**Issue by llogiq** [rust-lang/docs.rs#2530]
Currently, the features page is already quite helpful for finding out about what dependencies' features a feature will activate, but it would be even more useful to make that depended-on features link to their respective entries in that crate's features page on docs.rs.

**Comment by syphar** [comment]
thank you for that idea! 

my first hunch is that this is definitely possible. 

It would involve: 
- parsing the feature definition properly (things like optional dependencies `krate?/feature` syntax 
- adding HTML anchors to the feature names in the view 
- using the stored dependencies so we know the semver of the dependences 
- generate a link to the correct anchor on that feature page, for the right semver of that dependency.
