### ISSUE TITLE
Rebuild docs for openvino crate 0.7.2

### ISSUE THREAD

**Issue by rahulchaphalkar** [rust-lang/docs.rs#2537]
### Crate name

openvino

### Build failure link

https://docs.rs/crate/openvino/0.7.2

### Additional details

Failed because dependencies weren't published, so it depended on a couple of yanked crates. Has been fixed now.
https://docs.rs/crate/openvino/0.7.2/builds/1275044

**Comment by syphar** [comment]
build is queued

**Comment by syphar** [comment]
( and already finished )
