### ISSUE TITLE
My crate build fails and the build error message is not very informative

### ISSUE THREAD

**Issue by wada314** [rust-lang/docs.rs#2542]
### Crate name

protoc-plugin-by-closure

### Build failure link

https://docs.rs/crate/protoc-plugin-by-closure/0.1.3/builds/1281496

### Additional details

Hello! As title says, my relatively-trivial crate is failing to build in docs.rs and the error message is not very useful.
My crate is just a single `lib.rs` src file... Just one special thing I can imagine is that it's depending on a cargo unstable feature `bindeps` so the crate is containing `.cargo/config.toml` file with a simple content:

```toml
[unstable]
bindeps = true
```

and the crate is depending on an binary-only carte [`protoc-plugin-bin`](https://docs.rs/crate/protoc-plugin-bin/0.1.0).

[My repository dir](https://github.com/wada314/puroro/tree/1a667e626b90e07f81596108eec8e12511b283d3/protoc-plugin-by-closure)

thanks in advance,

**Comment by syphar** [comment]
the actual error is: 

> error: failed to parse manifest at `/home/cratesfyi/workspace-builder/builds/protoc-plugin-by-closure-0.1.3/source Cargo.toml`
> Caused by:
>  `artifact = …` requires `-Z bindeps` (protoc-plugin-bin)

 ( I need to check why this part is missing in the logs )

**Comment by syphar** [comment]
short research result: 

for these pre-build errors we just render the error variant we get, in this case `rustwide::CommandError`, which only contains the status code. 

We additionally need to collect & show the _output_ in the cases the error is coming from cargo commands. 

( not sure if we should add this to rustwide, or use `LogStorage` from inside docs.rs)

**Comment by syphar** [comment]
https://github.com/rust-lang/docs.rs/pull/2635 should help with this
