### ISSUE TITLE
Crate failed to build

### ISSUE THREAD

**Issue by cBournhonesque** [rust-lang/docs.rs#2545]
### Crate name

lightyear

### Build failure link

https://docs.rs/crate/lightyear/0.16.2/builds/1284564

### Additional details

If I run locally
```
cargo rustdoc --open -p lightyear --features=metrics,webtransport,leafwing,websocket,steam,zstd,avian2d/2d,avian2d/f32,avian2d/parry-f32 -- --document-private-items -D warnings --cfg docsrc
```

the docs are generated correctly

**Comment by syphar** [comment]
I see you also asked on zulip, here my comment from there: 

> I'm not sure either.
> Compiling locally with cargo +nightly docs-rs works too, I'll need to run it locally in a docs-rs container to know more.
> Until then I just queued a rebuild.
> I also see the 0.15. builds succeed, what did change related to these dependencies?

**Comment by syphar** [comment]
I see you also asked on zulip, here my comment from there: 

> I'm not sure either.
> Compiling locally with cargo +nightly docs-rs works too, I'll need to run it locally in a docs-rs container to know more.
> Until then I just queued a rebuild.
> I also see the 0.15. builds succeed, what did change related to these dependencies?

**Comment by cBournhonesque** [comment]
I couldn't figure it out so I disabled the faulty dependency `avian` (https://docs.rs/avian2d/latest/avian2d/) and now it works ..

**Comment by syphar** [comment]
thank you for the update! 

I would still leave this issue open. My hunch is that the issue is somehow between the dependency resolver and offline mode, but I don't know much about the relation between both.
