### ISSUE TITLE
increase RAM or lower number of jobs for crates diffsl and diffsol

### ISSUE THREAD

**Issue by martinjrobins** [rust-lang/docs.rs#2546]
### Crate name

diffsl

### Build failure link

https://docs.rs/crate/diffsl/0.1.7-beta.2/builds/1285534

### Additional details

The diffsl crate builds a C++ library EnzymeAD, and this causes the docs.rs builder to run out of memory and kill the build (https://docs.rs/crate/diffsl/0.1.7-beta.2/builds/1285534). On my machine the c++ compile uses about 1 GB per job, so I think that gives about 6GB of RAM for the docs.rs builder, which is just hitting the current limit.

Is is possible to raise the RAM limit for diffsl? Alternatively, is there a way to lower the number of jobs? I tried to pass "-j 1" to the docs.rs cargo command, but this gave an error (https://docs.rs/crate/diffsl/0.1.7-beta.3/builds/1285606)

Note this also applies to a dependent crate diffsol (https://docs.rs/crate/diffsol/0.1.14/builds/1285478)

**Comment by syphar** [comment]
I increased the RAM limit to 8 GB for `diffsl` and `diffsol` and queued a rebuild for both mentioned releases above. 

We have some more room to increase the RAM limit further, so feel free to ping me here when this is not enough. 

The CPU-limit currently is a global config value for all builds, we _could_ introduce an additional optional per-crate cpu limit, should only be a small change.

**Comment by syphar** [comment]
the `diffsl` build passes now, and `diffsol` fails with another error. 

I'm closing this issue now, feel free to reopen / create a new one if you need a higher limit.
