### ISSUE TITLE
Does not build for MacOS and Windows target.

### ISSUE THREAD

**Issue by LogicFan** [rust-lang/docs.rs#2548]
### Crate name

voro_rs

### Build failure link

https://docs.rs/crate/voro_rs/0.0.3/builds/1287760/x86_64-pc-windows-msvc.txt
https://docs.rs/crate/voro_rs/0.0.3/builds/1287760/x86_64-apple-darwin.txt

### Additional details
these two target build filed. but it crate can be built successfully in my github action runner. 
https://github.com/LogicFan/voro_rs/actions/runs/9881150943/job/27291293495

**Comment by syphar** [comment]
From [our page about builds](https://docs.rs/about/builds#cross-compiling): 
>  All targets other than x86_64-unknown-linux-gnu are cross-compiled. For implementation reasons, this is unlikely to change for the foreseeable future.

Also related are #1957 and #796. 

So currently we cannot build directly on the target platforms. 

Your only option is to use conditional compilation to make your docs build with cross compilation.
