### ISSUE TITLE
Build fails due to DNS resolution problem

### ISSUE THREAD

**Issue by sophokles73** [rust-lang/docs.rs#2558]
### Crate name

up-rust

### Build failure link

https://docs.rs/crate/up-rust/0.1.1/builds/1295573

### Additional details

The build tries to retrieve some proto3 files from GitHub as part of the build.rs file but seems to fail in resolving the (GitHub) host.

**Comment by syphar** [comment]
we don't allow network access in our builds: https://docs.rs/about/builds#hitting-resource-limits 

The options you have are: 
- add the files to your repo so they are part of the package 
- use conditional compilation so you don't need the downloads for docs
