### ISSUE TITLE
LIEF Rust bindings need network access

### ISSUE THREAD

**Issue by romainthomas** [rust-lang/docs.rs#2563]
### Crate name

lief

### Build failure link

https://docs.rs/crate/lief/0.15.0/builds/1298479

### Why your crate needs the resource increases

As described here: https://lief.re/doc/latest/api/rust/index.html LIEF's rust bindings need network access (or setting `LIEF_RUST_PRECOMPILED`) to compile.

While trying to generate the documentation for the LIEF crate: https://crates.io/crates/lief,
I got this network denied issue.

**Comment by syphar** [comment]
Sorry, network access won't be allowed for any crate, see https://docs.rs/about/builds#hitting-resource-limits. 

Your best options are probably either vendoring or conditional compilation.

**Comment by romainthomas** [comment]
Ok thanks you the info
