### ISSUE TITLE
Rebuild request: SQLx 0.8.0 crates

### ISSUE THREAD

**Issue by abonander** [rust-lang/docs.rs#2565]
### Crate name

sqlx-core

### Build failure link

https://docs.rs/crate/sqlx-core/0.8.0/builds/1300456

### Additional details

The error message is misleading because we couldn't find a yanked crate in the dependencies.

This is likely due to the `dev-dependency` on the `sqlx` crate, which was published after `sqlx-core` and just wasn't in the index yet when docs.rs went to build it.

Also: `sqlx-postgres 0.8.0` https://docs.rs/crate/sqlx-postgres/0.8.0/builds/1300458

Looks like the rest of the crates built successfully. Is there any plan in the works to add some sort of automatic retry in this case so we don't have to request one manually?

**Comment by syphar** [comment]
I queued a rebuild for both releases. 

> Is there any plan in the works to add some sort of automatic retry in this case so we don't have to request one manually?

From what I remember we _are_ retrying failed builds, I could imagine for this case we are retrying to fast for the error to be resolved, and we should wait between attempts.

**Comment by syphar** [comment]
both builds succeeded.

**Comment by abonander** [comment]
> From what I remember we _are_ retrying failed builds, I could imagine for this case we are retrying to fast for the error to be resolved, and we should wait between attempts.

Yeah, I have to publish 5 other crates between `sqlx-core` and `sqlx` and that takes at least a few minutes, especially if I have to redo one because I forgot something. I'll get around to automating it eventually, but it still won't be instant.

> both builds succeeded.

Thanks!
