### ISSUE TITLE
Crate Build Failure for `holochain_scaffolding_cli`

### ISSUE THREAD

**Issue by c12i** [rust-lang/docs.rs#2566]
### Crate name

holochain_scaffolding_cli

### Build failure link

https://docs.rs/crate/holochain_scaffolding_cli/0.3000.2/builds

**Comment by syphar** [comment]
I'm not sure what I'm missing here, 

when I compile the release (I assume the `holochain-0.3` is the correct one) then I'm seeing the same error as in our docs.rs build. 

Or are you talking about another tag?

**Comment by c12i** [comment]
Hi @syphar thanks for replying, yes that is the correct tag, along with `holochain-0.2`, I will close this as the root cause for the build error has been discovered and will be addressed with the next release
