### ISSUE TITLE
Doc build fails on nightly preventing stable doc to be released

### ISSUE THREAD

**Issue by lerouxrgd** [rust-lang/docs.rs#2570]
### Crate name

datachannel

### Build failure link

https://docs.rs/crate/datachannel/0.13.1/builds/1307206

**Comment by syphar** [comment]
The error tells us the real reason to the build failure, which is not nightly: 

> CMake Error: Could not open file for write in copy operation /opt/rustwide/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/datachannel-sys-0.21.2/libdatachannel/include/rtc/version.h.tmp
CMake Error: : System Error: Read-only file system
CMake Error at CMakeLists.txt:263 (configure_file):
configure_file Problem configuring file

the build script for `datachannel-sys` seems to try to write into the source directories itself, and not into cargo `OUT_DIR` as it should.

**Comment by lerouxrgd** [comment]
Indeed this has been reported in [libdatachannel #1227](https://github.com/paullouisageneau/libdatachannel/issues/1227), it should be fixed with its next release.
