### ISSUE TITLE
`system-memory` crate builds on docs.rs but seems to be missing serveral of the targets specified in the metadata table.

### ISSUE THREAD

**Issue by vcfxb** [rust-lang/docs.rs#2575]
<https://crates.io/crates/system-memory> -- looks like this may be similar to #787 -- even super "common" tier 1 targets like `x86_64-pc-windows-msvc` aren't showing up on docs.rs.

**Comment by syphar** [comment]
there is a default limit of 10 targets we build: https://docs.rs/crate/system-memory/latest/builds . 

I extended the limit and queued a rebuild for the latest release.

**Comment by syphar** [comment]
<img width="339" alt="grafik" src="https://github.com/user-attachments/assets/d3554788-a7f9-478d-86e5-7c709a4d6e96">
