### ISSUE TITLE
HTML misformatting on crate page

### ISSUE THREAD

**Issue by ThePuzzlemaker** [rust-lang/docs.rs#2580]
See [here](https://docs.rs/crate/serde/latest). Tested both on Chromium and Firefox, in case it's a browser issue.
![image](https://github.com/user-attachments/assets/68d1a134-1524-4fa1-b7d8-f9615f82e80d)
![image](https://github.com/user-attachments/assets/917f0890-b408-4254-8d7f-617ea1692e5d)
Not sure where in the code this would be, but at some point this `<span>` is getting turned into `&lt;span&gt;`

**Comment by syphar** [comment]
this was solved in #2576 and then even better in #2578
