### ISSUE TITLE
Update to Go 1.11 in builds

### ISSUE THREAD

**Issue by joshlf** [rust-lang/docs.rs#259]
[This build error](https://docs.rs/crate/mundane/0.2.0/builds/125855) is caused by Go not being on version 1.11. Would it be possible to upgrade to that version? Would it possible to manually re-trigger the build once that's done so I don't have to publish a new version of the crate?

Relevant portion of build log:

```text
read_symbols.go:30:2: cannot find package \"boringssl.googlesource.com/boringssl/util/ar\" in any of:
\t/usr/lib/go-1.7/src/boringssl.googlesource.com/boringssl/util/ar (from $GOROOT)
\t($GOPATH not set)
```

**Comment by joshlf** [comment]
[This Twitter thread](https://twitter.com/joshlf_/status/1061019417880883200) has a discussion of feasibility. TLDR: We will need to wait until Go 1.11 is available on Debian.

**Comment by jyn514** [comment]
It looks like mundane is building successfully on https://docs.rs/crate/mundane/0.4.1, closing as wontfix (same rational as #333).
