### ISSUE TITLE
Docs failed, suspect duplicate function name in different modules.

### ISSUE THREAD

**Issue by kenba** [rust-lang/docs.rs#2598]
### Crate name

unit-sphere

### Build failure link

https://docs.rs/crate/unit-sphere/0.3.0/builds

### Additional details

The function `calculate_haversine_distance` was declared in both the `trig` module and the `lib` module.  
I suspect that this may have been the cause of the failure despite `cargo doc --open` and `cargo clippy --all-features` reporting **no** errors when built with `rustc 1.81.0 (eeb90cda1 2024-09-04)`.

I've published a new version `0.3.1` of the crate with `lib::calculate_haversine_distance` renamed to `lib::calculate_haversine_distance` in an attempt to workaround the issue.

**Comment by syphar** [comment]
From what I see in the logs, it seems to be the issue is https://github.com/dimforge/nalgebra/issues/1437, or to be more exact, https://github.com/rust-lang/rust/issues/130056

**Comment by syphar** [comment]
I froze the nightly version that docs.rs uses and queued rebuilds for all releases on these nightlies. 

I assume when the builders worked through the list we're fine again. 

If not, feel free to reopen this issue
