### ISSUE TITLE
Kornia crate docs cannot build because of not found gstreamer libs

### ISSUE THREAD

**Issue by edgarriba** [rust-lang/docs.rs#2610]
### Crate name

kornia-io

### Build failure link

https://docs.rs/crate/kornia-io/0.1.6-rc.5/builds/1364839

### Why your crate needs the resource increases

hi, I'm facing some issues to build the docs of the `kornia-io` crate:

- `kornia-io`: https://docs.rs/crate/kornia-io/0.1.6-rc.5 (the one actually crashing with `all-features` enabled)
- `kornia`: https://docs.rs/kornia/latest/kornia (main crate using the above, not showing all the features)

The `kornia-io` has a couple of feature flags that depends on system dependencies like `nasm` or `gstreamer` which seems to be the issue while building the docs the crates.io.

I wanted to take also this opportunity to ask what's is the recommended way to upload the docs under this conditions. For all the deployment and testing I have a very simple docker file: https://github.com/kornia/kornia-rs/blob/main/devel-x86_64.Dockerfile

For publishing crates the only way I found to work around is via a separated bash **script as I couldn't figure from github actions to do it properly reusing the dockerfile. 

**https://github.com/kornia/kornia-rs/blob/main/scripts/release_rust.sh

**Comment by syphar** [comment]
you can add needed system dependencies into our build image. see 
- https://docs.rs/about/builds#missing-dependencies
- https://forge.rust-lang.org/docs-rs/add-dependencies.html
