### ISSUE TITLE
failed to generate `/tmp/.tmp1rdtAC/program.o` when building libbpf-rs based crate

### ISSUE THREAD

**Issue by arloor** [rust-lang/docs.rs#2619]
### Crate name

cgroup_traffic

### Build failure link

https://docs.rs/crate/cgroup_traffic/0.1.3/builds/1372216

### Additional details

This is a crate based on libbpf-rs. The build.rs use clang to generate ebpf intermediate code. But if failed and compained that it cannot write to tmpfs

```bash
called `Result::unwrap()` on an `Err` value: failed to generate `/tmp/.tmp1rdtAC/program.o`
```

**Comment by syphar** [comment]
Right now, everything except cargo `OUT_DIR` is readonly, see also [our documentation](https://docs.rs/about/builds#read-only-directories). 

So if the library writes to the directory in the `OUT_DIR`, you're fine. 

Thinking about this generally, I'm not sure why `/tmp/` isn't writeable too, though I'm not sure if it then should be a docker volume, or link to a temporary directory on our build server host.
