### ISSUE TITLE
kube-custom-resources-rs failed to build

### ISSUE THREAD

**Issue by sebhoss** [rust-lang/docs.rs#2624]
### Crate name

kube-custom-resources-rs

### Build failure link

https://docs.rs/crate/kube-custom-resources-rs/2024.10.1/builds/1375891

### Additional details

The build outputs says that `the crate depends on yanked dependencies` but I checked all dependencies and could not find anything that was yanked. Would it be possible to enrich the error reporting here?

**Comment by syphar** [comment]
currently the logs for these errors are limited, sorry about that, it's on my todo list (but some work). 

from our logs, after trying a rebuild: 
```
[stderr] error: failed to select a version for the requirement `k8s-openapi = "^2024.10.1"`
[stderr] candidate versions found which didn't match: 0.23.0, 0.22.0, 0.21.1, ...
```

**Comment by sebhoss** [comment]
Ok ok - thanks for the logs! This is actually helped me figure out the problem: I overwrite the version of the crate in a GitHub action using a `sed` call which worked fine in previous versions, however I recently changed how dependency versions are declared and thus `sed` now changes too much.

Sorry for the noise & thanks again for the help!

**Comment by syphar** [comment]
@sebhoss 
> Sorry for the noise & thanks again for the help!

no worries, docs.rs should also be better here. 

small tipp: 
you can use [`cargo +nightly docs-rs`](https://github.com/dtolnay/cargo-docs-rs) in our CI (probably after the `sed` call) to test if generating docs works. 

It's not 100% complete, but very near to the actual commands we run on our build server

**Comment by sebhoss** [comment]
ok ok will do!
