### ISSUE TITLE
Crate generating code with bindgen failed to build

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [rust-lang/docs.rs#2627]
### Crate name

libproc-rs

### Build failure link

https://docs.rs/crate/libproc/0.14.9/builds/1380760

### Additional details

Build script is here: https://github.com/andrewdavidmackenzie/libproc-rs/blob/master/build.rs

on macos the generated file is included by lib.rs https://github.com/andrewdavidmackenzie/libproc-rs/blob/master/src/lib.rs

with 
```
#[cfg(target_os = "macos")]
#[allow(warnings, missing_docs)]
mod osx_libproc_bindings {
    include!(concat!(env!("OUT_DIR"), "/osx_libproc_bindings.rs"));
}
```

and that fails to build with:
```
[INFO] [stderr]  Documenting libproc v0.14.9 (/opt/rustwide/workdir)
[INFO] [stderr] error: couldn't read /opt/rustwide/target/aarch64-apple-darwin/debug/build/libproc-305d8c67d250c2df/out/osx_libproc_bindings.rs: No such file or directory (os error 2)
[INFO] [stderr]   --> src/lib.rs:67:5
[INFO] [stderr]    |
[INFO] [stderr] 67 |     include!(concat!(env!("OUT_DIR"), "/osx_libproc_bindings.rs"));
[INFO] [stderr]    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[INFO] [stderr]    |
[INFO] [stderr]    = note: this error originates in the macro `include` (in Nightly builds, run with -Z macro-backtrace for more 
```

Is there any way I can fix this?

**Comment by syphar** [comment]
I'm not 100% sure what the problem is, but let's walk through it. 

More information about the build environment: https://docs.rs/about/builds 

docs.rs is using cross compilation to build docs for non linux targets, so xcode headers won't exist. 
My hunch would be that this is the reason for this error, though I'm not sure why you are not seeing an error from the build script. 

So might try running the build on a linux host, cross compiling to mac.

**Comment by andrewdavidmackenzie** [comment]
So, maybe I could detect docs.rs in build.rs and use vendored headers
instead of the generated ones....?

Would want to never actually compile with possibly out of date headers....

**Comment by syphar** [comment]
> So, maybe I could detect docs.rs in build.rs and use vendored headers instead of the generated ones....? Would want to never actually compile with possibly out of date headers....

That, or don't include any headers on docs.rs, don't generate any bindings, 
and use conditional compilation (`#[cfg(docsrs)]`) to make the code compile. 

( assuming the generated bindings are not part of the public interface of your library)

**Comment by andrewdavidmackenzie** [comment]
Is there anyway to test the build, without me having to do a release
each time?

**Comment by syphar** [comment]
- https://docs.rs/about/builds#testing-builds-locally
- https://github.com/rust-lang/docs.rs/blob/master/README.md#build-subcommand

( though to set it up is a little time intensive, and I'm not 100% certain if the documentation is 100% up-to-date)

**Comment by andrewdavidmackenzie** [comment]
I have fixed this using a pre-generated version of the macos bindings from a manual run of bindgen when building on docs.rs, otherwise I use the generated version as before, using `#[cfg(docsrs)]` in `build.rs`

The result can be seen here: https://docs.rs/crate/libproc/latest

and now I have the two platforms available in the drop-down.

Thanks for your help.
