### ISSUE TITLE
GTK4_NO_PKG_CONFIG error while building crate documentation

### ISSUE THREAD

**Issue by uriegel** [rust-lang/docs.rs#2630]
### Crate name

webview_app

### Build failure link

https://docs.rs/crate/webview_app/1.0.0-beta.8/builds

### Additional details

The automatic build on publish failed with:

[INFO] [stderr] warning: target filter specified, but no targets matched; this is a no-op
[INFO] [stderr]     Checking futures-util v0.3.31
[INFO] [stderr]     Checking gio-sys v0.20.4
[INFO] [stderr]     Checking pango-sys v0.20.4
[INFO] [stderr]    Compiling gdk4-sys v0.9.2
[INFO] [stderr]     Checking graphene-sys v0.20.4
[INFO] [stderr]    Compiling gtk4-sys v0.9.2
[INFO] [stderr] error: failed to run custom build command for `gdk4-sys v0.9.2`
[INFO] [stderr] 
[INFO] [stderr] Caused by:
[INFO] [stderr]   process didn't exit successfully: `/opt/rustwide/target/debug/build/gdk4-sys-e017c0dab28e64ae/build-script-build` (exit status: 1)
[INFO] [stderr]   --- stdout
[INFO] [stderr]   cargo:rerun-if-changed=/opt/rustwide/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/gdk4-sys-0.9.2/Cargo.toml
[INFO] [stderr]   cargo:rerun-if-env-changed=GTK4_NO_PKG_CONFIG
[INFO] [stderr]   cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
[INFO] [stderr]   cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
[INFO] [stderr]   cargo:rerun-if-env-changed=HOST_PKG_CONFIG
[INFO] [stderr]   cargo:rerun-if-env-changed=PKG_CONFIG
[INFO] [stderr]   cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
[INFO] [stderr]   cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
[INFO] [stderr]   cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
[INFO] [stderr]   cargo:rerun-if-env-changed=PKG_CONFIG_PATH
[INFO] [stderr]   cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
[INFO] [stderr]   cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
[INFO] [stderr]   cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
[INFO] [stderr]   cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
[INFO] [stderr]   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
[INFO] [stderr]   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
[INFO] [stderr]   cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
[INFO] [stderr]   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
[INFO] [stderr] 
[INFO] [stderr]   --- stderr
[INFO] [stderr] 
[INFO] [stderr]   pkg-config exited with status code 1
[INFO] [stderr]   > PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1 pkg-config --libs --cflags gtk4 gtk4 >= 4.14
[INFO] [stderr] 
[INFO] [stderr]   The system library `gtk4` required by crate `gdk4-sys` was not found.
[INFO] [stderr]   The file `gtk4.pc` needs to be installed and the PKG_CONFIG_PATH environment variable must contain its parent directory.
[INFO] [stderr]   The PKG_CONFIG_PATH environment variable is not set.
[INFO] [stderr] 
[INFO] [stderr]   HINT: if you have installed the library, try setting PKG_CONFIG_PATH to the directory containing `gtk4.pc`.
[INFO] [stderr] 
[INFO] [stderr] warning: build failed, waiting for other jobs to finish...
[INFO] running `Command { std: "docker" "inspect" "916f694b427c3d4907967e78417b5bb4d2f69cf65034cbe09ac6ae5fc91ebbd7",

**Comment by syphar** [comment]
please see [our docs about missing dependencies](https://docs.rs/about/builds#missing-dependencies). 

in short: you can add the packages to our build environment yourself. 

If that doesn't work, the option mostly used is to use conditional compilation to make the docs build _without_ the need for the library
