### ISSUE TITLE
Please increase timeout time for `rerun`

### ISSUE THREAD

**Issue by emilk** [rust-lang/docs.rs#2638]
### Crate name

rerun

### Build failure link

https://docs.rs/crate/rerun/0.19.0/builds/1395475

### Requested timeout

30

### Why your crate needs the resource increases

It timed out after 15 minutes.

Running `cargo doc -p rerun` locally on my MacBook (using 1.84.0-nightly 8c30ce536 2024-10-15) finishes in 1m15s (270s user), so I don't think it's hitting any particular "exponential-time" bug or similar.

**Comment by syphar** [comment]
I've increased the time limit to 30 minutes and queued a rebuild

Please keep in mind, according to our policies ( see [here](https://docs.rs/about/builds#hitting-resource-limits)) we only increase the time limit when we add a limit to one target at the same time.

**Comment by johndpierre1** [comment]
John
