### ISSUE TITLE
It failed to build bindings crate

### ISSUE THREAD

**Issue by thewh1teagle** [rust-lang/docs.rs#2654]
### Crate name

sherpa-rs

### Build failure link

https://docs.rs/crate/sherpa-rs/0.5.1/builds/1404232

### Additional details

Looks like the build script can't download file from Github.
By default the `download-binaries` feature enabled for fast build. It downloads prebuilt c++ library and link it.
Though, when I disabled it, it also failed to build on docs.rs.

By the way I can build it locally. is there a way to manually upload the docs to docs.rs?

**Comment by syphar** [comment]
Please check out our documentation page about the build environment: https://docs.rs/about/builds. 

Specifically network access won't be allowed generally. 

The most used options currently possible are you vendoring the needed files into your crate, or use conditional compilation to let the docs build without the need for the external library. 

Uploading your own docs is not possible right now, we're tracking this request in #93. A bunch of questions in there are unanswered, especially on how to prevent malicious docs to be uploaded.

**Comment by thewh1teagle** [comment]
The solution was to check `DOCS_RS` env variable and avoid build anything except the bindings with bindgen.

https://github.com/thewh1teagle/sherpa-rs/blob/66119f8f281a7fbd2ab0b04e0152fcbee553dfde/crates/sherpa-rs-sys/build.rs#L319
