### ISSUE TITLE
show documentation & source size on crate-detail page

### ISSUE THREAD

**Issue by syphar** [rust-lang/docs.rs#2658]
The sizes we started collecting in https://github.com/rust-lang/docs.rs/pull/2644 

on this page: https://docs.rs/crate/itertools/latest

I could imagine showing just the doc & source size for the latest build, perhaps similar to coverage?

**Comment by GuillaumeGomez** [comment]
I think it makes more sense to only show it for the last version.

**Comment by syphar** [comment]
you mean the latest build? 

the crate-detail page is version specific, so we would show the size of that version, if available

**Comment by GuillaumeGomez** [comment]
Ah right, forgot about that. Then sure. Sending a PR.
