### ISSUE TITLE
self-documenting info for documentation & source size

### ISSUE THREAD

**Issue by robo9k** [rust-lang/docs.rs#2662]
Showing "source code size" and "documentation size" on the versioned crate pages was introduced in #2658 

This could be improved by explaining how those sizes are calculated.

Taking the `byte-unit@5.1.6` example from https://toot.cat/@imperio/113415145952455653
[docs.rs](https://docs.rs/crate/byte-unit/5.1.6) shows "212.28 kB"
[crates.io](https://crates.io/crates/byte-unit/5.1.6) shows "25.9 KiB"

So "source code size" is not simply size of all (source code) files in "crate size". What does it entail, what is not part of it?
For "documentation size" there is no discrepancy, but an explanation would help here aswell.

Ideally those 2 websites would also use the same byte units.

**Comment by GuillaumeGomez** [comment]
This is indeed something that should be there. Gonna fix it in the next days.
