### ISSUE TITLE
metadata targets default is not applied when building crate documentation on docs.rs locally

### ISSUE THREAD

**Issue by jofas** [rust-lang/docs.rs#2668]
I followed the [setup](https://github.com/rust-lang/docs.rs?tab=readme-ov-file#getting-started) described in the README to set up docs.rs locally. I then built the documentation for a crate like [so](https://github.com/rust-lang/docs.rs?tab=readme-ov-file#build-subcommand). Works fine, but I realised that the `[package.metadata.docs.rs.targets]` weren't using the [same defaults as docs.rs uses](https://docs.rs/about/metadata), i.e. my docs were only built for the default target `x86_64-unknown-linux-gnu`, not for all `x86_64-unknown-linux-gnu`, `x86_64-apple-darwin`, `x86_64-pc-windows-msvc`, `i686-unknown-linux-gnu` and `i686-pc-windows-msvc` targets, which I had expected. This was easily fixed by specifying those targets explicitly in my `Cargo.toml` file, but I still found this a bit confusing. Is this expected behaviour? If so, we might could document this discrepancy between local builds and the build process of https://docs.rs? If this isn't the desired behaviour, I'd be happy to PR applying the default targets to local builds as well.

**Comment by syphar** [comment]
This sounds like the `include_default_targets` setting: 
https://github.com/rust-lang/docs.rs/blob/ca5e7076fa112204a72eafeaad2178aa471d3366/src/config.rs#L239

**Comment by syphar** [comment]
our `.env.sample` disables this to local builds run faster for developing docs.rs itself. 

so just removing `DOCSRS_INCLUDE_DEFAULT_TARGETS` from your `.env` is good enough, or setting it to `true`

**Comment by GuillaumeGomez** [comment]
Sounds like something that should be mentioned in the README. ;)

**Comment by jofas** [comment]
Indeed. I used `.env.sample` and it sets `DOCSRS_INCLUDE_DEFAULT_TARGETS` to `false`. Adding a comment to `.env.sample` seems like a straight-forward thing to do, although I don't know if I would've paid enough attention to it. I'm not sure if a section in the README about the environment variables would be a good idea, it adds maintenance overhead and in my experience documentation of the environment gets outdated and false rather quickly. I might've discovered this option quicker if we had a `--include-default-targets` argument on the `build crate` subcommand.
