### ISSUE TITLE
The link to BigUInt fails.

### ISSUE THREAD

**Issue by piaoyh** [rust-lang/docs.rs#2673]
### Crate name

cryptocol

### Build failure link

https://docs.rs/cryptocol/0.8.5-fix.1/cryptocol/number/big_uint/struct.BigUInt.html#struct.BigUInt

### Why your crate needs the resource increases

So far, I haven't had any problem to publish my crate cryptocol. But from version 0.8.5 on, I have a problem in the published documents. In the documents on the website (https://docs.rs/cryptocol/0.8.5-fix.1/cryptocol/index.html), the link to the page of struct BigUInt (for example, https://docs.rs/cryptocol/0.8.5-fix.1/cryptocol/number/big_uint/struct.BigUInt.html#struct.BigUInt) fails. Other links such as SmallUInt (https://docs.rs/cryptocol/0.8.5-fix.1/cryptocol/number/small_uint/trait.SmallUInt.html#trait.SmallUInt) work fine in the documents on the same website.

When I compiled the documentation by "cargo doc" on my local machine, I found that the compilation of documents were successful and all the link including the link to BigUInt in the documents worked fine. However, it does not work only on website. Can you please check whether or not  my crate cryptocol reaches the limitation? If the reason why the link fails is due to the server, please fix it. If the reason is in my documentation, please let me know how to fix it.
Thank you in advance.

**Comment by syphar** [comment]
hi, 

thank you for the report, I couldn't dig into this yet, as to why the links don't work. 

In the past these kind of issues were mostly a problem in the crate itself, and only sometimes an issue with cross crate links.

**Comment by piaoyh** [comment]
Please read the post #2676. I wrote the problem in far more detail.
