### ISSUE TITLE
please rebuild rerun 0.20.0 docs - failed due to spurious network error

### ISSUE THREAD

**Issue by astraw** [rust-lang/docs.rs#2674]
### Crate name

rerun

### Build failure link

https://docs.rs/crate/rerun/0.20.0/builds/1536551

### Additional details

Hi, as far as I can tell, the build of docs for rerun 0.20.0 https://docs.rs/crate/rerun/0.20.0/builds failed due to spurious network errors. Could you please trigger a re-build? Thanks!

**Comment by syphar** [comment]
A rebuild won't help here. 

From what I see, one of the build-scripts tries to run `cargo metadata`, which needs network access. 

And we don't (and never will) allow network access in the build process: https://docs.rs/about/builds 

It _looks_ like it's the build-script from `re_viewer` , which is calling something from `re_build_tools`, which then calls `cargo metadata`.

**Comment by astraw** [comment]
Thanks, I filed a regression with rerun at https://github.com/rerun-io/rerun/issues/8165

**Comment by syphar** [comment]
perfect, thanks! 

feel free to comment / reopen here if I'm wrong.
