### ISSUE TITLE
The server seems to fail to generate the documentation page BigUInt.

### ISSUE THREAD

**Issue by piaoyh** [rust-lang/docs.rs#2676]
### Crate name

cryptocol

### Build failure link

https://docs.rs/cryptocol/latest/cryptocol/number/big_uint/struct.BigUInt.html#struct.BigUInt

### Why your crate needs the resource increases

Up to the version 0.8.4 or earlier, if you click the tap `18 versions` on the website (https://crates.io/crates/cryptocol) and then you click the item `0.8.4` as shown bellow:

![Image](https://github.com/user-attachments/assets/210764ed-c701-4879-a43b-638308cbb7e4)

then the browser will navigate to the page (https://crates.io/crates/cryptocol/0.8.4). Then if you click the link of **docs.rs/cryptocol/0.8.4** on the right side of the cryptocol introduction page of crate.io (https://crates.io/crates/cryptocol) as shown below:

![Image](https://github.com/user-attachments/assets/5333955f-237e-4d65-8b10-760b71ae8aa3)

then the browser navigates to the main page of the crate cryptocol through the link (https://docs.rs/cryptocol/0.8.4/cryptocol/). There, if you click the link **BigUInt** (https://docs.rs/cryptocol/0.8.4/cryptocol/number/big_uint/struct.BigUInt.html#struct.BigUInt) to the documentation page of **BigUInt** as shown below:

![Image](https://github.com/user-attachments/assets/099d32de-4a34-4afe-8527-70d39cc5ac3c)

then the server generates the documentation page of BigUInt which the link (https://docs.rs/cryptocol/0.8.4/cryptocol/number/big_uint/struct.BigUInt.html#struct.BigUInt) is pointing to, and the browser shows the documentation page of **BigUInt**  (https://docs.rs/cryptocol/0.8.4/cryptocol/number/big_uint/struct.BigUInt.html#struct.BigUInt) correctly and successfully without any problem as shown below:

![Image](https://github.com/user-attachments/assets/60875aad-c1cf-4096-a64b-6342f0ad14f6)

That is fine!!!

**However**, from the version 0.8.5 on, when you click the link of **BigUInt** of the cryptocol introduction page of crate.io (https://crates.io/crates/cryptocol) as shown below:

![Image](https://github.com/user-attachments/assets/49fe96bb-4b3a-47c8-ba1a-b472503e527b)

then the browser navigates to the documentation page of BigUInt through the link (https://docs.rs/cryptocol/latest/cryptocol/number/big_uint/struct.BigUInt.html#struct.BigUInt), but the server does not generate the documentation page of BigUInt which the link (https://docs.rs/cryptocol/latest/cryptocol/number/big_uint/struct.BigUInt.html#struct.BigUInt) is pointing to, and the browser shows the page as shown below:

![Image](https://github.com/user-attachments/assets/600401cb-3a8f-4830-8247-cd6fb2ddf1f9)

in which it is written as follows:
**The requested resource does not exist**
no such resource. 

**Also** if you click the link of **docs.rs/cryptocol/0.8.5** on the right side of the cryptocol introduction page of crate.io (https://crates.io/crates/cryptocol) as shown below:

![Image](https://github.com/user-attachments/assets/f2e152b8-3a36-4bdb-b313-d709347213ed)

then the browser navigates to the main page of the crate cryptocol through the link (https://docs.rs/cryptocol/0.8.5/cryptocol/). There, if you click the link **BigUInt** (https://docs.rs/cryptocol/0.8.5/cryptocol/number/big_uint/struct.BigUInt.html#struct.BigUInt) to the documentation page of **BigUInt** as shown below:

![Image](https://github.com/user-attachments/assets/2b5cba93-c0f6-4789-9e8e-3665a9444b32)

then the server generates the documentation page of **BigUInt** which the link (https://docs.rs/cryptocol/0.8.5/cryptocol/number/big_uint/struct.BigUInt.html#struct.BigUInt) is pointing to, but the server does not generate the documentation page of **BigUInt** which the link is pointing to, but the browser shows the page as shown below:

![Image](https://github.com/user-attachments/assets/0cb79a97-be39-4034-966f-738075511ca7)

in which it is written as follows:
**The requested resource does not exist**
no such resource.

Actually, the source file '/src/number/big_uint.rs' has more than 40,000 lines as shown below and it will get more as I develop more. I don't know whether or not it reaches the limitation.

![Image](https://github.com/user-attachments/assets/8c255586-37d4-471e-b76d-1beb5f9cacb7)

Please dig this problem and let me know the reason if the reason is in my work. And if the reason of the problem is in the server, please fix it.

If you need more information about this problem, please let me know.

Many blessings

**Comment by syphar** [comment]
Hi, sorry for the delay here, was swamped with daywork, and the other docs.rs production issues :) 


I'm not sure what the problem is, but will investigate. 

Btw, a good starting point is sometimes the archive we are generating in the build: 
https://docs.rs/about/download

Which is where the files are pulled out by the webserver.

**Comment by syphar** [comment]
So to wrap it up: we are generating the documentation page, but it's too big to serve

**Comment by GuillaumeGomez** [comment]
> cc [@GuillaumeGomez](https://github.com/GuillaumeGomez) or is there a nicer way?

I'm surprised that doc pages can be so big. O.o

And absolutely no clue. Apart from removing docs/items I don't really see how to reduce the page size.

**Comment by piaoyh** [comment]
I wrote email to Denis about this matter but I haven't gotten any reply from him. So, I write it again here.

After I generated the documentation by "cargo doc" on my local machine, I found that the struct.BigUInt.html is only 4.6 MB on my machine.
Please see the following.

![Image](https://github.com/user-attachments/assets/451a5ba5-71e7-4891-bdee-7d780ec045a1)

Are we talking about the same file?
struct.BigUInt.html is located in '.../doc/cryptocol/number/big_uint'. Did you mean the same file '.../doc/cryptocol/number/big_uint/struct.BigUInt.html'?
Whole documentation files are all 39.2 MB only. Please see the following.

![Image](https://github.com/user-attachments/assets/b72fde91-352f-4aa2-979c-f69fa034cd39)

Strange! Why is '.../doc/cryptocol/number/big_uint/struct.BigUInt.html' so big in the server while it is only 4.6 MB on my machine?

**I think that the server does not generate the webpage as cargo does.**

Please report this problem to the team of crates.io webserver developers.
Merry Christmas.

**Comment by syphar** [comment]
I'll answer out of order. 

> Please report this problem to the team of crates.io webserver developers.

They don't have anything to do with this, it's either this (docs.rs) or the builder (rustdoc). 

> I wrote email to Denis about this matter but I haven't gotten any reply from him. So, I write it again here.

Sorry, we don't provide private support for anyone, the channels are either github issues, or zulip threads. 

> After I generated the documentation by "cargo doc" on my local machine, I found that the struct.BigUInt.html is only 4.6 MB on my machine.

back to the issue, super interesting :) 

To build docs the same we we do, you have to use a nightly toolchain, and set some build parameters. 

So first you should try to build with nightly (`cargo +nightly docs`) and check the output. These docs you then can also open and see what contributes to the size. 

On top of that we set some arguments we need for hosting, you can come quite near to these by using [`cargo docs-rs`](https://github.com/dtolnay/cargo-docs-rs) and then call 
```
$ cargo +nightly docs-rs 
...
```

to check the output. 

I

**Comment by piaoyh** [comment]
Strange!
When I execute `cargo +nightly docs`, it keeps running but never ends. It looks that the cargo falls into infinite loop. Frankly speaking, I don't know what is its reason or what causes cargo to fall into infinite loop. I have used `cargo +nightly docs` for the first time.

Do you think that my source code including documentation is guilty or that cargo does something wrong when it is executed with the arguments `+nightly` and `docs`?

**Comment by syphar** [comment]
> When I execute cargo +nightly docs, it keeps running but never ends. It looks that the cargo falls into infinite loop. Frankly speaking, I don't know what is its reason or what causes cargo to fall into infinite loop. I have used cargo +nightly docs for the first time.

how long did you try running it? 

> Would you please report this issue to the team of cargo developers? I dare to suspect that cargo does not work well (or properly) with the arguments +nightly and docs especially against big source codes. It works fine with the arguments doc even against big source codes such as 2.1 MB-sized file.

This is not a cargo issue. 

My current guess is: 
- there are some new features in rustdoc in nightly that are not on stable 
- with a source file that big building the docs takes more time (docs.rs has it), and creates a huge doc file. 
- my guess it that if you would let the local build run for an hour at least, you will see the same result 

Generally source files that big are difficult to handle for many systems, so making it smaller would be a good optimization in any case. 


@GuillaumeGomez might this be a size regression? Was there much added compared to stable?

**Comment by GuillaumeGomez** [comment]
The only big change in rustdoc I'm aware of is the add of the merged doctests, so it shouldn't impact things here. However there were a lot of small changes, so maybe one (or more) of them is messing things up.

We need to have something to debug to figure out what's wrong. ^^'

**Comment by piaoyh** [comment]
How long did you try running it?
I ran it for about twenty minutes or a little bit less.
I didn't let it run for an hour or that long.

Still, I feel it strange about why it takes so irrationally long and generates irrationally big size of file. For version 0.8.4, BigUInt.rs is only a little bit smaller than BigUInt.rs of version 0.8.5. Such a little change in size makes huge difference. There must be a size threshold that cargo cannot deal with files.

**Comment by GuillaumeGomez** [comment]
I think it's an infinite loop, the interesting thing would be to find a small case triggering this infinite loop so the rustdoc team could fix it and have a regression test.

**Comment by piaoyh** [comment]
Then, would you please report this issue to the team of cargo developers or whatever proper team?

I think, the fact that `cargo doc` works for the same source codes but `cargo +nightly docs` does not work for the same source code indicates something wrong in cargo. If my codes with documentation are guilty, both `cargo doc` and `cargo +nightly docs` should not work.

Thanks to Guillaume Gomez for your reporting this issue to the proper team of cargo development in advance.

Merry Christmas to everybody

**Comment by GuillaumeGomez** [comment]
You can open it [here](https://github.com/rust-lang/rust/issues/new/). ;)

Please cc me on it as well.

**Comment by piaoyh** [comment]
What category am I supposed to open?

**Comment by piaoyh** [comment]
> You can open it [here](https://github.com/rust-lang/rust/issues/new/). ;)
> 
> Please cc me on it as well.

cc @GuillaumeGomez I am sorry that I didn't know how to make cc so I couldn't cc to you. Is it correct now?
