### ISSUE TITLE
defmt-0.3.9 failed to build

### ISSUE THREAD

**Issue by jonathanpallant** [rust-lang/docs.rs#2679]
### Crate name

defmt

### Build failure link

https://docs.rs/crate/defmt/0.3.9/builds/1566395

### Additional details

I don't think we changed anything substantial since defmt-0.3.8, which built OK.

**Comment by syphar** [comment]
there wasn't any related change in docs.rs, though I can only imagine it's either related to your code, or perhaps that the new nightly version changed something.

**Comment by GuillaumeGomez** [comment]
Maybe `-Zbuild-std` is the one in fault here?

**Comment by syphar** [comment]
this is the diff: https://github.com/knurling-rs/defmt/compare/defmt-v0.3.8...defmt-v0.3.9

**Comment by syphar** [comment]
ah, I remember there is also diff.rs: https://diff.rs/defmt/0.3.8/defmt/0.3.9/Cargo.toml

**Comment by jonathanpallant** [comment]
Do you use `-Zbuild-std`? Because I don't think we do. And yes, on `thumbv6m-none-eabi` for example, I'm pretty sure you have to say `-Zbuild-std=core`

```console
➜  defmt git:(release-defmt-0.3.10) rustc +nightly --version
rustc 1.83.0-nightly (06bb8364a 2024-10-01)
➜  defmt git:(release-defmt-0.3.10) cargo +nightly build --target=thumbv6m-none-eabi
   Compiling bitflags v1.3.2
   Compiling defmt v0.3.9 (/Users/jonathan/Documents/knurling-rs/defmt/defmt)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.23s
➜  defmt git:(release-defmt-0.3.10) cargo +nightly build --target=thumbv6m-none-eabi -Zbuild-std
   Compiling gimli v0.29.0
error[E0432]: unresolved import `alloc::sync`
 --> /Users/jonathan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gimli-0.29.0/src/read/dwarf.rs:2:12
  |
2 | use alloc::sync::Arc;
  |            ^^^^ could not find `sync` in `alloc`

error[E0432]: unresolved import `alloc::sync`
 --> /Users/jonathan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gimli-0.29.0/src/read/abbrev.rs:4:12
  |
4 | use alloc::sync::Arc;
  |            ^^^^ could not find `sync` in `alloc`

For more information about this error, try `rustc --explain E0432`.
error: could not compile `gimli` (lib) due to 2 previous errors
➜  defmt git:(release-defmt-0.3.10) cargo +nightly build --target=thumbv6m-none-eabi -Zbuild-std=core
   Compiling bitflags v1.3.2
   Compiling defmt v0.3.9 (/Users/jonathan/Documents/knurling-rs/defmt/defmt)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.25s
➜  defmt git:(release-defmt-0.3.10)
```

**Comment by jonathanpallant** [comment]
The error message appears to come from here: https://github.com/rust-lang/cargo/blob/81e0670dddefc0b78b272e58decc0eea9def3720/src/cargo/core/compiler/standard_lib.rs#L80

**Comment by jonathanpallant** [comment]
Which was added last week: https://github.com/rust-lang/cargo/commit/5e4a1db935cbc1e1bb24ab0e48f0ba0e9d79aeb8

**Comment by jonathanpallant** [comment]
Yup:

```console
➜  defmt git:(release-defmt-0.3.10) RUSTC=~/Downloads/rust-nightly/rust-nightly-aarch64-apple-darwin/rustc/bin/rustc  ~/Downloads/rust-nightly/rust-nightly-aarch64-apple-darwin/cargo/bin/cargo build --target=thumbv6m-none-eabi -Zbuild-std
error: building std is not supported on the following targets: thumbv6m-none-eabi
```

```console
➜  defmt git:(release-defmt-0.3.10) RUSTC=~/Downloads/rust-nightly/rust-nightly-aarch64-apple-darwin/rustc/bin/rustc  ~/Downloads/rust-nightly/rust-nightly-aarch64-apple-darwin/cargo/bin/cargo build --target=thumbv6m-none-eabi -Zbuild-std=core
error: "/Users/jonathan/Downloads/rust-nightly/rust-nightly-aarch64-apple-darwin/rustc/lib/rustlib/src/rust/library/Cargo.lock" does not exist, unable to build with the standard library, try:
        rustup component add rust-src
```

No idea how to add rust-src to a tarball installation, but that's the error.

**Comment by jonathanpallant** [comment]
I sent https://crates.io/crates/thejpster-test-docs-target down the line, which is an inoffensive test crate. If you can't build it then I'm pretty sure it's a docs.rs but and not a defmt bug.

**Comment by syphar** [comment]
> Maybe `-Zbuild-std` is the one in fault here?

@GuillaumeGomez you mean we need add it do the docs.rs metadata to use https://github.com/rust-lang/docs.rs/pull/2107 ? 



> I sent https://crates.io/crates/thejpster-test-docs-target down the line, which is an inoffensive test crate. If you can't build it then I'm pretty sure it's a docs.rs but and not a defmt bug.

there was no docs.rs change that might cause this, so I imagine the nighty version changes you linked could cause the error. 

If you have a test crate that errors too (and IMO it likely will with the targets) we might try it with `cargo-args=["-Zbuild-std"]`

**Comment by jonathanpallant** [comment]
AFAIK will need -Zbuild-std=core when building for a target that doesn't have libstd. I guess most of your crates build for the host machine, but the docs.rs metadata for this one forces you to build it for `thumbv6m-none-eabi` and `thumbv7em-none-eabihf`, because it's known to *not* work on Windows/macOS/Linux.

**Comment by syphar** [comment]
> https://crates.io/crates/thejpster-test-docs-target is perpetually stuck at the back of the queue, perhaps because you've rated as a crate of low value (it is, it's terrible).

it's not deprioritized, so has the same prio as normal releases (deprioritized is shown in braces after the crate, if we do it, like ` (priority: -1) `)

**Comment by jonathanpallant** [comment]
So why is everything else being added to the queue in front of it?

**Comment by syphar** [comment]
I can't Check the logs right now, my guess is build-attempts. 

For a certain type of build errors ( like the one from the original crate) we actually try the build up to 5 times with a delay in between.

**Comment by jonathanpallant** [comment]
Ah, it did build but it went back in the queue!!

and it failed: https://docs.rs/crate/thejpster-test-docs-target/0.1.0/builds/1567394

> error: building std is not supported on the following targets: thumbv7em-none-eabihf, thumbv6m-none-eabi

So yup, not defmt's fault.

**Comment by syphar** [comment]
I want to create a bug-report for cargo, @jonathanpallant could you push the test crate to github so I can include it?

**Comment by syphar** [comment]
I wonder if `cargo-args = ["-Zbuild-std=core"]` in the metadata might help...

**Comment by syphar** [comment]
I started with [a zulip thread](https://rust-lang.zulipchat.com/#narrow/channel/246057-t-cargo/topic/help.20debugging.20a.20docs.2Ers.20issue.20with.20a.20new.20cargo.20error)

**Comment by jonathanpallant** [comment]
https://github.com/jonathanpallant/thejpster-test-docs-target

**Comment by syphar** [comment]
the final fix is still in progress, but since there were some other releases that needed a newer version I un-froze the nightly version. 

Feel free to ping me if you need to build another release, and we can handle it together. It might also be worth trying to add `Zbuild-std=core` as [done here](https://github.com/rust-lang/docs.rs/blob/5efa5e09bef0fcf8de3610724b0e441bba6482d3/tests/crates/build-std/Cargo.toml#L10-L12)

**Comment by syphar** [comment]
coming from the [zulip discussion](https://rust-lang.zulipchat.com/#narrow/channel/246057-t-cargo/topic/help.20debugging.20a.20docs.2Ers.20issue.20with.20a.20new.20cargo.20error) I would say this is fixed now. 

Feel free to reopen if it breaks again, if it fails please first try adding `-Zbuild-std=core` or `-Zbuild-std` to the docs.rs metadata
