### ISSUE TITLE
The server keeps failing to generate the documentation page BigUInt.

### ISSUE THREAD

**Issue by piaoyh** [rust-lang/docs.rs#2688]
### Crate name

cryptocol

### Build failure link

https://docs.rs/cryptocol/latest/cryptocol/number/big_uint/struct.BigUInt.html#struct.BigUInt

### Why your crate needs the resource increases

It is the same problem of the posts [#2676](https://github.com/rust-lang/docs.rs/issues/2676)  and [#2673](https://github.com/rust-lang/docs.rs/issues/2673).

I tried to make a off-line documentation as follows:
`$ cargo doc`

It successfully create the documentation, for example, at `/home/youngho/shared/rust-target/doc`. It shows some warnings but I found that they are minor and irrelevant to this problems.

When I open the `/home/youngho/shared/rust-target/doc/cryptocol/index.html` with web browser, it is shown as follows:

![Image](https://github.com/user-attachments/assets/823408e2-3e47-4610-b47e-1c855fcf948c)

And then, I scrolled down and clicked the link BigUInt as follows:

![Image](https://github.com/user-attachments/assets/620c5649-5db9-4122-a285-8e1a8f204fa6)
 

Then, the browser successfully shows the corresponding linked webpage as follows:
![Image](https://github.com/user-attachments/assets/500baf11-b140-4ca0-969e-3c3f0bd67d2e)

However, after I published the same crate to crates.io, if you follow the steps I showed at the post [#2676](https://github.com/rust-lang/docs.rs/issues/2676), you will find that the corresponding linked webpage is not shown. It only shows as follows:

![Image](https://github.com/user-attachments/assets/ebb12bd4-904d-43fa-abbd-f8a7aaedfd65)

It does not have any cross crate link at all and the offline documentation made with the cargo package manager works fine at switching to the linked webpage .

The cargo package manager generates documentation correctly but the server does not generates documentation as the cargo package manager does.

**It means that the link to the webpage of BigUInt is correct but the server fails in generating the corresponding linked webpage.**

Please recognize that the server does not generate the documentation webpages as the cargo package manager does. They works differently. Please seriously dig it or, at least, report this problem to the team of crates.io developers.

Merry Christmas!

**Comment by syphar** [comment]
Please refrain from creating new issues for the same problem. If you feel like we missed an issue, a comment is enough :)
