### ISSUE TITLE
My crates docs failed to build: `trait-cast`, `trait-cast-macros` and `tracing-proc-macros-ink`

### ISSUE THREAD

**Issue by raldone01** [rust-lang/docs.rs#2689]
### Crate name

`trait-cast`, `trait-cast-macros` and `tracing-proc-macros-ink`

### Build failure link

https://docs.rs/crate/trait-cast/0.3.1/builds/1586058, https://docs.rs/crate/trait-cast-macros/0.3.1/builds/1586057, https://docs.rs/crate/tracing-proc-macros-ink/0.1.2/builds/1586024

### Additional details

`cargo doc` builds successfully locally. If this is my fault, the error message `invalid Cargo.toml syntax` is not very helpful.

**Comment by syphar** [comment]
The actual error is: 
```
error: failed to parse manifest at `/Users/syphar/tmp/trait-cast-0.3.1/Cargo.toml`

Caused by:
  feature `edition2024` is required

  The package requires the Cargo feature called `edition2024`, but that feature is not stabilized in this version of Cargo (1.84.0-nightly (69e595908 2024-11-16)).
  Consider adding `cargo-features = ["edition2024"]` to the top of Cargo.toml (above the [package] table) to tell Cargo you are opting in to use this unstable feature.
  See https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#edition-2024 for more information about the status of this feature.
```

the nightly version docs.rs is using is currently frozen to `nightly-2024-11-20` due to #2679. When I try to build your crate with said version I can see the error above. 

You could make your crate build with that old nightly version, but there is also a good chance that I can unfreeze the used nightly version after this weekend.

**Comment by syphar** [comment]
it's shown here: 
https://docs.rs/about/builds

**Comment by syphar** [comment]
( I would totally accept a PR that shows it on the build error page too :) or also links to the about/builds page )

**Comment by raldone01** [comment]
Can you retrigger the build once the nightly is unfreezed or should I just push a new minor version?

**Comment by syphar** [comment]
I can totally trigger the rebuild once it's unfrozen (it isn't yet). 

( it might take a couple days more, I'm waiting for a fix and another nightly release right now). 

the other option for you is still to make your crate compile with the older nightly version

**Comment by raldone01** [comment]
Yeah, I will just go ahead and make it compatible.

> ( I would totally accept a PR that shows it on the build error page too :) or also links to the about/builds page )

Could be a good first issue for new contributors. :D

**Comment by raldone01** [comment]
Maybe also add a warning if the nightly is behind.
And the `pre-build` errors could use some polish.

**Comment by syphar** [comment]
seeing all the reports that need a newer nightly I decided to unfreeze the version. 

I also queued rebuilds for the three releases above
