### ISSUE TITLE
Incorrect fragment (#foo) links for foreign type implementations

### ISSUE THREAD

**Issue by Alexendoo** [rust-lang/docs.rs#269]
Example: https://docs.rs/serde/1.0.80/serde/trait.Serialize.html#impl-Serialize

All the links under `Implementations on Foreign Types` in the sidebar link to `impl Serialize for bool`

**Comment by jyn514** [comment]
This is a bug in rustdoc and was likely fixed between 2018 and now. You'd have to run `cargo doc` locally to confirm.

The reason it's still broken on the website is because of https://github.com/rust-lang/docs.rs/issues/464.

**Comment by jyn514** [comment]
Ok yes, if you look at https://docs.rs/serde/1.0.114/serde/trait.Serialize.html#impl-Serialize-for-char it goes to the correct implementation for `char`.
