### ISSUE TITLE
Issue with Docs.rs Rendering of Warnings

### ISSUE THREAD

**Issue by kands-code** [rust-lang/docs.rs#2696]
### Crate name

rmatrix_ks

### Build failure link

https://docs.rs/crate/rmatrix_ks/0.5.0/builds/1595181

### Additional details

The rendering of the normal warning div should look like the one shown on the right, but Docs.rs renders it like the one on the left. It appears that the background color and border color are blended together, and it is also being forcibly centered. There are no issues when compiled locally.

![Image](https://github.com/user-attachments/assets/ccdc90bb-9c90-47f2-a775-6b656e1f7242)

> cargo 1.85.0-nightly (99dff6d77 2024-12-18)
>
> rustc 1.85.0-nightly (9e136a30a 2024-12-19)

**Comment by syphar** [comment]
cc @GuillaumeGomez any idea?

**Comment by GuillaumeGomez** [comment]
I have a fix. Just checking a few things before opening the PR.
