### ISSUE TITLE
changes required in future nightlies

### ISSUE THREAD

**Issue by QuietMisdreavus** [rust-lang/docs.rs#270]
The following PRs add new files to the rustdoc distribution:

* ~~https://github.com/rust-lang/rust/pull/55707 (merged, in nightly) added `source-script.js` as a new static file, and `source-files.js` as a new per-doc-bundle file.~~ (added in https://github.com/rust-lang/docs.rs/pull/274)
* ~~https://github.com/rust-lang/rust/pull/56332 (merged, but not in nightly yet) added `down-arrow.svg` as a new static file.~~ (added in https://github.com/rust-lang/docs.rs/pull/274)

When both of these are in nightly (may take a while for the latter one), we'll need to update docs.rs to make sure it adds these files to the site-wide cache.

**Comment by QuietMisdreavus** [comment]
Once https://github.com/rust-lang/rust/pull/56577 lands, we'll want to start passing `--generate-redirect-pages` to rustdoc.

**Comment by QuietMisdreavus** [comment]
https://github.com/rust-lang/rust/pull/56005 adds a new static file: `noscript.css`.

**Comment by QuietMisdreavus** [comment]
I'm reopening this to keep as a running list of "changes necessary in new nightlies", especially since the last two weren't included in #274.

**Comment by QuietMisdreavus** [comment]
- After https://github.com/rust-lang/rust/pull/57011 merges, we can start passing `--static-root-path /` to rustdoc to adjust how CSS/JS files are loaded on documentation pages and increase browser cache usage.
- After https://github.com/rust-lang/rust/pull/57006 merges, we can start passing `--disable-per-crate-search` to disable the crate filter on the in-doc search box, which is useless for docs.rs anyway because of how it generates docs.

**Comment by QuietMisdreavus** [comment]
https://github.com/rust-lang/rust/pull/57400 changes the font files distributed/used by rustdoc. Since docs.rs loads these as "essential files" but *doesn't* apply a resource suffix, this may be problematic, but i think we can just get away with keeping the old font files in the database and loading in the new ones when we get them.

**Comment by QuietMisdreavus** [comment]
https://github.com/rust-lang/rust/pull/57552 adds two new static files: `favicon.ico` and `rust-logo.png`. Since docs.rs uses its own favicon, that one can technically be ignored, but new pages will start trying to reference the logo image.

**Comment by QuietMisdreavus** [comment]
https://github.com/rust-lang/rust/pull/59776 adds the resource suffix to the per-crate files (search index, source file list, etc). We currently hardcode those files into our route listing, so we'll need to make sure to handle those when that lands.

**Comment by jyn514** [comment]
Closing this since it hasn't been used in a while and I'd rather track these in separate issues.
