### ISSUE TITLE
An error occurs while trying to build add-essential-files

### ISSUE THREAD

**Issue by aleksuss** [rust-lang/docs.rs#278]
I try to start docs.rs from a vagrant image. But I got stuck when try to build `add-essential-files` stage and have an error: 
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ErrorMessage { msg: "sources path \'/home/cratesfyi/cratesfyi-prefix/sources\' does not exist" }
```

**Comment by onur** [comment]
Thanks for reporting @aleksuss. This error is caused by: https://github.com/rust-lang/docs.rs/pull/247#discussion_r227836744

You can create that directory manually with `mkdir /home/cratesfyi/cratesfyi-prefix/sources` and run `vagrant up --provision` again until we fix this issue.

**Comment by onur** [comment]
yea nightly rustc used in Vagrant also needs an update. Sorry @aleksuss I am prepared a patch to fix Vagrantimage. You can wait until it gets merged or you can directly use that branch.

**Comment by aleksuss** [comment]
@onur yes, with latest nightly rustc ok.
