### ISSUE TITLE
libnfs fails to build

### ISSUE THREAD

**Issue by cholcombe973** [rust-lang/docs.rs#283]
I suspect it's because it's missing the libnfs package dependency on whatever container or server is being used to build this.  
```
ii  libnfs-dev:amd64                            1.9.8-1                                      amd64        NFS client library (development files)
```
Would it be possible to get that installed?

**Comment by jyn514** [comment]
@cholcombe973 if you're willing to make a PR to crates-build-env, this would get fixed faster. Instructions here: https://github.com/rust-lang/docs.rs/wiki/Making-changes-to-the-build-environment

**Comment by jyn514** [comment]
It looks like libnfs hasn't been updated since 2018 so I'm going to close this issue; feel free to update the build environment if you come back to this :)
