### ISSUE TITLE
Add a possibility to build crate's docs from a path or repository

### ISSUE THREAD

**Issue by aleksuss** [rust-lang/docs.rs#284]
There is one method to build crate's docs at this moment, as I know. A crate should be published at crates.io. It would be nice to have a possibility to provide path or repo for crate to build docs for it. It nice to have for checking docs build for errors before publishing at crates.io. Any thoughts ?

**Comment by jyn514** [comment]
Are you asking for a way to build docs from a local directory to make sure it works before publishing it? This was implemented in  #460.
