### ISSUE TITLE
Try to serve index.html if link points to directory

### ISSUE THREAD

**Issue by almielczarek** [rust-lang/docs.rs#288]
This change may fix a lot of broken links such as the ones I've found in https://github.com/hyperium/hyper/issues/1749 and https://github.com/hyperium/hyper/issues/1750

**Comment by almielczarek** [comment]
I peeked at web::rustdoc::rustdoc_html_server_handler and it looks like it checks if a file exists at the request path and if it doesn't it immediately returns a 404.

Perhaps we could try pushing "index.html" to the end of the path once in the None branch of [this](https://github.com/rust-lang/docs.rs/blob/1a20968096e6e92fbb45223adbd2fe143ac9e957/src/web/rustdoc.rs#L152) match block and check if that new path exists before returning a 404.

**Comment by jyn514** [comment]
We currently add `index.html` for `/`, but not if the slash is missing. Thanks for writing up instructions!

**Comment by d-e-s-o** [comment]
Just hit the same issue with `tokio` docs. Wanted to see documentation for the https://docs.rs/tokio/0.2.11/tokio/time but "the resource does not exist". Adding slash or `/index.html` works, but would be good to have this done automatically.
