### ISSUE TITLE
Build queue hickup?

### ISSUE THREAD

**Issue by hellow554** [rust-lang/docs.rs#291]
The build queue is stalled for 8-ish hours. Is there something wrong?

https://docs.rs/releases/queue

> learn_rust-0.1.2
pentest-toolbox-improved-0.1.7
learn_rust-0.1.3
enpass-cli-0.1.1
pentest-toolbox-improved-0.1.8
pentest-toolbox-improved-0.1.9
diesel-citext-0.1.0
rustc-ap-syntax_pos-368.0.0
rustc-ap-syntax-368.0.0
rustc-ap-serialize-368.0.0
rustc-ap-rustc_target-368.0.0
rustc-ap-rustc_errors-368.0.0
rustc-ap-rustc_data_structures-368.0.0
[...]

https://docs.rs/releases

> pentest-toolbox-improved-0.1.6 7 hours ago
learn_rust-0.1.1 7 hours ago
pentest-toolbox-improved-0.1.5 7 hours ago
pentest-toolbox-improved-0.1.4 7 hours ago
pentest-toolbox-improved-0.1.3 7 hours ago
gog-0.3.0 8 hours ago
x86-0.14.0 8 hours ago
[...]

**Comment by hellow554** [comment]
Ok, the queue has been shortened now. Interestinly learn-rust version 0.1.2  hasn't been built although version 0.1.3 has released by now (which hasn't been built either).
Don't know if it's worth some investigation.

**Comment by QuietMisdreavus** [comment]
I manually kicked `learn_rust` out of the queue - it was triggering a bug in docs.rs which was causing a crash, which was holding up the queue. I'm testing a branch for it right now.

**Comment by QuietMisdreavus** [comment]
I've opened https://github.com/rust-lang/docs.rs/pull/292 to fix the crash that that crate was causing. Once it's deployed, i'll rebuild it..

**Comment by QuietMisdreavus** [comment]
Alright, #292 has been deployed and `learn_rust` has been built successfully. That crate shouldn't block the queue in the future.
