### ISSUE TITLE
Preserve .css files in target/doc

### ISSUE THREAD

**Issue by japaric** [rust-lang/docs.rs#294]
### Background / use case

For the `cortex-m-rtfm` crate I ship [an mdbook][book] with [the API
documentation][api] and host both on GH pages. This setup works OK for now but
I'll start having problems once I release a new minor version: people looking at
older minor versions (e.g. on docs.rs) will be directed to the latest version of
the book on GH pages and get confused.

[book]: https://japaric.github.io/cortex-m-rtfm/book/
[api]: https://japaric.github.io/cortex-m-rtfm/api/rtfm/index.html

Ideally, I'd like to move away from GH pages and host both the API docs and the
mdbook on docs.rs. That way people will get the right version of the mdbook
regardless of the minor version of the crate they are looking at.

---

I experimented a bit with getting an mdbook rendered on docs.rs and managed to
place the mdbook output in the target/doc directory using build scripts. You can
see the results at
https://docs.rs/cautious-octo-funicular/0.1.3/cautious_octo_funicular/ -- the
mdbook is [there] but the layout is all wrong. According to @quietmisdreavus the
mdbook CSS files are not being preserved and that's why the mdbook shows
unstyled.

[there]: https://docs.rs/cautious-octo-funicular/0.1.3/cautious_octo_funicular/book/index.html

This issue is to request that .css files placed in target/doc are preserved to
support the above use case.

**Comment by jyn514** [comment]
Hmm, I would like to support this, but I also don't want to copy .css files generated by rustdoc, since that would result in a lot of duplicated files for every crate.

**Comment by jyn514** [comment]
This change was reverted because it broke search: https://github.com/rust-lang/docs.rs/pull/1329. I hope https://github.com/rust-lang/rust/pull/83478 would allow relanding the change.

**Comment by jyn514** [comment]
> I experimented a bit with getting an mdbook rendered on docs.rs and managed to
place the mdbook output in the target/doc directory using build scripts.

FYI we are hoping to add first-class support for mdbook at some point: https://github.com/rust-lang/docs.rs/issues/1293
