### ISSUE TITLE
libsodium-sys causes Doc's Build to fail

### ISSUE THREAD

**Issue by Lakelezz** [rust-lang/docs.rs#307]
We released v0.5.12 of our crate _serenity_ and the documentation on docs.rs failed building, here is the build-log: https://docs.rs/crate/serenity/0.5.12/builds/143002

It tries to 

> Running `/home/cratesfyi/cratesfyi/debug/build/libsodium-sys-7ca54fcbf5c3a0bd/build-script-build

 fails with:

> failed to run custom build command for `libsodium-sys v0.1.0`\nprocess didn\'t exit successfully: `/home/cratesfyi/cratesfyi/debug/build/libsodium-sys-7ca54fcbf5c3a0bd/build-script-build` (exit code: 101)

caused by this panic:

> panicked at \'called `Result::unwrap()` on an `Err` value: \"`\\\"pkg-config\\\" \\\"--libs\\\" \\\"--cflags\\\" \\\"libsodium\\\"` did not exit successfully: exit code: 1\\n--- stderr\\nPackage libsodium was not found in the pkg-config search path.\\nPerhaps you should add the directory containing `libsodium.pc\\\'\\nto the PKG_CONFIG_PATH environment variable\\nNo package \\\'libsodium\\\' found\\n\"\'

Is there a way to fix this failed build for our v0.5.12? The build built fine on our CI: https://travis-ci.org/serenity-rs/serenity/builds/493369909 

Thanks for your time : )

**Comment by QuietMisdreavus** [comment]
We didn't have the libsodium development headers installed in the docs.rs build container. I've installed them and [rebuilt the docs](https://docs.rs/serenity/0.5.12/serenity/).

**Comment by QuietMisdreavus** [comment]
For future reference, we request that any documentation build failures be reported in [its dedicated issue](https://github.com/rust-lang/docs.rs/issues/23).
