### ISSUE TITLE
start sending ETag headers

### ISSUE THREAD

**Issue by QuietMisdreavus** [rust-lang/docs.rs#320]
With the caching issues described in https://github.com/rust-lang/docs.rs/issues/316, it may be worth updating the headers we send with static files. [Our current headers](https://github.com/rust-lang/docs.rs/blob/32b0d13214ea313fec029960e57d8c4d09ed089f/src/web/file.rs#L45-L55) include a `max-age` of 12 months, which is useful most of the time, but has started to run into some issues in certain situations. Calculating an ETag for some file requests and shortening this cache duration could be helpful in getting CloudFront to properly update its CDN caches when necessary. Updating our request handling to also react to receiving these ETags could also save us from having to serve the files even if they aren't updated.

**Comment by najamelan** [comment]
This is a bit more work to implement than ETAGs (because of the hash based uri), but I think it is the correct way, and in the very least I think everyone should read this, so I share it here:

https://engineering.fb.com/web/this-browser-tweak-saved-60-of-requests-to-facebook/

**Comment by syphar** [comment]
I think we can close this issue since it's problems are partially solved, and partially moved: 
- #1593 
- #1560
