### ISSUE TITLE
Some crate docs are broken

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/docs.rs#327]
https://docs.rs/futures/0.1.0/futures/ looks pretty broken. 0.1.1 is fine.

**Comment by QuietMisdreavus** [comment]
Huh. It looks like we don't have the static files for that version of rustdoc. I wonder if we lost them in the server migration... @onur 

I was able to pull the `main.js`, `main.css`, `rustdoc.css`, and `jquery.js` for that version and manually add them to the server. Those docs should load now.
