### ISSUE TITLE
GTK3 Version Too Old

### ISSUE THREAD

**Issue by BrainBlasted** [rust-lang/docs.rs#333]
The latest version of GTK3 is 3.24. docs-rs ships 3.22, which is too old to build https://crates.io/crates/libhandy

**Comment by QuietMisdreavus** [comment]
Unfortunately, the latest version available to Ubuntu 18.04 (used by our build server) is 3.22. https://packages.ubuntu.com/bionic/libgtk-3-0 Short of a way to load the newer GTK package separately, i'm not sure we can fix this.

**Comment by GuillaumeGomez** [comment]
And I think we shouldn't. It's up to users to check if their library are spread enough to force their users to use them.

**Comment by jyn514** [comment]
Closing as wontfix.
