### ISSUE TITLE
Question on difference between crates.io README and docs.rs

### ISSUE THREAD

**Issue by matthewkmayer** [rust-lang/docs.rs#334]
I'm trying to catch all straggling documentation on the Rusoto project to point all users away from the old, deprecated mega-crate to the current solution of many crates. 

https://crates.io/crates/rusoto shows the README correctly: the crate is deprecated and has links to how to migrate to new releases. 

https://docs.rs/rusoto/0.24.1/rusoto/ has our older README that is misleading.

As far as I can tell, the git tag for `rusoto` 0.24.1 has the correct README: https://github.com/rusoto/rusoto/blob/75b00b05f113bdc7a84ef1537f7a447859f69140/README.md .

I'd like https://docs.rs/rusoto/0.24.1/rusoto/ to have the same README contents as the crates.io link. How can I do this? Thanks! 😄

**Comment by QuietMisdreavus** [comment]
The link you gave shows the crate root's docs, not the readme. The "crate details" page for that version (https://docs.rs/crate/rusoto/0.24.1) does show the correct readme for that version number, though. To show it on that specific page you linked, you would have to modify the crate's documentation.

**Comment by matthewkmayer** [comment]
Ah, now I understand. Thanks for clearing up my confusion around the README vs docs. 😄
