### ISSUE TITLE
The layout at the time of code display may be broken

### ISSUE THREAD

**Issue by k-nasa** [rust-lang/docs.rs#337]
I can not see the code on the left side.
<img width="1159" alt="スクリーンショット 2019-04-26 23 47 26" src="https://user-images.githubusercontent.com/23740172/56816103-cd88b500-687d-11e9-9e50-590426b93a27.png">

It became visible if the window size was reduced.
<img width="662" alt="スクリーンショット 2019-04-26 23 47 35" src="https://user-images.githubusercontent.com/23740172/56816244-193b5e80-687e-11e9-8295-b3588b8cb841.png">

**Comment by GuillaumeGomez** [comment]
This is a bug that has been fixed recently in rustdoc: https://github.com/rust-lang/rust/pull/60032.

**Comment by GuillaumeGomez** [comment]
However the line numbers aren't correctly aligned. I need to fix that!

**Comment by k-nasa** [comment]
Ok. Thanks!

**Comment by k-nasa** [comment]
I will close it because it has been fixed.
