### ISSUE TITLE
stop building crates on all targets

### ISSUE THREAD

**Issue by QuietMisdreavus** [rust-lang/docs.rs#343]
After seeing the build queue get backed up by crates that take a long time to build (https://github.com/rust-lang/docs.rs/issues/335), i'm starting to wonder about the utility of building crates for all platforms all the time.

Currently, when we build a crate, we build it seven times:

* Once as the "initial" build, to prove that the crate builds in the first place. This generates the log shown in the builds page. If a crate specifies a `default-target` in its `[package.metadata.docs.rs]` it will use that target, otherwise it will build using the system's default of `x86_64-unknown-linux-gnu`.
* Six more times, to fill in all the supported targets:
  * `i686-apple-darwin`
  * `i686-pc-windows-msvc`
  * `i686-unknown-linux-gnu`
  * `x86_64-apple-darwin`
  * `x86_64-pc-windows-msvc`
  * `x86_64-unknown-linux-gnu`

This can cause a crate's build time to stretch out unnecessarily, especially if there are no API/docs differences between 32-/64-bit, or between Windows/Mac/Linux.

I'd like to propose removing the six extra builds, and replacing them with an `additional-targets` configuration item that would allow crates to choose which targets to build on. In the absence of this field, we would only build once for `default-target` (or `x86_64-unknown-linux-gnu`), and not create any additional builds.

This will allow us to build much more crates a lot faster, making it less likely that releasing a bunch of `stm32` crates at the same time will clog up the queue again. On the other hand, crates would have to start listing the platforms they want to build with, instead of just depending on docs.rs to build the major platforms without asking.

**Comment by GuillaumeGomez** [comment]
I think this is a good idea. Alongside this, we should try to make `docs.rs` specific options (more) easily available. We're starting to have a few and it'd be a shame that people don't know about them!

**Comment by dekellum** [comment]
Like in section _Metadata for custom builds_ of https://docs.rs/about ?  

Though it could use short descriptions of each item. In this context, I'm not personally sure what `default-target` does, for example.

**Comment by jamesmunns** [comment]
We (embedded-wg) would definitely love a conservative opt-in version of this to prevent our crates from being built for all non-embedded targets, as typically we only build for one or a few `thumb*` targets.

CC @adamgreig @killercup

**Comment by jyn514** [comment]
Now that #632 is merged, you should be able to opt-in to only building one target with
```
[package.metadata.docs.rs]
targets = [] # or targets = ["x86_64-unknown-linux-gnu"] if you think that looks nicer
```
See https://docs.rs/about#metadata for full documentation.

**Comment by marcospb19** [comment]
Hey @jyn514, do you recall why was this tagged as S-blocked?

**Comment by jyn514** [comment]
@marcospb19 it needs an RFC and I got private feedback that such an RFC likely wouldn't be accepted. At that point I gave up because I only have so much time to throw away on the rust project.

**Comment by syphar** [comment]
@rust-lang/docs-rs what are your thoughts on this? 

seeing the last comment by Jyn & the already increased build capacity I would close this issue.

**Comment by GuillaumeGomez** [comment]
No opinion.

**Comment by Nemo157** [comment]
I would _like_ to do it still, the current default set is going to get more and more out of date (it has i686 targets which are not really relevant anymore, but no aarch64 targets which are), but I agree that unless someone puts in the effort to actually write an RFC and get buy-in that's not going to happen anytime soon and there's no need to have an issue here. (Maybe in a few more years when the default set is more out of date it'll be easier to get buy-in to drop it instead of trying to change it).
