### ISSUE TITLE
Add gitlab statistics similar to github

### ISSUE THREAD

**Issue by imp** [rust-lang/docs.rs#35]
If crate's git repo is hosted on github docs.rs shows projects stats fetched from github.com. This ticket is for having similar arrangement for gitlab.com as well

**Comment by SShrike** [comment]
The same would be nice for BitBucket as well (if it doesn't already exist), seeing as it another large hosting provider.

**Comment by Kixiron** [comment]
Triage: This is fairly low priority for us to do but if a PR were made we would accept it

**Comment by GuillaumeGomez** [comment]
I started to work on gitlab integration.

**Comment by jyn514** [comment]
Implemented in https://github.com/rust-lang/docs.rs/pull/1249.
