### ISSUE TITLE
Causes mixed content

### ISSUE THREAD

**Issue by JohnTitor** [rust-lang/docs.rs#352]
I found docs.rs has mixed content in some pages.
It seems the top page is okay but some crates' pages are bad (attempted to load `http://docs.rs/favicon.ico`).

<img width="708" alt="mixed content" src="https://user-images.githubusercontent.com/25030997/57411803-9d4ff780-7229-11e9-9b93-c1885bee94c2.png">

**Comment by est31** [comment]
This should be easy to fix. My guess is that [this code](https://github.com/rust-lang/docs.rs/blob/e3b022edb7dc19ab4d463e86987947c0c89ff247/src/web/mod.rs#L498) should either be changed to use the requesting scheme or to always use https. Something like `let url = ctry!(Url::parse("/favicon.ico"));` or `format!("https://{}:{}/favicon.ico"`. I'd prefer the `"/favicon.ico"` variant as it would work both on local development setups as well as when you use the service in production.

**Comment by est31** [comment]
This was fixed by #365. Thanks @pietroalbini !

**Comment by QuietMisdreavus** [comment]
I'll go ahead and close this then. If this crops up again, feel free to open up a new issue!
