### ISSUE TITLE
Please install `rustfmt` to the docs.rs doc build environment

### ISSUE THREAD

**Issue by Lokathor** [rust-lang/docs.rs#357]
My crate builds bindings, and the bindings output comes out as [all one line](https://docs.rs/fermium/0.0.11/src/fermium/home/cratesfyi/cratesfyi/debug/build/fermium-2e11252b8a4909e1/out/bindings.rs.html#3) without rustfmt available.

**Comment by jyn514** [comment]
@Lokathor  It looks like this is fixed in new versions of fermium, probably because of #407. Can you take a look at https://docs.rs/fermium/0.1.4/src/fermium/SDL2-v2.0.8-x86_64-pc-windows-msvc.rs.html#4692-4695 and make sure it looks about right?

**Comment by Lokathor** [comment]
Well, that's correct, but probably because I have since stopped using bindgen on `docs.rs`. The file you linked is just permanently in the repo: https://github.com/Lokathor/fermium/blob/master/src/SDL2-v2.0.8-x86_64-pc-windows-msvc.rs

but i guess we can close this and someone else will report if it's still a problem later.

**Comment by jyn514** [comment]
I'd actually rather keep it open until I know it's fixed, sorry we took so long you found a workaround instead.

**Comment by jyn514** [comment]
Mentoring instructions:
- In [`update_toolchain`](https://github.com/rust-lang/docs.rs/blob/master/src/docbuilder/rustwide_builder.rs#L143), call [`toolchain.add_component("rustfmt")`](https://docs.rs/rustwide/0.5.1/rustwide/toolchain/struct.Toolchain.html#method.add_component).

If you have any questions, feel free to reach out here or [on Discord](https://discord.gg/f7mTXPW).

**Comment by elmurci** [comment]
`add_component` requires two parameters:

`self.toolchain.add_component(&self.workspace, "rustfmt");`

**Comment by elmurci** [comment]
the solution above didn't work...

**Comment by jyn514** [comment]
What do you mean by didn't work? Can you put up a draft branch?

**Comment by elmurci** [comment]
adding the command:

`self.toolchain.add_component(&self.workspace, "rustfmt")?;`

to `update_toolchain`

**Comment by jyn514** [comment]
@elmurci can you join the discord so I can help you debug without spamming notifications for people watching the issue? https://discord.gg/f7mTXPW

**Comment by elmurci** [comment]
I managed to fix it. Putting it here as it may help others.
The problem was due to a dependency ([tonic-build](https://github.com/hyperium/tonic/tree/master/tonic-build) having rustfmt in its features section:

```
...
[features]
default = ["transport", "rustfmt", "prost"]
...
```

I solved it by disabling `tonic-build`'s `rustfmt` dependency:

```
...
[build-dependencies]
tonic-build = { version = "0.1.1", default-features = false, features = ["transport"] }
...
```

After doing this it built correctly.

**Comment by jyn514** [comment]
@pietroalbini if `rustfmt` isn't available on the latest nightly, should we refuse to update the toolchain or instead remove the rustfmt component? I lean towards not updating but I could be convinced otherwise.

**Comment by pietroalbini** [comment]
I'd prefer not updating as well.
