### ISSUE TITLE
Compress html documents when sending them to the user

### ISSUE THREAD

**Issue by bendem** [rust-lang/docs.rs#360]
Html documents served by docs.rs are not compressed resulting in large bandwidth waste on pages for complex types.

See for example the iterator page as discussed here: https://github.com/rust-lang/rust/issues/55900#issuecomment-497657997

**Comment by GuillaumeGomez** [comment]
I wondered for a long time if we should handle compression directly inside rustdoc. That could be a good time to talk about it as well...

**Comment by pickfire** [comment]
If the docs are compressed locally, `rustup doc --std` probably needs some changes such as starting up a server instead of just opening the file, I think it affects search as well.

**Comment by GuillaumeGomez** [comment]
It would indeed. Which is why we never did.

**Comment by pickfire** [comment]
@GuillaumeGomez The current possible solution may be minifying the html resource which can probably shave like ~5% off while keeping the same output without much changes. What do you think?

**Comment by GuillaumeGomez** [comment]
If the web browsers can still work with local compressed files, then I'm totally going to add it.

**Comment by syphar** [comment]
NGINX & CloudFront are serving compressed content when the browser supports it. 

So I assume this issue is solved. 

Please feel free to reopen if not.

**Comment by syphar** [comment]
This repo here is purely about https://docs.rs . 

"local docs" sounds like this is about rustdoc itself (when it's about crate docs), which lives in https://github.com/rust-lang/rust , or the std docs, which live there too.
