### ISSUE TITLE
docs.rs About should mention that *|latest|newest in URLs redirects to latest version

### ISSUE THREAD

**Issue by skierpage** [rust-lang/docs.rs#361]
I didn't realize that asterisk for version appears to redirect to the latest published version, e.g. https://docs.rs/clap/*/clap/struct.App.html#methods
This is sort-of implied by wildcards in semver, but is not mentioned in https://docs.rs/about ; I think an example in "Redirections" section would help. [`match_version()`](https://github.com/rust-lang/docs.rs/blob/master/src/web/mod.rs#L300) suggests "latest" and "newest" also work in place of *, I'm not sure which is preferred/canonical.

(The same documentation request was earlier made in a comment to [issue 169](https://github.com/rust-lang/docs.rs/issues/169#issuecomment-351224782).)

**Comment by jyn514** [comment]
Added in https://github.com/rust-lang/docs.rs/pull/578
