### ISSUE TITLE
save docs/source files outside of the database

### ISSUE THREAD

**Issue by QuietMisdreavus** [rust-lang/docs.rs#367]
One potentially problematic design decision for docs.rs is that it saves all the documentation and crate source files in a database table, complete with the entire file content. This works fine for keeping the database self-contained, and also allows for saving other metadata alongside the file content. However, this also causes the side of the database to balloon over time, as more and more crates are saved into the database.

It would be prudent to work out how to move these files out of the database. Many people have suggested using Amazon S3 to store the files, which would at least lessen our hosting cost. Regardless, we would need to consider it carefully, since the storage of the rustdoc output files and crate sources is a fundamental layer of docs.rs.

* We'll need to figure out how to migrate an existing database to the new storage format. It would be best to provide some way to dump existing files out of the database. (If we're changing the `files` table as part of this, it could be done in the migration script...)
* Specific to using S3, what of development servers, who might not want to (or be able to) use the external service? We should provide a fallback so that we can allow docs.rs contributors to not require an AWS account.
  * In this case, would we keep the files in the database? Would we dump them to the filesystem under the prefix directory?
* Actually swapping out the logic of "saving files into the database" should be straightforward - all the existing code calls `db::file::add_path_into_database` with a folder or file to add, so any change could just go in there.
* Similarly for "load files from the database", all the file-loading logic eventually calls `web::file::File::from_path`, which loads a file out of the database. Modifying just this function to load from the new storage would affect anything that needs to load a file out.

**Comment by pietroalbini** [comment]
> Specific to using S3, what of development servers, who might not want to (or be able to) use the external service? We should provide a fallback so that we can allow docs.rs contributors to not require an AWS account. 

There is [Minio](https://min.io), an S3 clone that you can host locally.

**Comment by QuietMisdreavus** [comment]
> > Specific to using S3, what of development servers, who might not want to (or be able to) use the external service? We should provide a fallback so that we can allow docs.rs contributors to not require an AWS account.
> 
> There is [Minio](https://min.io), an S3 clone that you can host locally.

This feels a little like overkill? We may be able to wedge a standalone Minio service into the Vagrant development container, but it doesn't seem like a viable solution for personal development systems that aren't using it. (Like mine... `>_>`)

**Comment by pietroalbini** [comment]
> This feels a little like overkill? We may be able to wedge a standalone Minio service into the Vagrant development container, but it doesn't seem like a viable solution for personal development systems that aren't using it. (Like mine... >_>)

There is also a demo instance that's resetted every few days: https://play.minio.io:9000/minio/

**Comment by QuietMisdreavus** [comment]
That's still an external service, though. I was hoping for something that could be completely local.

**Comment by Mark-Simulacrum** [comment]
To give a bit of an update here -- I found getting started with minio *super simple* and was pleasantly surprised by how well it went (wget + run and you're good to go, in my experience).

However, we've gone with the approach of not requiring S3 credentials, and if we don't find them we fall back to storing/retrieving files from the database.

**Comment by Mark-Simulacrum** [comment]
I'm going to close this as we've fully migrated over to making S3-like file storage a possibility for any deployment of docs.rs.
