### ISSUE TITLE
Have a "one-click" removal option for admins to remove a version across both crates.io and docs.rs

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/docs.rs#368]
Recently, we had a trademark violation crate we needed to take down. We took care of crates.io, but that didn't remove the crate from docs.rs.

The short-term solution for this issue could be documenting the exact procedures/commands/etc that should happen manually when we need to remove a version or an entire crate, across both crates.io and docs.rs.

The long-term solution for this issue could be creating a button/command/something for admins of crates.io to quickly remove a version or all versions of a crate that removes the same content from docs.rs automatically.

This is a sibling issue of https://github.com/rust-lang/crates.io/issues/1764, filed in both places so we can collaborate ❤️

**Comment by carols10cents** [comment]
Documentation started at https://github.com/rust-lang/crates-io-cargo-teams/blob/master/crate-removal-procedure.md

**Comment by jyn514** [comment]
> The short-term solution for this issue could be documenting the exact procedures/commands/etc that should happen manually when we need to remove a version or an entire crate, across both crates.io and docs.rs.

This is documented at https://forge.rust-lang.org/docs-rs/maintenance.html#removing-a-crate-from-the-website. It requires someone with admin access to the server, currently me or @pietroalbini. There's an up-to-date list at https://forge.rust-lang.org/infra/docs/docs-rs.html.

> The long-term solution for this issue could be creating a button/command/something for admins of crates.io to quickly remove a version or all versions of a crate that removes the same content from docs.rs automatically.

@pietroalbini suggested a web API. Since he's the one currently in charge of deleting crates he volunteered to help write it if he gets tired of doing it manually.

**Comment by jyn514** [comment]
By the way, the `crates-io-cargo-teams` link is broken.

**Comment by jyn514** [comment]
https://github.com/rust-lang/docs.rs/issues/285 suggested that docs.rs delete crates automatically when they're deleted from crates.io by looking at the index. This would need support from crates-index-diff, but otherwise seems simpler to me than webhooks or anything like that.

**Comment by jyn514** [comment]
The way to do this while logged into the server is `cratesfyi database delete version <crate name> <version> && cratesfyi database update-registry-fields <crate name>`. There is still no webhook or anything like that.

**Comment by syphar** [comment]
since we execute release-deletes and crate-deletes on docs.rs, when they are deleted from the index, 

I assume this is done.
