### ISSUE TITLE
Build failure: "does not have these features"

### ISSUE THREAD

**Issue by dhardy** [rust-lang/docs.rs#369]
Rand 0.7.0-pre.1 [failed to build](https://docs.rs/crate/rand/0.7.0-pre.1/builds/165503):
```
thread 'main' panicked at 'ErrorMessage {
    msg: "Package `rand v0.7.0-pre.1` does not have these features: `rand_xorshift, rand_isaac`"
}', src/bin/cratesfyi.rs:160:13
```
These are not features. They are workspace members and `dev-dependencies`, but not features, so why do they get enabled as features?

We use the following, so this may be `docs.rs` mis-detecting what is a feature:
```
[package.metadata.docs.rs]
all-features = true
```

**Comment by QuietMisdreavus** [comment]
It looks like the `serde1` feature is [trying to enable these dependencies](https://github.com/rust-random/rand/blob/703452450770d4b2bb0b117dfc83aea5ba61ec60/Cargo.toml#L31), but since those dependencies are only dev-dependencies, Cargo is choking trying to enable that feature. Is it possible to enable that feature locally?

**Comment by vks** [comment]
> `serde1 = ["rand_core/serde1", "rand_isaac/serde1", "rand_xorshift/serde1"]`

`rand` should probably get rid of `rand_isaac/serde1` and `rand_xorshift/serde1`. They are not dependencies of `rand` anymore. (However, `rand_chacha/serde1` and possibly `rand_pcg/serde1` might need to be added, possibly creating the problem again.)

**Comment by dhardy** [comment]
Yes, this is an error on our part. (We don't need the `serde1` feature for dev builds anyway.)

I think it may be an error on Cargo's part too though; I believe one can do this with optional dependencies without problem.
