### ISSUE TITLE
`dyn` could be explained better

### ISSUE THREAD

**Issue by knocte** [rust-lang/docs.rs#374]
There are two issues with this page: https://doc.rust-lang.org/edition-guide/rust-2018/trait-system/dyn-trait-for-trait-objects.html

1) It doesn't explain where does "dyn" come from, is it from the word "dynamic"? It should mention dynamic dispatching AFAIU.
2) It's targeted to people that are already familiar with Rust (that is, the people that were already using Rust before `dyn` keyword existed). If a new developer comes, it's better to just talk about the new way of doing things, not just mentioning that dyn is some new way to do some old stuff.

**Comment by pietroalbini** [comment]
Thanks for reporting this! Edition guide issues are tracked in [its repo](https://github.com/rust-lang-nursery/edition-guide) though, could you file the issue there?

**Comment by knocte** [comment]
Thanks, opened https://github.com/rust-lang-nursery/edition-guide/issues/183

**Comment by knocte** [comment]
@pietroalbini looks like the bullet (2) of my list doesn't apply to editions. We should reopen this issue to have a non-edition docs about dyn.

**Comment by pietroalbini** [comment]
@knocte this repository is not about Rust documentation though, it's about the docs.rs service, hosting crates' documentation. The repository for the book is https://github.com/rust-lang/book.

**Comment by knocte** [comment]
Well I have to say this is all very confusing for a newbie. If you google "rust docs" you end up here. Probably this repo should be renamed to cratesdocs.rs.
