### ISSUE TITLE
Side bar over crate source code in "view source" page

### ISSUE THREAD

**Issue by Gekkio** [rust-lang/docs.rs#378]
If you view the source code of a crate by clicking the **[src]** link somewhere, the side bar on the left side hides much of the source code.

![Screenshot from 2019-07-17 10-44-46](https://user-images.githubusercontent.com/94033/61357482-0cc51180-a881-11e9-88b5-849b1095e309.png)

Tested on Firefox 68, Chrome 75.

Looking at the CSS, perhaps the `margin-left: 0px` override should not be there, or perhaps the side bar should be completely hidden since it doesn't seem to have meaningful content on this page...(?)

![Screenshot from 2019-07-17 10-44-55](https://user-images.githubusercontent.com/94033/61357581-39792900-a881-11e9-92ff-33a552e23fc4.png)

**Comment by GuillaumeGomez** [comment]
This problem has been fixed a while ago already. It's just that this crate has last been updated before we released the fix on docs.rs.

**Comment by Gekkio** [comment]
Sorry, I'm confused now :smile: Fixed in the production site, or fixed in this repository but not deployed to production? Because this problem happens in production (https://docs.rs)

**Comment by Gekkio** [comment]
Sorry, I should've been more specific about where this problem appears. Looks like there's two different pages for viewing the source, and this problem only appears in one of them.

https://docs.rs/crate/gfx/0.18.1/source/src/macros/structure.rs

https://docs.rs/gfx/0.18.1/src/gfx/macros/structure.rs.html

**Comment by GuillaumeGomez** [comment]
I didn't know there were two kind of urls for the same thing... Also, rustdoc is fixed and this fixed version is used on docs.rs *but* this crate has been generated before the fix and is therefore keeping the bug.

**Comment by Gekkio** [comment]
It's a bit unfortunate that infrequently updated crates don't get fixes, but I guess fixing that would require some new process for regenerating docs which sounds like a bigger task than just a simple bugfix. Thanks for the explanation! 😄
