### ISSUE TITLE
Grave errors during building do not increment attempt counter

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/docs.rs#382]
This means that we will build crates forever if every build results in a grave error.

**Comment by jyn514** [comment]
I wonder if we should be catching this panic at all? The worst that happens is no more builds finish until an admin logs in and restarts the server, but I'd expect most panics to be keep happening on every retry anyway, and at least that way we avoid wasting resources.

https://github.com/rust-lang/docs.rs/blob/55c7386b9178dc3d33e34508aad29a9b8f4f2639/src/utils/queue_builder.rs#L83-L99
