### ISSUE TITLE
Search results cut off

### ISSUE THREAD

**Issue by svenstaro** [rust-lang/docs.rs#388]
Recently, search results now look weird. See picture.
![2019-07-29-115057_1041x346_scrot](https://user-images.githubusercontent.com/1664/62039150-64f00200-b1f7-11e9-8c84-ed06a656c071.png)
Basically, everything is cut off after a certain y coordinate. The problematic CSS seems to be `overflow-y: auto`. Removing that css entry fixes this issue but I don't know whether this is actually the proper fix.

**Comment by GuillaumeGomez** [comment]
Indeed, removing it fixes the issue.

**Comment by heftig** [comment]
Removing the `position: absolute` from `#results` also fixes the issue.

**Comment by GuillaumeGomez** [comment]
I feel a bit less sure about this solution...

**Comment by GuillaumeGomez** [comment]
@heftig: I don't see the `position: absolute` on `#results` on this page: https://docs.rs/stm32f2/0.8.0/stm32f2/stm32f215/hash/sr/struct.R.html?search=as

**Comment by GuillaumeGomez** [comment]
Nevermind, the only issue with your solution would be that we'd overload more rustdoc css. This doesn't sound like a good idea at this point...
