### ISSUE TITLE
Unclear which platforms are used to build docs

### ISSUE THREAD

**Issue by shepmaster** [rust-lang/docs.rs#399]
I got an issue on SNAFU that its docs are not built for `*-apple-*` unlike some other crates. This made the reporter think that the crate wasn't supported on certain platforms.

I don't actually know which platforms are used to build the docs, so it's difficult to know if my crate is failing to build for some reason on certain platforms. I also couldn't find how to view the build logs when there's not a complete total build failure. Through hunting through other issues, I see that there's [a `/builds`](https://docs.rs/crate/snafu/0.5.0/builds) route, which doesn't appear to be linked from anywhere. The [build log](https://docs.rs/crate/snafu/0.5.0/builds/181198) only shows the output from a single platform, and doesn't specify which it is.

Related:

- #343
- #141

**Comment by jyn514** [comment]
Hello and sorry for the long wait. The available platforms are unfortunately not currently documented, I've listed them below:

-  x86_64-unknown-linux-gnu
- x86_64-apple-darwin
- x86_64-pc-windows-msvc
- i686-unknown-linux-gnu
- i686-apple-darwin
- i686-pc-windows-msvc

The output you're seeing is for the default target, x86_64-unknown-linux-gnu. I am actually not sure how to access build logs from other targets, I'd have to look into that.

I'll leave this open until we properly document all the on the /about page.

**Comment by jyn514** [comment]
This was documented in #550. You can see the docs here: https://docs.rs/about#metadata
