### ISSUE TITLE
Top bar covers target of anchor link

### ISSUE THREAD

**Issue by bluss** [rust-lang/docs.rs#403]
If you go to search inside a specific crate, the search results for methods are focused in a way so that the method you want to see is covered by the top bar.

One example is this link: https://docs.rs/chrono/0.4.9/chrono/struct.Date.html#method.timezone

To reproduce

1. Go to https://docs.rs/chrono/0.4.9/
2. Search for timezone
3. Click the chrono::Date::timezone result (a method)
4. The method is focused, aligned flush to the top of the view — this is beneath the top bar, so it's not actually visible — scroll up a bit to see the method you clicked

Tested in browser: Firefox 68.0.2 and Chromium 76.0.3809

**Comment by GuillaumeGomez** [comment]
It's a known issue that should have been fixed a while ago by https://github.com/rust-lang/docs.rs/pull/358 I should maybe check another time...

**Comment by bluss** [comment]
I see. Since I see this in chromium and firefox, it seems persistent. Platform is Linux 64-bit. I guess that change has been applied, docs rs lists 2019-07-30 as its version

**Comment by GuillaumeGomez** [comment]
I don't know if the fix has been deployed actually. Any idea @onur ?

**Comment by PonasKovas** [comment]
This is extremely annoying, any progress?

**Comment by jyn514** [comment]
This was fixed a while ago but regressed in #637. The fix is waiting on review in #640

**Comment by jyn514** [comment]
Reverted #637: #642
