### ISSUE TITLE
imageproc docs fail to build

### ISSUE THREAD

**Issue by theotherphil** [rust-lang/docs.rs#408]
https://docs.rs/crate/imageproc/0.19.1/builds/185422

The docs build fails while attempting to document the sdl2-sys dependency https://github.com/Rust-SDL2/rust-sdl2/blob/master/sdl2-sys/build.rs#L50

This isn't an issue with docs.rs per se, but I was hoping there would be a known workaround for dependencies that docs.rs cannot build. This dependency is only required if a feature is enabled, so  I'll disable that feature in package.metadata.docs.rs for now to get _some_ documentation.

**Comment by pietroalbini** [comment]
I'll take a look on Monday if nobody else from the team beats me to it.

**Comment by pietroalbini** [comment]
I'm sorry but you'll have to disable that feature. One of your dependencies is trying to download with `curl` something from the internet in its build script.

While it's technically possible for me to fix that build failure (looks like the `curl` CLI is missing?) [an upcoming docs.rs change](https://github.com/rust-lang/docs.rs/pull/407) is going to remove all network access from builds. That's going to break your crate anyway, so there is no point in hacking a fix right now.

**Comment by theotherphil** [comment]
Ok, thanks for looking. Disabling network access sounds pretty sensible!
