### ISSUE TITLE
Platform selection in metadata

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/docs.rs#412]
It would be nice if one could specify a list of platforms to build the docs for in the metadata section, maybe supporting how these docs are built. 

For example, the `libc` crate currently builds the docs of the crate for pretty much all platforms that the nightly-x86_64-unknown-linux-gnu host supports, using cargo-xbuild (`cargo xdoc`) for platforms for which rustup does not ship a libcore (https://docs.rs/libc/0.2.63/libc/ - see thee "Documentation for other platforms links").

**Comment by jyn514** [comment]
See also #343

**Comment by jyn514** [comment]
This is now supported! #633

**Comment by jyn514** [comment]
Also, I noticed that the libc link is broken (it goes to https://rust-lang.github.io/libc/#platform-specific-documentation which gives a 404). However I assume that libc wants to build for a large number of targets. If you want to build for more than 10 (our current default limit), you can open a new issue and I'll raise the limit.
