### ISSUE TITLE
Left slider not working

### ISSUE THREAD

**Issue by liborty** [rust-lang/docs.rs#417]
Firefox 69.0.1, Linux x86-64.
Even when the left hand slider is put hard down, some of the docs menu items (functions, crates, etc) remain hidden and inaccessible.
![Screenshot from 2019-10-01 09-30-17](https://user-images.githubusercontent.com/457124/65924210-0fbab180-e42f-11e9-8ebe-1f8a36c543c9.png)

**Comment by liborty** [comment]
Thank you. I would not say it was such a small matter, as it made a lot of documentation inaccessible.

**Comment by GuillaumeGomez** [comment]
It's fixed in rustdoc.

@pietroalbini @QuietMisdreavus Any idea if we could/should update the current noscript stylesheets to backport this change?

**Comment by pietroalbini** [comment]
That's not trivial as we'd need to change the noscript stylesheets for each affected nightly.

**Comment by GuillaumeGomez** [comment]
Indeed. :)

**Comment by jyn514** [comment]
Closing in favor of #464
