### ISSUE TITLE
A crate published on crates.io is missed by docs.rs

### ISSUE THREAD

**Issue by CreepySkeleton** [rust-lang/docs.rs#425]
I published [proc-macro-error 0.3.0](https://crates.io/crates/proc-macro-error/0.3.0) crate about 8 hours ago but docs.rs *still* hasn't built docs for it. 

Once I published v0.3.1 with minimal cosmetic changes it got the docs in ~5 minutes.

Is it ok?

**Comment by fbstj** [comment]
this is #422 being fixed by #424

**Comment by pietroalbini** [comment]
The error is weird, I'll look into it.

**Comment by pietroalbini** [comment]
A fix is ready in #426.

**Comment by pietroalbini** [comment]
This should now be fixed! Queued a build for version 0.3.0 of your crate.

**Comment by CreepySkeleton** [comment]
I confirm this is now fixed, docs for 0.3.0 are in place. Thank you!
