### ISSUE TITLE
Publish of a crate was missed

### ISSUE THREAD

**Issue by nagisa** [rust-lang/docs.rs#431]
**Crate name:** stacker 0.1.6
**Build failure link:** https://docs.rs/crate/stacker/0.1.6/builds

**Additional details:**

[stacker 0.1.6](https://crates.io/crates/stacker) was released 5 days ago. docs.rs appears to not have been able to pick-up on this and never scheduled a build?

Another crate published at approx the same time did get built fine: https://docs.rs/crate/psm/0.1.5/builds

**Comment by pietroalbini** [comment]
Weird, did a rebuild and it was fine. There were a few bugs after the rustwide rollout, so this crate might have encountered one of them. The docs are available here now: https://docs.rs/stacker/0.1.6/stacker/
