### ISSUE TITLE
Host core and alloc

### ISSUE THREAD

**Issue by Michael-F-Bryan** [rust-lang/docs.rs#433]
In the same vein as #56, docs.rs should also host docs for the `core` and `alloc` crates.

Originally mentioned [on the users forum](https://users.rust-lang.org/t/publish-docs-for-std-on-docs-rs/32769/4?u=michael-f-bryan):

> https://docs.rs/std 2 now redirects! Looks like it has been done for std, but not core or alloc.

**Comment by de-vri-es** [comment]
Would be fixed by #435.
