### ISSUE TITLE
stm32h7xx-hal build timeout

### ISSUE THREAD

**Issue by hargoniX** [rust-lang/docs.rs#434]
**Crate name:** stm32h7xx-hal
**Build failure link:** https://docs.rs/crate/stm32h7xx-hal/0.2.0/builds/190458

**Requested RAM limit:** No changes
**Requested timeout:** I am not exactly sure by how much this should be increased but the logs look like its about to finish building the main crate itself which shouldn't take too long, 18 minutes should be perfectly fine, probably even an overkill. 

**Why your crate needs the resource increases:** It's an embedded crate so the build, quite sadly, takes an eternity.

**Comment by pietroalbini** [comment]
Increased the timeout to 20 minutes and queued a rebuild!
