### ISSUE TITLE
Add dependency

### ISSUE THREAD

**Issue by 19h** [rust-lang/docs.rs#436]
**Crate name:** traildb-sys
**Build failure link:** https://docs.rs/crate/traildb-sys/0.6.0/builds/192057

**Additional details:**
I just published a new low-level crate supporting the traildb crate in providing a high-level API to TrailDB. This depends on Judy (http://judy.sourceforge.net/). Is it possible to add that dependency?

Thanks! 🐻

**Comment by GuillaumeGomez** [comment]
@pietroalbini @QuietMisdreavus It'd be really nice to start explaining to people how to handle doc generation without enforcing external libraries dependencies.

**Comment by pietroalbini** [comment]
Thanks for reporting this @19h!

I pushed [a commit](https://github.com/rust-lang/crates-build-env/commit/6879b813340c1ab605d74d6c3f5fa1964b72d916) to add `libjudy-dev` (from Ubuntu 18.04 LTS) to the build environment. I'll check back in in a few hours once the environment rebuild is complete to schedule a build of your crate.

**Comment by pietroalbini** [comment]
@GuillaumeGomez it's actually good that people report missing dependencies and that we add them, as the build environment is also used by Crater which needs to actually build and sometimes test the crates.

**Comment by GuillaumeGomez** [comment]
The two should be separated from my point of view. Testing a crate and documenting it are two very different things.

**Comment by pietroalbini** [comment]
@19h did a rebuild, but it seems like `libarchive-dev` is also missing. Added it https://github.com/rust-lang/crates-build-env/commit/9dda900fec0bed82a6f363644dacc00f0554c96a, will need to wait for the environment rebuild to happen.

**Comment by 19h** [comment]
@pietroalbini thanks for adding the dependencies!

**Comment by pietroalbini** [comment]
The docs are live! https://docs.rs/traildb-sys/0.6.3/traildb_sys/
