### ISSUE TITLE
Missing docs for non proc-macro crates

### ISSUE THREAD

**Issue by devashishdxt** [rust-lang/docs.rs#438]
Crate names:
- `abci-rs`: https://docs.rs/crate/abci-rs/0.1.1
- `libsecp256k1`: https://docs.rs/crate/libsecp256k1/0.3.1

**Comment by CreepySkeleton** [comment]
My [`proc-macro-error v0.3.4`](https://crates.io/crates/proc-macro-error/0.3.4) is missing on docs.rs. It's been 4 hours since publish.

**Comment by jyn514** [comment]
@CreepySkeleton proc-macro failures are a known error, see #422.

**Comment by CreepySkeleton** [comment]
@jyn514 Yes, but, despite its name, `proc-macro-error` is not a proc-macro on it's on but a lib that is supposed to be used by proc-macros. And by the way, I reported it 19 days ago, it was time when *no* crates got their docs, and now it's long fixed.

**Comment by Arnavion** [comment]
>Crate names:
>
>    * `abci-rs`: https://docs.rs/crate/abci-rs/0.1.1
>
>    * `libsecp256k1`: https://docs.rs/crate/libsecp256k1/0.3.1

Both of these are due to #477

**Comment by jyn514** [comment]
@pietroalbini can you rerun the build for these crates? After that we can close this issue.

**Comment by pietroalbini** [comment]
Queued a rebuild for them.
