### ISSUE TITLE
capnp-rpc v0.10.0 failed to build

### ISSUE THREAD

**Issue by dwrensha** [rust-lang/docs.rs#439]
**Crate name:**
capnp-rpc

**Build failure link:**
https://docs.rs/crate/capnp-rpc/0.10.0/builds/166316

**Additional details:**
The reported error is
```
Error while trying to execute `capnp compile`: Failed: No such file or directory (os error 2).  Please verify that version 0.5.2 or higher of the capnp executable is installed on your system. See https://capnproto.org/install.html\" }\', src/libcore/result.rs:999:5\nnote: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```
This can happen when the `capnp` executable is not installed on the system. However, it appears to me that `capnp` ought to be installed, as `capnproto` appears in the package list: https://github.com/rust-lang/crates-build-env/blob/9dda900fec0bed82a6f363644dacc00f0554c96a/packages.txt#L11

How can I debug this problem?

...
Actually, looking deeper, apparently at least one previous release succeeded: https://docs.rs/crate/capnp-rpc/0.9.0
Nothing major should have changed since then on my side.
Is it possible that it will work if I try again? Is there a way to try again without releasing a new version?

**Comment by jyn514** [comment]
@dwrensha The change happened on our side, we switched the builder to use Rustwide: #407. https://docs.rs/crate/capnp-rpc/0.9.0/builds shows it was built before that switch.

I am not sure why capnp is missing, but there are instructions for debugging here: https://github.com/rust-lang/docs.rs/wiki/Making-changes-to-the-build-environment

**Comment by dwrensha** [comment]
Thanks!
Looks like the latest version succeeded, so I'm not going to worry about it.
https://docs.rs/capnp-rpc/0.11.0/capnp_rpc/
