### ISSUE TITLE
Cfg missing during build script build

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/docs.rs#440]
**Crate name:** proc-macro2
**Old working build:** https://docs.rs/crate/proc-macro2/1.0.4/builds/186665
**Build failure link:** https://docs.rs/crate/proc-macro2/1.0.6/builds/192719

**Additional details:**
With the switch to rustwide, it seems that `--cfg` entries from our `[package.metadata.docs.rs]` are no longer seen by our build script (but still present when building the crate), which causes the build to fail.

Notice how in the working 1.0.4 build the rustc invocation that builds build.rs has `--cfg procmacro2_semver_exempt`. From tracing through the types in the failing 1.0.6 build, I believe that failure could only happen if `--cfg procmacro2_semver_exempt` is set for the lib.rs rustc invocation but not for the build.rs rustc invocation.

Relevant part of Cargo.toml: https://github.com/alexcrichton/proc-macro2/blob/1.0.6/Cargo.toml#L18-L20

Diff between working build current failing build: https://github.com/alexcrichton/proc-macro2/compare/1.0.4...1.0.6
(no relevant changes on our end).

**Comment by dtolnay** [comment]
FYI @pietroalbini -- this was causing the failure you saw in https://github.com/rust-lang/docs.rs/issues/23#issuecomment-540228220.

**Comment by jyn514** [comment]
@dtolnay it looks like this error started occurring after the switch to rustwide (https://github.com/rust-lang/docs.rs/pull/407). It's probably due to https://github.com/rust-lang/cargo/issues/4423 - as you can see in the build logs `--target` is set in the latest (broken) build, but not in the old one.

**Comment by elichai** [comment]
@dtolnay I don't think this is an issue with docs.rs. 
https://github.com/alexcrichton/proc-macro2/pull/207

**Comment by jyn514** [comment]
This was fixed in https://github.com/rust-lang/docs.rs/pull/491, 1.0.7 is live: https://docs.rs/crate/proc-macro2/1.0.7
