### ISSUE TITLE
provide option to run daemon without the crates.io index updater

### ISSUE THREAD

**Issue by QuietMisdreavus** [rust-lang/docs.rs#443]
When testing docs.rs, it's sometimes useful to just queue crates manually, and not try to keep up with the entire crates.io index. Since the code that refreshes the index and queues up builds is already a separate thread in the daemon, it shouldn't be that much work to provide an option to disable that thread for development.

(If done right, his can also make it easier to provide a sort of "white-label" installer in the future that allows people to only host docs for certain crates, potentially from custom registries or arbitrary repositories. This is something that's been requested a few times informally, and would probably be a boon to production/enterprise Rust users.)

**Comment by jyn514** [comment]
This would also make it easier to develop locally without having my CPU/disk burn up.

**Comment by jyn514** [comment]
Another thing to tack onto this - It would be nice to run local builds for docs.rs offline, for example when you have limited internet or in an enterprise scenario.

Blockers for builds:
- Use cached toolchain versions: https://github.com/rust-lang/docs.rs/issues/447#issuecomment-546836765
- Use cached versions of `rustops/crates-build-env`
- Use cached versions of {cargo-install-update,rustup-toolchain-install-master,git-credential-null}
- Don't fetch yanked versions and authors from `crates.io` in `db::add_package`

Blockers for web ui:
- Fallback to local CSS files if cloudflare doesn't respond. This is how it looks without the CSS: 
![image](https://user-images.githubusercontent.com/23638587/68545389-bed99980-039a-11ea-89d3-40dc8c1d0232.png)

**Comment by jyn514** [comment]
Fixed by https://github.com/rust-lang/docs.rs/pull/872
