### ISSUE TITLE
nrfxlib needs bindgen binary to build

### ISSUE THREAD

**Issue by jonathanpallant** [rust-lang/docs.rs#444]
**Crate name:**
nrfxlib
nrfxlib-sys

**Build failure link:**
https://docs.rs/crate/nrfxlib-sys/0.2.0
https://docs.rs/crate/nrfxlib/0.2.1

**Additional details:**
I used to use bindgen as a build-dependency to convert my third-party header files to Rust source in nrfxlib-sys. Now I shell out to the bindgen command line tool, to work around Cargo 5730. Is it possible to get bindgen pre-installed in the build environment? I found it was already installed when I used the Rust action on Github.

**Comment by jyn514** [comment]
@jonathanpallant if bindgen is not packaged on Ubuntu 18.04, it is unlikely this can be fixed. We use https://github.com/rust-lang/crates-build-env for the build environment and it only installs dependencies that are packaged.

**Comment by thejpster** [comment]
(swapped to my personal account)

Hmm, that makes sense. It's packaged for 19.04 - https://packages.ubuntu.com/disco/bindgen.

I assume there's no mechanism to `cargo install` something?

**Comment by jyn514** [comment]
> It's packaged for 19.04

Ok, in that case we can add it when 20.04 gets released in a few months.

> I assume there's no mechanism to cargo install something?

No, because the build environment doesn't have a Rust toolchain installed.

**Comment by jonathanpallant** [comment]
So, it seems rust-bindgen isn't packaged for focal (20.04) yet. I presume that means someone needs to do some work to package it?

**Comment by jyn514** [comment]
That's correct. I didn't realize that packages for 19.04 weren't automatically transferred over to 20.04, that seems like a shame.

**Comment by jyn514** [comment]
Another alternative I just thought of is to install bindgen on the host toolchain with the rest of the toolchain components. Rustwide exposes a [cargo command](https://docs.rs/rustwide/0.5.1/rustwide/toolchain/struct.Toolchain.html#method.cargo) - cc @pietroalbini , if I run `cargo install bindgen` with that, will `bindgen` be in PATH inside the build environment?

**Comment by pietroalbini** [comment]
> if I run cargo install bindgen with that, will bindgen be in PATH inside the build environment?

It should be.

**Comment by jyn514** [comment]
rust-lang/cargo#5730 is fixed with the new resolver, so you should no longer need this workaround. Eventually rust-lang/rfcs#3028 would allow having a build-dependency on the bindgen binary if for some reason crates want to call it as a CLI instead of a library.

I'm going to close this since there are alternatives to having docs.rs install bindgen.

**Comment by jonathanpallant** [comment]
Indeed. https://docs.rs/nrfxlib/0.6.0/nrfxlib/ rendered correctly using the new resolver.
