### ISSUE TITLE
[Feature Request] Cache builds

### ISSUE THREAD

**Issue by jyn514** [rust-lang/docs.rs#447]
I don't mind this being all or nothing, but it would be nice in `cratesfyi build crate my_crate_here && cratesfyi build crate my_crate_here` for the second build to be a no-op. I see the line `2019/10/26 03:02:42 [DEBUG] cratesfyi::db::add_package: Adding package into database` in the output, so the binary would just have to check whether the database entry exists already, and if so not rebuild the package.

Cache invalidation shouldn't be an issue since all versions on crates.io should be immutable.

**Comment by jyn514** [comment]
Related: `rustup install nightly` always installs the latest version, even if there is an earlier version that is cached. Rustwide should avoid installing the toolchain if it already exists.

**Comment by pietroalbini** [comment]
> it would be nice in `cratesfyi build crate my_crate_here && cratesfyi build crate my_crate_here` for the second build to be a no-op.

We actually rely on being able to rebuild the same version of a crate multiple times on production, for example when there is a bug in docs.rs or rustdoc and the output is broken. What's your use case for this?

> Related: rustup install nightly always installs the latest version, even if there is an earlier version that is cached. Rustwide should avoid installing the toolchain if it already exists.

This is intentional, because on production we need to always build on the latest nightly. While developing locally it's annoying though (especially with the huge stds nowadays), so what do you think about adding an environment variable that disables toolchain updates in docker-compose?

**Comment by jyn514** [comment]
> We actually rely on being able to rebuild the same version of a crate multiple times on production

Ok, in that case this probably doesn't make sense to add. I just wanted it for convenience so I don't have to remember which crates have already been built, but I can do that by looking at the website locally.

> what do you think about adding an environment variable that disables toolchain updates in docker-compose

That might be convenient. It looks like rustup doesn't have an easy way to say 'install this only if it's not installed' but we can just look at the output of `rustup toolchain list`.

**Comment by pietroalbini** [comment]
You can use [`Workspace::installed_toolchains`](https://docs.rs/rustwide/0.3.2/rustwide/struct.Workspace.html#method.installed_toolchains) to check whether the toolchain is already installed.

**Comment by jyn514** [comment]
The toolchain thing actually doesn't need a separate environment variable, you can just set `DOCSRS_TOOLCHAIN` to a specific nightly. So I don't think there's much point in keeping this issue open.
