### ISSUE TITLE
Increase sandbox limits for mimxrt1062

### ISSUE THREAD

**Issue by dflemstr** [rust-lang/docs.rs#458]
**Crate name:** mimxrt1062
**Build failure link:** https://docs.rs/crate/mimxrt1062/0.1.0/builds/194340

**Requested RAM limit:** 5GiB
**Requested timeout:** 25 min

**Why your crate needs the resource increases:** It is a typical `svd2rust` generated crate and hence contains a lot of code.  The above limits came from running `rustdoc` locally, and looking at the peaks.

**Comment by pietroalbini** [comment]
Hello, and sorry for the long delay!

The limits increase is fine, but at the moment we can't increase the amount of RAM due to a bug. Once https://github.com/rust-lang/docs.rs/pull/567 is merged we'll increase both limits!

**Comment by pietroalbini** [comment]
Increased the limits and queued a new build!
