### ISSUE TITLE
Use `minio` instead of postgres locally

### ISSUE THREAD

**Issue by jyn514** [rust-lang/docs.rs#463]
Discussed on discord:

> @QuietMisdreavus @jynelson btw... if we want to "bless" docker-compose we could add minio to it (to replicate s3) and completly ditch storing files in the db

> QuietMisdreavusYesterday at 4:32 PM
true, if there's a stock minio container then we could do that

 > pietroalbiniYesterday at 4:33 PM
yeah -- https://docs.min.io/docs/minio-docker-quickstart-guide

 > QuietMisdreavusYesterday at 4:34 PM
my current dev server would have to start running minio but that sounds fairly easy
based on your descriptions

 > jynelsonYesterday at 4:42 PM
minio is like s3 but locally? I like databases, but that would allow us to get rid of the database code which sounds nice ..

I _think_ this involves spinning up a minio container instead of a postgres container and using rusoto_s3 to interact with it. @pietroalbini would know more.

**Comment by pietroalbini** [comment]
minio wouldn't replace PostgreSQL altogether: on production we store documentation files in S3, and the rest (queue, build logs, releases...) on PostgreSQL. Adding minio locally would allow us to get rid of *parts* of the database code, but more importantly align the development environment with production.

**Comment by koenaad** [comment]
Hi :wave: I would like to dive into this.

**Comment by jyn514** [comment]
@koenaad :wave: I've never used minio myself, so you'll have to experiment with that. Here are some of the things you'll have to modify, though:

- Add a new container to the [`docker-compose.yml`](https://github.com/rust-lang/docs.rs/blob/master/docker-compose.yml) file
- Set the `AWS_ACCESS_KEY_ID` environment variable (it will be read in [`src/db/file.rs`](https://github.com/rust-lang/docs.rs/blob/master/src/db/file.rs#L121)) in that file
- ... possibly other things?

**Comment by koenaad** [comment]
Thanks for the pointers @jyn514. Don't have any experience with minio either, but I'll simply spin up the docker and see what I can do with it 😃
