### ISSUE TITLE
`nannou` crate build failed

### ISSUE THREAD

**Issue by mitchmindtree** [rust-lang/docs.rs#471]
**Crate name:** nannou
**Build failure link:** https://docs.rs/crate/nannou/0.12.0/builds/196525

**Additional details:**
The build seems to fail on the xcb dependency version 0.8.2, however this build has succeeded in the past and is currently [available on docs.rs](https://docs.rs/xcb/0.8.2/xcb/). This leads me to wonder if the cause is a bug in the latest rustdoc nightly. Is it possible to get the documentation re-built with stable?

**Comment by jyn514** [comment]
Related: https://github.com/rust-lang/docs.rs/pull/229, https://github.com/rust-lang/docs.rs/issues/228

**Comment by jyn514** [comment]
Your build error doesn't seem to be related to the version of rust, though. cc @pietroalbini, do you intentionally make `/opt/rustwide/cargo-home` read-only?

**Comment by jyn514** [comment]
It looks like `xcb` is a new dependency in `nannou 0.12`, I wonder if it's trying to write to part of the filesystem it's not supposed to. I know we changed the sandboxing pretty significantly about a month ago in the switch to rustwide: https://github.com/rust-lang/docs.rs/pull/407, maybe `xcb` hasn't been rebuilt since then?

**Comment by pietroalbini** [comment]
> Your build error doesn't seem to be related to the version of rust, though. cc @pietroalbini, do you intentionally make /opt/rustwide/cargo-home read-only?

Yeah, otherwise a malicious crate could've messed up the state for other crates.

**Comment by alberdingk-thijm** [comment]
> It looks like `xcb` is a new dependency in `nannou 0.12`, I wonder if it's trying to write to part of the filesystem it's not supposed to. I know we changed the sandboxing pretty significantly about a month ago in the switch to rustwide: #407, `xcb` hasn't been rebuilt since 2018: https://docs.rs/crate/xcb/0.8.2/builds/87332

I just tried building `xcb 0.8.2` myself using `docker-compose run web build crate xcb 0.8.2`, and this appears to be what caused the problem.
The crate has a python script `rs_client.py` which it uses to create some FFI files. The exact line it fails at is [`rs_client.py:114`](https://github.com/rtbo/rust-xcb/blob/b49e2102d62007102f2ee601f706a57196dd3af0/rs_client.py#L114).

The good news is, `xcb 0.9.0` works fine, so I think if `x11-clipboard` (the dependency of `copypasta`, the dependency of `conrod_core`, the dependency of `nannou`) upgrades to `0.9.0`, this should be fixed.

**Comment by jyn514** [comment]
Looks like this isn't a bug in docs.rs, going to close this.

**Comment by mitchmindtree** [comment]
Thanks for digging into this @alberdingk-thijm!

**Comment by alberdingk-thijm** [comment]
> Looks like this isn't a bug in docs.rs, going to close this.

@jyn514, do you happen to know when docs.rs will try to build `nannou` (and the other crates related to this error in `xcb`) again?

**Comment by jyn514** [comment]
Rebuilding automagically is #464 . Currently someone has to schedule a manual build.

**Comment by jyn514** [comment]
This particular crate won't be helped by rebuilding however because it tries to write to a read only filesystem.

**Comment by alberdingk-thijm** [comment]
We tracked down the dependency (`x11-clipboard`) that caused the error and sent a PR https://github.com/quininer/x11-clipboard/pull/17 through, which has been bubbled up to the other dependency `copypasta` in a minor patch https://github.com/jwilm/alacritty/pull/3024. `conrod_core` (the dependency which pulls in `copypasta`) just requests `0.6`, so I would think building with `copypasta 0.6.1` would get rid of this issue, although admittedly I can't seem to figure out how to tell the docker container to do that on my own machine.

**Comment by jyn514** [comment]
@alberdingk-thijm Could you make these updates in a different repo, such as https://github.com/nannou-org/nannou/issues/429? This is not a docs.rs bug.

**Comment by jyn514** [comment]
Oh hold on I think I misunderstood your comment. You're asking us to build with a different version of a minor dependency? We don't control dependency management, that's done by cargo. If you've fixed the bug you can publish a new version and docs.rs will build that version.

**Comment by alberdingk-thijm** [comment]
> Oh hold on I think I misunderstood your comment. You're asking us to build with a different version of a minor dependency? We don't control dependency management, that's done by cargo. If you've fixed the bug you can publish a new version and docs.rs will build that version.

Gotcha, that's what I was asking. Thanks for your help!
