### ISSUE TITLE
`rust-pulsectl` crate build failed

### ISSUE THREAD

**Issue by krruzic** [rust-lang/docs.rs#473]
**Crate name:**
`rust-pulsectl`

**Build failure link:**
https://docs.rs/crate/rust-pulsectl/0.2.6/builds/198526

**Additional details:**
Requested 'libpulse >= 12.0' but version of libpulse is 11.1. This happens while compiling `libpulse-sys v1.11.0`. That package successfully compiles though: https://docs.rs/crate/libpulse-sys/1.11.0/builds/185864

**Comment by jyn514** [comment]
@krruzic no obligation, but this would get fixed faster if you're willing to make a PR to crates-build-env :) instructions here: https://github.com/rust-lang/docs.rs/wiki/Making-changes-to-the-build-environment

**Comment by krruzic** [comment]
I'll see what I can do if I get a chance. Thanks for the response :)

**Comment by jyn514** [comment]
I just read your comment above more thoroughly -

> That package successfully compiles though: https://docs.rs/crate/libpulse-sys/1.11.0/builds/185864

That build happened in September, we had a big change to the build environment in early October: #407

**Comment by jyn514** [comment]
@krruzic I saw that https://github.com/krruzic/pulsectl hasn't been updated since november 2019, so I'm going to close this issue. Feel free to make a PR adding libpulse to crates-build-env if you're still interested in getting the docs working :)
