### ISSUE TITLE
Missing documentation, possibly due to package renaming

### ISSUE THREAD

**Issue by alecmocatta** [rust-lang/docs.rs#477]
**Crate name:**
constellation-rs

**Build failure link:**
https://docs.rs/crate/constellation-rs/0.1.8
"constellation-rs-0.1.8 doesn't have any documentation."

**Additional details:**
The crate is substantially unchanged since v0.1.6 which built documentation correctly in September: https://docs.rs/crate/constellation-rs/0.1.6

My other crates crates are building fine; the only out of the ordinary thing about this crate is probably this in the Cargo.toml:

```toml
[lib]
name = "constellation"
```

From a cursory glance this might be the issue:

https://github.com/rust-lang/docs.rs/blob/d9d7a33fc4405c2385aff0200b049181f6dbf83f/src/docbuilder/rustwide_builder.rs#L284-L289

Perhaps instead of the crate name it should test if any of the package names exist as directories?

**Comment by jyn514** [comment]
Build log: https://docs.rs/crate/constellation-rs/0.1.8/builds/198779

This doesn't appear to be a sandboxing issue, there's no errors in the build.

**Comment by jyn514** [comment]
Ah I missed where you said that the lib name differed from the crate name, that's probably it.

**Comment by GuyL99** [comment]
I think my crate encounters the same problem:
https://crates.io/crates/metropolis
Do you have any solution to this problem?

**Comment by pietroalbini** [comment]
Opened a PR to fix the underlying issue: https://github.com/rust-lang/docs.rs/pull/487

**Comment by pietroalbini** [comment]
@alecmocatta @GuyL99 scheduled a rebuild of constellation-rs 0.1.8 and metropolis 0.3.2. Please let me know if you need to build more crates.

**Comment by zao** [comment]
@pietroalbini I didn't bother mention my crate as I assumed that everything that missed docs would be rebuilt automagically. I've got serpent-cipher 0.1.2 suffering from the same problem.

**Comment by pietroalbini** [comment]
@zao just queued a rebuild.

**Comment by jyn514** [comment]
@zao rebuilding automagically is #464
