### ISSUE TITLE
pam-sys needs libpam0g-dev

### ISSUE THREAD

**Issue by 1wilkens** [rust-lang/docs.rs#479]
**Crate name:**
- `pam-sys`

**Build failure link:**
https://docs.rs/crate/pam-sys/1.0.0-alpha1/builds/198171

**Additional details:**
`pam-sys` generated bindings for the Linux PAM stack via `bindgen` and thus needs headers of this library to include them in `wrapper.h`. The required Ubuntu package should be `libpam0g-dev`.

**Comment by jyn514** [comment]
@1wilkens no obligation, but this would get fixed faster if you're willing to make a PR to crates-build-env :) instructions here: https://github.com/rust-lang/docs.rs/wiki/Making-changes-to-the-build-environment

**Comment by 1wilkens** [comment]
Ah sorry I totally missed that. Will do as soon as I have the time! Thanks for the pointer!

**Comment by 1wilkens** [comment]
PR is up: https://github.com/rust-lang/crates-build-env/pull/28

**Comment by jyn514** [comment]
Just rebuilt 1.0.0-alpha, your docs are up! https://docs.rs/pam-sys/1.0.0-alpha1/pam_sys/
