### ISSUE TITLE
doesn't have any documentation

### ISSUE THREAD

**Issue by GuyL99** [rust-lang/docs.rs#482]
My crate metropolis builds ok  and when I run cargo doc --no-deps (or cargo doc --all) it builds ok and I can see that the documentation is ok(in target/doc) but when I publish it, I get this message:
metropolis-0.1.8 doesn't have any documentation.
this is the link to the crate:
https://crates.io/crates/metropolis

I've tried out some things butt nothing worked. Can anyone help me with this?
Does anybody have any idea what can I do to solve this?
Thanks!

**Comment by alecmocatta** [comment]
This I belive has the same cause as https://github.com/rust-lang/docs.rs/issues/477; namely docs.rs not correctly handling your package rename: https://github.com/GuyL99/metropolis/blob/d567a715a90e08bb44af1422b5b8bd4bb48492a9/Cargo.toml#L32-L33

**Comment by jyn514** [comment]
#477 was fixed by https://github.com/rust-lang/docs.rs/pull/487.
