### ISSUE TITLE
No Fortran compiler available

### ISSUE THREAD

**Issue by SolidTux** [rust-lang/docs.rs#483]
**Crate name:** arpack-ng-sys
**Build failure link:** https://docs.rs/crate/arpack-ng-sys/0.1.0/builds/200378

**Additional details:** arpack-ng needs a Fortran compiler for building.

Would it be possible to make gfortran available?

**Comment by jyn514** [comment]
Sorry about that, apparently github automatically closes mentioned issues even if the changes haven't been merged yet.

**Comment by jyn514** [comment]
This is waiting for the new docker image to be uploaded; after that's finished I can queue a rebuild.

**Comment by jyn514** [comment]
This is built!
