### ISSUE TITLE
The syntax highlighter used for the HTML source code display does not account for the "logical and" operator.

### ISSUE THREAD

**Issue by slightlyoutofphase** [rust-lang/docs.rs#484]
That is, `&&`. This is the case in both dark and light mode, it seems (it only ever highlights the first `&`.)

Some source from a crate of mine, with the bug visible:
https://docs.rs/staticvec/0.4.4/src/staticvec/lib.rs.html#384

**Comment by jyn514** [comment]
@slightlyoutofphase this page is generated by rustdoc, not by docs.rs. Do you have the same problem when running `cargo doc` locally?

**Comment by matklad** [comment]
I believe this was fixed a while ago in rustc, looks correctly now: https://docs.rs/staticvec/0.10.2/src/staticvec/lib.rs.html#964. I think that version is just cached output of older rustc?

**Comment by jyn514** [comment]
Closing as duplicate of https://github.com/rust-lang/docs.rs/issues/464
