### ISSUE TITLE
Confusing how to get to docs for old versions of a crate

### ISSUE THREAD

**Issue by faern** [rust-lang/docs.rs#488]
Today I figured out how to go to documentation for old versions of crates without entering the address manually. After using the site for a few years. But it was not very obvious. Here I will take `futures` as an example. It had a 0.3 release recently, but a ton of software uses the 0.1 branch, so it's important to be able to reach that.

1. Search for `futures` on docs.rs.
2. Click the top result. I end up at https://docs.rs/futures/0.3.1/futures/.
3. I hover the "futures-0.3.1" menu in the top left, go to the "versions" list and click "0.1.29". Now I come to https://docs.rs/crate/futures/0.1.29.
4. So far so good. But the page I land on does not show the docs for 0.1.29. Instead I see this in the side bar:
  ![docs rs-confusing-links-to-old-docs](https://user-images.githubusercontent.com/332294/69541168-d3b45080-0f88-11ea-83ad-f7f7d6f4c1d9.png)

In the above screenshot, one of the links titled "Documentation" leads to https://docs.rs/futures and the other one to https://docs.rs/futures/0.1.29/futures/. However, nothing visual indicates that the links would lead to different places, nor which one would actually take me to the docs I'm looking for.

**Comment by faern** [comment]
I think there are two UX inconsistencies at play here.

1. Being on the docs for a crate and clicking the link leading to another version brings me to a "crate" tab for that version. I would expect it to bring me directly to the documentation for the other version. Because I was already looking at docs, and what would I do on docs.rs if not look at docs?

2. The "documentation" tab does not work how a tab usually works. It does not change the content *under* said tab, it brings me to a whole different page where the tabs are gone. So if I click on the "documentation" tab I can't go to the "crate" or "source" tabs again, because this entire view is gone. The other two tabs are consistent in that they actually only change the content under the tab, not bring me to a completely different page.

**Comment by jyn514** [comment]
1. is definitely non-intuitive, I think we should change it to redirect like you said to https://docs.rs/futures/0.1.29/futures/.

2. can't be fixed, unfortunately (or at least, I don't think we want to fix it). That 'Documentation' link is from the `documentation = ` section of Cargo.toml, which of course doesn't have the version in it. We can't infer the version in every case because it could also lead to another site that's not docs.rs and doesn't use our URL scheme. See e.g. https://docs.rs/crate/ring/

**Comment by jyn514** [comment]
Actually I think the right thing to do for 1. is to redirect to the same page but with the version number bumped, like we do for `latest_version`. We have most of the groundwork in place, we just have to pass it to the template.

**Comment by roy-work** [comment]
I would also like having the version select — if I'm on the documentation — to keep me, as much as possible, on the documentation. (Instead of having to jump through the crate's page, back to the docs, then look up the thing I wanted in that version…)
