### ISSUE TITLE
docs.rs search is ordered randomly for non-exact matches

### ISSUE THREAD

**Issue by CGQAQ** [rust-lang/docs.rs#489]
Search for Tokio and tokio cames out completely different result
tokio first result: `tokio-0.2.0-alpha.6`
Tokio first result: `new-tokio-smtp-0.8.1`, and DO NOT have `tokio-0.2.0-alpha.6` at all
futures first result:  `futures-0.3.1`
Futures first result: `futures_future-0.1.1`, and `futures-0.3.1` is fifth result
I don't think this is the behavior a search engine should be.

![a](https://user-images.githubusercontent.com/15936231/69608569-b653b500-1062-11ea-9536-3476bfe0009c.png)
![a-r](https://user-images.githubusercontent.com/15936231/69608570-b653b500-1062-11ea-85db-298333a3054e.png)
![b](https://user-images.githubusercontent.com/15936231/69608571-b6ec4b80-1062-11ea-8136-01b95b42bd0a.png)
![b-r](https://user-images.githubusercontent.com/15936231/69608572-b6ec4b80-1062-11ea-8652-8a551dd38f0f.png)
![c](https://user-images.githubusercontent.com/15936231/69608573-b6ec4b80-1062-11ea-9130-19c35cb1a697.png)
![c-r](https://user-images.githubusercontent.com/15936231/69608575-b784e200-1062-11ea-8684-49315dfcbb16.png)

P.S.: I found this when I was in bed, using my phone to search tokio doc, and my keyboard auto capitalized first character of tokio

**Comment by Zexbe** [comment]
I'm not sure that is the problem. If you do the exact same search, and hit refresh the results change.

**Comment by jyn514** [comment]
I came up with a SQL query that works but is kind of complicated:
```sql
WITH valid_releases AS (
    SELECT *
    FROM releases INNER JOIN crates ON releases.crate_id = crates.id
    WHERE yanked = false AND rustdoc_status = true AND name LIKE '%regex%'
), ordering AS (
  SELECT ROW_NUMBER() OVER (
    PARTITION BY name
    ORDER BY
      name = 'regex' DESC,
      MAX(version) > '1.0', -- TODO: semver in SQL ??
      SUM(downloads) DESC,
      name
  ) as row,
      name, MAX(version) as version,
      SUM(downloads) as downloads
    FROM valid_releases
    GROUP BY name
    ORDER BY
      name = 'regex' DESC,
      MAX(version) > '1.0', -- TODO: semver in SQL ??
      SUM(downloads) DESC,
      name
    LIMIT 10
) SELECT ordering.*, release_time -- , description, github_stars
  FROM releases INNER JOIN crates ON releases.crate_id = crates.id
                INNER JOIN ordering
                  ON releases.version = ordering.version AND crates.name = ordering.name
  ORDER BY ordering.row ASC;
```

**Comment by jyn514** [comment]
> I'm not sure that is the problem. If you do the exact same search, and hit refresh the results change.

BTW this is also partially cause by using `LIKE` instead of `ILIKE`, so the original issue report was also correct.

**Comment by jyn514** [comment]
The new behavior for `tokio` is
1. `tokio`
2. `tokyo`
3. `tokio-h2`
... various other `tokio-` crates

The new behavior for `Tokio` is
1. `tokio`
2. `tokio-h2`
... various other `tokio-` crates
