### ISSUE TITLE
Build succeeds, yet no documentation shows up

### ISSUE THREAD

**Issue by davidpdrsn** [rust-lang/docs.rs#500]
**Crate name:** https://crates.io/crates/bae
**Build failure link:** https://docs.rs/crate/bae/0.1.2/builds

**Additional details:**
The build succeeds, yet no documentation shows up https://docs.rs/crate/bae/0.1.2 🤔

**Comment by jyn514** [comment]
Duplicate of https://github.com/rust-lang/docs.rs/issues/422
