### ISSUE TITLE
gpgme docs doesn't build

### ISSUE THREAD

**Issue by alexanderkjall** [rust-lang/docs.rs#501]
**Crate name:**
gpgme

**Build failure link:**
https://docs.rs/crate/gpgme/0.9.1/builds/188420

**Additional details:**

Issue seems to be that the binary gpg-error-config isn't installed, this binary is provided by libgpg-error-dev in debian.

**Comment by johnschug** [comment]
I've opened a pull request (rust-lang/crates-build-env#23) that should fix this once it makes its way to the doc.rs builders.

**Comment by pietroalbini** [comment]
I will queue a rebuild once the image is ready.

**Comment by pietroalbini** [comment]
Queued a build with the new Docker image.

**Comment by pietroalbini** [comment]
And it's live :tada: 

https://docs.rs/gpgme/0.9.1/gpgme/
