### ISSUE TITLE
What should happen if crate name conflicting with internal link like https://docs.rs/releases and https://docs.rs/about

### ISSUE THREAD

**Issue by matematikaadit** [rust-lang/docs.rs#51]
For example, if someone publish a crate named [**releases**](https://crates.io/crates/releases) or [**about**](https://crates.io/crates/about) (which currently doesn't exist), their docs should be served in https://docs.rs/releases and https://docs.rs/about respectively right? But currently those page was used as a listing and about page.

Possible solutions: move those internal page under something that isn't a valid crate name.

EDIT: https://docs.rs/about/0.1.1 already exist.

**Comment by SShrike** [comment]
I suppose the only way to fix this is to put all the docs under a seperate folder? Something like https://docs.rs/crate/<name>?

**Comment by matematikaadit** [comment]
Ah, after checking, just notice that we already have https://docs.rs/crate/<cratename>

Using clap crate as example:
- https://docs.rs/crate/clap/ (the readme section of the crate)
- https://docs.rs/crate/clap/2.13.0/ (also the readme section)
- https://docs.rs/crate/clap/2.13.0/source/ (the source section)

**Comment by SShrike** [comment]
Oh yes, I forgot about that, it's actually just a shortcut. I suppose in that case this is mostly a non-issue, people with those crate names will just have to link directly.

**Comment by matematikaadit** [comment]
Though, it means those people can't have shortcut to the latest version of their docs page.

**Comment by onur** [comment]
@matematikaadit actually they can.

`releases` and `about` are the only keywords reserved for docs.rs (`crate` is already a keyword in rust). And only this URL will serve docs.rs' about page: <https://docs.rs/about>. If crate owner wants to give a link to his crate, he can use: <https://docs.rs/about/>.

`releases` is a bit different. If someone releases a crate named `releases` he needs use a URL similar to this: <https://docs.rs/releases/*/releases>.

**Comment by matematikaadit** [comment]
Oh.. that's handy. Didn't know you can do that. But I suppose people who want to links to docs.rs' about page didn't mistakenly use https://docs.rs/about/

Anyway, since those link are just shortcut, and there's a workaround, I'm back to the question: What should happen if a crate name conflicting with internal link?

1. Just left it as it's and inform the crate owner those workaround if they want to use the shortcut.
2. Moves those internal page (`release`, `about`, and if there's a plan for others) into another place which won't conflict with any crate name.
3. Other possible alternatives. (like treating `https://docs.rs/crate/<cratename>` as another shortcut, which currently isn't redirecting to `https://docs.rs/crate/<cratename>/<latest-version>`)

**Comment by onur** [comment]
TBH I am not planning to change URL structure. First solution is best for me. And this is only an exception for `releases` crate name. If someone releases a crate with `releases` name and if he decides to use docs.rs for documentation link, we can inform him with correct link.

**Comment by jyn514** [comment]
cc #514, which blacklists crates with these names. As mentioned in https://github.com/rust-lang/docs.rs/pull/514#issuecomment-563388094, future internal routes will have a `/_/` prefix.

**Comment by jyn514** [comment]
Closing this since `releases` and `about` have been blacklisted, and future core pages will use a leading `/_/` to make sure they don't conflict.
