### ISSUE TITLE
sysinfo crate is marked "not a library", but it's wrong

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/docs.rs#511]
As you can see when going on https://docs.rs/crate/sysinfo/0.10.0, you have a big message saying "sysinfo-0.10.0 is not a library", which is wrong.

**Comment by jyn514** [comment]
Duplicate of https://github.com/rust-lang/docs.rs/issues/503. Should be fixed by https://github.com/rust-lang/docs.rs/pull/508.
