### ISSUE TITLE
Go to latest version breaks for /src/ when item was renamed

### ISSUE THREAD

**Issue by jyn514** [rust-lang/docs.rs#513]
I noticed this while investigating https://github.com/rust-lang/docs.rs/issues/357: any time you click 'Go To Latest' while viewing source code, it redirects to https://docs.rs/:crate/:version/src/:crate/?search=rs. This is clearly not desired behavior (it gives a 404).

Don't have time to debug right now but the relevant code is https://github.com/rust-lang/docs.rs/blob/d9d7a33fc4405c2385aff0200b049181f6dbf83f/src/web/rustdoc.rs#L293.

**Comment by jyn514** [comment]
I can't reproduce this bug :laughing:

**Comment by jyn514** [comment]
Ok it turns out the bug is much more limited than I thought which is good - it's only if the item was renamed or deleted. Test case: https://docs.rs/pyo3/0.2.7/src/pyo3/objects/exc.rs.html

**Comment by jyn514** [comment]
Mentoring instructions:

This only requires changing [the frontend](https://github.com/rust-lang/docs.rs/blob/master/src/web/rustdoc.rs#L300).

1. Check [here](https://github.com/rust-lang/docs.rs/blob/master/src/web/rustdoc.rs#L314) if the 3rd part of the URL is `src`; if so, don't add it to `crate_root`.
2. Currently, we unconditionally search for the 2nd part of the filename, which for source files is the file extension (usually `.rs`). Change this to search for the 1st part of the filename if the 3rd part of the URL is `src`.

There's more information about this in the comments for the function I linked.

Note that the URL may include both a platform and `src`, e.g. https://docs.rs/pyo3/0.2.7/x86_64-pc-windows-msvc/src/pyo3/lib.rs.html.

**Comment by Zexbe** [comment]
I found another example, If you go to this link
https://docs.rs/playground/0.1.0/playground/
The go to latest version has a bad link that goes to
https://docs.rs/playground/0.1.1/playground/?search=playground

**Comment by jyn514** [comment]
This is https://github.com/rust-lang/docs.rs/issues/502, I have an open PR waiting for review: #509

**Comment by jyn514** [comment]
This has been half-fixed - we now redirect to https://docs.rs/pyo3/0.13.2/pyo3/?search=rs, which is correct except that the search query is wrong.
