### ISSUE TITLE
Can't navigate sources from the source tab

### ISSUE THREAD

**Issue by CryZe** [rust-lang/docs.rs#515]
If you go to the source tab such as [here](https://docs.rs/crate/static_locks/0.1.0/source) all the files end up with `The requested resource does not exist`. This is because the URL is missing the `source/` in front of the navigated to file:

https://docs.rs/crate/static_locks/0.1.0/Cargo.toml
vs.
https://docs.rs/crate/static_locks/0.1.0/source/Cargo.toml

**Comment by pietroalbini** [comment]
This was caused https://github.com/rust-lang/docs.rs/pull/514, pushed and deployed a commit to fix the issue. Sorry for the bug!
