### ISSUE TITLE
phper-sys needs php-src header files.

### ISSUE THREAD

**Issue by jmjoy** [rust-lang/docs.rs#525]
**Crate name:**
phper-sys 0.0.1

**Build failure link:**
https://docs.rs/crate/phper-sys/0.0.1/builds/205828

**Why your crate needs the resource increases:**
`phper-sys` generate rust source code via `bindgen` and needs php header files and `php-config`, the required ubuntu package is `php7.1-cli`.

**Comment by jyn514** [comment]
@jmjoy no obligation, but this would get fixed faster if you're willing to make a PR to crates-build-env :) instructions here: https://github.com/rust-lang/docs.rs/wiki/Making-changes-to-the-build-environment

**Comment by jmjoy** [comment]
> @jmjoy no obligation, but this would get fixed faster if you're willing to make a PR to crates-build-env :) instructions here: https://github.com/rust-lang/docs.rs/wiki/Making-changes-to-the-build-environment

Thanks!

**Comment by jyn514** [comment]
I'd like to keep this open until we rebuild the crate, it doesn't rebuild automatically.

**Comment by jyn514** [comment]
Whoops, I [rebuilt 0.0.1](https://docs.rs/crate/phper-sys/0.0.1/builds) instead of 0.1.0, that's rebuilding now.
