### ISSUE TITLE
HTTP Status 410 Gone for the glue crate

### ISSUE THREAD

**Issue by CryZe** [rust-lang/docs.rs#527]
I just found this crate and docs.rs is acting very weird for all versions of it https://docs.rs/glue/0.1.1/glue/

and if you don't specify a version https://docs.rs/glue

**Comment by pietroalbini** [comment]
The crate was removed from the website, this is expected behavior.

**Comment by CryZe** [comment]
Maybe the error message could be improved? This looks like some internal nginx error and not some expected behavior where the crate is not available anymore.

**Comment by pietroalbini** [comment]
Yeah, I'm working on a way to do that.
