### ISSUE TITLE
Don't make calls to the database in for loops

### ISSUE THREAD

**Issue by jyn514** [rust-lang/docs.rs#530]
This is a low-priority issue, we should fix #379 and #343 first.

This came up while reviewing #529. Offenders:

- [`add_owners_into_database`](https://github.com/rust-lang/docs.rs/blob/master/src/db/add_package.rs#L415)
- [`add_package_into_database`](https://github.com/rust-lang/docs.rs/blob/master/src/db/add_package.rs#L160) (not the same but related)
- [`add_keywords_into_database`](https://github.com/rust-lang/docs.rs/blob/master/src/db/add_package.rs#L160)
- [`add_authors_into_database`](https://github.com/rust-lang/docs.rs/blob/master/src/db/add_package.rs#L160)
- [`add_path_into_database`](https://github.com/rust-lang/docs.rs/blob/master/src/db/file.rs#L216)

**Comment by jyn514** [comment]
@syphar are you interested in taking a look at this? I don't want to burden you with too much work, but it seems right up your alley :)

**Comment by syphar** [comment]
It's definitely my alley :) 

Actually I'm not sure why I already saw and fixed it when I looked through all issues :)

**Comment by syphar** [comment]
on current master, it looks like the remaining fixes are: 
- `update_owners_in_database`
- `add_keywords_into_database`
- `add_compression_into_database`

I'll start with these. 

can you elaborate where you see an issue with `add_path_into_database` or `add_package_into_database`?

**Comment by jyn514** [comment]
add_path_into_database is very different now, most of it is in the storage module. I don't see anything in storage that looks bad off the top of my head (and performance doesn't matter for the test database anyway, only for S3).

I don't remember what I was thinking about `add_package_into_database`. Maybe I wanted to combine everything into a database transaction? That's already tracked at https://github.com/rust-lang/docs.rs/issues/1071.

**Comment by syphar** [comment]
I'll leave `add_compression_into_database` as it is, it's only one record in all our cases.
