### ISSUE TITLE
`ripasso` crate build failed

### ISSUE THREAD

**Issue by alexanderkjall** [rust-lang/docs.rs#531]
**Crate name:**
ripasso

**Build failure link:**
https://docs.rs/crate/ripasso/0.3.0/builds/202407

**Additional details:**
I think the dependencies should have been added by this PR, but I can't find a way to trigger a rebuild: https://github.com/rust-lang/crates-build-env/pull/23

**Comment by jyn514** [comment]
There is not a way for library owners to queue a rebuild, see https://github.com/rust-lang/docs.rs/issues/301#issuecomment-558256524 for why this is hard. I'll queue a rebuild now and see if that helps.

**Comment by jyn514** [comment]
Queued and built! https://docs.rs/ripasso/0.3.0/ripasso/
