### ISSUE TITLE
Bad source view for some crates

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/docs.rs#535]
https://docs.rs/optional/0.5.0/optional/struct.Optioned.html links to https://docs.rs/optional/0.5.0/src/optional/lib.rs.html#1358-1361 which looks like a broken page: the line numbers come first, and then way below the actual code is shown.

**Comment by jyn514** [comment]
Hmm, that looks like a CSS issue, but it's a page generated by rustdoc ... Do you have the same problem when running `cargo doc` locally?

**Comment by RalfJung** [comment]
I think rustdoc used to have a bug that looked exactly like this. Is it possible that docs.rs generated this page with an old rustdoc and still ships it like that?

**Comment by RalfJung** [comment]
Here's the rustdoc bug: https://github.com/rust-lang/rust/issues/56720

**Comment by jyn514** [comment]
Yes, that's the issue exactly, the last build was in November 2018: https://docs.rs/crate/optional/0.5.0/builds.

Closing as duplicate of #464.

**Comment by jyn514** [comment]
@RalfJung I rebuilt optional, so it should work for this specific crate. Other crates built around the same time will still have the same bug, though.
