### ISSUE TITLE
Add support for blacklisting crates

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/docs.rs#536]
Some of the crates on docs.rs are blacklisted for legal reasons, but are still up on crates.io. Before #529 was merged we disabled them globally by blocking the route in nginx, but I'd like to move away from that model.

Deleting the old content is already covered by the `delete-crate` command, but even with that new releases would still be published. We need to add a `blacklisted_crates` table containing the names of those crates, and change the docbuilder to refuse building those crates.

**Comment by pietroalbini** [comment]
Here are some mentoring instructions for this issue!

1. A new database migration should be added [here][db-migrate], creating the database table.
2. [In the build process][build-package], use [the connection][connect-db] to query the table you just created, and return an error if the crate we're trying to build is blacklisted.
3. Add the commands `cratesfyi blacklist add CRATE` and `cratesfyi blacklist remove CRATE` [to the CLI](https://github.com/rust-lang/docs.rs/blob/master/src/bin/cratesfyi.rs). The logic to add or remove a crate should not be on the binary, but on the main docs.rs crate.

You can learn how to contribute to docs.rs [in the README](https://github.com/rust-lang/docs.rs#development), and feel free to ask questions here or on [Discord](https://discord.gg/rust-lang) (channel `#docs-rs`)! If you plan to work on this please leave a comment saying so, so we don't get multiple people working on the same issue.

[db-migrate]: https://github.com/rust-lang/docs.rs/blob/2d412a6bf5fa188850255a363487efebc88f509d/src/db/migrate.rs#L259
[build-package]: https://github.com/rust-lang/docs.rs/blob/2d412a6bf5fa188850255a363487efebc88f509d/src/docbuilder/rustwide_builder.rs#L229
[connect-db]: https://github.com/rust-lang/docs.rs/blob/2d412a6bf5fa188850255a363487efebc88f509d/src/docbuilder/rustwide_builder.rs#L244

**Comment by koenaad** [comment]
Hi @pietroalbini, thank you for the clear instructions! I would like to work on this.

**Comment by koenaad** [comment]
I have a question about how the filtering / blacklisting should function: if I understand this issue correctly, we want to prevent new versions of a known 'bad' crate to be built and added to doc.rs.

Q's:
- could there be a case in which only certain versions of a 'bad' crate are blocked and other not?
- do we want to be able to specify a version after which builds are stopped? I.e., "all versions of crate xyz after version 1.2.3".

The simple implementation I have working now only stores a crate name in `blacklisted_crates` and does not build a crate if the name exists in `blacklisted_crates`. Is this enough? (For now?)

**Comment by jyn514** [comment]
Closed in #539
