### ISSUE TITLE
Crate `grex` did not build

### ISSUE THREAD

**Issue by pemistahl** [rust-lang/docs.rs#548]
**Crate name:** grex
**Build failure link:** https://docs.rs/crate/grex/0.3.1/builds/210840

**Additional details:**
The problem is dependent crate `matrixmultiply v0.2.3`. 
The error is `array lengths can't depend on generic parameters`. 
This bug has been reported already in [bluss/matrixmultiply#50](https://github.com/bluss/matrixmultiply/issues/50). 
Seems to be a problem with the current Rust nightly as reported in [rust-lang/rust#67743](https://github.com/rust-lang/rust/issues/67743).

**Comment by jyn514** [comment]
Ping me when this gets fixed upstream and I can manually schedule a rebuild. This is hard to fix in general, see #464 and #506

**Comment by pemistahl** [comment]
I'll do. It is really unfortunate that you cannot use an older nightly or stable Rust for building the docs. This would solve the problem instantly.

**Comment by pietroalbini** [comment]
Using stable is unfortunately not possible, as docs.rs uses (a lot of) unstable features to build documentation. Using another nightly is... doable, but complicated :(

**Comment by magnusuMET** [comment]
@jyn514 This is fixed in the upstream nightly. I also have an affected crate, `netcdf` that needs a rebuild due to the same error.

**Comment by pemistahl** [comment]
@magnusuMET Thanks for letting me know. Yes please, a rebuild of the docs for crate _grex_, versions 0.3.1 and 0.3.2 would be great. Thanks in advance.

**Comment by jyn514** [comment]
I rebuilt [grex 0.3.1](https://docs.rs/crate/grex/0.3.1), [grex 0.3.2](https://docs.rs/crate/grex/0.3.2), and [netcdf 0.4.0](https://docs.rs/crate/netcdf/0.4.0).
