### ISSUE TITLE
"Versions" dropdown no longer populated.

### ISSUE THREAD

**Issue by MaulingMonkey** [rust-lang/docs.rs#554]
This seems to be missing in every crate I've checked so far - both those recently updated and those that haven't updated in awhile.  No console errors, DOM doesn't appear to be populated, occurs in both Chrome (including with adblock disabled) and FireFox (which I don't have adblock installed for at all) on multiple computers.

### Example: https://docs.rs/lazy_static/1.4.0/lazy_static/
![image](https://user-images.githubusercontent.com/75894/71953724-f21c8700-3197-11ea-8f81-da9cff5ef514.png)

**Comment by jyn514** [comment]
Probably because of https://github.com/rust-lang/docs.rs/pull/546. cc @koenaad

**Comment by jyn514** [comment]
Looks like the template is referring directly to `versions`, but we changed that field to `releases`.

https://github.com/rust-lang/docs.rs/blob/master/templates/navigation_rustdoc.hbs#L76
