### ISSUE TITLE
Consider hosting std docs

### ISSUE THREAD

**Issue by retep998** [rust-lang/docs.rs#56]
Because the Rust team is apparently incapable of hosting docs for more than one platform (https://github.com/rust-lang/rust/issues/24658), it would be cool if docs.rs could host Rust docs for all the platforms.

**Comment by sbstp** [comment]
Yeah, I would also like this. Getting docs for Windows on Linux is basically impossible. You guys already handle different platforms well, so it would be nice to integrate the docs even further.

**Comment by cbarrick** [comment]
I would like to bump this issue as well. Docs.rs is a great improvement over the plane rustdoc interface. For reference, Godoc hosts the standard library for Go: https://godoc.org/-/go

**Comment by bennofs** [comment]
This would also allow one to use `docs.rs` as an universal search for rust docs, right now I need to switch between `docs.rs` and `ruststd` docs

**Comment by yjh0502** [comment]
How about hosting standard library documentation on https://docs.rs/std ? I'm using docs.rs extensively, and usually by typing address on browser omnibox directly. It's quite annoying to type `docs.rs/crate_name` for crates and `doc.rust-lang.org/std` for standard library.

**Comment by vi** [comment]
Maybe add a quicky temporary redirect from `docs.rs/std` to `https://doc.rust-lang.org/std/` until proper implementation lands?

**Comment by Arnavion** [comment]
Official libstd docs have been publishing OS-specific docs for some time now. Don't think this is needed any more.

**Comment by suhr** [comment]
Having std docs on docs.rs would be *extremely* convenient.

**Comment by m-ou-se** [comment]
https://docs.rs/std is now online! (As a redirect to https://doc.rust-lang.org/stable/std/)

**Comment by pietroalbini** [comment]
Thanks for implementing this @m-ou-se! Closing the issue.

**Comment by Progdrasil** [comment]
The redirect is online, is it possible to have the standard library to be hosted by docs.rs eventually?

**Comment by jyn514** [comment]
@Progdrasil We do not plan to host the standard library.
