### ISSUE TITLE
Sandbox limits increase request:  jni-android-sys

### ISSUE THREAD

**Issue by MaulingMonkey** [rust-lang/docs.rs#566]
**Crate name:** jni-android-sys
**Build failure link:** https://docs.rs/crate/jni-android-sys/0.0.10/builds/212799

**Requested RAM limit:** 5GB
**Requested timeout:** As is (15 minutes)

**Why your crate needs the resource increases:**
rustdoc.exe alone uses 3.7GB of memory on windows, when executed via `cargo doc --no-deps --features "api-level-28 all force-define"`, as this crate includes generated source code to bind to the entire Android API.  While the build logs obliquely mention SIGKILL, I'm assuming this is from similar memory use on linux exceeding memory limits.

Previous builds have finished in approximately 10 minutes, so the default timeout at 15 is probably fine?

**Comment by pietroalbini** [comment]
The limits increase is fine, but at the moment we can't apply it due to a bug. Once https://github.com/rust-lang/docs.rs/issues/458 is merged we'll increase the amount of RAM available to you!

**Comment by pietroalbini** [comment]
Increased the limits and queued a new build!

**Comment by MaulingMonkey** [comment]
Build passed, much appreciated!  👍
