### ISSUE TITLE
Return crate id from match_version

### ISSUE THREAD

**Issue by jyn514** [rust-lang/docs.rs#569]
If I look at where `match_version` is used, it's always followed by a query on the database fetching the `rustdoc_status`.
    - here we fetch `rustdoc_status`: https://github.com/rust-lang/docs.rs/blob/master/src/web/releases.rs#L486
    - here we fetch `rustdoc_status` and `target_name`: https://github.com/rust-lang/docs.rs/blob/master/src/web/rustdoc.rs#L160
  
  Maybe we can change `match_version` to expose some additional information that makes the next queries easier or, even better, unnecessary?
  A simple tweak would be to return the id of the release, making the next query easier.

_Originally posted by @koenaad in https://github.com/rust-lang/docs.rs/pull/565#issuecomment-577442795_

**Comment by jyn514** [comment]
Mentoring instructions:

- Change the `Exact` and `Semver` variants on [`MatchVersion`](https://github.com/rust-lang/docs.rs/blob/9c0d43f/src/web/mod.rs#L190) to have a `(String, id)` tuple, not just a `String`.
- Change [`match_version`](https://github.com/rust-lang/docs.rs/blob/9c0d43f/src/web/mod.rs#L216) to query for `id` as well as `version`.
- Change the usages of match version (linked above) to use that id instead of `crates inner join releases ...`

**Comment by Zeegomo** [comment]
Hi, I'd like to work on this if it's still unclaimed!

**Comment by jyn514** [comment]
@Zeegomo go for it! If you have any questions, feel free to reach out here or [on Discord](https://discordapp.com/invite/f7mTXPW/). There's also lots of information in the README.
