### ISSUE TITLE
Allow compiling without libmagic

### ISSUE THREAD

**Issue by jyn514** [rust-lang/docs.rs#580]
This has been an issue for various contributors. I would like to be able to run the test suite (even if not the builds) on architectures other than x86_64 debian.

See https://github.com/bjorn3/rustc_codegen_cranelift/issues/884.

cc @Zexbe

**Comment by jyn514** [comment]
libmagic is used in [`add_path_into_database`](https://github.com/rust-lang/docs.rs/blob/master/src/db/file.rs#L154) to detect the file type. I wonder if we could get away with having a static database of file extensions?

**Comment by Zexbe** [comment]
Do you always have the file extension? Would this work? https://crates.io/crates/mime_guess

**Comment by jyn514** [comment]
Not all files have file extensions, so this isn't 100% reliable, I was mostly imagining it for local testing where you really only care about .html, .css and .js

**Comment by jyn514** [comment]
But yeah that could work locally

**Comment by jyn514** [comment]
Fixed in https://github.com/rust-lang/docs.rs/pull/600
