### ISSUE TITLE
sequoia-openpgp missing dependency nettle-dev

### ISSUE THREAD

**Issue by alexanderkjall** [rust-lang/docs.rs#583]
**Crate name:**
sequoia-openpgp

**Build failure link:**
https://docs.rs/crate/sequoia-openpgp/0.13.0/builds/207007

**Additional details:**
dependencies in debian: https://salsa.debian.org/rust-team/debcargo-conf/blob/master/src/nettle-sys/debian/debcargo.toml

**Comment by jyn514** [comment]
If you have the time, this would get fixed faster if you make a PR to crates-build-env: https://github.com/rust-lang/docs.rs/wiki/Making-changes-to-the-build-environment

**Comment by alexanderkjall** [comment]
I actually started to do that, but the instructions was for rust installations with rustup, so none of the paths matched my system.

I will take the time to get it to work and supply a PR.

**Comment by jyn514** [comment]
If you do get it working, please let me know so I can add it to the wiki!

**Comment by jyn514** [comment]
Although now that I think about it, I think Rustwide might expect rustup to be installed . . . I think the solution might be to allow a custom docker environment when running docs.rs normally. cc #522

**Comment by jyn514** [comment]
As a fallback, you can also try modifying the build environment to install rustup, which won't mess with your local rust installation and should be platform independent, it's just a few more steps and doesn't replicate the sandbox environment: https://blog.rust-lang.org/2019/09/18/upcoming-docsrs-changes.html#how-to-prepare-for-the-changes

**Comment by alexanderkjall** [comment]
Here is a pull request: https://github.com/rust-lang/crates-build-env/pull/31

It got complicated fixing the paths to the local installation of rust, so I just entered the docker instance with:

```
docker run -it --entrypoint bash build-env:latest
```

And installed what I needed inside the docker image and ran the build there.

**Comment by jyn514** [comment]
This is strange ... I requeued the build and it had the proper dependencies this time, but it failed at the very last step:

```
Feb 06 20:49:46 docsrs cratesfyi[21399]: 2020/02/06 20:49:46 [DEBUG] cratesfyi::docbuilder::rustwide_builder: adding sources into database
Feb 06 20:49:47 docsrs cratesfyi[21399]: 2020/02/06 20:49:47 [DEBUG] cratesfyi::docbuilder::rustwide_builder: adding documentation for the default target to the database
Feb 06 20:49:47 docsrs cratesfyi[21399]: 2020/02/06 20:49:47 [INFO] cratesfyi::docbuilder::rustwide_builder: /home/cratesfyi/workspace/builds/sequoia-openpgp-0.13.0/target/ /tmp/docsrs-docs.1LMlLW5UkSLi
Feb 06 20:49:47 docsrs cratesfyi[21399]: 2020/02/06 20:49:47 [ERROR] cratesfyi::docbuilder::queue: Failed to build package sequoia-openpgp-0.13.0 from queue: No such file or directory (os error 2)
```

Could you have a broken symbolic link or something similar in your sources?

**Comment by jyn514** [comment]
Sorry, this was our own bug (https://github.com/rust-lang/docs.rs/commit/f29b56239479e07aec2c4b89917f6e9dd5a86e69). `nettle-dev` is rebuilding now.

**Comment by jyn514** [comment]
Rebuilt: https://docs.rs/sequoia-openpgp/0.13.0/sequoia_openpgp/

**Comment by alexanderkjall** [comment]
Thanks :)
