### ISSUE TITLE
Feature request: list crate features at the top of package index.html

### ISSUE THREAD

**Issue by kespindler** [rust-lang/docs.rs#590]
When learning Rust, it's surprising to not find a namespace available within a package. Having crate features available at the top of the docs.rs package would be a great indication that some namespaces are gated behind features.

**Comment by jyn514** [comment]
I think listing all the features of the crate is useful and in scope (maybe under the `crate` tab). However, we can't put it on the page for every module since those pages are generated by rustdoc.

**Comment by jyn514** [comment]
Or in other words: just finding which features are available is simple, we just parse `Cargo.toml`; finding what changes when a given feature is enabled/disabled requires expanding macros and parsing the code and also lies on a weird boundary between cargo and rustdoc.

**Comment by jyn514** [comment]
There's an extension that adds this already and I like their approach - they put an extra `Features` drop-down in the header at the top.

https://rust-search-extension.now.sh/feature-flags.png

**Comment by jyn514** [comment]
Relevant code:
- [header template](https://github.com/rust-lang/docs.rs/blob/master/templates/navigation_rustdoc.hbs#L103)
- [adding releases to the database](https://github.com/rust-lang/docs.rs/blob/master/src/db/add_package.rs#L28)
- [`Cargo.toml` parsing](https://github.com/rust-lang/docs.rs/blob/master/src/utils/cargo_metadata.rs#L26) - note that this is `CargoMetadata`, not `Metadata`. `Metadata` is only used for controlling the build parameters.

**Comment by Nemo157** [comment]
One change I would suggest for the example drop-down would be to highlight the `default` feature, maybe by moving it to the top and adding a little whitespace/horizontal rule between it and the rest.

**Comment by jyn514** [comment]
This was added in https://github.com/rust-lang/docs.rs/pull/1144.
