### ISSUE TITLE
docs.rs failed to build deno-0.32.0

### ISSUE THREAD

**Issue by MikePryadko** [rust-lang/docs.rs#591]
From https://docs.rs/crate/deno/0.32.0 I see `docs.rs failed to build deno-0.32.0`, going to log I see `[INFO] [stderr] error: linking with `cc` failed: exit code: 1` and after alot of lines `/opt/rustwide/cargo-home/registry/src/github.com-1ecc6299db9ec823/rusty_v8-0.2.1/src/{some_file_and_line_number}: undefined reference to {some_symbol_name}`

**Comment by jyn514** [comment]
I'm not sure I understand what went wrong... I see that it's trying to link to v8, do you know if it needs the runtime libraries installed? How would we fix this?

**Comment by MikePryadko** [comment]
> How would we fix this?
Sorry, I'm not Rust-programmer -- I just walked by and noticed this

**Comment by jyn514** [comment]
Upstream bug is https://github.com/denoland/deno/issues/3875. Looks like they have different builds steps on docs.rs because of the blocked network access?

**Comment by jyn514** [comment]
I'm going to close this as "not actionable"; building large projects like this needs both a fundamental redesign of how builds work (e.g. multiple hosts) and the funding to do hour-long builds.

**Comment by jyn514** [comment]
Oh and also the upstream issue was closed; so more reason not to keep this open.
