### ISSUE TITLE
Include methods in search results

### ISSUE THREAD

**Issue by Kinrany** [rust-lang/docs.rs#601]
I wanted to find the description of the `StreamExt::flatten` method from the [`futures`] crate.

Querying "flatten", [the results] were not very helpful. Fortunately there's the `Flatten` struct that references the method in its description.

The method is present in the "In Return Types" tab (and tabs are a bit unintuitive), so it seems showing the method is already possible. But the method shows up in those results only because it returns `Flatten`.

[`futures`]: https://docs.rs/futures/0.3.4/futures/index.html
[the results]: https://docs.rs/futures/0.3.4/futures/index.html?search=flatten

**Comment by Kinrany** [comment]
Oh, the method is there, it's the fourth result. I guess I can't read, sorry.

...consider this a request to move exact matches to the top of the list?

**Comment by jyn514** [comment]
This is a feature request for rustdoc, not docs.rs. Can you open an issue in https://github.com/rust-lang/rust instead?

Also, I would count `Flatten` as an exact match ... Maybe what you want is a way to show methods before structs or vice versa?

**Comment by GuillaumeGomez** [comment]
You can do so by filterin the items: `fn:your-method`

**Comment by Kinrany** [comment]
> This is a feature request for rustdoc, not docs.rs. Can you open an issue in rust-lang/rust instead?

Sure, done! https://github.com/rust-lang/rust/issues/69025

**Comment by Kinrany** [comment]
> Also, I would count Flatten as an exact match ... Maybe what you want is a way to show methods before structs or vice versa?

Not sure, but I don't think so. Intuitively it's simpler and makes more sense to look for symbols that have exactly the same name, including casing. It takes zero additional effort to type the name with the correct casing.

> You can do so by filtering the items: fn:your-method

That's useful, thanks!
