### ISSUE TITLE
unable to build nginx crate docs

### ISSUE THREAD

**Issue by yaa110** [rust-lang/docs.rs#602]
**Crate name:** [nginx](https://crates.io/crates/nginx)
**Build failure link:** https://docs.rs/crate/nginx/0.6.2/builds

**Additional details:**
I locally tested it using [this guide](https://blog.rust-lang.org/2019/09/18/upcoming-docsrs-changes.html), and it is successfully built:

```
[HOST] docker pull rustops/crates-build-env
[HOST] docker run --rm --memory 3221225472 -it rustops/crates-build-env bash
```

```
# curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
# rustup toolchain install nightly
# rustup default nightly
# git clone https://github.com/arvancloud/nginx-rs
# cd nginx-rs
# cargo fetch
# time cargo doc --no-deps
   Compiling memchr v2.3.0
   Compiling libc v0.2.66
   Compiling glob v0.3.0
   Compiling version_check v0.1.5
   Compiling cc v1.0.50
   Compiling proc-macro2 v1.0.8
   Compiling bitflags v1.2.1
   Compiling log v0.4.8
   Compiling lazy_static v1.4.0
   Compiling regex-syntax v0.6.14
   Compiling unicode-xid v0.2.0
   Compiling cfg-if v0.1.10
   Compiling quick-error v1.2.3
   Compiling unicode-width v0.1.7
   Compiling termcolor v1.1.0
   Compiling vec_map v0.8.1
   Compiling bindgen v0.53.1
   Compiling strsim v0.8.0
   Compiling ansi_term v0.11.0
   Compiling rustc-hash v1.1.0
   Compiling lazycell v1.2.1
   Compiling shlex v0.1.1
   Compiling peeking_take_while v0.1.2
   Compiling thread_local v1.0.1
   Compiling humantime v1.3.0
   Compiling textwrap v0.11.0
   Compiling nom v4.2.3
   Compiling clang-sys v0.28.1
   Compiling aho-corasick v0.7.8
   Compiling quote v1.0.2
   Compiling libloading v0.5.2
   Compiling atty v0.2.14
   Compiling which v3.1.0
   Compiling clap v2.33.0
   Compiling cexpr v0.3.6
   Compiling regex v1.3.4
   Compiling env_logger v0.7.1
   Compiling nginx v0.6.2 (/nginx-rs)
 Documenting nginx v0.6.2 (/nginx-rs)
Finished dev [unoptimized + debuginfo] target(s) in 52.93s

real	0m52.943s
user	1m20.640s
sys	0m5.748s
```

```
# cargo --version
cargo 1.42.0-nightly (9d32b7b01 2020-01-26)
```

```
# rustc --version
rustc 1.43.0-nightly (58b834344 2020-02-05)
```

```
# rustup --version
rustup 1.21.1 (7832b2ebe 2019-12-20)
```

**Comment by jyn514** [comment]
Unfortunately the build log doesn't have enough information for me to help. Do you know why this could have failed? If not, could you change your build.rs to show more information on failure?

**Comment by yaa110** [comment]
in `Makefile` of the crate which is run in `build.rs`, target [prepare-nginx](https://github.com/arvancloud/nginx-rs/blob/master/Makefile#L11) is failed which tries to download NGINX from nginx.org.

**Comment by jyn514** [comment]
Network access is blocked when building crates. I believe nginx is installed in the build environment, could you use the system version instead?

**Comment by jyn514** [comment]
Hmm, maybe [it's not installed](https://github.com/rust-lang/crates-build-env/blob/master/packages.txt) ... Could you try again with the guide locally and see if it works? If not, you could [make a PR to crates-build-env](https://github.com/rust-lang/docs.rs/wiki/Making-changes-to-the-build-environment).

**Comment by yaa110** [comment]
The crate needs the source code of nginx

**Comment by jyn514** [comment]
Ok, as a workaround you could include `nginx` as a submodule in your git repository.

**Comment by elBoberido** [comment]
I've the same problem with the iceoryx-sys crate. Would it be possible to specify additional repositories as dependencies for docs.rs?
Maybe something like this
```toml
[package.metadata.docs.rs]
external-git-dep = "https://github.com/foo/bar.git"
external-git-dep-clone-path = "OUT_DIR"
```
After cloning the repo of the crate, the dependency could also be cloned to the desired path.

This would be a great help for sys crates.

**Comment by elBoberido** [comment]
Oh, instead of a git repo, downloading a release artifact would also be fine, e.g. from `https://github.com/foo/bar/archive/refs/tags/v2.0.2.tar.gz`
