### ISSUE TITLE
The source view is not available when crate failed to build.

### ISSUE THREAD

**Issue by pftbest** [rust-lang/docs.rs#607]
It should be possible to view the source code of a crate even if it failed to compile for some reason. I think some time ago this was working correctly, but I'm not sure.

It seems docs.rs is the only website on the internet which allows you to read the source code of a crate, because github link is often missing and even if it's not it contains a different source code than an actual crate version. It is very unfortunate that you are not able to see the source just because it failed to compile on docs.rs platform.

Example links:
https://docs.rs/crate/libui-sys/0.1.9/source/
https://docs.rs/crate/stm32ral/0.3.1/source/

**Comment by jyn514** [comment]
I think this should be as simple as moving this block outside of the `if res.result.successful` block: https://github.com/rust-lang/docs.rs/blob/master/src/docbuilder/rustwide_builder.rs#L313

**Comment by jyn514** [comment]
Testing instructions: Once you've gotten set up (either with [docker-compose](https://github.com/rust-lang/docs.rs#development) or [natively](https://github.com/rust-lang/docs.rs/wiki/Developing-without-docker-compose)), run a build for a crate that you know will fail to build. You can choose any crate off of https://docs.rs/releases/recent-failures. 

```
# for docker-compose
docker-compose run web build crate <name> <version>
# running locally
cargo run build crate <name> <version>
```

You can then go to http://localhost:3000, click on the crate name, and click 'Source' in the top-left. It should show a list of all the files in the crate, including a `Cargo.toml`.

I expect this to also add sources for binaries when fixed, if you could test that as well that would be great, for example with `bat 0.13.0`.

**Comment by pftbest** [comment]
The same problem with binary crates. They all lost the source code too. Examples: cargo-bloat, ripgrep.

**Comment by pftbest** [comment]
Now even [log](https://docs.rs/crate/log/0.4.8/source/) crate lost its source code. It seems like soon there will be no source left on docs.rs :(

**Comment by jyn514** [comment]
That seems like a different bug, log 0.4.8 built successfully.

**Comment by jyn514** [comment]
This would be fixed by https://github.com/rust-lang/docs.rs/issues/826.

**Comment by jyn514** [comment]
> Now even [log](https://docs.rs/crate/log/0.4.8/source/) crate lost its source code. It seems like soon there will be no source left on docs.rs :(

This was fixed by https://github.com/rust-lang/docs.rs/pull/830.

**Comment by pftbest** [comment]
Thank you!
