### ISSUE TITLE
Add button to copy dependency text

### ISSUE THREAD

**Issue by twitu** [rust-lang/docs.rs#609]
It's a tiny enhancement feature. A small button on the side of a particular crate version that copies the text required for the `cargo.toml` file.

1. It will make it super easy to copy and paste dependencies.
2. It might reduce the chance of a one of memory slip error.

I have added an image of where the copy to clipboard button might be placed.
![rust_docs](https://user-images.githubusercontent.com/23196890/74553375-3eb86680-4f7d-11ea-8273-af793f67a103.png)

**Comment by jyn514** [comment]
Steps to add this:
1. In [`templates/navigation.hbs`](https://github.com/rust-lang/docs.rs/blob/master/templates/navigation.hbs#L37), add an id to the h1 tag
2. Next to the h1, add a [clipboard icon](https://fontawesome.com/v4.7.0/icon/clipboard) using font-awesome
3. Create a new file (index.js ?) in the templates/ folder that adds an event listener, something like https://www.w3schools.com/howto/howto_js_copy_clipboard.asp

**Comment by reese** [comment]
Hi folks, would love to take this ticket on! It looks pretty straightforward and seems like a nice usability feature.

**Comment by jyn514** [comment]
@reese thanks so much! Feel free to reach out here or [on Discord](https://discord.gg/f7mTXPW) with questions :)
