### ISSUE TITLE
github (repository) links are hard to find

### ISSUE THREAD

**Issue by seeekr** [rust-lang/docs.rs#61]
It would be really useful if there was a link to the (github) repository from a crate's page on docs.rs! Maybe they are there somewhere, but I can't find them.
Those would improve usability quite a bit and stump me as a user a lot less in my flow, if I didn't have to leave the docs.rs page in order to check out a crate's GH page!
(It's very nice though for some use cases I imagine that there is a "source" tab already integrated in docs.rs! Keep up the good work!)

**Comment by onur** [comment]
There is a GitHub link in crate pages. [`regex`](https://docs.rs/crate/regex) crate for example:

![githublink](https://cloud.githubusercontent.com/assets/345828/19005152/a79c6f08-8761-11e6-906d-ceeb98e2ae4a.png)

You are not the only one missing this link. I don't know how can I make it more clear.

**Comment by seeekr** [comment]
OK, a couple bits of feedback about that:

1) The visual you're using is not really a common one, so for most users they won't recognize that as a GH page link even if they see that thing in front of their eyes. The idea is nice to give an overview of important GH stats, but that will not help spot the link very well.

2) The visual is only visible on the "crate" tab. The default tab is "documentation", and users really shouldn't have to navigate to the "crate" tab in order to be able to go to the crate's (GH) repository.

So basically I'd suggest putting an additional link in a well-known, common, most recognizable format on either the docs tab or on all tabs. I just did a quick look at how people are linking their GH repos, and the most common is of course the "fork me on GH" banner in the top right. That might be somewhat intrusive but would the user serve better than a hidden link. Alternatively lots of sites use (or used to use?) the GH star button thingy to link to their GH repo, which is less intrusive and could also be placed right next to the crate name at the top of the docs.rs page.

HTH!

**Comment by Kixiron** [comment]
Closing as the links do exist

**Comment by jyn514** [comment]
Reopening as it looks like this is more about the design of the links then whether they exist or not.

**Comment by LucianoBestia** [comment]
It is indeed hard to find. I didn't find it. This is the reason I came here searching for a solution. 
Now I know, but it is absolutely not intuitive.
First find the "menu bar" that is hardly visible. It looks like "disabled items".

<img src="https://user-images.githubusercontent.com/31509965/83673270-3a2fc080-a5f5-11ea-8091-9f0593f65677.png" width="500">

Then open the name+version of the crate. Then find links.
<img src="https://user-images.githubusercontent.com/31509965/83673765-63e8e780-a5f5-11ea-8928-4d7cf43573c2.png" width="500">

It would be much easier to have something familiar like crates.io:
<img src="https://user-images.githubusercontent.com/31509965/83675005-f6898680-a5f5-11ea-9cbd-43cb4a440c71.png" width="500">

<img src="https://user-images.githubusercontent.com/31509965/83675544-d5756580-a5f6-11ea-9a2f-a721f7d79bb8.png" width="500">

Thank you for docs.rs, it is fantastic to have documentation all in one place. Great !

**Comment by jyn514** [comment]
@LucianoBestia my concern for your suggestion is that it takes up more of the top-level real estate in the header bar. The more links we put there, the harder it is to find any individual link. Notice how your mockup has 6 links, compared to the 3 in crates.io and 4 on docs.rs currently.

**Comment by Nemo157** [comment]
One thing that could help with that is inserting spacers for grouping. There is a _lot_ of available whitespace on a desktop view there.

**Comment by jyn514** [comment]
> The visual you're using is not really a common one, so for most users they won't recognize that as a GH page link even if they see that thing in front of their eyes. The idea is nice to give an overview of important GH stats, but that will not help spot the link very well.

This was fixed in https://github.com/rust-lang/docs.rs/pull/1242.

**Comment by bestia-dev** [comment]
You can Close this issue. 
Now the Links for the Repository are very intuitive:
![image](https://user-images.githubusercontent.com/31509965/174282047-7688f460-72b2-492f-9832-af51d6e81d9c.png)

Thanks.
