### ISSUE TITLE
Sandbox limits increase request for stm32ral

### ISSUE THREAD

**Issue by adamgreig** [rust-lang/docs.rs#616]
**Crate name:** stm32ral
**Build failure link:** https://docs.rs/crate/stm32ral/0.4.1/builds

**Requested RAM limit:** 6GB
**Requested timeout:** 15min is OK

**Why your crate needs the resource increases:**

Related to #608, stm32ral is an alternative register access crate for all STM32 microcontrollers in one package. As with those crates, it documents thousands of hardware registers and so is quite resource-intensive to build. I measured the doc build for the latest version as taking 1m39s and 5432MB RAM, so a 6GB RAM limit should work OK. 8GB might be more conservative if the crate continues to grow.

On balance the #608 crates are more important as they are much more widely used, but if it would be possible to get the RAM limit increased for stm32ral too, I'd really appreciate it.

Thanks!

**Comment by adamgreig** [comment]
Any chance of getting this limit raised alongside #608 now that #632 is in?

Thanks!

**Comment by jyn514** [comment]
Just updated the memory limit for stm32ral to 8 GB. Could you also set `targets = []` for this crate to avoid unnecessary load on the server? Thanks again for your patience.

**Comment by adamgreig** [comment]
Great, thank you! I have done so in https://github.com/adamgreig/stm32ral/commit/cd0bfa3386282d6699025daf2a746eba6a8c94ab so will be in the next release.
