### ISSUE TITLE
Reflect GitHub Username Changes

### ISSUE THREAD

**Issue by AldaronLau** [rust-lang/docs.rs#617]
In the owners section on [the `cala` crate page](https://docs.rs/crate/cala/0.7.0), one of the crates I have, it shows all of my previous GitHub usernames that I've had as separate owners, and not the current one.  Likely because I haven't published a new version of `cala` with my current username yet, but it seems silly to keep around the old usernames (especially if other people take my old usernames).  Ideally, the username in the owners section would update (like it did [on crates.io](https://crates.io/crates/cala)).

**Comment by jyn514** [comment]
@LordAldaron how would we tell if a username had changed?

**Comment by LordAldaron** [comment]
@jyn514 docs.rs should be able to do it the same way that crates.io can.  It might be a matter of just pulling the data from crates.io when the docs get updated, or copying the code that does it from crates.io.  There might be some query that can be made to crates.io to get the owners of a crate (probably already used in the code).  So, it might just be a matter of clearing the owner data before re-adding the owners list from crates.io on docs updates.

**Comment by jyn514** [comment]
Fixed by #917. I updated `cala` manually to have the new username changes. Future publishes should have the owner updated automatically.
