### ISSUE TITLE
Crates that are fetched but not added to the index because of a crash will be lost

### ISSUE THREAD

**Issue by jyn514** [rust-lang/docs.rs#628]
Secondary problem: apparently crates that are fetched but not added to the index will be lost and not build. Relevant code: https://github.com/rust-lang/docs.rs/blob/master/src/docbuilder/queue.rs#L13

_Originally posted by @jyn514 in https://github.com/rust-lang/docs.rs/issues/626#issuecomment-591989434_

`crates-index-diff` just released a change in 5.1.0 that will let us peek without consuming the changes :tada: :tada: . This will give us much better durability in the event of a crash, I just need to implement using the new API.

**Comment by jyn514** [comment]
Mentoring instructions:

- In [`get_new_crates()`](https://github.com/rust-lang/docs.rs/blob/master/src/docbuilder/queue.rs#L16), change the line from using `fetch_changes()` to using [`peek_changes()`](https://docs.rs/crates-index-diff/5.1.0/crates_index_diff/struct.Index.html#method.peek_changes).
- After adding all new crates to the queue, call `index.last_seen_reference().set_target(changes)`, as per [the instructions in the changelog](https://github.com/Byron/crates-index-diff-rs/blob/99c33e6936dadd7b3ab0af6709791a8cbdda2071/changelog.md#L3). See also [`git2::Reference`](https://docs.rs/git2/0.11.0/git2/struct.Reference.html).
- Optionally, change [`add_crate_to_queue`](https://github.com/rust-lang/docs.rs/blob/master/src/utils/queue.rs#L6) to add multiple crates at once, so the operation will be atomic and we won't add crates that we've already built if we crash halfway through adding crates.

**Comment by harrisonbrock** [comment]
If this is still open, I would like to work on it.

**Comment by jyn514** [comment]
@harrisonbrock go for it! If you have questions, feel free to reach out here or [on Discord](https://discord.gg/f7mTXPW) :)

**Comment by jyn514** [comment]
There was a new API added recently that will make this a little easier: https://docs.rs/crates-index-diff/6.2.0/crates_index_diff/struct.Index.html#method.set_last_seen_reference

Also note that we currently use crates-index-diff 4.0, so it will need to be upgraded to at least 5 (preferably 6) to use this new API.

**Comment by harrisonbrock** [comment]
Thanks. I have been a little sick and have not had a chance to start yet.

**Comment by jyn514** [comment]
Get well soon!

**Comment by Byron** [comment]
I hope you are doing better, @harrisonbrock!
In case you need additional support related to how to use crates-index-diff, I am happy to help (_I have authored `crates-index-diff`_).

**Comment by jyn514** [comment]
https://github.com/rust-lang/docs.rs/pull/746 only logged the failure, it will still not be added to the index.

**Comment by jyn514** [comment]
Ok, this is a slightly different issue than originally - we _record_ the failure internally, it won't be lost, we just don't display it anywhere but in the logs. So it seems from the outside as if the build was never there, but we can still rerun it with `UPDATE queue SET attempts = 0;`

**Comment by jyn514** [comment]
Closing in favor of https://github.com/rust-lang/docs.rs/issues/903, the original bug this was for has been fixed.
