### ISSUE TITLE
libzetta needs libzfs_core to build

### ISSUE THREAD

**Issue by andoriyu** [rust-lang/docs.rs#630]
**Crate name:** libzetta
**Build failure link:** https://docs.rs/crate/libzetta/0.2.0/builds/226022

**Additional details:** I'm confused why is it building docs for all the dependencies even with `--no-deps` specified. I don't want this native dependency to be added to the builder because it's _heavy_.

**Comment by jyn514** [comment]
@andoriyu rustdoc needs the dependency because it generates hyperlinks based on the type signature of a function. If the dependencies aren't built, it can't do type checking and so can't generate the hyperlinks.

@GuillaumeGomez might know more about why the dependencies are necessary.

**Comment by andoriyu** [comment]
@jyn514 I see that makes sense. Reason I opened it as a bug is because libzfs_core is PITA to build and install. Plus it pretty big. 

So the only way to fix is to add `libzfs_core`?

**Comment by jyn514** [comment]
Yes, unfortunately. How big is big? We have sandbox limits (https://docs.rs/about) that we can raise if necessary, and also we block network access.

**Comment by andoriyu** [comment]
@jyn514 on public pool in azure pipelines it takes ~5 minutes to install from packages, but it pulls in entire ZOL stack https://dev.azure.com/andoriyu/libpandemonium/_build/results?buildId=308&view=logs&j=fbfd68f3-c45d-5150-490a-ea46a8fff233&t=4d880c2f-7af5-59d0-cc8c-6b0059fc3b5e

I guess since builder is ubuntu based it can install the same packages.

**Comment by jyn514** [comment]
Oh that's not bad at all. We preinstall all packages so this would only count the time to build the bindings, not the time to run `apt`.

**Comment by andoriyu** [comment]
@jyn514 I didn't realize that docs builder is very similar to what i use for CI, so I thought it might be PITA to add. If it's ubuntu than it's easy.

**Comment by jyn514** [comment]
Great! If you're interested in adding it yourself, there are instructions at https://forge.rust-lang.org/docs-rs/add-dependencies.html. Otherwise I might get around to it this weekend.

Once it's been added to crates-build-env I can schedule a rebuild so you don't have to publish a new point release.

**Comment by andoriyu** [comment]
> Great! If you're interested in adding it yourself, there are instructions at https://forge.rust-lang.org/docs-rs/add-dependencies.html. Otherwise I might get around to it this weekend.
> 
> Once it's been added to crates-build-env I can schedule a rebuild so you don't have to publish a new point release.

Any update on this? I don't any macOS or Linux installed anywhere to test it myself.

**Comment by jyn514** [comment]
You don't need Mac or Linux to test it, just docker-compose.

**Comment by andoriyu** [comment]
> You don't need Mac or Linux to test it, just docker-compose.

Well, I do need docker though. Anyone, I setup the VM with docker.
Documentation says how to add packages from official repos, but in my case it's from 3rd party PPA.

I tried at least building the docs dirty way. I built the image, but building actual docs isn't working for me:
```

docker-compose run -e DOCS_RS_LOCAL_IMAGE=build-env \
                     -v /opt/libzetta-rs:/opt/rustwide/workdir \
    web build crate --local /opt/rustwide/workdir

Starting docsrs_db_1 ... done
Starting docsrs_s3_1 ... done

export CRATESFYI_PREFIX=/opt/docsrs/prefix
export DOCS_RS_DOCKER=true
export RUST_LOG=cratesfyi,rustwide=info
export PATH="$PATH:/build/target/release"

# Try migrating the database multiple times if it fails
# This avoids the docker container crashing the first time it's started with
# docker-compose, as PostgreSQL needs some time to initialize.
set +e
failed=0
while true; do
    if ! cratesfyi database migrate; then
        ((failed=failed + 1))
        if [ "${failed}" -eq 5 ]; then
            exit 1
        fi
        echo "failed to migrate the database"
        echo "waiting 1 second..."
        sleep 1
    else
        break
    fi
done
set -e

cratesfyi database update-search-index
cratesfyi database update-release-activity

if ! [ -d "${CRATESFYI_PREFIX}/crates.io-index/.git" ]; then
    git clone https://github.com/rust-lang/crates.io-index "${CRATESFYI_PREFIX}/crates.io-index"
    # Prevent new crates built before the container creation to be built
    git --git-dir="$CRATESFYI_PREFIX/crates.io-index/.git" branch crates-index-diff_last-seen
fi

cratesfyi build update-toolchain --only-first-time
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', src/bin/cratesfyi.rs:205:31
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

send help

**Comment by jyn514** [comment]
What are the permissions on `/opt/libzetta-rs` directory on the host? If you can run with RUST_BACKTRACE=1 on the host that would also be helpful.

In the meantime I'll see if I can make that PR to crates-build-env for you.

**Comment by jyn514** [comment]
I haven't been able to build this, even installing every package you install on CI. I have the following added:
- zfs-dkms zfsutils-linux libnvpair1linux
- libblkid-dev libattr1-dev libcurl4-openssl-dev libelf-dev libdw-dev cmake gcc binutils-dev libiberty-dev zlib1g-dev libssl-dev
- libzfslinux-dev

but the builder is still telling me libzfs_core not found (I'm building zfs-core-sys 0.1.0 because it doesn't take as long):
```
2020/03/24 06:55:00 [INFO] rustwide::cmd: [stderr] thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Failure { command: "\"pkg-config\" \"--libs\" \"--cflags\" \"libzfs_core\"", output: Output { status: ExitStatus(ExitStatus(256)), stdout: "", stderr: "Package libzfs_core was not found in the pkg-config search path.\nPerhaps you should add the directory containing `libzfs_core.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'libzfs_core\' found\n" } }', build.rs:8:9
```

**Comment by jyn514** [comment]
Oh whoops, our docs on forge are out of date, that should say `DOCS_RS_LOCAL_DOCKER_IMAGE`. I'll update it in a second.
