### ISSUE TITLE
docs.rs should ignore .cargo/config

### ISSUE THREAD

**Issue by jyn514** [rust-lang/docs.rs#650]
Fixing this should be basically the same steps as https://github.com/rust-lang/docs.rs/issues/555#issuecomment-571950211, rustwide should remove `.cargo/config` before starting the build.

_Originally posted by @jyn514 in https://github.com/rust-lang/docs.rs/issues/647#issuecomment-602042380_

**Comment by Freax13** [comment]
i'll try working on it

**Comment by jyn514** [comment]
This won't be fixed until we bump the version of rustwide.

**Comment by phil-opp** [comment]
I'm maintaining a crate whose docs.rs builds fail because of this issue. Do you plan to bump `rustwide` soon or should I try work around it?

**Comment by Nemo157** [comment]
#758 will have a `rustwide` bump once the async changes are released, though that may take some time, so a small PR bumping to 0.7.0 to get this fix out seems useful.

**Comment by jyn514** [comment]
I'll make a PR updating it.

**Comment by phil-opp** [comment]
Thanks a lot!

**Comment by phil-opp** [comment]
That was quick, thank you! Is there a way to rerun a failed docs.rs build or do I need to push a new version?

**Comment by jyn514** [comment]
I can rerun the build for you. What crate and version?

**Comment by jyn514** [comment]
I guessed that it was `bootloader 0.9.3`, it just rebuilt successfully :) https://docs.rs/crate/bootloader/0.9.3

**Comment by phil-opp** [comment]
Yes, it was. Thank you so much!
