### ISSUE TITLE
Use --cap-lints warnings to prevent unnecessary failures

### ISSUE THREAD

**Issue by jyn514** [rust-lang/docs.rs#651]
Some crates like to put `deny (warnings)` in their crate root. This is fine for developing locally, but can cause docs.rs builds to fail since new lints may have been added in nightly. docs.rs can avoid these unnecessary build failures by passing `--cap-lints warn` to rustdoc.

Example failure: https://docs.rs/crate/ring/0.16.11/builds/218514

See also: https://doc.rust-lang.org/rustc/lints/levels.html

I think the best way to do this would be to add --cap-lints to `RUSTDOCFLAGS` in [`execute_build`](https://github.com/rust-lang/docs.rs/blob/master/src/docbuilder/rustwide_builder.rs#L438).

**Comment by pietroalbini** [comment]
I'm not sure if this is a good idea. `--cap-lints` does indeed ignore custom `#[forbid(...)]` or `#[deny(...)]`, but it also ignores deny-by-default and forbid-by-default lints.

**Comment by jyn514** [comment]
If we're building a crate, that means it's already been published to crates.io, which means that someone ran `cargo publish` successfully. So the only lints that will be failing are lints that were introduced in a newer version of `rustdoc`. I don't think it makes sense to fail builds for lints the authors didn't know about - maybe for crater that makes sense, but not for docs.rs.

**Comment by jyn514** [comment]
Rebuilt ring: https://docs.rs/crate/ring/0.17.0-alpha.1. The non-alpha version was already working thanks to https://github.com/djc/ring/commit/27a8be5d9ef38b7c18b09a12b8a9af90d4040971.
