### ISSUE TITLE
Tracking issue: docs.rs leaks memory

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/docs.rs#656]
We started noticing that docs.rs occasionally leaks gigabytes of memory at once, causing production outages due to the excessive amount of used RAM.

![2020-03-26--16-19-04](https://user-images.githubusercontent.com/2299951/77663605-87e8d680-6f7d-11ea-94dc-6d77840f11fa.png)

At the moment we're investigating what the root cause is.

**Comment by jyn514** [comment]
Possibly fixed by #666. Since it's intermittent, we won't know for a while, though.

**Comment by jyn514** [comment]
We haven't had any spikes of this sort in a week, are you comfortable closing this?

![image](https://user-images.githubusercontent.com/23638587/78926099-8550ab80-7a6a-11ea-8a42-a79d90332866.png)

**Comment by jyn514** [comment]
Hmm, we don't have any spikes, but we're still using 2 more GB of RAM at rest than after a server restart ... maybe it's worth keeping this open.

![image](https://user-images.githubusercontent.com/23638587/78926754-a06feb00-7a6b-11ea-82dd-f16084550f73.png)

**Comment by jyn514** [comment]
Someone on hackernews suggested using processes instead of threads, which would automatically clean up resources on panics: https://news.ycombinator.com/item?id=22946237

Not sure how crucial that is at the moment, but if we start having issues again it's certainly something to consider.

**Comment by Mark-Simulacrum** [comment]
That's true, but I think the main concern in my mind right now is the high baseline memory usage. I wouldn't expect a docs.rs idling (i.e. not serving requests) to need, well, really any memory (a hundred megabytes seems more than enough). It would be helpful to narrow down what is using memory in the current process architecture.

**Comment by jyn514** [comment]
I'm going to close this since we haven't had trouble with leaks as such - we might be running into buffer bloat or something, but given that we're only using 3 GB out of the 15 GB available I don't think that's a big deal.
