### ISSUE TITLE
Try to percent-decode the crate name if it gives a 404

### ISSUE THREAD

**Issue by jyn514** [rust-lang/docs.rs#670]
> I use the DuckDuckGo bangs feature a lot to search for crates on docs.rs using the `!drs cratename` bang, however it doesn't seem to work with crates that have hyphens in the name like `async-std`, for example. I get redirected to `https://docs.rs/async%2Dstd` -- which upon pasting that looks like its because it percent encodes the hyphen! I wouldn't mind putting in a PR to percent decode the parameters if that's a change everyone is okay with :+1: (edit: well, assuming that's the problem haha)

This would be great to have, but it should only redirect if the current page would give a 404 to avoid making some crates unnameable.

_Originally posted by @repnop in https://github.com/rust-lang/docs.rs/issues/603#issuecomment-606913272_

**Comment by jyn514** [comment]
Hmm this looks a little trickier than I thought at first because `/:crate` and `/:crate/:version` are handled by `rustdoc_redirector_handler` but `/:crate/:version/*.html` is handled by `rustdoc_html_server_handler`, so any changes have to be made to both.

**Comment by jyn514** [comment]
See also #105, https://github.com/rust-lang/docs.rs/pull/348

**Comment by pietroalbini** [comment]
> but it should only redirect if the current page would give a 404 to avoid making some crates unnameable.

How would this make some crates unnameable? `%` is not allowed in crate names, so if we always urldecode the crate names we would only increase the amount of names we accept.

**Comment by jyn514** [comment]
Aha! Perfect, then we can always do url-decode.

Although that now makes me wonder why `iron` isn't doing that for us ...
