### ISSUE TITLE
Inconsistent source views

### ISSUE THREAD

**Issue by notriddle** [rust-lang/docs.rs#68]
Compare move.rs shown in [docs.rs source view](https://docs.rs/crate/mitochondria/1.1.1/source/src/move.rs) and [rustdoc source view](https://docs.rs/mitochondria/1.1.1/src/mitochondria/.cargo/registry/src/github.com-1ecc6299db9ec823/mitochondria-1.1.1/src/move.rs.html).
- the rustdoc search bar is only shown in the rustdoc view
- the rustdoc search bar is pushed away from a nonexistent sidebar, and there's way too much margin between it and the source listing
- line numbers are only shown in the rustdoc view
- the file tree is only shown in the docs.rs view
- the docs.rs view uses the Source tab, while the rustdoc view uses the Documentation tab
- the syntax coloring schemes differ

**Comment by onur** [comment]
Thanks for reporting. Some people suggested replacing `[src]` links in documentation to docs.rs source view. But IMO rustdoc source view is much better.

docs.rs source view is actually exist for crates that don't have any documentation. It is also useful to view Cargo.toml and see all features of a crate.

I am not sure how can we solve this issue.

**Comment by notriddle** [comment]
Add line numbers and line anchors to the docs.rs view? Those are the big missing features.

**Comment by Kixiron** [comment]
Closing in favor of #31
