### ISSUE TITLE
kas-wgpu build failure

### ISSUE THREAD

**Issue by dhardy** [rust-lang/docs.rs#695]
**Crate name:** kas-wgpu
**Build failure link:** https://docs.rs/crate/kas-wgpu/0.3.0/builds/224255

**Additional details:**
```
[INFO] [stderr] error: failed to run custom build command for `xcb v0.8.2`
```

According to [packages.txt](https://github.com/rust-lang/crates-build-env/blob/master/packages.txt), xcb libraries are already installed. All I need installed for Travis is `libxcb-shape0-dev libxcb-xfixes0-dev` which are included.

Additionally, all dependent packages of `kas-wgpu` appear to build successfully, and the crate doesn't directly link against any external libraries, so I don't understand what the issue is.

Thanks in advance for any help!

**Comment by jyn514** [comment]
The relevant error message is here: 

```
[INFO] [stderr]     with open(path, 'w') as f:
[INFO] [stderr] OSError: [Errno 30] Read-only file system: '/opt/rustwide/cargo-home/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.2/src/ffi/selinux.rs'
```

Crates are not allowed to write to the `src` directory for security reasons (so we only have to download the crate source once and can reuse that for multiple builds). As an alternative you could write files to OUT_DIR: https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-crates

**Comment by jyn514** [comment]
Oops, I misread the error, that's coming from one of your dependencies. You'll have to ask that dependency to stop writing to `src`, or they might have already fixed it in a later release.

**Comment by dhardy** [comment]
Ugh, the `clipboard` crate I'm using is really quite dated. Thanks for the help!
