### ISSUE TITLE
docs.rs failed to build hash2curve-0.0.4

### ISSUE THREAD

**Issue by mikelodder7** [rust-lang/docs.rs#702]
I have published 4 versions of my crate `hash2curve` but only the first one succeeded. The build.log says it ran out of ram or couldn't connect through the network to some external process. I'm not sure why it failed on the most recent 3 but my other crates seem to be working just fine when I publish. Not sure why this one is failing.

**Comment by jyn514** [comment]
You can see the build logs [here](https://docs.rs/crate/hash2curve/0.0.4/builds/234884) (linked to from [the crate page](https://docs.rs/crate/hash2curve/0.0.4)). The error is that `doc(cfg)` requires a feature to be enabled:

```
[INFO] [stderr]  Documenting hash2curve v0.0.4 (/opt/rustwide/workdir)
[INFO] [stderr] error[E0658]: `#[doc(cfg)]` is experimental
[INFO] [stderr]    --> src/lib.rs:290:20
[INFO] [stderr]     |
[INFO] [stderr] 290 | #[cfg_attr(docsrs, doc(cfg(feature = "bls")))]
[INFO] [stderr]     |                    ^^^^^^^^^^^^^^^^^^^^^^^^^
[INFO] [stderr]     |
[INFO] [stderr]     = note: see issue #43781 <https://github.com/rust-lang/rust/issues/43781> for more information
[INFO] [stderr]     = help: add `#![feature(doc_cfg)]` to the crate attributes to enable
```

**Comment by jyn514** [comment]
I saw that the build for 0.0.6 succeeded, so I'm assuming you figured this out. Let us know if you have more trouble!
