### ISSUE TITLE
docs.rs should clean up after itself

### ISSUE THREAD

**Issue by jyn514** [rust-lang/docs.rs#703]
After running the daemon on a server for a while, the `$CRATESFYI_PREFIX/cargo-home` directory can grow to be very large (currently ~45 GB on the docs.rs server). We should clean up build artifacts and source code after building the crate instead of leaving the files around.

**Comment by syphar** [comment]
solved in https://github.com/rust-lang/docs.rs/commit/e04509d2690fc8a093e14874a0b4b7d129d59103
