### ISSUE TITLE
docs for guppy 0.1.8 failed to build because of a borrow checker issue in proptest

### ISSUE THREAD

**Issue by sunshowers** [rust-lang/docs.rs#704]
**Crate name:** guppy 0.1.8
**Build failure link:** https://docs.rs/crate/guppy/0.1.8/builds/237873

**Additional details:**

It looks like this might be a bug in the latest nightly, since proptest builds fine with rustc stable and earlier nightlies.

**Comment by jyn514** [comment]
Unfortunately we don't have a way to chose what version docs are built with ( #506 , #228 ). I can requeue guppy manually once a fixed version of rustc comes out.

**Comment by sunshowers** [comment]
I've released a new version of guppy since so no longer need this. thanks!
