### ISSUE TITLE
Is it a good idea to distinguish associated method and instance method in docs?

### ISSUE THREAD

**Issue by denglitong** [rust-lang/docs.rs#711]
Well i wonder if it's the right place to say this, if it's not please correct me.
As the follow screenshot shows, i wonder if it's a good idea to make docs better by adding some symbol in the sidebar to distinguish the associated method vs instance mathod?
![image](https://user-images.githubusercontent.com/13757307/79067867-26529700-7cf5-11ea-8132-f196bef130e5.png)
for example we can add something like a star ahead of associated method?
\* open
metadata
\* create

**Comment by jyn514** [comment]
> Well i wonder if it's the right place to say this, if it's not please correct me.

The right place would be https://github.com/rust-lang/rust/issues. Docs.rs just builds the documentation, we don't control what it looks like for the most part.

In response to your question - distinguishing sounds useful but takes up more screen space on the overview, which there's already not very much of. So I wonder if it's worth it given you can just look at the method signature.

**Comment by denglitong** [comment]
Thanks for your response, I got it.
