### ISSUE TITLE
Separate normal and deprioritized crates in the queue size metric

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/docs.rs#718]
Now that we implemented automatic deprioritization for large projects (#714) we should extend the metrics exposed by docs.rs to our monitoring system to account for that.

I'd love for the `docsrs_queued_crates_count` metric to be split into two:

* `docsrs_queued_crates_count` with the queued crates that have a neutral or positive priority
* `docsrs_deprioritized_queued_crates_count` with the queued crates that have a negative priority

This would allow us to define alerting rules such as "alert when there are more than 50 non-prioritized crates in the queue, or more than 300 deprioritized crates".

**Comment by Kixiron** [comment]
I believe I fixed this in #774
