### ISSUE TITLE
Redirect to latest version when latest version is missing platform 404s

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/docs.rs#722]
Example page: https://docs.rs/libc/0.1.5/x86_64-pc-windows-gnu/libc/funcs/extra/winsock/index.html, clicking "latest version" will redirect to https://docs.rs/libc/0.2.69/x86_64-pc-windows-gnu/libc/?search=winsock which 404s as 0.2.69 doesn't have docs built for `x86_64-pc-windows-gnu`.

At this point I guess the choice is to redirect to default-target, or just go to the crate root page.

**Comment by jyn514** [comment]
> crate root page

You mean /crate? I'd rather not redirect there from a doc page, most people just see it as an inconvenient step in the way of the docs. Redirecting to the default target sounds fine.

**Comment by jyn514** [comment]
https://docs.rs/libc/0.1.5/x86_64-pc-windows-gnu/libc/funcs/extra/winsock/index.html now links to https://docs.rs/libc/0.2.93/libc/?search=winsock, which exists.
