### ISSUE TITLE
 Low FPS on Safari 13.1

### ISSUE THREAD

**Issue by ppamorim** [rust-lang/docs.rs#725]
I noticed a low FPS when opening the docs on Safari 13.1. This problem does not happen when the page is not focused and does not happen on Chrome. I do not use any extension.

I tested the page by compiling the source code from this repo and configuring it to create the docs for the crate postgres.

I have recorded two videos showing the problem, being the first one a screen recording (less noticiable) and the second one I recorded my screen from a iPhone. I recommend you to watch the one recorded from the iPhone since the low FPS is more visible.

The low FPS does not happen if the page is not focused, I show this in the second video. To simulate this just open the page and move to another app.

https://www.youtube.com/watch?v=zhvuoTpoz2c&feature=youtu.be
https://www.youtube.com/watch?v=Y7Sy7rsCfsM&feature=youtu.be

**Comment by jyn514** [comment]
Possibly related to #595

**Comment by Nemo157** [comment]
After some testing it seems like these safari scrolling issuers are more related to the `.focus()` calls in the javascript than the `position: fixed` css. Commenting out all focusing seems to fix the lagginess.

**Comment by jyn514** [comment]
@ppamorim we just deployed a possible fix, can you check https://docs.rs/postgres/0.17.3/postgres/ and see if the problem is still there?

**Comment by ppamorim** [comment]
@jyn514 Thank you very much! This beauty is running smooth at 144hz now!
