### ISSUE TITLE
Fails to build doc

### ISSUE THREAD

**Issue by darlaam** [rust-lang/docs.rs#727]
**Crate name:** guidon
**Build failure link:** https://docs.rs/crate/guidon/0.1.0/builds/242520

**Additional details:** works using `cargo doc` in the clone project.
Logs claims that jsonnet-sys is not a git repository ?

**Comment by jyn514** [comment]
This looks like `jsonnet-sys` is trying to write to the `src` directory, which is not allowed:
```
[INFO] [stderr] error: failed to run custom build command for `jsonnet-sys v0.6.0`
[INFO] [stderr] 
[INFO] [stderr] Caused by:
[INFO] [stderr]   process didn't exit successfully: `/opt/rustwide/target/debug/build/jsonnet-sys-9cd69f94bb60a6ac/build-script-build` (exit code: 101)
[INFO] [stderr] --- stdout
[INFO] [stderr] embedding: "jsonnet/stdlib/std.jsonnet" -> "jsonnet/core/std.jsonnet.h"
[INFO] [stderr] 
[INFO] [stderr] --- stderr
[INFO] [stderr] fatal: not a git repository (or any parent up to mount point /opt/rustwide)
[INFO] [stderr] Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
[INFO] [stderr] thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 30, kind: Other, message: "Read-only file system" }', /opt/rustwide/cargo-home/registry/src/github.com-1ecc6299db9ec823/jsonnet-sys-0.6.0/build.rs:28:25
```

Unfortunately there is not a more recent release of jsonnet-sys, so you will have to open an issue with that project. They could instead write to `$CARGO_OUT_DIR`, an environment variable set by cargo that we make sure is read/write.

**Comment by darlaam** [comment]
Ok, thanks. 
I'll see if I can get rid of this dependancy....
