### ISSUE TITLE
_/- redirection does not work for rustdoc paths

### ISSUE THREAD

**Issue by Folyd** [rust-lang/docs.rs#733]
Thanks #712 fixes the crate name unequal on -/_ bug. https://docs.rs/async_std can redirect to https://docs.rs/async-std/1.5.0/async_std/ . However, some path still get 404 `The requested resource does not exist`, for example, this URL: https://docs.rs/async_std/1.5.0/async_std/task/fn.spawn.html

[Rust Search Extension](https://github.com/huhu/rust-search-extension) shipped a new feature in recently to search the external crate's doc, this would be annoying if this bug wouldn't fix.

![rust-search-extension](https://user-images.githubusercontent.com/3369694/80305277-73069980-87ee-11ea-81f9-d03a7a2feb9d.png)

**Comment by jyn514** [comment]
This seems to me like a bug in Rust Search Extension. We intentionally did not redirect for exact paths under the rationale that if you had an exact path, you already knew the exact name of the crate. I think it would be better to fix Rust Search Extension to instead use the proper url.

**Comment by Folyd** [comment]
I don't think this is a bug of the extension. I mean https://docs.rs/async_std/1.5.0/async_std/task/fn.spawn.html should also be redirected to https://docs.rs/async-std/1.5.0/async_std/task/fn.spawn.html .

**Comment by jyn514** [comment]
I understand what you're asking, I'm saying this would be difficult on our end and I don't see the benefit since the only people using that path seem to be your search extension.

**Comment by jyn514** [comment]
I'm willing to take a PR adding this but otherwise I don't plan on working on it. The PR should

- include tests using `crate::test::wrapper`
- redirect to the normalized url only if the original file was not found

You can find the normalized url using the index in the database, see https://github.com/rust-lang/docs.rs/blob/master/src/web/mod.rs#L265 for an example.

**Comment by Folyd** [comment]
Thanks, @jyn514 . I think I can do this. 😸

**Comment by jyn514** [comment]
See also [`assume_exact`](https://github.com/rust-lang/docs.rs/blob/master/src/web/mod.rs#L208) and [`rustdoc_html_server_handler`](https://github.com/rust-lang/docs.rs/blob/master/src/web/rustdoc.rs#L211).

**Comment by Folyd** [comment]
This is fixed by #736

**Comment by jyn514** [comment]
Deployed, https://docs.rs/async_std/1.5.0/async_std/task/fn.spawn.html no longer gives a 404 :)

**Comment by Folyd** [comment]
> Deployed, https://docs.rs/async_std/1.5.0/async_std/task/fn.spawn.html no longer gives a 404 :)

Wow, I can't believe this is so efficient to ship production! 🎉🥳
