### ISSUE TITLE
mutable argument name replaced with `__arg0` in async fn doc

### ISSUE THREAD

**Issue by vlmutolo** [rust-lang/docs.rs#737]
## Summary
When generating documentation for async functions, `cargo doc` will replace mutable argument names with `__arg0`.

## How to Reproduce
```sh
cargo new --lib bar
cd bar
echo 'pub async fn foo(mut string: String) {}' > ./src/lib.rs
cargo doc
```

Then view the documentation generated for `foo`. It should look like the following.
```rust
pub async fn foo(__arg0: String)
```

## Version Info
`rustc 1.43.0 (4fb7144ed 2020-04-20)`

I'm not sure how to find the exact `cargo doc` version, but I just did `rustup update` and it updated `cargo doc` and the issue persists.

**Comment by jyn514** [comment]
This is an issue with rustdoc, not with docs.rs. Can you open it on https://github.com/rust-lang/rust/issues/ instead?

**Comment by vlmutolo** [comment]
Shoot. My bad. I’ll post it there.
