### ISSUE TITLE
Switch templating to Tera

### ISSUE THREAD

**Issue by Kixiron** [rust-lang/docs.rs#740]
The current templates have lots of redundancy, breaking things into smaller units will help with consistency across pages and maintainability

**Comment by Kixiron** [comment]
This has now changed slightly, I've been investigating the [tera](https://github.com/Keats/tera) templating engine as a suitable replacement for handlebars

**Comment by jyn514** [comment]
Motivation for `tera`, as discussed on discord:
- hot reloading so that modifying templates isn't as painful
- inheritance in templates
- more processing done in templates instead of code so we can use more `derive(Serialize)`
- better docs

**Comment by Kixiron** [comment]
All of that culminates into what at the end of the day is better, more modifiable and more maintainable code, which is a bonus on every front

**Comment by pietroalbini** [comment]
I'd also be in favor of moving to tera.

**Comment by jyn514** [comment]
Status: waiting on the bugs mentioned in https://github.com/rust-lang/docs.rs/pull/885 to be fixed. Then we can go another round at https://github.com/rust-lang/docs.rs/pull/879.

**Comment by jyn514** [comment]
Implemented in https://github.com/rust-lang/docs.rs/pull/887
