### ISSUE TITLE
Go to latest should not consider prereleases (unless there are only prereleases)

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/docs.rs#749]
Example: <https://docs.rs/nemo157/0.3.0/nemo157/> shows "Go to latest" linking to <https://docs.rs/nemo157/0.3.1-pre.1/nemo157/index.html>.

Need to also take yanked into account, I think it should go through these four subsets, showing the first that gives any result:

 * latest non-prerelease non-yanked version
 * latest prerelease non-yanked version
 * latest non-prerelease yanked version
 * latest prerelease yanked version

(Probably in <https://github.com/rust-lang/docs.rs/blob/ece1b2115957ad606e252a88acec2c0ca0e061d4/src/web/crate_details.rs#L281>, if it doesn't affect anything else).

**Comment by shorsher** [comment]
I'm assuming the only way to tell if a version is prelease is checking the version string in the Release struct?

**Comment by Nemo157** [comment]
We have `semver::Version` objects earlier, I think you could change `map_to_release` and `Release` to use this instead of a `String` and only convert to a string where needed for the db query (though I'm not sure if there'll be issues outside this file with that); then just check if `version.is_prerelease()`.

https://github.com/rust-lang/docs.rs/blob/ece1b2115957ad606e252a88acec2c0ca0e061d4/src/web/crate_details.rs#L159-L179
