### ISSUE TITLE
Advertising and tracking policy

### ISSUE THREAD

**Issue by briansmith** [rust-lang/docs.rs#75]
In the "About docs.rs" page, please:
1. Document your tracking and advertising policy on pages that are generated from crates.
2. Document how a crate author can avoid advertising and other tracking appearing on docs.rs pages generated from their content.

**Comment by jyn514** [comment]
1. Technically we have a privacy policy at https://www.rust-lang.org/policies/privacy, but it's very vague and we don't link to it from anywhere. I'll take a look at improving this and leave the issue open until that's fixed.

Unofficially though: We only have server-side logs, there's no client-side tracking at all. We track the page visited and the time to serve the page. I don't personally have access to the IPs of visitors but it's possible that the infra-team does, I've contacted them about how much information they have and how long it's stored. This is the same for pages generated by rustdoc as it is for the index and other 'core' pages.

2. I'm not sure what you mean here. We never generate advertising or client-side tracking on the HTML/JS pages, so there's no need for authors to opt-out.

Sorry for the long wait!

**Comment by jyn514** [comment]
The foundation recently added a privacy policy for all the web infra: https://foundation.rust-lang.org/policies/privacy-policy/#docs.rs. I'll leave this issue open until we link to it on every page (either in the header or by adding a footer).
