### ISSUE TITLE
Document need to add-essential-files

### ISSUE THREAD

**Issue by sunjay** [rust-lang/docs.rs#755]
If you don't run the command below, you will not be able to load CSS when running docs.rs locally. This should probably be documented in the README as it took quite a lot of time (and some help) to find.

```bash
docker-compose run web build add-essential-files
```

**Comment by jyn514** [comment]
@sunjay most of the website will be very broken unless you run at least one build first, not just the CSS. For example, many pages will return 404s even though they work fine in production. We don't document this explicitly but the example in the readme does show running a build before starting the server: https://github.com/rust-lang/docs.rs#getting-started

If you want to document this, it would be a great first PR!

**Comment by sunjay** [comment]
I ran a local build, but maybe I needed to build at least one other crate first?

**Comment by jyn514** [comment]
Hmm if you ran a build first then this is a bug, we should have run `add-essential-files` under the hood. I'll look into it.

**Comment by sunjay** [comment]
To give you some more details, I ran the following:

```bash
$ git clone https://github.com/rust-lang/docs.rs.git docs.rs
$ cd docs.rs
$ cp .env.sample .env
$ docker-compose build && docker-compose run -v "/path/to/crate":/build web build crate --local /build
$ docker-compose up
```

If running this doesn't reproduce the error for some reason, it might just be something on my machine.

**Comment by jyn514** [comment]
Unfortunately I was not able to reproduce the issue. If you figure out how to make it happen consistently, please do let me know!

**Comment by sunjay** [comment]
Thanks for looking into it!
