### ISSUE TITLE
azul-desktop failed to build

### ISSUE THREAD

**Issue by fschutt** [rust-lang/docs.rs#757]
**Crate name:** [azul-desktop](https://docs.rs/azul-desktop)
**Build failure link:** https://docs.rs/crate/azul-desktop/0.0.5/builds/250073

**Additional details:** It seems that azul-desktop expects xcb to be present (azul uses it for managing the system clipboard), but it isn't installed?

**Comment by jyn514** [comment]
The relevant error is 
```
[INFO] [stderr] OSError: [Errno 30] Read-only file system: '/opt/rustwide/cargo-home/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.2/src/ffi/selinux.rs'
```

IIRC this was fixed in xcb 0.9, you could try updating.

**Comment by jyn514** [comment]
@fschutt did you ever get this working?

**Comment by fschutt** [comment]
I haven't tried publishing azul-desktop again since I depend on the upstream master directly
