### ISSUE TITLE
Going back from source requires three clicks

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/docs.rs#764]
See https://a.pomf.cat/qyfvmb.webm

**Comment by jyn514** [comment]
I can't replicate with firefox, what browser are you using? https://a.pomf.cat/ohdprb.mkv

**Comment by mahkoh** [comment]
I'm using chromium. I believe the cause is this part of the site which changes the location object:

```js
    var doc_body = document.getElementById("rustdoc_body_wrapper");
    if(window.location.hash) {
        var notFirefox = typeof InstallTrigger === 'undefined';
        if(notFirefox) {
            var hash = window.location.hash;
            window.location.hash = "";          <-------------
            setTimeout(function () {
                window.location.hash = hash;         <-------------
                doc_body.focus();
            }, 1);
        }
    } else {
        doc_body.focus();
    }
```

According to the spec, under some arcane conditions, changing the hash causes a new history entry to be created (in the spec language: the previous entry to not be replaced): https://html.spec.whatwg.org/multipage/history.html#location-object-setter-navigate

**Comment by jyn514** [comment]
cc @GuillaumeGomez , @Nemo157 , this looks related to #750

**Comment by jyn514** [comment]
Would a possible workaround be to remove the messing around with `window.location.hash` and instead just call `doc_body.focus()` in the setTimeout?

**Comment by GuillaumeGomez** [comment]
I'm not even sure why it has been done like this in the first place...

**Comment by Nemo157** [comment]
I couldn't figure out what the `focus` calls were even meant to be doing, or how to navigate the menu with the keyboard, which is why I was very glad to find out just a css change in #750 was enough to fix the performance and I could just ignore the JS.

**Comment by GuillaumeGomez** [comment]
Then maybe let's remove this code and see if anyone complains?

**Comment by jyn514** [comment]
Relevant code:

https://github.com/rust-lang/docs.rs/blob/https://github.com/rust-lang/docs.rs/blob/master/templates/rustdoc.hbs#L19/templates/rustdoc.hbs#L19
