### ISSUE TITLE
Stale caching of crate that has apparently been deleted from crates.io

### ISSUE THREAD

**Issue by Richard-W** [rust-lang/docs.rs#765]
My crate 'advantage' has two published versions on crates.io (0.0.0 and 0.1.0). Apparently this crate name previously belonged to someone else who published a placeholder with the same name and version 0.1.1. I was not aware of this until I checked docs.rs.

### Expected behavior
* https://docs.rs/advantage leads to documentation for version 0.1.0 of my crate.
* In the owners section only my avatar is displayed.

### Actual behavior
* https://docs.rs/advantage leads to documentation for version 0.1.1 of the deleted crate.
* The previous owner's avatar is displayed in the owners section too.

### Notes
I understand that deleted crates constitute an absolute edge-case. Maybe a manual cleanup of the database is the solution here?

**Comment by Richard-W** [comment]
Apparently the previous owner published a lot of crates that have since been deleted from crates.io but are still on docs.rs. See https://docs.rs/releases/rustbae.

**Comment by pietroalbini** [comment]
Thanks for opening the issue!

I deleted all the contents of the `advantage` crate and queued a rebuild of `advantage` 0.0.0 and 0.1.0.

**Comment by pietroalbini** [comment]
The documentation is now live!

https://docs.rs/advantage/0.1.0/advantage/
