### ISSUE TITLE
ht32f1yyy RAM limit increase

### ISSUE THREAD

**Issue by hargoniX** [rust-lang/docs.rs#771]
**Crate name: ht32f1yyy**
**Build failure link: https://docs.rs/crate/ht32f1yyy/0.1.0/builds/254186**

**Requested RAM limit: Not 100% sure how much it takes...though it seems like the current limits aren't enough**

**Why your crate needs the resource increases:**
It's a PAC crate for embedded Rust, hence it consumes bigger amounts of memory during docs generation as the amount of automatically generated code is quite huge. Judging from the log line 
```
[INFO] [stderr] WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
```
I'm guessing it's an issue with the RAM limits.

**Comment by pietroalbini** [comment]
That warning is not related to your crate. The actual error is:

```
error: Package `ht32f1yyy v0.1.0 (/opt/rustwide/workdir)` does not have these features: `htf32f1655_56`
```

**Comment by Nemo157** [comment]
It appears to have a `ht32f1655_56` feature instead.

**Comment by hargoniX** [comment]
Oh you're right on both, thank's a bunch! I shall close these then.
