### ISSUE TITLE
ht32f5xxxx RAM limit increase

### ISSUE THREAD

**Issue by hargoniX** [rust-lang/docs.rs#772]
**Crate name: ht32f5xxxx**
**Build failure link: https://docs.rs/crate/ht32f5xxxx/0.1.0/builds/254183**

**Requested RAM limit: Not 100% sure how much it takes...though it seems like the current limits aren't enough**

**Why your crate needs the resource increases:**
It's a PAC crate for embedded Rust, hence it consumes bigger amounts of memory during docs generation as the amount of automatically generated code is quite huge. Judging from the log line 
```
[INFO] [stderr] WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
```
I'm guessing it's an issue with the RAM limits.

**Comment by pietroalbini** [comment]
As the other crate, the error is:

```
[INFO] [stderr] error: Package `ht32f5xxxx v0.1.0 (/opt/rustwide/workdir)` does not have these features: `þ32f52344_54`
```
