### ISSUE TITLE
No link to builds tab on crate page

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/docs.rs#777]
E.g. <https://docs.rs/crate/escargot/0.5.0> has no link to <https://docs.rs/crate/escargot/0.5.0/builds>, despite the latter having a "Builds" tab highlighted next to "Source".

**Comment by Kixiron** [comment]
I've actually discovered that there's another, more secretive tab. Squired deep in the cracks and crevices of Docs.rs, the [author tab](https://docs.rs/releases/chase-wilson) lurks. Some say it's never seen the light of day and that any mortal who gazes upon it will be driven mad by the brilliance of it

**Comment by jyn514** [comment]
Reopening since https://github.com/rust-lang/docs.rs/pull/879 was reverted.

**Comment by jyn514** [comment]
Fixed (again) in https://github.com/rust-lang/docs.rs/pull/887
