### ISSUE TITLE
Fix "I'm feeling lucky" query and add metrics

### ISSUE THREAD

**Issue by Kixiron** [rust-lang/docs.rs#789]
[This snippet](https://github.com/rust-lang/docs.rs/blob/master/src/web/releases.rs#L545-L547) states that the [query](https://github.com/rust-lang/docs.rs/blob/master/src/web/releases.rs#L534-L541) was made for a *vastly* different docs.rs, one that had `280 crates with docs`. We now have over 200k crates, so this should probably get fixed. Additionally, metrics for it would be interesting, because why not?

**Comment by jyn514** [comment]
That part of the code is only run if the query is empty, i.e. someone hit "I'm feeling lucky" without putting anything in the search box. In that case I think selecting a random crate is fine.

**Comment by Kixiron** [comment]
It's definitely far from perfect, as it can panic if the offset is off. For example, my test db only has ~50 crates right now, so since the offset is calculated with `FLOOR(RANDOM() * 280)` that always panics except when `RANDOM()` is 0

**Comment by Kixiron** [comment]
The math of my last comment may be a wee off, but point stands, it may even be possible (if horrifically improbable) that it panics in prod

**Comment by syphar** [comment]
This was fixed in #1251 and #1260, so it could be closed.
