### ISSUE TITLE
Source tab isn't shown for postgres 0.15.2

### ISSUE THREAD

**Issue by Kixiron** [rust-lang/docs.rs#800]
For [`postgres 0.15.2`](https://docs.rs/postgres/0.15.2/postgres/) the source tab is displayed, but clicking on the [link](https://docs.rs/crate/postgres/0.15.2/source/) gives a 404

**Comment by jyn514** [comment]
As a workaround you could use the rustdoc sources: https://docs.rs/postgres/0.15.2/src/postgres/lib.rs.html#1-1396

**Comment by Kixiron** [comment]
It unfortunately doesn't show the Cargo.toml (that I know of)

**Comment by Nemo157** [comment]
The source files definitely exist on S3 according to the last inventory, so somethings going wrong when attempting to load them

```
inventory/data/5b665bba-71d3-4c73-81d6-ec663ea81ec0.csv:"rust-docs-rs","sources/postgres/0.15.2/Cargo.toml","2846","c8ae098975318cbb129c3da561945e0c",""
```
