### ISSUE TITLE
docs.rs reports 404s for internal server errors

### ISSUE THREAD

**Issue by jyn514** [rust-lang/docs.rs#801]
Originally found in https://github.com/rust-lang/docs.rs/pull/784.

If we encounter an error in `impl Handler for CratesfyiHandler`, we always return the first error even if it was a 404, ignoring all future errors. This hides panics/errors and makes things very hard to debug (I have a suspicion https://github.com/rust-lang/docs.rs/issues/800 is because of an internal error being hidden by this bug).

Relevant code: https://github.com/rust-lang/docs.rs/blob/9bd032f0ef07b217450cee3fda4906086de9cc93/src/web/mod.rs#L140

**Comment by Kixiron** [comment]
Something that could help with identifying more errors would be adding `log::error!("called ctry on an Err value: {} {}:{}", file!(), line!(), column!())` to these three macros, then we'd at least have a log of invocation locations and specific errors (where applicable)
https://github.com/rust-lang/docs.rs/blob/9bd032f0ef07b217450cee3fda4906086de9cc93/src/web/mod.rs#L9-L44

**Comment by jyn514** [comment]
That helps with debugging, but still returns a 404 incorrectly.
