### ISSUE TITLE
404s from module item links when module url doesn't with a /

### ISSUE THREAD

**Issue by dnsmt** [rust-lang/docs.rs#803]
I regularly navigate back to a module page from a function description by removing the function name from the url. If I also remove the `/` the module overview page loads just fine, but the urls to its children all 404.

Example:
1. Initial url: https://docs.rs/tokio/0.2.21/tokio/time/fn.advance.html
2. Remove the `/fn.advance.html` to navigate to https://docs.rs/tokio/0.2.21/tokio/time
3. Observe that all items at the bottom of the page listed under modules, structs, and functions now 404. This does not happen on https://docs.rs/tokio/0.2.21/tokio/time/ (note the final slash).

The 404s are correct, since the url for the children lacks module name (`time`). The submodule `delay_queue` links to https://docs.rs/tokio/0.2.21/tokio/delay_queue/index.html instead of https://docs.rs/tokio/0.2.21/tokio/time/delay_queue/index.html and `tokio::delay_queue` of course does not exist.

I'd prefer to either be redirected from https://docs.rs/tokio/0.2.21/tokio/time (without slash) to https://docs.rs/tokio/0.2.21/tokio/time/ (with slash) or that the urls on https://docs.rs/tokio/0.2.21/tokio/time (without slash) are derived properly.

**Comment by Nemo157** [comment]
The redirect will much easier (and more correct) to do. Around here we just need to check if the original url ended with a `/` when trying to load the `index.html`, if it didn't and we successfully found an `index.html` then we should redirect to the current url + `/`.

https://github.com/rust-lang/docs.rs/blob/9bd032f0ef07b217450cee3fda4906086de9cc93/src/web/rustdoc.rs#L300-L305

**Comment by Kixiron** [comment]
I think this may be a related issue, but when in a source view navigating to sub-directories requires a trailing `/`, for the case of [tokio](https://docs.rs/crate/tokio/0.2.21/source/) [this](https://docs.rs/crate/tokio/0.2.21/source/src/) brings you to the `src` folder but [this](https://docs.rs/crate/tokio/0.2.21/source/src) doesn't
