### ISSUE TITLE
tensorflow 0.15.0 docs.rs failure

### ISSUE THREAD

**Issue by xd009642** [rust-lang/docs.rs#806]
https://docs.rs/crate/tensorflow/0.15.0
https://docs.rs/crate/tensorflow/0.15.0/builds

So tensorflow doesn't have a way to get the prebuilt C runtime other than downloading it (as far as I know) so it failed to build the most recent release. I was just wondering if there was a feasible way of relaxing that restriction i.e. a size limitation for downloads?

Disclaimer: I'm not a project maintainer just a user but I didn't see any issues raised

**Comment by jyn514** [comment]
If we ever implemented https://github.com/rust-lang/docs.rs/issues/315, that would work as well.

**Comment by Nemo157** [comment]
It may be useful to raise an issue for the tensorflow project to see if they can just not require the binary to build documentation. As an example the [`discord_game_sdk`](https://docs.rs/discord_game_sdk/1.0.0/discord_game_sdk/) is not allowed to distribute the binary they link against and require you to manually download it, yet they still have docs on docs.rs by [using an internal feature](https://github.com/ldesgoui/discord_game_sdk/blob/8cc079c7e98385c1e41195ca323e18da2e30e57f/discord_game_sdk/Cargo.toml#L13-L15) to skip attempting to link against the binary and just expose the bare minimum so the documentation can be generated.

**Comment by xd009642** [comment]
tensorflow is a rather large bazel build with numerous dependencies so it'll probably exceed memory and build time limits. I've raised an issue with the project page for the bindings so we'll see what they say but I think all suggestions mentioned would work.

I'll close this as there's nothing to do here, thanks for the help :smile:
