### ISSUE TITLE
Target directories are not purged after build failures

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/docs.rs#820]
While there is code to purge target directories once a build finishes, if an error happens during the build that code is never executed, leaking disk space. We should make sure the target directory is always purged, otherwise we risk running out of disk space if a lot of crates fail to build (for example during today's outage).

**Comment by jyn514** [comment]
@pietroalbini I think this would be best addressed by making [`BuildDir`](https://docs.rs/rustwide/0.8.0/rustwide/struct.BuildDirectory.html) having a `drop` impl that calls `purge()`. I can make a PR to that effect.

**Comment by pietroalbini** [comment]
That shouldn't be the default behavior, but I'd welcome a `BuildDirectory::purge_on_drop(bool)`.

**Comment by jyn514** [comment]
As an alternative to the drop impl, we decided it would be more reliable to have a shared `cleanup: AtomicBool`. When the directory is created, `cleanup` is set to true to indicate there are resources that are being used. When the build finishes, the directory will be deleted and `cleanup` will be set to `false`. Whenever the daemon starts a new build, it will check `cleanup`, and if set to true, delete all build directories.

Rustwide will need a new `.clean_build_directories()` API to go with `clean_caches()`.

**Comment by jyn514** [comment]
The advantage of this method is it works even if the thread is killed and does not run destructors.

**Comment by pietroalbini** [comment]
Hmm, wait, that's not what I was proposing during the triage meeting.

The builder thread currently starts each loop by checking if a crate is available to build, and if one is present it builds that crate. My suggestion is to add a check in every iteration of the loop that purges all the build directories and, if the disk usage is over a threshold, purges all the caches.

**Comment by jyn514** [comment]
Thanks for the correction, I keep calling it the wrong thing. What I mean is this bit of code: https://github.com/rust-lang/docs.rs/blob/master/src/utils/daemon.rs#L78

**Comment by syphar** [comment]
@Nemo157 what's your thought on this? 

Currently we are not purging all build dirs on each iteration. 

( we _are_ purging all caches on toolchain change )

**Comment by syphar** [comment]
and while normal build failures would also lead to the release target directory being purged _after_ the build, 

there are some error situations where we use `?`, where we wouldn't do this (apart from normal panics)
