### ISSUE TITLE
There are no tests for a full build

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/docs.rs#822]
We don't currently execute any kind of test to ensure a full build actually works. Such tests would've caught the root cause of today's outage.

**Comment by pietroalbini** [comment]
I'll work on implementing those tests next week.

**Comment by jyn514** [comment]
As a short-term thing, I think it would be fairly easy to add unit tests that we're using the crates.io API properly.

**Comment by jyn514** [comment]
This was fixed by https://github.com/rust-lang/docs.rs/pull/1309.
