### ISSUE TITLE
Make docs.rs documentation more visible on website

### ISSUE THREAD

**Issue by XAMPPRocky** [rust-lang/docs.rs#825]
There is documentation for docs.rs' crate metadata in the [source](https://github.com/rust-lang/docs.rs/blob/master/src/docbuilder/metadata.rs), but it isn't accessible from the website, which makes hard for users to find. It would be nice if there was a page on the website that explained what metadata you can and should set.

**Comment by XAMPPRocky** [comment]
I missed that this is available under "about docs.rs" under "Rust". Though it wasn't obvious to me that, that's where I should be looking.

**Comment by Nemo157** [comment]
I have long thought the location of "about docs.rs" was really weird and annoying to find, feel like reopening this as making it more obvious somehow? (Maybe the current about page should be split into "about" and "docs.rs documentation"?)

**Comment by XAMPPRocky** [comment]
Yeah I think it would be good to split the websites about to the top level of the nav.

**Comment by jyn514** [comment]
@Kixiron plans to work on this as part of https://github.com/rust-lang/docs.rs/issues/740.

**Comment by jyn514** [comment]
@XAMPPRocky we split this up in #924. How does it look now?

![image](https://user-images.githubusercontent.com/23638587/90300471-99694700-de68-11ea-8899-8a1a941ff95d.png)
![image](https://user-images.githubusercontent.com/23638587/90300475-9ec69180-de68-11ea-885c-27d9f757dd9f.png)

**Comment by XAMPPRocky** [comment]
It looks good to me, aside from the fact that the top bar is radically different when you're looking at a crate vs docs.rs pages. I would expect them to be consistent.

## Home
![image](https://user-images.githubusercontent.com/4464295/90315774-5f5a7c80-df1e-11ea-8b7b-97b1aa6d2406.png)

## Crate
![image](https://user-images.githubusercontent.com/4464295/90315773-579ad800-df1e-11ea-982b-811d32690f2d.png)

**Comment by jyn514** [comment]
Hmm well I agree the design is pretty inconsistent, but the information is different on those two pages. On the main page, it's information about docs.rs itself, while on /crate it's information about that specific crate. This is the same page on desktop so you can see the titles:

![image](https://user-images.githubusercontent.com/23638587/90315835-8bf5a080-deec-11ea-8459-e1bd3b98a375.png)

Maybe we should consider adding the labels on mobile too? Or adding the docs.rs header to `/crate` and rustdoc pages?

**Comment by jyn514** [comment]
@XAMPPRocky we redid this again in https://github.com/rust-lang/docs.rs/pull/1089. What do you think now?

Main page: 
![image](https://user-images.githubusercontent.com/23638587/96824670-5b0a7e00-13fd-11eb-8356-4922baa9b98b.png)
Rustdoc pages: 
![image](https://user-images.githubusercontent.com/23638587/96824695-6cec2100-13fd-11eb-9da3-925818033dda.png)
/crate pages: 
![image](https://user-images.githubusercontent.com/23638587/96824711-76758900-13fd-11eb-9495-7da2df24f407.png)

**Comment by XAMPPRocky** [comment]
@jyn514 Looks great! I found a minor bug where the gear icon doesn't work on tap on iOS, but it's nice and consistent now.

**Comment by jyn514** [comment]
Awesome! Can you open a new issue for the iOS bug?

**Comment by jyn514** [comment]
Actually - I think that might be intentional, there's no platforms to display if there's no targets. The bug is that we still display the dropdown, not that it doesn't do anything.
