### ISSUE TITLE
Show more feedback on building crates

### ISSUE THREAD

**Issue by Kixiron** [rust-lang/docs.rs#826]
Currently crates are not added into the releases database until they're fully built, but that's not needed. When adding crates to the queue, we should download the source files and add them to the database and give the release a status page that allows users to see that their crate is building and what its position in queue is. This allows us to better display build failures and to even display source files of failed builds and binaries. Crates on the `/queue` page should link to the crate's status page instead of the crates.io page

**Comment by jyn514** [comment]
Note that in particular, this means we show the sources for a crate regardless of whether the build succeeded.

**Comment by syphar** [comment]
I think this is solved with #2467 , and https://github.com/rust-lang/docs.rs/pull/2529
