### ISSUE TITLE
'rustfmt' is not installed for the toolchain

### ISSUE THREAD

**Issue by davidli2010** [rust-lang/docs.rs#836]
**Crate name:** etcd-client
**Build failure link:** https://docs.rs/crate/etcd-client/0.5.1/builds/261250

**Additional details:**  'rustfmt' is not installed for the toolchain 'nightly-2020-06-11-x86_64-unknown-linux-gnu'

**Comment by Nemo157** [comment]
See also #357

I would highly recommend not making `rustfmt` a hard-dependency of your crate, not every developer will have it installed, and especially not on CI systems. If you look at how `bindgen` handles it they just [log and output the unformatted code](https://github.com/rust-lang/rust-bindgen/blob/117e2a1d5b12f63e0ade4b4acdad52fd7a1b5f7d/src/lib.rs#L2178-L2189) if `rustfmt` is not available.

**Comment by davidli2010** [comment]
Thank you! My crate depends on `tonic`, and it enables `rustfmt` by default. I will disable it.

**Comment by Nemo157** [comment]
It might be worth opening an issue on `tonic` to have a fallback when `rustfmt` isn't available like `bindgen`, so that you get nicer generated code when possible.
