### ISSUE TITLE
Stale caching of crate that has apparently been deleted from crates.io

### ISSUE THREAD

**Issue by nhristov** [rust-lang/docs.rs#837]
My crate 'pioneer' has one published version on crates.io (0.0.1). Apparently this crate name previously belonged to someone else who published a placeholder with the same name and version 0.1.1. I was not aware of this until I checked docs.rs.

**Expected behavior**
https://docs.rs/pioneer leads to documentation for version 0.0.1 of my crate.
In the owners section only my avatar is displayed.

**Actual behavior**
https://docs.rs/pioneer leads to documentation for version 0.1.1 of the deleted crate.
The previous owner's avatar is displayed in the owners section too.

**Comment by jyn514** [comment]
See also #766.

I'm not at a computer right now but for a single crate it's an easy fix on our end.

**Comment by jyn514** [comment]
I deleted 0.1.1, so your 0.0.1 version is the only one left on docs.rs :)

Hmm, it looks like that didn't remove the other owner though. Probably a bug in `delete version`, I'll look into it.

**Comment by jyn514** [comment]
I removed the other owner.
