### ISSUE TITLE
termwiz doc build failure

### ISSUE THREAD

**Issue by wez** [rust-lang/docs.rs#842]
**Crate name:** termwiz
**Build failure link:** https://docs.rs/crate/termwiz/0.9.0/builds/251200

**Additional details:**
The build seems to get SIGKILL'd but it's not clear why.  There's not enough context in the build log to know whether this requires an increase in limits or how to quantify it.

Do you have guidelines on how to measure this?

**Comment by jyn514** [comment]
`SIGKILL` usually means you hit a memory or time limit. How long does it take to build `termwiz` locally (`cargo doc --no-deps`)? Our default limit is 15 minutes and 3 GB of RAM but we can increase that if your crate needs it.

I don't have a great way to measure memory usage, but you could use something like `ps aux | grep cargo` or `htop` to see the approximate usage.

**Comment by Kixiron** [comment]
It’s worth noting that this happened for 0.7.1, did you change anything for 0.7.2?

**Comment by wez** [comment]
Looks like the memory usage is closer to 4GB.

Also: I wonder if docs.rs can use this same trick with `/usr/bin/time -v`?

```bash
$ cargo clean
$ /usr/bin/time -v time -v cargo doc --no-deps -p termwiz
...
        Command being timed: "cargo doc --no-deps -p termwiz"
        User time (seconds): 90.74
        System time (seconds): 6.77
        Percent of CPU this job got: 456%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:21.37
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 3810736
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 0
        Minor (reclaiming a frame) page faults: 2504493
        Voluntary context switches: 4301
        Involuntary context switches: 50046
        Swaps: 0
        File system inputs: 0
        File system outputs: 705048
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
```

**Comment by jyn514** [comment]
That's a nice trick with `time -v`! That seems like a good addition to the build log.

**Comment by jyn514** [comment]
I raised the memory limit for termwiz to 5 GB and rebuilt 0.9.0.

RE using `time`: It looks like rustwide doesn't currently allow running a wrapper around cargo: https://docs.rs/rustwide/0.8.0/rustwide/struct.Build.html

cc @pietroalbini, could you make `build.toolchain` public so we can call `build.cmd("time").arg(build.toolchain.cargo())`?

**Comment by pietroalbini** [comment]
> could you make build.toolchain public so we can call build.cmd("time").arg(build.toolchain.cargo())

This wouldn't work, as `toolchain.cargo()` doesn't return a list of arguments. I'm not sure what the best solution would be though.

**Comment by jyn514** [comment]
Since termwiz has been built successfully I'm going to close this issue. I'll open a separate one about using `time`.
