### ISSUE TITLE
rusty_ffmpeg build successfully

### ISSUE THREAD

**Issue by ldm0** [rust-lang/docs.rs#851]
**Crate name:**
rusty_ffmpeg
**Build success link:**
https://docs.rs/crate/rusty_ffmpeg/0.1.1/builds/264209
**Additional details:**
Hm, creating a issue about a successful build sounds strange. But you will find it confusing.

The rusty_ffmpeg crate uses ffmpeg's build results(some header files and some package-config files) to generate bindings in the build script.  
This crate can be built successfully in a local environment with PKG_CONFIG_PATH environment variable set to path where the *.pc files is located in.  
However, it's super weird that this crate built successfully on the doc.rs where no FFmpeg is compiled and no environment variable is set. If you check the [sources](https://docs.rs/crate/rusty_ffmpeg/0.1.1/source/) you will find that no FFmpeg sources is provided.

I suspect that the docker environment contains FFmpeg? Or the docs.rs uses the bindgen result locally?(I think the second is less possible)  Or any other reason? Anyway, this really confuses me....

**Comment by Nemo157** [comment]
> I suspect that the docker environment contains FFmpeg?

Exactly, you can see [around here](https://github.com/rust-lang/crates-build-env/blob/master/packages.txt#L105) in the package list that a lot of `libav*` packages are installed.

**Comment by ldm0** [comment]
@Nemo157  Ah thanks for quick response! That makes things clear!
