### ISSUE TITLE
Switch to sqlx for compile-time checked queries

### ISSUE THREAD

**Issue by jyn514** [rust-lang/docs.rs#874]
A common source of outages is an incorrect query with no tests (https://github.com/rust-lang/docs.rs/pull/862, https://github.com/rust-lang/docs.rs/pull/829, https://github.com/rust-lang/docs.rs/pull/648, etc). While it's good to have tests for all queries, it's not always feasible (especially until #822 is fixed). [SQLx](http://docs.rs/sqlx) offers that advantage that it can check all queries at build time without having to write a test for that specific query. It is also fully async (cc @Kixiron), although that might mean we have to wait until we switch to tokio 0.2.

To avoid needless database connections, this should only connect to the database when a query is changed or added, or a schema change is made: https://github.com/launchbadge/sqlx/pull/249. During CI it should always connect to the database.

**Comment by pietroalbini** [comment]
During CI it should *not* connect to the database, or do a build with and without the database: we want to make sure the cached data is correct and a build can work without a connection.

**Comment by Nemo157** [comment]
By my understanding there will be a separate CLI utility that prepares the queries. So we can run a build job that calls `sqlx-cli prepare` or whatever the command is, then `git diff --color --exit-code` to show and fail if any file changed. Then the normal build can run without connecting to the database.

**Comment by Kixiron** [comment]
I think this’d be a great change, I’ll take a look at it once we’re async-capable

**Comment by jyn514** [comment]
I have a WIP for this in https://github.com/jyn514/docs.rs/tree/sqlx, using `block_on` since we're still stuck on iron.

**Comment by Nemo157** [comment]
(compare link: https://github.com/rust-lang/docs.rs/compare/master...jyn514:sqlx)

**Comment by jyn514** [comment]
Currently blocked on https://github.com/launchbadge/sqlx/issues/700.

**Comment by jyn514** [comment]
One footgun I found will this: If a migration fails and leaves the database in an inconsistent state, you can no longer compile the code to fix it, because `query!` gives an error. I think `sqlx prepare` should fix that though.

**Comment by Kixiron** [comment]
The sqlx cli tool can also run migrations, so that can be used to fix anything broken

**Comment by syphar** [comment]
short update here: 
in my axum-experimental branch I came onto two issues trying sqlx: 
- composite types in arrays are not supported ( I believe fixed in 0.7, but i didn't dig deeper on which exact issues / PRs fixed it). We use this for the `releases.features` field
- binding arrays to parameters in queries also raised errors, short digging didn't give me a solution, long digging needed. 

apart from that the user experience especially with the `query!` macro is really awesome. Sometimes an nullable field was returned as non-option and this needed tweaking the query to help the sqlx parser.
