### ISSUE TITLE
Crate build failure: quic-p2p

### ISSUE THREAD

**Issue by lionel1704** [rust-lang/docs.rs#875]
**Crate name:** 
quic-p2p

**Build failure link:** 
https://docs.rs/crate/quic-p2p/0.7.0/builds/265854

**Additional details:** 
The documentation build was successful. But it was not deployed correctly.

**Comment by jyn514** [comment]
This was https://github.com/rust-lang/rustwide/issues/30 (now fixed by #864). I'll queue a rebuild for your crate.

**Comment by jyn514** [comment]
Rebuilt successfuly: https://docs.rs/quic-p2p/0.7.0/quic_p2p/
