### ISSUE TITLE
API for programmatic documentation fetching

### ISSUE THREAD

**Issue by ghost** [rust-lang/docs.rs#88]

**Comment by conradev** [comment]
I would love to see this as well. If there was a way to download an archive of the raw HTML of the documentation, that would be fantastic.

My goal is to hook `docs.rs` up to [Dash](https://kapeli.com/dash)

**Comment by xusss** [comment]
@conradev How is the progress? :)

**Comment by jyn514** [comment]
Duplicate of https://github.com/rust-lang/docs.rs/issues/174
