### ISSUE TITLE
Clicking on a crate name redirect to the crate tab instead of its documentation

### ISSUE THREAD

**Issue by antoyo** [rust-lang/docs.rs#880]
Hi.
Now, when I click on a crate name in the search result, it redirects to the carte tab instead of the documentation page.
Could you please do the previous behavior, which was to go directly to the documentation page?
Or, at least, add a link to go there directly.
Thanks.

**Comment by Kixiron** [comment]
Thank you for reporting this, could you give reproduction steps with links, annotated with the actual vs. expected behavior?

**Comment by antoyo** [comment]
Reproduction steps:

1. Go on [docs.rs](https://docs.rs/).
2. [Click on a crate in recent release.](https://docs.rs/crate/nbssh/2.0.1)

Actual behavior: [The page is the crate tab.](https://docs.rs/crate/nbssh/2.0.1)

Expected behavior: [The page is the documentation.](https://docs.rs/nbssh/2.0.1/nbssh/)

**Comment by jyn514** [comment]
@Kixiron this is a regression from #849, could you make a follow-up PR fixing it?

**Comment by jyn514** [comment]
There is a similar bug for `/releases`. Working on a fix now.
