### ISSUE TITLE
Ayu theme doesn't work

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/docs.rs#889]
Go to a recently published crate like <https://docs.rs/streaming_algorithms/0.3.0/streaming_algorithms/>, and try to switch to ayu theme, the page loses all styling information because the ayu css is 404. I'm guessing we don't pull it in as part of the "per-nightly" files.

cc @Cldfire

**Comment by Nemo157** [comment]
Specifically missing from

https://github.com/rust-lang/docs.rs/blob/master/src/docbuilder/rustwide_builder.rs#L36-L52

_but_, I think adding it here might make building with older nightlies fail, if that's an issue we may need some kind of "optional files" as well?

**Comment by Cldfire** [comment]
Interesting, thanks for noticing that!

Is failing to build with older nightlies a problem? I was under the assumption that docs.rs would only upgrade nightly versions as time went on. Do builds get downgraded sometimes as well?

**Comment by pietroalbini** [comment]
> but, I think adding it here might make building with older nightlies fail, if that's an issue we may need some kind of "optional files" as well?

I don't care much about older nightlies tbh.

**Comment by jyn514** [comment]
Yes, the nightly version is sometimes locked to an older one if a release has bugs. See for example https://github.com/rust-lang/docs.rs/issues/832. It needs to be possible to build with a nightly that does not yet have the Ayu theme (at least for the next 4 months or so until it hits stable).

**Comment by jyn514** [comment]
> I don't care much about older nightlies tbh.

I guess we only need one nightly of buffer. So since there are several nightlys with Ayu now we can just require it's always there.

**Comment by Cldfire** [comment]
Ah that makes sense. So it sounds like we should wait a couple of days and then go ahead and add `ayu.css` to the list of files there.

**Comment by jyn514** [comment]
Marking as P-high since this looks really bad. Marking as E-medium because testing this requires doing a full build locally.

**Comment by jyn514** [comment]
I tried adding `ayu.css` but it didn't help. Not sure why.
