### ISSUE TITLE
Crates that are fetched but not added to the index appear to be lost

### ISSUE THREAD

**Issue by jyn514** [rust-lang/docs.rs#903]
This is a slightly different issue than #628 - we _record_ the failure internally, it won't be lost, we just don't display it anywhere but in the logs. So it seems from the outside as if the build was never there, but we can still rerun it with `UPDATE queue SET attempts = 0;`

_Originally posted by @jyn514 in https://github.com/rust-lang/docs.rs/issues/628#issuecomment-660687177_

**Comment by jyn514** [comment]
The crate I originally noticed this for was `zbus_macros 1.0.0`, which failed to fetch due to a dependency on a yanked crate.

**Comment by Nemo157** [comment]
Looks like #797

**Comment by jyn514** [comment]
Yes, this looks like the same issue. I was looking for it but couldn't find it.
