### ISSUE TITLE
self-host all static content

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/docs.rs#921]
Currently we use some libraries hosted on cdnjs (run by Cloudflare)

https://github.com/rust-lang/docs.rs/blob/664577aa55756d77124efc29e891ccbe44cf7897/templates/base.html#L12-L17

This has [caused issues at least once](https://discord.com/channels/442252698964721669/541978667522195476/738691962642890793). To reduce our points of failure it might be worth self-hosting these files.

**Comment by pietroalbini** [comment]
Yeah, I'd go for it.
