### ISSUE TITLE
Ballista build failure due to rustfmt not installed on nightly toolchain

### ISSUE THREAD

**Issue by andygrove** [rust-lang/docs.rs#922]
**Crate name:**
ballista

**Build failure link:**
https://docs.rs/crate/ballista/0.3.0-alpha-1/builds/275261

**Additional details:**

Builld fails with:

```
error: 'rustfmt' is not installed for the toolchain 'nightly-x86_64-unknown-linux-gnu'
```

There is a build.rs in one of our dependencies that generates code from protobuf then tries to format it.

**Comment by jyn514** [comment]
This was fixed in #913, your publish just missed it. I queued a rebuild for your crate: https://docs.rs/ballista/0.3.0-alpha-1/ballista/
