### ISSUE TITLE
Link to docs.rs environment details from "Build failed" page

### ISSUE THREAD

**Issue by Shnatsel** [rust-lang/docs.rs#923]
My crate [`auditable`](https://crates.io/crates/auditable) is doing something quite weird and fails to build on docs.rs. I needed to detect whether it's being built on docs.rs or not to work around the issue. Turns out it's possible and documented [here](https://docs.rs/about), but that page is not easily discoverable. If "Build failed" page contained either a link to that page or mentioned the DOCS_RS env variable, such situations would be easier to handle.

**Comment by jyn514** [comment]
Mentoring instructions:
Around https://github.com/rust-lang/docs.rs/blob/6b74ba17bb7be39267b6763150b93fa39bd26a43/templates/crate/details.html#L148-L153, add a link to `/about` and a mention of `DOCS_RS=1`.

**Comment by jyn514** [comment]
Actually - what if instead we made an FAQ page for failed builds?

Q: How do I detect docs.rs?
A: `DOCS_RS=1`

Q: I need a dependency that's not installed.
A: crates-build-env

Q: I need internet access.
A: Sorry, but no.

**Comment by jyn514** [comment]
I guess at that point we should just fix https://github.com/rust-lang/docs.rs/issues/888

**Comment by Kixiron** [comment]
Agreed, those would be fitting things for full-on docs. Chapters I've had ideas for are:
- Detect docs.rs in build scripts
- Detect docs.rs in `cfg`
- Limits
    - Internet access
- Need a dependency
- Badges
- Redirects
- Cargo metadata
- Local testing
- How do I get my crate on docs.rs (I've seen this question *many* times)
