### ISSUE TITLE
unable to add component rustfmt for toolchain nightly via rustup

### ISSUE THREAD

**Issue by eeeebbbbrrrr** [rust-lang/docs.rs#933]
**Crate name:**  `pgx`
**Build failure link:** https://docs.rs/crate/pgx/0.0.9/builds/277703

**Additional details:**

I understand why my crate (there's a few actually) are failing to build on docs.rs -- I'm **not** looking for help with that.

I thought I'd clone this repo and use the really fancy docker-compose stuff to work through a solution locally w/o trying to blackbox docs.rs by publishing new versions every few minutes.

Unfortunately, this command (on MacOS 10.15.1):

```
$ docker-compose run -v "$(realpath /Users/xxx/_work/pgx/pgx)":/build web build crate --local /build
```

ultimately fails with: 

```
2020/08/03 18:46:15 [INFO] rustwide::cmd: running `Command { std: "/opt/docsrs/rustwide/cargo-home/bin/rustup" "component" "add" "--toolchain" "nightly" "rustfmt", kill_on_drop: false }`
2020/08/03 18:46:15 [INFO] rustwide::cmd: [stderr] error: component 'rustfmt' for target 'x86_64-unknown-linux-gnu' is unavailable for download for channel nightly
2020/08/03 18:46:15 [INFO] rustwide::cmd: [stderr] Sometimes not all components are available in any given nightly.
Error: Building documentation failed

Caused by:
    unable to add component rustfmt for toolchain nightly via rustup
```

This is as of 482d56660df6c8a5ac329d372c42ce9547c04b4d.

I'm stumped.  I've successfully used this process in the past to debug similar build issues for another crate and it worked flawlessly.

Any suggestions?

I've attached the entire output from docker-compose for more investigation.

[build.log](https://github.com/rust-lang/docs.rs/files/5017808/build.log)

**Comment by jyn514** [comment]
This was fixed in #931. Try pulling master and rebasing.

**Comment by eeeebbbbrrrr** [comment]
Thanks.  I've just re-cloned the repo and am starting the entire docker building process from scratch.  Will report back...

**Comment by jyn514** [comment]
Ouch. For future reference, `git pull` should work as well, although it wouldn't help much in this case since we changed the lockfile in https://github.com/rust-lang/docs.rs/pull/929.

You could also try building without docker, that should work now that we no longer depend on the host being linux. I really need to update the docs ... https://forge.rust-lang.org/docs-rs/no-docker-compose.html#building-the-site

**Comment by eeeebbbbrrrr** [comment]
I was current with master, but maybe my original `docker-compose build` was out of date.

Anyways, I'm making progress now.  I'm able to see the same errors as on docs.rs.

Thanks for all your work!

**Comment by jyn514** [comment]
Thank you for your patience!
