### ISSUE TITLE
Provide a way to copy dependency string from docs.rs

### ISSUE THREAD

**Issue by inikulin** [rust-lang/docs.rs#934]
Usually, before adding a dependency, I first open docs.rs and check crate documentation. Then, to add the latest version I need to open crates.io from dropdown menu and only then copy `Cargo.toml` entry. These doesn't sound like a big deal, but then you repeat this process over and over again it may become bothersome. 

Probably there are hidden shortcuts that I'm missing, but it would be great if docs.rs allowed to copy a `Cargo.toml` entry for the current version like crates.io does.

**Comment by Nemo157** [comment]
(I'm agnostic on this proposal itself, but I highly recommend the [`cargo-edit`](https://crates.io/crates/cargo-edit) set of utilities so that you can just `cargo add foo bar baz` and avoid having to manually edit `Cargo.toml` for dependencies at all).

**Comment by inikulin** [comment]
@Nemo157 true, but it's still easier copy-paste a string into Cargo.toml. Also, since it's not a part of the official cargo distribution, very small fraction of people is aware of `cargo-edit`.

**Comment by jyn514** [comment]
This already exists: 
![image](https://user-images.githubusercontent.com/23638587/89295144-8b2c5700-d62e-11ea-848e-d567da5c076d.png)

Maybe it's hard to find because it's on /crate, not on the documentation pages? I'm not sure where we'd put it on the rustdoc page, there's not a lot of space.

**Comment by jyn514** [comment]
Another alternative people have suggested is making that whole top tag show up even for the documentation, but then it's taking up a lot of screen real estate when you're trying to read the docs themselves.

**Comment by inikulin** [comment]
@jyn514 Agh, didn't realise it's there! That's handy. Though, it's more a UI design issue then - it's not obvious that's it's a "copy to clipboard" button (though maybe it's just me).

**Comment by inikulin** [comment]
Oh, it's only on the "Source" tab, it would be cool to have this button in this dropdown too:
![image](https://user-images.githubusercontent.com/453071/89315033-47f3d780-d672-11ea-88cd-f2f03fbe2db3.png)
