### ISSUE TITLE
Add CSS hot-reloading

### ISSUE THREAD

**Issue by Kixiron** [rust-lang/docs.rs#949]
Currently we have template reloading, but not CSS reloading. This is *really* annoying when making css changes because it means to see any changes you have to stop and rebuild the server

I think the best route for this would be to add `sass_rs` as a dev-dependency, add a `#[cfg(debug_assertions)]` css rebuild to [`start_template_reloading`](https://github.com/rust-lang/docs.rs/blob/master/src/web/page/templates.rs#L42) and then to have another `#[cfg(debug_assertions)]` toggle between serving from `STYLE_CSS` and from a routed CSS in [`style_css_handler`](https://github.com/rust-lang/docs.rs/blob/master/src/web/mod.rs#L517), much like we do with our template engine. The hot-reloaded css can just be stored in an `ArcSwap` so that we can swap it whenever something in the templates directory changes.

**Comment by jyn514** [comment]
`cfg(debug_assertions)` doesn't seem like the right way to do this because you can have debug assertions on in release mode.

Is there a reason not to  _always_ use routed CSS and get rid of STYLE_CSS altogether?

**Comment by Kixiron** [comment]
Realistically no, but there is probably a performance difference between using something baked into the binary and querying the router for an `Arc`'d string.
It would have the bonus of removing sass compilation from the build script, so slightly slower startup in exchange for faster builds

**Comment by Nemo157** [comment]
Bigger issue than the slower startup is shipping the sass compiler in the production binary if we don't need it.

If you don't want it toggleable, use an explicit feature for it rather than a `cfg` (you don't get access to `dev-dependencies` at all from the binary so you would want the dependency to be `optional` anyway).

**Comment by syphar** [comment]
we removed template reloading , proposing that people could just use `cargo watch`. 

FOllowing the same argument I'll close this issue to. 

I'm happy to discuss if people disagree :)
