### ISSUE TITLE
Errors following _Getting Started_ instructions

### ISSUE THREAD

**Issue by ohaddahan** [rust-lang/docs.rs#950]
I  tried following [Getting Started instructions](https://github.com/rust-lang/docs.rs#getting-started).

```bash
git clone https://github.com/rust-lang/docs.rs.git docs.rs
cd docs.rs
# Configure the default settings for external services
cp .env.sample .env
# Builds the docs.rs binary
cargo build
# Start the extenal services
docker-compose up -d db s3
# Build a sample crate to make sure it works
# This sets up the docs.rs build environment, including installing the nightly
# Rust toolchain. This will take a while the first time but will be cached afterwards.
cargo run web build crate regex 1.3.1
# This starts the web server but does not build any crates.
cargo run start-web-server
```

But I'm getting the following failure:

```bash
     Running `target/debug/cratesfyi web build crate regex 1.3.1`
error: Found argument 'web' which wasn't expected, or isn't valid in this context
 
USAGE:
    cratesfyi <SUBCOMMAND>
 
For more information try --help
```

Full log is attached.
[run.log](https://github.com/rust-lang/docs.rs/files/5046153/run.log)

**Comment by Nemo157** [comment]
@ohaddahan that's a bug in the docs, see #951 updating them, anywhere you see `cargo run web ...` you can just ignore the `web` from there.

**Comment by ohaddahan** [comment]
@Nemo157 than you for the quick response , I tried your suggestion and I'm getting:


>     Finished dev [unoptimized + debuginfo] target(s) in 2.90s
>      Running `target/debug/cratesfyi build crate regex 1.3.1`
> 2020/08/08 23:38:26 [DEBUG] cratesfyi::config: optional configuration variable DOCSRS_BUILD_ATTEMPTS is not set
> 2020/08/08 23:38:26 [DEBUG] cratesfyi::config: optional configuration variable REGISTRY_INDEX_PATH is not set
> 2020/08/08 23:38:26 [DEBUG] cratesfyi::config: optional configuration variable DOCSRS_MAX_POOL_SIZE is not set
> 2020/08/08 23:38:26 [DEBUG] cratesfyi::config: optional configuration variable DOCSRS_MIN_POOL_IDLE is not set
> 2020/08/08 23:38:26 [DEBUG] cratesfyi::config: optional configuration variable DOCSRS_S3_BUCKET is not set
> 2020/08/08 23:38:26 [DEBUG] cratesfyi::config: optional configuration variable CRATESFYI_GITHUB_USERNAME is not set
> 2020/08/08 23:38:26 [DEBUG] cratesfyi::config: optional configuration variable CRATESFYI_GITHUB_ACCESSTOKEN is not set
> 2020/08/08 23:38:26 [DEBUG] cratesfyi::config: optional configuration variable DOCSRS_MAX_FILE_SIZE is not set
> 2020/08/08 23:38:26 [DEBUG] cratesfyi::config: optional configuration variable DOCSRS_MAX_FILE_SIZE_HTML is not set
> 2020/08/08 23:38:26 [DEBUG] cratesfyi::config: optional configuration variable DOCSRS_MAX_PARSE_MEMORY is not set
> 2020/08/08 23:38:26 [DEBUG] cratesfyi::config: optional configuration variable REGISTRY_GC_INTERVAL is not set
> Error: The given paths were invalid
> 
> Caused by:
>     registry index path 'ignored/cratesfyi-prefix/crates.io-index' does not exist
> 

So I ran `mkdir -p ignored/cratesfyi-prefix/crates.io-index`  and rerun the `build`.
So I guess we should also add to run `mkdir -p $CRATESFYI_PREFIX` from `.env` settings.

**Comment by Nemo157** [comment]
Yes, it looks like we're missing some data there. I think the [_The "prefix" directory_](https://forge.rust-lang.org/docs-rs/no-docker-compose.html#the-prefix-directory) section probably needs to be brought over?

**Comment by ohaddahan** [comment]
@Nemo157 no need to follow https://forge.rust-lang.org/docs-rs/no-docker-compose.html#the-prefix-directory, `mkdir -p` is enough.

Seems like `cargo run` takes care of the rest.

**Comment by ohaddahan** [comment]
BTW, it's a very slow and high CPU process with no real progress info, I thought it was handing multiple times.
Might want to add some kind of progress info.

**Comment by ohaddahan** [comment]
Finally finished but not successfully:

> 2020/08/09 00:03:00 [INFO] rustwide::cmd: running `Command { std: "/Users/ohaddahan/Projects/docs.rs/.rustwide/cargo-home/bin/cargo" "+nightly" "metadata" "--format-version" "1", kill_on_drop: false }`
> 2020/08/09 00:03:00 [INFO] rustwide::cmd: running `Command { std: "docker" "create" "-v" "/Users/ohaddahan/Projects/docs.rs/.rustwide/builds/essential-files-20200807-1.47.0-nightly-09f4c9f50/target:/opt/rustwide/target:rw,Z" "-v" "/Users/ohaddahan/Projects/docs.rs/.rustwide/builds/essential-files-20200807-1.47.0-nightly-09f4c9f50/source:/opt/rustwide/workdir:ro,Z" "-v" "/Users/ohaddahan/Projects/docs.rs/.rustwide/cargo-home:/opt/rustwide/cargo-home:ro,Z" "-v" "/Users/ohaddahan/Projects/docs.rs/.rustwide/rustup-home:/opt/rustwide/rustup-home:ro,Z" "-e" "SOURCE_DIR=/opt/rustwide/workdir" "-e" "MAP_USER_ID=501" "-e" "CARGO_TARGET_DIR=/opt/rustwide/target" "-e" "RUSTFLAGS=" "-e" "RUSTDOCFLAGS=-Z unstable-options --resource-suffix -20200807-1.47.0-nightly-09f4c9f50 --static-root-path / --cap-lints warn" "-e" "DOCS_RS=1" "-e" "CARGO_HOME=/opt/rustwide/cargo-home" "-e" "RUSTUP_HOME=/opt/rustwide/rustup-home" "-w" "/opt/rustwide/workdir" "-m" "3221225472" "--network" "none" "rustops/crates-build-env" "/opt/rustwide/cargo-home/bin/cargo" "+nightly" "doc" "--lib" "--no-deps", kill_on_drop: false }`
> 2020/08/09 00:03:00 [INFO] rustwide::cmd: [stdout] 55dd178fabd7baa8c4ee154b48de36250ada472190f8e4d33758f31252041d5c
> 2020/08/09 00:03:00 [INFO] rustwide::cmd: running `Command { std: "docker" "start" "-a" "55dd178fabd7baa8c4ee154b48de36250ada472190f8e4d33758f31252041d5c", kill_on_drop: false }`
> 2020/08/09 00:03:01 [ERROR] rustwide::cmd: error running command: stream did not contain valid UTF-8
> 2020/08/09 00:03:01 [INFO] rustwide::cmd: running `Command { std: "docker" "inspect" "55dd178fabd7baa8c4ee154b48de36250ada472190f8e4d33758f31252041d5c", kill_on_drop: false }`
> 2020/08/09 00:03:02 [INFO] rustwide::cmd: running `Command { std: "docker" "rm" "-f" "55dd178fabd7baa8c4ee154b48de36250ada472190f8e4d33758f31252041d5c", kill_on_drop: false }`
> 2020/08/09 00:03:02 [INFO] rustwide::cmd: [stdout] 55dd178fabd7baa8c4ee154b48de36250ada472190f8e4d33758f31252041d5c
> Error: Building documentation failed
> 
> Caused by:
>     failed to build dummy crate for rustc 1.47.0-nightly (09f4c9f50 2020-08-07)

**Comment by ohaddahan** [comment]
Seem to succeed after trying to run it again.


>     Finished dev [unoptimized + debuginfo] target(s) in 0.85s
>      Running `target/debug/cratesfyi build crate regex 1.3.1`
> 2020/08/09 00:04:45 [DEBUG] cratesfyi::config: optional configuration variable DOCSRS_BUILD_ATTEMPTS is not set
> 2020/08/09 00:04:45 [DEBUG] cratesfyi::config: optional configuration variable REGISTRY_INDEX_PATH is not set
> 2020/08/09 00:04:45 [DEBUG] cratesfyi::config: optional configuration variable DOCSRS_MAX_POOL_SIZE is not set
> 2020/08/09 00:04:45 [DEBUG] cratesfyi::config: optional configuration variable DOCSRS_MIN_POOL_IDLE is not set
> 2020/08/09 00:04:45 [DEBUG] cratesfyi::config: optional configuration variable DOCSRS_S3_BUCKET is not set
> 2020/08/09 00:04:45 [DEBUG] cratesfyi::config: optional configuration variable CRATESFYI_GITHUB_USERNAME is not set
> 2020/08/09 00:04:45 [DEBUG] cratesfyi::config: optional configuration variable CRATESFYI_GITHUB_ACCESSTOKEN is not set
> 2020/08/09 00:04:45 [DEBUG] cratesfyi::config: optional configuration variable DOCSRS_MAX_FILE_SIZE is not set
> 2020/08/09 00:04:45 [DEBUG] cratesfyi::config: optional configuration variable DOCSRS_MAX_FILE_SIZE_HTML is not set
> 2020/08/09 00:04:45 [DEBUG] cratesfyi::config: optional configuration variable DOCSRS_MAX_PARSE_MEMORY is not set
> 2020/08/09 00:04:45 [DEBUG] cratesfyi::config: optional configuration variable REGISTRY_GC_INTERVAL is not set
> 2020/08/09 00:04:45 [DEBUG] cratesfyi::docbuilder: Loading cache
> 2020/08/09 00:04:45 [DEBUG] cratesfyi::docbuilder: Loading database cache
> 2020/08/09 00:04:45 [INFO] rustwide::cmd::sandbox: pulling image rustops/crates-build-env from Docker Hub
> 2020/08/09 00:04:45 [INFO] rustwide::cmd: running `Command { std: "docker" "pull" "rustops/crates-build-env", kill_on_drop: false }`
> 2020/08/09 00:04:45 [INFO] rustwide::cmd: [stdout] Using default tag: latest
> 2020/08/09 00:04:48 [INFO] rustwide::cmd: [stdout] latest: Pulling from rustops/crates-build-env
> 2020/08/09 00:04:48 [INFO] rustwide::cmd: [stdout] Digest: sha256:a636fd89d022f18117e1dc8fb37a0a009933cdbbe082814857f0e2024962d47c
> 2020/08/09 00:04:48 [INFO] rustwide::cmd: [stdout] Status: Image is up to date for rustops/crates-build-env:latest
> 2020/08/09 00:04:48 [INFO] rustwide::cmd: [stdout] docker.io/rustops/crates-build-env:latest
> 2020/08/09 00:04:48 [INFO] rustwide::cmd::sandbox: checking the image rustops/crates-build-env is available locally
> 2020/08/09 00:04:48 [INFO] rustwide::cmd: running `Command { std: "docker" "image" "inspect" "rustops/crates-build-env", kill_on_drop: false }`
> 2020/08/09 00:04:48 [INFO] rustwide::workspace: installing tools required by rustwide
> 2020/08/09 00:04:48 [INFO] rustwide::tools: tool rustup is installed, trying to update it
> 2020/08/09 00:04:48 [INFO] rustwide::cmd: running `Command { std: "/Users/ohaddahan/Projects/docs.rs/.rustwide/cargo-home/bin/rustup" "self" "update", kill_on_drop: false }`
> 2020/08/09 00:04:48 [INFO] rustwide::cmd: [stderr] info: checking for self-updates
> 2020/08/09 00:04:48 [INFO] rustwide::cmd: [stdout]   rustup unchanged - 1.22.1
> 2020/08/09 00:04:48 [INFO] rustwide::cmd: [stdout] 
> 2020/08/09 00:04:48 [INFO] rustwide::cmd: running `Command { std: "/Users/ohaddahan/Projects/docs.rs/.rustwide/cargo-home/bin/rustup" "update" "stable", kill_on_drop: false }`
> 2020/08/09 00:04:48 [INFO] rustwide::cmd: [stderr] info: syncing channel updates for 'stable-x86_64-apple-darwin'
> 2020/08/09 00:04:48 [INFO] rustwide::cmd: [stdout] 
> 2020/08/09 00:04:49 [INFO] rustwide::cmd: [stdout]   stable-x86_64-apple-darwin unchanged - rustc 1.45.2 (d3fb005a3 2020-07-31)
> 2020/08/09 00:04:49 [INFO] rustwide::cmd: [stdout] 
> 2020/08/09 00:04:49 [INFO] rustwide::cmd: [stderr] info: checking for self-updates
> 2020/08/09 00:04:49 [INFO] rustwide::tools: tool rustup-toolchain-install-master is installed, trying to update it
> 2020/08/09 00:04:49 [INFO] rustwide::cmd: running `Command { std: "/Users/ohaddahan/Projects/docs.rs/.rustwide/cargo-home/bin/cargo" "+stable" "install" "rustup-toolchain-install-master", kill_on_drop: false }`
> 2020/08/09 00:04:49 [INFO] rustwide::cmd: [stderr]     Updating crates.io index
> 2020/08/09 00:04:51 [INFO] rustwide::cmd: [stderr]      Ignored package `rustup-toolchain-install-master v1.8.0` is already installed, use --force to override
> 2020/08/09 00:04:51 [INFO] rustwide::tools: tool git-credential-null is installed, trying to update it
> 2020/08/09 00:04:51 [INFO] rustwide::cmd: running `Command { std: "/Users/ohaddahan/Projects/docs.rs/.rustwide/cargo-home/bin/cargo" "+stable" "install" "git-credential-null", kill_on_drop: false }`
> 2020/08/09 00:04:51 [INFO] rustwide::cmd: [stderr]     Updating crates.io index
> 2020/08/09 00:04:51 [INFO] rustwide::cmd: [stderr]      Ignored package `git-credential-null v1.0.1` is already installed, use --force to override
> 2020/08/09 00:04:51 [INFO] cratesfyi::docbuilder::rustwide_builder: detecting rustc's version...
> 2020/08/09 00:04:51 [INFO] rustwide::cmd: running `Command { std: "/Users/ohaddahan/Projects/docs.rs/.rustwide/cargo-home/bin/rustc" "+nightly" "--version", kill_on_drop: false }`
> 2020/08/09 00:04:51 [INFO] cratesfyi::docbuilder::rustwide_builder: found rustc rustc 1.47.0-nightly (09f4c9f50 2020-08-07)
> 2020/08/09 00:04:51 [INFO] rustwide::cmd: running `Command { std: "/Users/ohaddahan/Projects/docs.rs/.rustwide/cargo-home/bin/rustup" "target" "list" "--installed" "--toolchain" "nightly", kill_on_drop: false }`
> 2020/08/09 00:04:52 [INFO] rustwide::toolchain: installing toolchain nightly
> 2020/08/09 00:04:52 [INFO] rustwide::cmd: running `Command { std: "/Users/ohaddahan/Projects/docs.rs/.rustwide/cargo-home/bin/rustup" "toolchain" "install" "nightly" "--profile" "minimal", kill_on_drop: false }`
> 2020/08/09 00:04:52 [INFO] rustwide::cmd: [stderr] info: syncing channel updates for 'nightly-x86_64-apple-darwin'
> 2020/08/09 00:04:52 [INFO] rustwide::cmd: [stdout] 
> 2020/08/09 00:04:52 [INFO] rustwide::cmd: [stdout]   nightly-x86_64-apple-darwin unchanged - rustc 1.47.0-nightly (09f4c9f50 2020-08-07)
> 2020/08/09 00:04:52 [INFO] rustwide::cmd: [stdout] 
> 2020/08/09 00:04:52 [INFO] rustwide::cmd: [stderr] info: checking for self-updates
> 2020/08/09 00:04:52 [INFO] rustwide::toolchain: adding component rustfmt for toolchain nightly
> 2020/08/09 00:04:52 [INFO] rustwide::cmd: running `Command { std: "/Users/ohaddahan/Projects/docs.rs/.rustwide/cargo-home/bin/rustup" "component" "add" "--toolchain" "nightly" "rustfmt", kill_on_drop: false }`
> 2020/08/09 00:04:52 [INFO] rustwide::cmd: [stderr] error: component 'rustfmt' for target 'x86_64-apple-darwin' is unavailable for download for channel nightly
> 2020/08/09 00:04:52 [INFO] rustwide::cmd: [stderr] Sometimes not all components are available in any given nightly.
> 2020/08/09 00:04:52 [WARN] cratesfyi::docbuilder::rustwide_builder: failed to install rustfmt: unable to add component rustfmt for toolchain nightly via rustup
> 2020/08/09 00:04:52 [INFO] cratesfyi::docbuilder::rustwide_builder: continuing anyway, since this must be the first build
> 2020/08/09 00:04:52 [INFO] cratesfyi::docbuilder::rustwide_builder: detecting rustc's version...
> 2020/08/09 00:04:52 [INFO] rustwide::cmd: running `Command { std: "/Users/ohaddahan/Projects/docs.rs/.rustwide/cargo-home/bin/rustc" "+nightly" "--version", kill_on_drop: false }`
> 2020/08/09 00:04:52 [INFO] cratesfyi::docbuilder::rustwide_builder: found rustc rustc 1.47.0-nightly (09f4c9f50 2020-08-07)
> 2020/08/09 00:04:52 [INFO] cratesfyi::docbuilder::rustwide_builder: building package regex 1.3.1
> 2020/08/09 00:04:52 [INFO] rustwide::crates::cratesio: fetching crate regex 1.3.1...
> 2020/08/09 00:04:54 [INFO] rustwide::crates::cratesio: extracting crate regex 1.3.1 into .rustwide/builds/regex-1.3.1/source
> 2020/08/09 00:04:54 [INFO] rustwide::prepare: validating manifest of crates.io crate regex 1.3.1 on toolchain nightly
> 2020/08/09 00:04:54 [INFO] rustwide::cmd: running `Command { std: "/Users/ohaddahan/Projects/docs.rs/.rustwide/cargo-home/bin/cargo" "+nightly" "read-manifest" "--manifest-path" "Cargo.toml", kill_on_drop: false }`
> 2020/08/09 00:04:55 [INFO] rustwide::prepare: started tweaking crates.io crate regex 1.3.1
> 2020/08/09 00:04:55 [INFO] rustwide::prepare: removed 0 missing tests
> 2020/08/09 00:04:55 [INFO] rustwide::prepare: finished tweaking crates.io crate regex 1.3.1
> 2020/08/09 00:04:55 [INFO] rustwide::prepare: tweaked toml for crates.io crate regex 1.3.1 written to .rustwide/builds/regex-1.3.1/source/Cargo.toml
> 2020/08/09 00:04:55 [INFO] rustwide::prepare: crate crates.io crate regex 1.3.1 already has a lockfile, it will not be regenerated
> 2020/08/09 00:04:55 [INFO] rustwide::cmd: running `Command { std: "/Users/ohaddahan/Projects/docs.rs/.rustwide/cargo-home/bin/cargo" "+nightly" "fetch" "--locked" "--manifest-path" "Cargo.toml", kill_on_drop: false }`
> 2020/08/09 00:04:55 [INFO] rustwide::cmd: [stderr]  Downloading crates ...
> 2020/08/09 00:04:55 [INFO] rustwide::cmd: [stderr]   Downloaded rand_core v0.3.1
> 2020/08/09 00:04:55 [INFO] rustwide::cmd: [stderr]   Downloaded rand_core v0.4.2
> 2020/08/09 00:04:55 [INFO] rustwide::cmd: [stderr]   Downloaded rand v0.6.5
> 2020/08/09 00:04:55 [INFO] rustwide::cmd: [stderr]   Downloaded cloudabi v0.0.3
> 2020/08/09 00:04:56 [INFO] rustwide::cmd: [stderr]   Downloaded bitflags v1.1.0
> 2020/08/09 00:04:56 [INFO] rustwide::cmd: [stderr]   Downloaded winapi-x86_64-pc-windows-gnu v0.4.0
> 2020/08/09 00:05:00 [INFO] rustwide::cmd: [stderr]   Downloaded fuchsia-cprng v0.1.1
> 2020/08/09 00:05:00 [INFO] rustwide::cmd: [stderr]   Downloaded doc-comment v0.3.1
> 2020/08/09 00:05:00 [INFO] rustwide::cmd: [stderr]   Downloaded rand_chacha v0.1.1
> 2020/08/09 00:05:00 [INFO] rustwide::cmd: [stderr]   Downloaded memchr v2.2.1
> 2020/08/09 00:05:00 [INFO] rustwide::cmd: [stderr]   Downloaded rand_hc v0.1.0
> 2020/08/09 00:05:00 [INFO] rustwide::cmd: [stderr]   Downloaded rdrand v0.4.0
> 2020/08/09 00:05:00 [INFO] rustwide::cmd: [stderr]   Downloaded autocfg v0.1.6
> 2020/08/09 00:05:00 [INFO] rustwide::cmd: [stderr]   Downloaded quickcheck v0.8.5
> 2020/08/09 00:05:00 [INFO] rustwide::cmd: [stderr]   Downloaded rand_os v0.1.3
> 2020/08/09 00:05:00 [INFO] rustwide::cmd: [stderr]   Downloaded rand_xorshift v0.1.1
> 2020/08/09 00:05:00 [INFO] rustwide::cmd: [stderr]   Downloaded rand_isaac v0.1.1
> 2020/08/09 00:05:00 [INFO] rustwide::cmd: [stderr]   Downloaded rand_jitter v0.1.4
> 2020/08/09 00:05:00 [INFO] rustwide::cmd: [stderr]   Downloaded thread_local v0.3.6
> 2020/08/09 00:05:00 [INFO] rustwide::cmd: [stderr]   Downloaded aho-corasick v0.7.6
> 2020/08/09 00:05:00 [INFO] rustwide::cmd: [stderr]   Downloaded rand_pcg v0.1.2
> 2020/08/09 00:05:00 [INFO] rustwide::cmd: [stderr]   Downloaded winapi-i686-pc-windows-gnu v0.4.0
> 2020/08/09 00:05:04 [INFO] rustwide::cmd: [stderr]   Downloaded libc v0.2.62
> 2020/08/09 00:05:04 [INFO] rustwide::cmd: [stderr]   Downloaded winapi v0.3.8
> 2020/08/09 00:05:04 [INFO] rustwide::cmd: [stderr]   Downloaded regex-syntax v0.6.12
> 2020/08/09 00:05:04 [INFO] rustwide::cmd: running `Command { std: "/Users/ohaddahan/Projects/docs.rs/.rustwide/cargo-home/bin/cargo" "+nightly" "metadata" "--format-version" "1", kill_on_drop: false }`
> 2020/08/09 00:05:05 [INFO] rustwide::cmd: running `Command { std: "docker" "create" "-v" "/Users/ohaddahan/Projects/docs.rs/.rustwide/builds/regex-1.3.1/target:/opt/rustwide/target:rw,Z" "-v" "/Users/ohaddahan/Projects/docs.rs/.rustwide/builds/regex-1.3.1/source:/opt/rustwide/workdir:ro,Z" "-v" "/Users/ohaddahan/Projects/docs.rs/.rustwide/cargo-home:/opt/rustwide/cargo-home:ro,Z" "-v" "/Users/ohaddahan/Projects/docs.rs/.rustwide/rustup-home:/opt/rustwide/rustup-home:ro,Z" "-e" "SOURCE_DIR=/opt/rustwide/workdir" "-e" "MAP_USER_ID=501" "-e" "CARGO_TARGET_DIR=/opt/rustwide/target" "-e" "RUSTFLAGS=" "-e" "RUSTDOCFLAGS=-Z unstable-options --resource-suffix -20200807-1.47.0-nightly-09f4c9f50 --static-root-path / --cap-lints warn --extern-html-root-url aho_corasick=https://docs.rs/aho-corasick/0.7.6 --extern-html-root-url rand=https://docs.rs/rand/0.6.5 --extern-html-root-url thread_local=https://docs.rs/thread_local/0.3.6 --extern-html-root-url memchr=https://docs.rs/memchr/2.2.1 --extern-html-root-url regex_syntax=https://docs.rs/regex-syntax/0.6.12 --extern-html-root-url lazy_static=https://docs.rs/lazy_static/1.4.0 --extern-html-root-url quickcheck=https://docs.rs/quickcheck/0.8.5 --extern-html-root-url doc_comment=https://docs.rs/doc-comment/0.3.1" "-e" "DOCS_RS=1" "-e" "CARGO_HOME=/opt/rustwide/cargo-home" "-e" "RUSTUP_HOME=/opt/rustwide/rustup-home" "-w" "/opt/rustwide/workdir" "-m" "3221225472" "--network" "none" "rustops/crates-build-env" "/opt/rustwide/cargo-home/bin/cargo" "+nightly" "doc" "--lib" "--no-deps", kill_on_drop: false }`
> 2020/08/09 00:05:06 [INFO] rustwide::cmd: [stdout] dca6b7a83ba8c51adef2ac827d89cc4a45ba2049af9b93af8c05ffcbc78c3c55
> 2020/08/09 00:05:06 [INFO] rustwide::cmd: running `Command { std: "docker" "start" "-a" "dca6b7a83ba8c51adef2ac827d89cc4a45ba2049af9b93af8c05ffcbc78c3c55", kill_on_drop: false }`
> 2020/08/09 00:05:08 [ERROR] rustwide::cmd: error running command: stream did not contain valid UTF-8
> 2020/08/09 00:05:08 [INFO] rustwide::cmd: running `Command { std: "docker" "inspect" "dca6b7a83ba8c51adef2ac827d89cc4a45ba2049af9b93af8c05ffcbc78c3c55", kill_on_drop: false }`
> 2020/08/09 00:05:09 [INFO] rustwide::cmd: running `Command { std: "docker" "rm" "-f" "dca6b7a83ba8c51adef2ac827d89cc4a45ba2049af9b93af8c05ffcbc78c3c55", kill_on_drop: false }`
> 2020/08/09 00:05:09 [INFO] rustwide::cmd: [stdout] dca6b7a83ba8c51adef2ac827d89cc4a45ba2049af9b93af8c05ffcbc78c3c55
> 2020/08/09 00:05:09 [DEBUG] cratesfyi::docbuilder::rustwide_builder: adding sources into database
> 2020/08/09 00:05:11 [DEBUG] cratesfyi::db::add_package: Adding package into database
> 2020/08/09 00:05:11 [DEBUG] cratesfyi::db::add_package: Adding build into database
> 2020/08/09 00:05:12 [INFO] cratesfyi::db::add_package: Updating crate data for regex
> 2020/08/09 00:05:12 [DEBUG] cratesfyi::db::add_package: Updating owner data for alexcrichton: CrateOwner { avatar: "https://avatars1.githubusercontent.com/u/64996?v=4", email: "", login: "alexcrichton", name: "Alex Crichton" }
> 2020/08/09 00:05:12 [DEBUG] cratesfyi::db::add_package: Updating owner data for BurntSushi: CrateOwner { avatar: "https://avatars3.githubusercontent.com/u/456674?v=4", email: "", login: "BurntSushi", name: "Andrew Gallant" }
> 2020/08/09 00:05:12 [DEBUG] cratesfyi::db::add_package: Updating owner data for github:rust-lang:libs: CrateOwner { avatar: "https://avatars1.githubusercontent.com/u/5430905?v=4", email: "", login: "github:rust-lang:libs", name: "Libs" }
> 2020/08/09 00:05:12 [DEBUG] cratesfyi::db::add_package: Updating owner data for github:rust-lang-nursery:regex-owners: CrateOwner { avatar: "https://avatars.githubusercontent.com/u/14631425?v=3", email: "", login: "github:rust-lang-nursery:regex-owners", name: "regex-owners" }
> 2020/08/09 00:05:12 [DEBUG] cratesfyi::docbuilder: Saving cache

**Comment by jyn514** [comment]
>  Might want to add some kind of progress info.

This is https://github.com/rust-lang/rustwide/issues/9.

It sounds like you figured this out, so I'm going to close the issue. Let me know if you're still having trouble and I'm happy to help.
