### ISSUE TITLE
Document read-only and writable file system

### ISSUE THREAD

**Issue by schulzch** [rust-lang/docs.rs#952]
[About/Builds](https://docs.rs/about/builds) does not mention that the sandbox file system is mostly read-only, except `OUT_DIR` (?). I think this should be documented, along with maximum writable disk space and best practices.

Several crates seem to have run into this issue already. Just to mention a few:
- https://github.com/rtbo/rust-xcb/issues/74
- https://github.com/avr-rust/avrd/issues/18
- https://github.com/rust-lang/docs.rs/issues/727
- https://github.com/rust-lang/docs.rs/issues/811

**Comment by jyn514** [comment]
Mentoring instructions: near https://github.com/rust-lang/docs.rs/blob/master/templates/core/about/builds.html#L5, add a line about the source directory being read-only. It should probably also mention that this affects dependencies as well as the crate you published.

**Comment by jyn514** [comment]
Documented in #954
