### ISSUE TITLE
The header bar's contents cover the content area

### ISSUE THREAD

**Issue by maroider** [rust-lang/docs.rs#958]
The contents of the header bar currently cover the main content area instead of staying inside the header bar.
As a result, the main content area is completely inaccessible.
This happens in Firefox, Chrome and IE.
![image](https://user-images.githubusercontent.com/54416743/90005843-1b564600-dc98-11ea-93e9-a24f6f3dbbaf.png)

**Comment by Nemo157** [comment]
I see issues loading some of the css from cdnjs at the moment (SSL_ERROR_NO_CYPHER_OVERLAP), so this would be fixed by #921.

**Comment by maroider** [comment]
Ah, that explains it. I've experienced this issue briefly before, but I had chalked it up to something on my end.
It seems to be fixed for me now.
