### ISSUE TITLE
'Rust' dropdown should take you to rust-lang.org

### ISSUE THREAD

**Issue by jyn514** [rust-lang/docs.rs#959]
Right now, we have three dropdown tabs: 'About', 'Releases', and 'Rust'. The first two take you to a separate page when you click on them. The last does nothing - you have to click on one of the drop-down items. To make it consistent, 'Rust' should take you to rust-lang.org and the 'Rust Programming Language' item should be removed.

**Comment by shorsher** [comment]
New to contributing to this project but happy to pick this up 🎉

**Comment by jyn514** [comment]
@shorsher thank you so much! To get started, change https://github.com/rust-lang/docs.rs/blob/master/templates/header/topbar.html#L56 to be a hyperlink, then run `cargo run start-web-server` to view your changes locally (more instructions in the README).
