### ISSUE TITLE
READMEs have no margins on mobile

### ISSUE THREAD

**Issue by jyn514** [rust-lang/docs.rs#962]
It makes them a little difficult to read because your eyes have to scan to the very end of the line. Screenshot taken on Android with a chrome derived browser.

![Screenshot_20200813-090656_Ecosia](https://user-images.githubusercontent.com/23638587/90138094-79d8fe00-dd44-11ea-98e7-38cd47eba08f.jpg)

**Comment by Nemo157** [comment]
Also, seems like we might want to collapse the "sidebar" on mobile? So that you see the start of the readme above the fold.

**Comment by shorsher** [comment]
I’ll see what I can do. I believe readme is displayed in `templates/crate/details.html`

**Comment by jyn514** [comment]
Yes, that's right: https://github.com/rust-lang/docs.rs/blob/master/templates/crate/details.html#L144
