### ISSUE TITLE
Rebuild request: glyph_brush_layout 0.2.0

### ISSUE THREAD

**Issue by alexheretic** [rust-lang/docs.rs#967]
**Crate name:** glyph_brush_layout
**Build failure link:** https://docs.rs/crate/glyph_brush_layout/0.2.0/builds/253202
**Additional details:** 
Doc builds failed for this crate due to a ICE https://github.com/rust-lang/rust/issues/72213. This is now fixed in the latest nightlies, so a rebuild should work.

Crate issue: https://github.com/alexheretic/glyph-brush/issues/110

**Comment by jyn514** [comment]
Rebuilt: https://docs.rs/glyph_brush_layout/0.2.0/glyph_brush_layout/
