### ISSUE TITLE
Avoid creating two <title>s

### ISSUE THREAD

**Issue by Koxiaet** [rust-lang/docs.rs#971]
docs.rs creates two titles for most pages, the Rustdoc title and docs.rs title:

![two-titles](https://user-images.githubusercontent.com/38139193/90306115-e4637880-dec1-11ea-9583-15414458ecb3.png)

This is [invalid HTML](https://www.w3.org/TR/html53/document-metadata.html#the-title-element) and causes my browser to sometimes just display the URL on the titlebar, since it doesn't know which title to use.

I would actually prefer to use just the Rustdoc title because it provides more information about the site.

**Comment by jyn514** [comment]
This is fallout from #930. If we're just using the rustdoc title this should be pretty easy, just remove this line: https://github.com/rust-lang/docs.rs/blob/1107e9b337e2851b8d82faf539d0a1094ef125e1/templates/rustdoc/head.html#L11
