### ISSUE TITLE
Can not fetch git submodules

### ISSUE THREAD

**Issue by inflation** [rust-lang/docs.rs#978]
**Crate name:** jpegxl-sys
**Build failure link:**
https://docs.rs/crate/jpegxl-sys/0.1.2/builds/281684
**Additional details:**
Because the underlying C library uses multiple submodules, I'm using a command in `build.rs` to fetch them recursively:
```rust
Command::new("git")
    .args(&["submodule", "update", "--init", "--recursive"])
    .output()
    .expect("Sync submodules failed!");
```

It works locally but failed on docs.rs. I'm wondering if there is any restrictions about that. Thanks.

**Comment by Kixiron** [comment]
Unfortunately crates building within the docs.rs environment have [no network access](https://docs.rs/about/builds), so fetching while in the build environment is impossible

**Comment by jyn514** [comment]
The build logs don't match up with the submodule snippet you posted.

```
[INFO] [stderr]   CMake Error: The source directory "/opt/rustwide/workdir/jpeg-xl" does not exist.
[INFO] [stderr]   Specify --help for usage, or press the help button on the CMake GUI.
[INFO] [stderr]   thread 'main' panicked at '
[INFO] [stderr]   command did not execute successfully, got: exit code: 1
[INFO] [stderr] 
[INFO] [stderr]   build script failed, must exit now', /opt/rustwide/cargo-home/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.44/src/lib.rs:885:5
```

**Comment by jyn514** [comment]
Note that the source directory is mounted read only, so if you need to generate source files in build.rs, then you have to write them to OUT_DIR.

> the underlying C library uses multiple submodules, I'm using a command in build.rs to fetch them recursively

I'm not sure I follow - builds don't happen in a git subdirectory (unless you packaged the whole git directory in the crates.io tarball). So any operation you do with git won't work.

**Comment by inflation** [comment]
Well, because `jpeg-xl` itself uses multiple third party sources, and they are presented as submodules under that, what I'm doing now is pulling everything so my library can build and link against it. I'll try to figure out if I can ship the header files then bindgen would work without the whole git repo.

**Comment by inflation** [comment]
It works!
